const de = {
  language: 'de-DE',
  'kline.time_Line': 'Zeit',
  'kline.time_1m': '1m',
  'kline.time_3m': '3m',
  'kline.time_5m': '5m',
  'kline.time_15m': '15m',
  'kline.time_30m': '30m',
  'kline.time_1H': '1H',
  'kline.time_2H': '2H',
  'kline.time_4H': '4H',
  'kline.time_6H': '6H',
  'kline.time_1D': '1D',
  'kline.time_1W': '1W',
  'kline.time_1M': '1M',
  'kline.tab_line': 'Diagramm',
  'kline.tab_depth': 'Tiefe',
  'kline.chartType_Bars': 'Bars',
  'kline.chartType_Candles': 'Kerzen',
  'kline.chartType_Hollow_Candles': 'Hohle Kerzen',
  'kline.chartType_Line': 'Linie',
  'kline.chartType_Area': 'Fläche',
  'kline.chartType_Heikin_Ashi': 'Heikin Ashi',
  degate_account: 'DeGate Account',
  Trade: 'Handeln',
  Order: 'Auftrag',
  Grid: 'Grid Strategie',
  Campaign: 'Kampagne',
  DCA: 'DCA',
  Advanced: 'Erweitert',
  Add: 'Hinzufügen',
  Add_Funds: 'Mittel hinzufügen',
  eth_added_1: '1 ETH hinzugefügt',
  eth_sent_1: '1 ETH gesendet',
  Send: 'Senden',
  Internal_Transfer: 'Interner Transfer',
  Miscellaneous: 'Verschiedenes',
  Bridge: 'Brücke',
  Mining: 'Mining',
  Liquidity_Mining: 'Liquidity Mining',
  Analytics: 'Analysen',
  Support: 'Support',
  Help: 'Hilfe',
  Tips: 'Tipp',
  Statistics: 'Statistiken',
  Coming_soon: 'Demnächst verfügbar',
  Faucet: 'Faucet',
  more: 'Mehr',
  hide: 'Verstecken',
  change: 'Ändern',
  'Wrong Network': 'Falsches Netzwerk',
  avbl: 'Verfügbar:',
  insufficient_balance_AAA:
    'In Ihrer Wallet sind nicht genug AAA. Bitte überprüfen Sie und versuchen Sie es erneut.',
  insufficient_balance: 'Unzureichendes Guthaben',
  wallet_denied_sign: 'Die Signatur der Nachricht wurde abgelehnt.',
  common_err: 'Irgendetwas ist schiefgelaufen. Versuchen Sie es später erneut.',
  common_err_ledger_version:
    'Ein Fehler ist aufgetreten. Bitte stellen Sie sicher, dass Ihre Ledger Ethereum-App auf dem neuesten Stand ist (1.9.10 oder höher), oder versuchen Sie es später erneut.',
  network_1: 'Ethereum Mainnet',
  network_err: 'Netzwerkfehler. Bitte versuchen Sie es später noch einmal.',
  rate_limit_err:
    'Die Zugriffshäufigkeit ist zu hoch. Bitte versuchen Sie es in einer Minute erneut.',
  error_InsufficientGasFunds: 'Nicht genug Gas im Wallet',
  notification_transaction_send: 'Transaktion gesendet',
  view_on_etherscan: 'Auf Blockchain Explorer anzeigen',
  view_on_explorer: 'Adresse anzeigen',
  switch_network: 'Netzwerk wechseln',
  switch_to_Arbitrum: 'Wechseln Sie zu Arbitrum, um fortzufahren.',
  switch_to_MAINNET_in_metamask: 'Bitte wechseln Sie in MetaMask zu MAINNET',
  switch_to_MAINNET: 'Bitte wechseln Sie zu MAINNET',
  switch_network_in_walletconnect:
    'Gehen Sie zu Ihrem Wallet und wechseln Sie das Netzwerk mit WalletConnect',
  Retry: 'Wiederholen',
  wallet_tips: 'Bitte im Browser-Wallet genehmigen.',
  wallet_ledger_tips: 'Bitte in Ledger Hardware genehmigen.',
  wallet_metamask_tips: 'Bitte in MetaMask genehmigen.',
  wallet_walletconnect_tips:
    'Bitte gehen Sie zu Ihrem Wallet, um mit WalletConnect zu genehmigen.',
  wallet_cancelled_tips: 'Sie haben die Signatur storniert',
  Close: 'Schließen',
  copied: 'Kopiert',
  Details: 'Details',
  view_details: 'Details anzeigen',
  Share: 'Teilen',
  view_graph: 'Ansicht in Chart',
  Dismiss: 'Zurückweisen',
  Cancel: 'Abbrechen',
  End: 'Ende',
  End_grid: 'Ende',
  Confirm: 'Bestätigen',
  Cancel_all: 'Alle stornieren',
  cancel_all_tips: 'Alle offenen Orders stornieren',
  Submit: 'Einreichen',
  no_data: 'Keine Daten',
  all_data_displayed: 'Alle Daten werden angezeigt',
  no_data_within_90_days: 'Keine Daten innerhalb von 90 Tagen',
  only_display_90_days: 'Es werden nur Daten der letzten 90 Tage angezeigt',
  displayed_90_days: 'Daten der letzten 90 Tage anzeigen',
  only_data_beyond_90_days_trade:
    'Um auf Daten zuzugreifen, die älter als 90 Tage sind, wählen Sie bitte „Alle anzeigen“ und anschließend die Funktion „Daten exportieren“',
  only_data_beyond_90_days_grid_detail:
    'Die historische Abfrage von Daten über die letzten 90 Tage hinaus wird derzeit nicht unterstützt',
  only_data_beyond_90_days_spot_history:
    'Um auf Daten über 90 Tage hinaus zuzugreifen, verwenden Sie bitte die Funktion „Daten exportieren“',
  View: 'Ansicht',
  service_unavailable_for_region_REGION:
    'Dieser Dienst ist in REGION nicht verfügbar.',
  service_unavailable: 'Dienst ist nicht verfügbar',
  service_error: 'Bitte versuchen Sie es später noch einmal',
  service_maintenance: 'Dieser Dienst wird derzeit gewartet.',
  connect_wallet: 'Wallet verbinden',
  switch_address: 'Adresse wechseln',
  wallet_wc: 'Verbunden mit WalletConnect',
  wallet_ledger: 'Verbunden mit Ledger',
  register_dexAccount: 'Registrieren',
  deposit_ETH: 'ETH hinzufügen',
  initialize: 'Initialisieren',
  initialization: 'Initialisierung',
  invalid_signature: 'Ungültige Signatur',
  possible_cause: 'Mögliche Ursache:',
  locale_time_error: 'Die lokale Uhrzeit Ihres Geräts ist ungenau.',
  authorization_mode: 'Auth. Modus',
  authorization_mode_standard: 'Signatur-frei',
  authorization_mode_single_use: 'Immer signen',
  turn_on: 'Einschalten',
  turn_on_signature_free_mode: 'Signatur-freien Modus einschalten',
  signatre_free_mode: 'Signatur-freier Modus',
  turn_on_signature_free_mode_tips:
    'In diesem Modus können Sie Aufträge erteilen, ohne zu signen. Um den Modus zu wechseln, navigieren Sie zu „Einstellungen“ unter der Schaltfläche „Handeln“.',
  turn_on_signature_free_mode_tips_grid:
    'In diesem Modus können Sie Gridtstrategien erstellen, ohne zu signen. Um den Modus zu wechseln, navigieren Sie zu „Einstellungen“ unter der Schaltfläche „Handeln“.',
  turn_on_signature_free_mode_tips_dca:
    'In diesem Modus können Sie DCA Pläne erstellen, ohne zu signen. Um den Modus zu wechseln, navigieren Sie zu „Einstellungen“ unter der Schaltfläche „Handeln“.',
  yes: 'Ja',
  no: 'Nein',
  free_mode_on: 'Signaturfreier Modus an',
  view_balance: 'Guthaben anzeigen',
  delete_asset_key: 'Asset Key löschen',
  delete_asset_key_desc:
    'Der signaturfreie Modus wird deaktiviert, sobald der Asset-Key aus Ihrem Browser gelöscht wird.',
  no_asset_key_tips: 'Kein Asset-Key in Ihrem Browser gefunden',
  turn_off_standard_mode: 'Und schalten Sie den Signaturfreien Modus aus',
  reset_asset_key: 'Asset Key zurücksetzen',
  view_asset_key: 'Asset Key anzeigen',
  lock_success: 'Asset Key gelöscht',
  reset: 'Asset Key zurücksetzen',
  delete: 'Löschen',
  withdraw_ETH: 'ETH senden',
  transfer_ETH: 'Interner Transfer',
  history: 'Verlauf',
  view_history: 'Im Verlauf ansehen',
  internal_transfer: 'Transfer',
  assets_record_link: 'Verlauf',
  other: 'Andere',
  login_success: 'Erfolgreich verbunden',
  Account: 'Account',
  Address: 'Adresse',
  Disconnect: 'Trennen',
  copy_address: 'Adresse kopieren',
  copy_grid: 'Strategie kopieren',
  Copy: 'Kopieren',
  btn_search: 'Suchen',
  btn_reset: 'Zurücksetzen',
  btn_confirm: 'Schließen',
  btn_max: 'Max',
  btn_ok: 'Ok',
  spot_trade: 'SPOT',
  grid_trade: 'GRID',
  err_balance_title: 'Order konnte nicht aufgegeben werden',
  err_balance_content:
    'Nicht genügend verfügbares Guthaben. Bitte überprüfen Sie und versuchen Sie es erneut.',
  order_failed: 'Order fehlgeschlagen',
  insufficient_order_value: 'Unzureichender Orderwert',
  grid_failed: 'Erstellung fehlgeschlagen',
  err_eth_gas: 'Ethereum-Netzwerk stark überlastet',
  err_insufficient_balance_TOKEN1: 'Unzureichendes TOKEN1-Guthaben',
  err_insufficient_balance_TOKEN1_TOKEN2:
    'Unzureichende TOKEN1- und TOKEN2-Guthaben',
  please_add_funds_before_ordering:
    'Bitte laden Sie vor der Order Geld auf Ihr DeGate-Guthaben auf.',
  err_balance_content_spot:
    'Aufgrund unzureichenden Guthabens konnte die Order nicht aufgegeben werden.',
  err_balance_content_grid:
    'Aufgrund unzureichenden Guthabens konnte keine Gridstrategie erstellt werden.',
  trade_min_volume_tips_XXX: 'Min XXX',
  grid_min_volume_tips:
    'Die Ordermenge entspricht nicht der Mindestmenge. Versuchen Sie es bitte erneut.',
  trade_risk_orders_tips:
    'Sie können keine Order aufgeben, da Sie zu viele offene Orders haben',
  gas_token_tips: 'Gas-Fee-Token auswählen',
  add_favorite_tooltip: 'Zu meinen Favoriten hinzufügen',
  remove_favorite_tooltip: 'Aus Favoriten entfernen',
  expire_tips_X: 'Diese Order läuft am X ab.',
  today: 'Jetzt',
  now: 'Jetzt',
  time_D_day: 'Dd',
  time_D_day_H_hour: 'Dd Hh',
  time_H_hour_M_minute: 'Hh Mm',
  time_M_minute_S_second: 'Mm Ss',
  time_S_second: 'Ss',
  around: '～',
  time_now: 'Jetzt',
  time_before: '',
  time_before_ago: 'vor',
  time_1_minute: '1 Minute',
  time_1_hour: '1 Stunde',
  time_1_day: '1 Tag',
  time_1_year: '1 Jahr',
  time_M_minutes: 'M Minuten',
  time_M_m: 'Mm',
  time_H_hours: 'H Stunden',
  time_H_h: 'Hh',
  time_D_days: 'D Tage',
  time_Y_years: 'Y Jahre',
  time_Y_y: 'Yy',
  fee_change_tips: 'Preis geupdated',
  no_pairs: 'Handelspaar nicht gefunden',
  register_new_pair: 'Neues Paar hinzufügen',
  register_pair: 'Handelspaar hinzufügen',
  add_pair: 'Paar hinzufügen',
  tips_hide_forever: 'Nicht mehr anzeigen',
  token: 'Token',
  action: 'Aktion',
  more_actions: 'Mehr',
  gas_fee: 'Gasgebühr',
  'orders.detail_gas': 'Tatsächliche Gasgebühr',
  trade_fee: 'Handelsgebühr',
  about_degate: 'Über DeGate',
  metrics: 'Metriken',
  fees: 'Gebühren',
  document: 'Dokumentation',
  join_us: 'Mitmachen',
  feedback: 'Feedback',
  email_optional: 'Deine Email Adresse (optional)',
  Upload: 'Uploaden',
  feedback_upload_tip:
    'Bitte teilen Sie uns Ihr Feedback mit. Ziehen Sie zum Anhängen Dateien per Drag & Drop.',
  feedback_upload_tip_mobile: 'Bitten teilen Sie uns Ihr Feedback mit.',
  image_upload_tip: 'Zum Hinzufügen freigeben',
  feedback_success: 'Wir hören Sie laut und deutlich!',
  feedback_success_2: 'Vielen Dank',
  feedback_failed:
    'Die Übermittlung ist fehlgeschlagen. Versuchen Sie es später erneut.',
  image_upload_rule_1: 'Unterstützt nur PNG, JPG, JPEG.',
  image_upload_rule_2: 'Die maximale Größe beträgt 20 MB pro Datei.',
  image_upload_rule_3: 'Bis zu 5 Dateien.',
  image_upload_rule_2_3:
    'Die maximale Größe beträgt 20 MB pro Datei. Bis zu 5 Dateien.',
  no_pair: 'Token Paar nicht gefunden',
  no_token: 'Token nicht gefunden',
  choose_base_token: 'Base Token auswählen',
  choose_quote_token: 'Quote Token auswählen',
  get_test_token: 'Testnet Token erhalten',
  faucet: 'Faucet',
  expire_in: 'Läuft ab in',
  expire_in_empty_err: 'Bitte geben Sie eine Nummer ein',
  go_back: 'Geh zurück',
  max_XXX: 'Max XXX',
  min_XXX: 'Min XXX',
  fill_in: 'Ausfüllen',
  my_balance: 'Mein Guthaben',
  deGate_insufficient_fees:
    'DeGate-Guthaben reicht nicht aus, um die Gasgebühr zu bezahlen',
  wallet_balance: 'Wallet Guthaben',
  your_wallet_balance: 'Dein Wallet Guthaben',
  degate_balance: 'DeGate-Guthaben',
  wallet_insufficient_fees: 'Unzureichendes Guthaben im Wallet',
  wallet_insufficient_balance: 'Unzureichendes Guthaben',
  insuffficient_wallet_balance: 'Unzureichendes Walletguthaben',
  degate_insufficient_balance: 'Unzureichendes verfügbares Guthaben',
  open_discord: 'Zur Discord Community',
  err_valid_until:
    'Bitte passen Sie die Ortszeit auf Ihrem Gerät an die Standardzeit an',
  tips_gas:
    'Die Gasgebühr für die Ausführung dieser On-Chain-Transaktion wird direkt von Ihrem DeGate-Guthaben abgezogen.',
  maker_free: 'Maker kostenlos',
  trading_fee_rate: 'Handelsgebührensatz',
  Free: 'Gratis',
  stop_service_1: 'Die Site wird derzeit gewartet',
  stop_service_2: 'Geschätzte Wiederherstellungszeit',
  stop_upgrade: 'Die neue Version des Testnets wird derzeit migriert.',
  stop_trading_1: 'Systemaktualisierung',
  stop_trading_2: 'Der Handel ist vorübergehend ausgesetzt',
  sell: 'verkaufen',
  buy: 'kaufen',
  SELL: 'VERKAUFEN',
  BUY: 'KAUFEN',
  Sell: 'Verkaufen',
  Buy: 'Kaufen',
  sell_order: 'Verkaufsorder',
  buy_order: 'Kaufsorder',
  edit: 'Bearbeiten',
  status_processing: 'Verarbeitung',
  status_processed: 'Ausstehend',
  status_pending: 'Ausstehend',
  status_confirming: 'Bestätigen',
  status_success: 'Erfolg',
  status_completed: 'Abgeschlossen',
  status_failed: 'Fehler',
  status_speeding_up: 'Beschleunigen',
  status_canceling: 'Abbrechen',
  status_canceled: 'Abgebrochen',
  in_progress: 'Im Gange',
  limit_order: 'Limit',
  market_order: 'Market',
  stop_limit_order: 'Stop Limit',
  balance: 'Guthaben',
  empty_connect: 'Bitte verbinden Sie zuerst das Wallet',
  empty_register: 'Bitte zuerst initialisieren',
  empty_months3: 'Keine Daten für die letzten 3 Monate',
  show_months3: 'Es werden nur Daten der letzten 3 Monate angezeigt',
  view_all: 'Alle anzeigen',
  D1: '1D',
  D5: '5D',
  M1: '1M',
  M3: '3M',
  M6: '6M',
  YTD: 'YTD',
  Y1: '1Y',
  all: 'Alle',
  paste: 'Einfügen',
  clear: 'Löschen',
  total: 'Gesamt',
  amount: 'Betrag',
  order_amount: 'Orderbetrag',
  price: 'Preis',
  order_total: 'Gesamt',
  filledAmount: 'Betrag',
  tradeFilledTotal: 'Wert',
  orderFilledTotal: 'Gesamt',
  filledAmount_amount: 'Filled/Betrag',
  profit: 'Profit',
  incompatible_token:
    'Die technischen Spezifikationen dieses Tokens sind nicht mit dem DeGate-Protokoll kompatibel.',
  next: 'Nächstes',
  token_not_verified: 'Nicht verifiziert',
  token_not_verified_tips:
    'Contract Adresse, Icon und Symbol sind nicht verifiziert. Bitte überprüfen Sie die Contract Adresse anhand offizieller Quellen, um Betrug zu vermeiden.',
  token_verified: 'Verifiziert',
  token_verified_tips: 'Contract Adresse, Icon und Symbol stimmen überein.',
  deposit_tips_region:
    'Bitte beachten Sie, dass Sie auf DeGate in REGION zugreifen. Die Handels- und internen Überweisungsfunktionen sind nach der Einzahlung des Guthabens nicht mehr verfügbar.',
  complete_time: 'Abschließen in',
  unable_to_initialize: 'Initialisierung nicht möglich',
  filter_base: 'Base',
  filter_quote: 'Quote',
  filter_type: 'Typ',
  filter_role: 'Rolle',
  option_maker: 'Maker',
  option_taker: 'Taker',
  start_data: 'Anfangsdatum',
  end_data: 'Enddatum',
  added_to_favorites: 'Zu Favoriten hinzugefügt',
  removed_to_favorites: 'Aus Favoriten entfernt',
  show_recents_50: 'Es wurden die letzten 50 Daten angezeigt.',
  terms_of_service: 'Servicebedingungen',
  tips_small_unfilled:
    'Basierend auf den im Systemdesign angegebenen Genauigkeitsgraden wurde ein kleiner, nicht ausgeführter Teil der Order an Ihr DeGate-Guthaben zurückgegeben.',
  notification: 'Benachrichtigung',
  server_message_SystemRecovery:
    'Bitte beachten Sie, dass es nach der Systemwiederherstellung zu Änderungen an Ihrem Orderstatus kommt.',
  learn_more: 'Mehr erfahren',
  connect_ledger: 'Ledger verbinden',
  ledger_disconnect:
    'Ausführung von „transferOut“ auf „USBDevice“ fehlgeschlagen: Das Gerät wurde getrennt.',
  gas_fee_expired: 'Die Gasgebühr ist abgelaufen. Bitte erneut einreichen.',
  scroll_down_to_refresh: 'Zum Aktualisieren nach unten scrollen',
  release_to_refresh_immediately: 'Zum Aktualisieren loslassen',
  no_more: 'Keine weiteren Daten',
  loading: 'Laden...',
  force_withdrawing_token_tips:
    'Der aktuelle Vorgang kann nicht ausgeführt werden, da Ihre Anforderung zur erzwungenen Auszahlung verarbeitet wird.',
  speed_up: 'Beschleunigen',
  transaction_submitted: 'Transaktion übermittelt',
  tx_speed_up: 'Transaktion beschleunigen',
  tx_cancel: 'Transaktion abbrechen',
  none: 'Keine',
  Language: 'Sprache',
  page: '/Seite',
  go_to: 'Gehe nach',
  icon_indicators: 'Indikatoren',
  icon_back: 'Zurück',
  icon_forward: 'Nach vorne',
  icon_full_screen: 'Vollbild',
  icon_exit_full_screen: 'Vollbild verlassen',
  icon_buy_sell_orders: 'Kauf und Verkaufsorders',
  icon_buy_orders: 'Kauforders',
  icon_sell_orders: 'Verkaufsorders',
  icon_enable: 'Klicken Sie hier, um zu aktivieren',
  icon_disable: 'Klicken Sie hier, um zu deaktivieren',
  icon_copy: 'Adresse kopieren',
  icon_view_explorer: 'Im Block Explorer anzeigen',
  icon_display_by_profit: 'Anzeige nach Gewinn',
  icon_display_by_time: 'Anzeige nach Zeit',
  icon_switch: 'Wechseln',
  eth_code_tips: 'Nativer Token von Ethereum. Keine Token-Contractadresse.',
  TBD: 'TBD',
  TVL: 'TVL',
  go_to_discord: 'Oder treten Sie Discord bei, um ein Ticket zu erstellen',
  release: 'Veröffentlichung:',
  security: 'Sicherheit',
  colon: ':',
  zero_balance: 'Nullsaldo',
  ledger_app_version_tips:
    'Aktualisieren Sie die Ethereum-App Ihres Ledgers auf Version 1.9.19 oder höher, um vor dem Signieren eine Vorschau der Nachricht anzuzeigen.',
  ledger_contract_data_tips:
    'Bitte aktivieren Sie Blindsignatur oder Contract data in den Einstellungen der Ethereum-App',
  input_auto_corrected_tooltips:
    'Automatische Korrektur Ihrer Eingabe nach Überschreiten der maximalen Ziffernanzahl',
  maximum_decimal_reached: 'Maximale Dezimalstellen erreicht',
  verify_ownership: 'Eigentümerschaft bestätigen',
  enable_trading: 'Handel ermöglichen',
  learn_more_about_signatures_link: 'Erfahren Sie mehr über Signaturen >',
  learn_more_about_signatures: 'Erfahren Sie mehr über Signaturen ',
  sign: 'Signieren',
  sign_step1: 'Vervollständigen Sie in Ihrer Wallet',
  sign_step2: '2. Signatur vervollständigen',
  not_now: 'Nicht jetzt',
  view_on_block_explorer: 'Im Block Explorer anzeigen',
  view_in_history: 'Im Verlauf anzeigen',
  continue_to_place_order: 'Weiter zur Order',
  Save: 'Speichern',
  sign_to_view: 'Melden Sie sich an, um die Ansicht anzuzeigen',
  available_degate_balance: 'Verfügbares DeGate-Guthaben',
  Back: 'Zurück',
  token_has_not_listed: 'Dieses Token wurde nicht auf DeGate gelistet.',
  list_now: 'Jetzt listen',
  spread_15: 'Spread > 15%',
  connected: 'Verbunden',
  self_list_token: 'Sofortiges Listing',
  claim_REBASE: 'REBASE beanspruchen',
  time: 'Zeit',
  time_updated: 'Zeit aktualisiert',
  show_in_X_m: 'Anzeigen in ~Xm',
  max_gas: 'Max Gasgebühr',
  total_required: 'Insgesamt erforderlich',
  Required: 'Erforderlich',
  available_balance: 'Verfügbares Guthaben',
  please_add_funds: 'Bitte fügen Sie Mittel Ihrem DeGate-Guthaben hinzu.',
  Side: 'Seite',
  pending: 'Ausstehend',
  active: 'Aktiv',
  ended: 'Beendet',
  name: 'Name',
  yield: 'Rendite',
  time_created: 'Erstellungszeit',
  time_ended: 'Endzeit',
  frequency: 'Frequenz',
  chain_cancel: 'On-Chain Abbrechen',
  status: 'Status',
  status_chainCancelProgressing: 'On-chain Abbrechen',
  status_chainCancelCompleted: 'On-chain Abgebrochen',
  filled_total: 'Filled/Gesamt',
  start_time: 'Startzeit',
  end_time: 'Endzeit',
  Summary: 'Zusammenfassung',
  Orders: 'Orders',
  Tutorial: 'Tutorial',
  Earn: 'Verdienen',
  top_winner_24h: '24h Top Rangliste',
  ID: 'ID',
  Select: 'Auswählen',
  Create: 'Erstellen',
  Review: 'Review',
  Airdrop: 'Airdrop',
  Countdown: 'Countdown',
  Day: 'Tag',
  Hour: 'Stunde',
  Minute: 'Minute',
  Second: 'Sekunde',
  Days: 'Tage',
  Hours: 'Stunden',
  Minutes: 'Minuten',
  Seconds: 'Sekunden',
  Claim: 'Beanspruchen',
  Expired: 'Abgelaufen',
  Claimed: 'Beansprucht',
  Welcome: 'Willkommen',
  gas_tips_for_amount_exceed_6_digits:
    'Es fallen zusätzliche Gebühren an, da die Ziffernanzahl des Betrags die nominelle Grenze von sechs Ziffern überschreitet.',
  input_auto_corrected_minStep_tips:
    'Ihre Eingabe wurde automatisch korrigiert, um die Mindestgenauigkeit zu erreichen',
  order_max_limit: 'Maximalgrenze überschritten',
  order_min_limit: 'Mindestgrenze nicht erreicht',
  order_faild_min_limit:
    'Auftragserteilung fehlgeschlagen: Mindestlimit nicht erreicht.',
  order_faild_max_limit:
    'Auftragserteilung fehlgeschlagen: Maximallimit überschritten.',
  disconnect_m: 'Trennen',
  'account.account_manage': 'Sicherheit',
  'account.account_manage_more':
    'Über den Autorisierungsmodus und den Asset-Key >',
  'account.what_is_asset_key':
    'Über den Autorisierungsmodus und den Asset-Key ',
  'account.total_value': 'Gesamtwert',
  'account.hide_small_balances': 'Kleine Guthaben verbergen',
  'account.add_to_metamask': 'Token zum Wallet hinzufügen',
  'account.assets_balance_total': 'Gesamt',
  'account.assets_balance_available': 'Verfügbar',
  'account.assets_market': 'Wert',
  'account.transfer_to_degate_balance': 'Zum DeGate-Guthaben hinzufügen',
  'account.search_tokens': 'Token suchen',
  'account.deposit_title':
    'Vermögenswerte werden auf Ihr dezentrales DeGate-Konto eingezahlt. Sie haben die volle Kontrolle über diese Vermögenswerte.',
  'account.deposit_tips': 'Sie behalten die volle Kontrolle über diese Gelder.',
  'account.deposit_confirm_btn': 'Hinzufügen',
  'account.deposit_approved_btn': 'Genehmigt',
  'account.deposit_1_ETH': 'Fügen Sie Ihrem DeGate-Guthaben 1 ETH hinzu',
  'account.deposit_status_pending': 'Ausstehend',
  'account.deposit_status_pay_pending': 'Fällige Zahlung',
  'account.deposit_status_pay_waiting': 'Zahlung übertragen',
  'account.deposit_status_pay_confirming': 'Zahlung bestätigen',
  'account.deposit_tips_block': 'Transaktion wartet auf Blockaufnahme',
  'account.deposit_status_pay_btn': 'Bezahlen',
  'account.pay_deposit_warning':
    'Beim Aufladen von Guthaben können zusätzliche Gasgebühren anfallen.',
  'account.pay_deposit_warning_tips':
    'Die Kosten für die Aufstockung der Mittel müssen ggf. von den Benutzern getragen werden, da die Zuschüsse von DeGate vollständig aufgebraucht sind.',
  'account.deposit_pending_tips':
    'Beschleunigen Sie Transaktionen in Ihrer Wallet, wenn die Wartezeit länger als 5 Minuten beträgt.',
  'account.deposit_pending_tips_ledger':
    'Beschleunigen Sie die Transaktion, wenn die Wartezeit länger als 5 Minuten beträgt.',
  'account.deposit_contract_tips_over_AMOUNT':
    'Für Fondserhöhungen über AMOUNT USD ist die erweiterte Methode erforderlich.',
  'account.deposit_contract_tips_only_all':
    'Es wird nur die erweiterte Methode der Mittelzuführung unterstützt.',
  'account.suggest_100': '≥$100 empfohlen',
  'account.suggest_100_tips':
    'Zum Platzieren einer Limit-Order wird ein Betrag über $100 empfohlen.',
  'account.deposit_failed': 'Fehlgeschlagen',
  'account.deposit_failed_tips':
    'Die On-Chain-Transaktion zum Hinzufügen von Geldern ist fehlgeschlagen.',
  'account.payment_due': 'Fällige Zahlung',
  'account.payment_due_tips':
    'Um die Mittel Ihrem DeGate-Guthaben gutzuschreiben, ist eine zusätzliche Zahlung erforderlich.',
  'account.register_token_code_placeholder': 'Contractadresse eingeben',
  'account.register_token_code': 'Contractadresse',
  'account.register_token_symbol': 'Symbol',
  'account.register_token_check': 'Listing-Fortschritt prüfen',
  'account.register_token_code_err_added': 'Dieses Token wird gelistet',
  'account.register_token_next_step': 'Nächstes',
  'account.register_token_tips1':
    'Für die On-Chain-Token-Auflistung ist keine Berechtigung erforderlich. Bitte fahren Sie sofort mit der Auflistung Ihres Tokens fort.',
  'account.register_token_btn': 'Token auflisten',
  'account.list_token': 'Token auflisten',
  'account.withdraw_warning_XXX':
    'Aufgrund der erhöhten Nachfrage dauert das Senden von Geldern derzeit ~ XXX.',
  'account.withdraw_status_pending': 'Verarbeitung',
  'account.tansferred_1_ETH': '1 ETH überwiesen',
  'account.transfer_status_sent': 'Gesendet',
  'account.transfer_status_received': 'Erhalten',
  'account.th_me': 'Ich',
  'account.th_tx_hash': 'Transaction Hash',
  'account.th_time': 'Zeit',
  'account.locked_order': 'Limit Order',
  Sending: 'Wird gesendet',
  'account.locked_claimable': 'Beanspruchbar',
  'account.locked_grid': 'Gridstrategie',
  'account.personal_sign_reason': 'Mögliche Gründe',
  'account.personal_sign_reason1':
    '1. MetaMask ist mit einer Hardware-Wallet verbunden',
  'account.personal_sign_reason2': '2. Die MetaMask-Version ist veraltet',
  'account.personal_sign_reason3': '3. Andere',
  'account.personal_sign_btn': 'Erneut signen',
  'account.deposit_arrive_in_30s': 'Ankunft in ~30 Sekunden',
  'account.deposit_arrive_in_30s_s': 'Ankunft in ~ 30 Sekunden',
  'account.account_completed_time_XXX': 'Abgeschlossen in ~XXX',
  'account.search_result_no_token': 'Token kann nicht gefunden werden',
  'account.search_result_invalid_code': 'Ungültige Contractadresse',
  'account.search_result_not_listed':
    'Token ist derzeit nicht auf DeGate gelistet',
  'account.search_result_tips_register':
    'Sie können die Contractadresse eingeben, um die Token-Auflistung zu vervollständigen',
  'account.search_result_not_find': 'Immer noch nicht gefunden?',
  'account.search_pair_tips3': 'Kein Handelspaar für das Asset',
  'account.search_pair_tips3_add': 'Bitte Paar hinzufügen',
  'account.register_token': 'Genehmigungsfreies Token-Listing',
  'account.search_again': 'Erneut suchen',
  'account.deposit_type': 'Methode',
  'account.deposit_type_standard': 'Standard',
  'account.switch_account_tips': 'Gewechselt zu',
  'account.switch_account_tips_register': 'Bitte zuerst initialisieren.',
  'account.initialize_success': 'Initialisierung erfolgreich',
  'account.approve': 'Genehmigen',
  'account.reset_USDT': 'USDT-Genehmigung zurücksetzen',
  'account.reset_USDT_tips':
    'USDT erfordert eine Zurücksetzung der Genehmigung, wenn die Ausgabenlimits zu niedrig sind.',
  'account.next_step': 'Nächstes',
  'account.profit_total': 'Gesamtgewinn',
  'account.profit_history': 'Gewinnhistorie',
  'account.tab_mining_rewards': 'Mining Belohnungen',
  'account.yield_total': 'Gesamtertrag',
  'account.yield_24h': '24h Ertrag',
  'account.claimable': 'Einforderbar',
  'account.yield_history': 'Ertragsverlauf',
  'account.total_grid_profit': 'Gesamt Grid-Gewinn',
  'account.grid_strategies': 'Gridstrategien',
  'account.total_rewards': 'Gesamtbelohnungen',
  'account.rewards_24h': '24h Belohnungen',
  'account.rewards': 'Belohnungen',
  'menu.register_err':
    'Ihre Adresse hat keinen Blockchain-Transaktionsdatenrecord. Bitte führen Sie eine On-Chain-Transaktion durch und versuchen Sie es erneut. Führen Sie beispielsweise eine Token-Übertragung auf Ihr Wallet durch.',
  'menu.reset_post_success_withOrders':
    'Reset für Asset Key eingeleitet. Alle Ihre offenen Aufträge und Grid-Strategien wurden storniert.',
  'menu.reset_post_success': 'Reset für Asset Key eingeleitet. ',
  'menu.reset_processing_title': 'Asset-Key wird zurückgesetzt',
  'menu.reset_processing_desc':
    'Bitte warten Sie, bis der Vorgang abgeschlossen ist',
  'trade.choose_token': 'Token auswählen',
  'trade.token_info': 'Token Info',
  'trade.token_address': 'Token Adresse',
  'trade.price_range_24h': '24h Preisspanne',
  'trade.vol_24h': '24h Volumen',
  'trade.item_price_TOKEN': 'Preis (TOKEN)',
  'trade.item_amount_TOKEN': 'Betrag (TOKEN)',
  'trade.order_book_title': 'Orderbuch',
  'trade.order_book_total': 'Gesamt',
  'trade.trade_history_title': 'Letzte Trades',
  'trade.trade_history_time': 'Zeit',
  'trade.market_placeholder_price': 'Marktpreis',
  'trade.what_is_stop_limit': 'Was ist Stop Limit',
  'trade.what_is_stop_limit_link': 'Was ist Stop Limit >',
  'trade.placeholder_total': 'Gesamt',
  'trade.more_settings': 'Einstellungen',
  'trade.expire_in_tips': 'Die Order wird nach Ablauf automatisch storniert.',
  'trade.period_day_s': 'd',
  'trade.period_hour_s': 'h',
  'trade.period_minute_s': 'm',
  'trade.period_err_input_tips': 'Bitte geben Sie eine gültige Nummer ein',
  'trade.post_only_label': 'Nur Maker',
  'trade.post_only_tips':
    'Der Maker-Only-Modus stellt sicher, dass nur Maker-Aufträge in das Orderbuch gelangen. Wenn ein Teil der Order als Taker-Order ausgeführt werden kann, wird die gesamte Order zurückgegeben. Für Orders im Maker-Only-Modus fallen keine Gasgebühren oder Handelsgebühren an.',
  'trade.post_only_fail_title': 'Order kann nicht erstellt werden',
  'trade.post_only_fail_desc':
    'Bitte passen Sie den Preis an oder deaktivieren Sie den „Maker-Only“-Modus.',
  'trade.max_gas_fee_tips':
    'Die Max Gas Fee deckt die On-Chain-Kosten für Handelsabwicklungen, die von Takern bezahlt werden und für Maker kostenlos sind. Überschüssige Gebühren werden zurückerstattet.',
  'trade.auto': 'Auto',
  'trade.custom': 'Benutzerdefiniert',
  'trade.enough_for_XX_trades': 'Genug für XX Trades',
  'trade.gas_fee_per_trade': 'Gasgebühr pro Trade',
  'trade.gas_fee_per_trade_tips':
    'Um die On-Chain Abwicklung zu erleichtern, fallen für die Taker Gasgebühren pro Handel an, wobei die Kosten je nach den Bedingungen des Ethereum-Netzwerks schwanken.',
  'trade.max_number_of_trades': 'Maximale Anzahl an Trades',
  'trade.btn_buy_ETH': 'ETH Kaufen',
  'trade.btn_sell_ETH': 'ETH Verkaufen',
  'trade.max_buy_fee_deducted_NUM': 'Gasgebühr abgezogen. Max ist NUM.',
  'trade.notification_limit_order_title': 'Limit Order platziert',
  'trade.notification_stop_limit_order_title': 'Stop Limit Order platziert',
  'trade.err_price': 'Bitte Preis eingeben',
  'trade.err_amount_total': 'Bitte Betrag oder Gesamtwert eingeben',
  'trade.err_amount': 'Bitte einen Betrag eingeben',
  'trade.err_insufficientFee_title': 'Unzureichende Gasgebühr',
  'trade.err_insufficientFee_desc':
    'Bitte überprüfen Sie Ihre Einstellung für die maximale Gasgebühr und Ihr DeGate-Guthaben.',
  'trade.cancel_order_success': 'Order storniert',
  'trade.pair_favorite': 'Favorit',
  'trade.pair_search': 'Suche Token, Contractadresse',
  'trade.pair_last_price': 'Preis',
  'trade.pair_change': 'Veränderung',
  'trade.url_parse_err_title': 'Dieses Paar existiert nicht.',
  'trade.risk_tips': 'Risikohinweis',
  'trade.base_is_not_default_token_tips':
    'Überprüfen Sie die Adresse des Token-Contracts durch offizielle Quellen, um Betrug zu vermeiden, bevor Sie handeln.',
  'trade.chain_cancel': 'Order On-Chain stornieren',
  'trade.chain_cancel_no_need_tips':
    'Diese Order muss nicht on-chain storniert werden.',
  'trade.chain_cancel_success': 'Anfrage gesendet',
  'trade.depth_empty': 'Noch keine Orders',
  'trade.depth_empty_asks': 'Keine Verkaufsorders',
  'trade.depth_empty_bids': 'Keine Kauforders',
  'trade.depth_empty_tips':
    'Market Order fehlgeschlagen, da nicht genügend offene Aufträge im Orderbuch vorhanden waren',
  'trade.history_empty': 'Noch keine Trades',
  'trade.err_price_stable':
    'Der Preis war ungültig. Bitte versuchen Sie es erneut.',
  'trade.price_warning':
    'Der von Ihnen eingegebene Preis weicht vom Marktpreis ab. Bitte bestätigen Sie dies, bevor Sie die Order aufgeben.',
  'trade.order_value_tips':
    'Der Mindestorderwert beträgt <b>QUOTE_A</b> oder <b>BASE_A</b>, was MINUSD USD entspricht. Verwenden Sie eine Marktorder, um diese Einschränkung zu umgehen.',
  'trade.order_value_tips_quote':
    'Der Mindestorderwert beträgt <b>QUOTE_A</b>, was MINUSD USD entspricht. Verwenden Sie eine Marktorder, um diese Einschränkung zu umgehen.',
  'trade.order_value_tips_stable_quote':
    'Der Mindestorderwert beträgt <b>QUOTE_A</b>. Verwenden Sie eine Marktorder, um diese Einschränkung zu umgehen.',
  'trade.system_limit': 'Systemlimit überschritten',
  'trade.stop_limit_untriggered_tips':
    'Die Order wurde nicht an das Orderbuch übermittelt, da der Stoppkurs nicht erreicht wurde.',
  'trade.stop_limit_triggered_tips_TIME':
    'Die Order wurde zu TIME in das Orderbuch eingegeben',
  'trade.flow_of_funds': 'Geldfluss',
  'trade.flow_of_funds_tip2':
    'Ihre Order wurde aufgegeben. Der Orderbetrag wird Ihrem DeGate-Guthaben und nicht Ihrem Wallet-Guthaben gutgeschrieben.',
  'orders.show_current_pair_orders': 'Andere Paare ausblenden',
  'orders.orderHistory': 'Orderverlauf',
  'orders.th_time': 'Zeit',
  'orders.th_average_price': 'Durchschnittlicher Preis',
  'orders.th_stop_price': 'Stop Preis',
  'orders.th_limit_price': 'Limit Preis',
  'orders.th_filled_price': 'Preis',
  'orders.th_filled_amount': 'Gefüllt',
  'orders.th_filled_total': 'Gesamt',
  'orders.th_trade_reconciliation': 'Abstimmung',
  'orders.th_trade_reconciliation_tips':
    'Bitte beachten Sie, dass es aufgrund der unterschiedlichen Berechnungsmodelle, die für das Matching auf DeGate und die Abwicklung in der Chain verwendet werden, zu leichten Abweichungen zwischen den beiden Berechnungsergebnissen kommen kann. Sollte dies der Fall sein, verwendet das System den Wert in der Chain als Standard und gleicht etwaige Defizite im DeGate-Guthaben aus.',
  'orders.hide_cancelled_expired_orders': 'Storniert/abgelaufen ausblenden',
  'orders.status_open': 'Offen',
  'orders.status_pending': 'Ausstehend',
  'orders.status_completed': 'Gefüllt',
  'orders.status_completed_part': 'Teilweise gefüllt',
  'orders.status_expired': 'Abgelaufen',
  'orders.detail_price': 'Durchschnitt/Preis',
  'orders.average_price': 'Durchschnittlicher Preis',
  'orders.detail_type': 'Orderart',
  'orders.detail_trade_fee': 'Handelsgebühr:',
  'orders.gas_preAuth': 'Maximale Gasgebühr:',
  'orders.fee_reconciliation': 'Abstimmung:',
  'orders.gas_paid': 'Bezahlte Gasgebühr:',
  'orders.gas': 'Gasgebühr:',
  'orders.trades_N': 'Trades(N)',
  'orders.detail_filled_total': 'Gesamt',
  'orders.detail_filled_detail': 'Handelsdetails',
  'orders.detail_filled_time': 'Zeit',
  'orders.order_maker_free': 'Maker-Gebühren frei',
  'orders.openOrders_empty': 'Keine offenen Orders',
  'orders.export_orders_1_year':
    'Exportieren Sie die Orderdaten des letzten Jahres.',
  'orders.export_trades_1_year':
    'Exportieren Sie die Handelsdaten des letzten Jahres.',
  'orders.export_data': 'Daten exportieren',
  'orders.export': 'Exportieren',
  'orders.export_processing': 'Wird verarbeitet.   Bitte warten Sie.',
  'orders.export_tips_100_percent':
    'Die Datei wird heruntergeladen, sobald der Fortschritt 100% erreicht hat.',
  'orders.sign_to_view_balance': 'Signen, um Guthaben zu sehen',
  'orders.sign_to_view_history': 'Signen, um Verlauf zu sehen',
  'orders.sign_to_view_security_options':
    'Signen, um Sicherheitsoptionen zu sehen',
  'gridTrade.automatic_strategy': 'Automatisch',
  'gridTrade.manual_strategy': 'Manuell',
  'gridTrade.placeholder_amount': 'Betrag eingeben',
  'gridTrade.low_price': 'Untergrenze',
  'gridTrade.high_price': 'Obergrenze',
  'gridTrade.initial_investment': 'Investment',
  'gridTrade.grid_levels_tips':
    'Wird verwendet, um die Anzahl offener Aufträge innerhalb der Preisspanne zu ermitteln.',
  'gridTrade.profit_per_grid': 'Profit pro Grid',
  'gridTrade.profit_per_grid_tips':
    'Ein wichtiger Parameter für die Rentabilität der Grid-Strategie. Gewinn pro Grid = (Höherer Preis - Niedrigerer Preis) / Niedrigerer Preis. Die höheren und niedrigeren Preise beziehen sich auf die Preise zweier benachbarter Grid-Linien innerhalb der Grid-Strategie.',
  'gridTrade.min_grid_volume_XXX_ETH': 'Betrag pro Grid: Min ist XXX ETH',
  'gridTrade.min_grid_volume_err':
    'Bitte erhöhen Sie die Investition oder reduzieren Sie die Anzahl der Grids',
  'gridTrade.grid_no_depth_tips_BASE_QUOTE':
    'Für dieses Paar kann die Grid-Strategie nicht erstellt werden, da sich im Orderbuch nicht genügend Orders befinden.',
  'gridTrade.grid_to_spot_trade': 'Gehe zu Spot',
  'gridTrade.grid_level_over_err': 'Bitte reduzieren Sie die Anzahl der Grids',
  'gridTrade.grid_prices_err': 'Bitte erweitern Sie die Preisspanne',
  'gridTrade.grid_create_err':
    'Bitte passen Sie die Parameter an und versuchen Sie es erneut.',
  'gridTrade.tips_grid_profit':
    'Die Gewinne werden direkt Ihrem DeGate-Guthaben gutgeschrieben und sind sofort verfügbar.',
  'gridTrade.tips_grid_balance_0_BASE':
    'Der Anstieg des Marktpreises hat dazu geführt, dass alle Aufträge im Rahmen dieser Grid-Strategie zu Kaufaufträgen wurden. Daher beträgt der aktuelle Saldo von BASE jetzt 0.',
  'gridTrade.tips_grid_balance_0_BASE_2':
    'Der Anstieg des Marktpreises hat dazu geführt, dass alle Aufträge im Rahmen dieser Grid-Strategie zu Kaufaufträgen wurden. Darüber hinaus werden einige dieser Aufträge teilweise ausgeführt. Daher ist der aktuelle Saldo von BASE >0.',
  'gridTrade.tips_grid_balance_0_QUOTE':
    'Der Rückgang des Marktpreises hat dazu geführt, dass alle Aufträge im Rahmen dieser Grid-Strategie zu Verkaufsaufträgen wurden. Daher beträgt der aktuelle Saldo von QUOTE jetzt 0.',
  'gridTrade.tips_grid_balance_0_QUOTE_2':
    'Der Rückgang des Marktpreises hat dazu geführt, dass alle Aufträge im Rahmen dieser Grid-Strategie zu Verkaufsaufträgen wurden. Darüber hinaus sind einige dieser Aufträge teilweise ausgeführt. Daher ist der aktuelle QUOTE-Saldo >0.',
  'gridTrade.grid_param_err': 'Bitte geben Sie die Gridstrategieparameter ein',
  'gridTrade.tv_buy': 'Kaufen',
  'gridTrade.tv_sell': 'Verkaufen',
  'gridTrade.tv_waiting': 'warten',
  'gridTrade.chain_cancel_no_need_tips':
    'Diese Gridstrategie erfordert keine On-Chain-Stornierung.',
  'gridTrade.grid_over_max_number_err':
    'Maximale Anzahl laufender Gridstrategien erreicht, neues Grid kann nicht erstellt werden.',
  'gridTrade.preview_orders_in_graph': 'Orders anzeigen',
  'gridTrade.greate_news': 'Gute Nachrichten:',
  'gridTrade.min_amount_required_XXX': 'Mindestens XXX erforderlich',
  'gridTrade.highest_grid_apy': 'Höchster Grid APY',
  'gridTrade.for_the_last_7_days': 'In den letzten 7 Tagen',
  'gridTrade.min_investment': 'Min. Investment',
  'gridTrade.grid_need_XXX': '$XXX für Grid',
  'gridTrade.mining_need_XXX': '$XXX für Mining',
  'gridTrade.recommended_params_cannot_be_applied':
    'Aufgrund unzureichender Investition können die empfohlenen Parameter nicht angewendet werden. Sie können sie im manuellen Modus anpassen.',
  'gridTrade.copy_params_to_manual': 'Parameter zu Manual kopieren',
  'gridOrders.grid_recents': 'Meine letzten Trades',
  'gridOrders.th_created_time': 'Erstellungszeit',
  'gridOrders.grid_profit': 'Grid Profit',
  'gridOrders.grid_cancel': 'Ende',
  open_orders: 'Offene Orders',
  'gridOrders.tab_history_orders': 'Gefüllte Orders',
  'gridOrders.tab_trade_history': 'Tradeverlauf',
  'gridOrders.detail_current_balance': 'Aktuelles Guthaben',
  'gridOrders.detail_ending_balance': 'Endguthaben',
  'gridOrders.detail_ending_balance_tips':
    'Das Guthaben bei geschlossener Gridstrategie.',
  'gridOrders.detail_in_order_funds': 'Mittel im Order:',
  'gridOrders.detail_on_hold_funds':
    'Zurückgehaltene Mittel (aus teilweise erfüllten Orders):',
  'gridOrders.detail_transactions': 'Anzahl der ausgeführten Orders',
  'gridOrders.detail_investment': 'Erstinvestition',
  'gridOrders.detail_running_time': 'Dauer',
  'gridOrders.detail_prices': 'Preisspanne',
  number_of_grids: 'Anzahl der Grids',
  'gridOrders.detail_expire_time': 'Läuft ab in',
  'gridOrders.detail_expire_time_tooltip':
    'Orders im Rahmen dieser Gridstrategie werden nach deren Ablauf storniert.',
  'gridOrders.detail_valid_period': 'Ablaufeinstellung',
  'gridOrders.open_orders_sell': 'VERKAUFEN',
  'gridOrders.open_orders_buy': 'KAUFEN',
  'gridOrders.open_orders_index': '#',
  'gridOrders.open_orders_total': 'Gesamt',
  'gridOrders.history_orders_filled': 'Gefüllt:',
  'gridOrders.history_orders_price': 'Preis:',
  'gridOrders.history_orders_time': 'Zeit',
  'gridOrders.history_orders_filled_price': 'Durchschnittlicher Preis',
  'gridOrders.history_orders_filled_amount': 'Gefüllt',
  'gridOrders.history_orders_filled_total': 'Gesamt',
  'gridOrders.history_orders_profit_tips':
    'Der Gewinn ergibt sich aus der Preisdifferenz nach einem Zyklus von Käufen zu niedrigen und Verkäufen zu hohen Kursen. Wenn beispielsweise eine Gridorder zum Kauf von 1 ETH zu einem Preis von 4000 USDC ausgeführt wurde und der Gridabstand 50 USDC beträgt, platziert das System automatisch eine neue Order zum Verkauf von 1 ETH zu einem Preis von 4050 USDC. Wenn diese Order ebenfalls ausgeführt wird, wird ein Gewinn von 50 USDC erzielt.',
  'gridOrders.history_orders_buy_flip_order_tips_PRICE':
    'Der Gewinn wird angezeigt, nachdem die Kauforder zum PREIS ausgeführt wurde.',
  'gridOrders.history_orders_sell_flip_order_tips_PRICE':
    'Der Gewinn wird angezeigt, nachdem die Verkaufsorder von PRICE ausgeführt wurde.',
  'gridOrders.m_history_orders_flip_order_tips_PRICE':
    'Die Order zum PREIS wird hier angezeigt, wenn sie gefüllt ist',
  'gridOrders.grid_cancel_title': 'Gridstrategie beenden',
  'gridOrders.grid_cancel_content':
    'Sämtliche Aufträge dieser Gridstrategie werden umgehend storniert.',
  'gridOrders.grid_cancel_content2':
    'Sie betreiben derzeit Mining mit dieser Grid-Strategie. Wenn Sie diese Grid-Strategie beenden, verlieren Sie alle Mining-Belohnungen und alle zugehörigen Grid-Aufträge werden sofort storniert.',
  'gridOrders.copy_grid_title':
    'Die folgenden Gridstrategieparameter werden kopiert',
  'gridOrders.copy_grid_btn': 'In Bedienfeld kopieren',
  'gridOrders.copy_grid_success': 'Gridstrategie kopiert',
  'gridOrders.grid_init_funds_XXX': 'Wert der Anfangsinvestition: $XXX',
  'gridOrders.grid_init_funds_tips':
    'APYs werden basierend auf dem Wert der Erstzuteilung zum Zeitpunkt der Erstellung der Gridstrategie berechnet.',
  'gridOrders.tab_m_trade': 'Handeln',
  grid_apy: 'Grid APY',
  grid_apy_tips:
    'Die annualisierte Gewinnrate nur durch Grid-Handel. Float-Gewinn ausgeschlossen.',
  'gridOrders.tab_mining_profit': 'Mining APY',
  'gridOrders.tab_mining_profit_tips':
    'Die jährlichen Miningprofits werden aus dem Anfangswert und der Dauer der Gridstrategie berechnet.',
  'gridOrders.mining_rewards': 'Belohnungen:',
  'gridOrders.open_orders_empty_tips':
    'Bitte warten, während die Daten geladen werden',
  'gridOrders.market_value': 'Marktwert:',
  'gridOrders.market_value_details': 'Details',
  'gridOrders.fund_details': 'Fondsdetails',
  'gridOrders.m_in_order_funds': 'In-Order Mittel',
  'gridOrders.m_in_order_funds_tips':
    'Gesamtmittel aller offenen Aufträge im Rahmen dieser Grid-Strategie.',
  'gridOrders.m_on_hold_funds': 'Zurückgehaltene Mittel',
  'gridOrders.m_on_hold_funds_tips': 'Ergebnis teilweise ausgeführter Orders.',
  'gridOrders.initial_value': 'Anfangswert',
  'mining.my_title': 'Mein Mining Pool',
  'mining.index_desc':
    'Erstellen Sie eine Gridstrategie. Steigern Sie Ihre Gridgewinne mit Belohnungen aus dem Liquidity-Mining.',
  'mining.apply': 'Neuer Poolantrag',
  'mining.claimable_rewards_box': 'Einforderbare Belohnungen',
  'mining.rewards_more': 'und mehr',
  'mining.tab_pools': 'Mining Pools',
  'mining.tab_my': 'Meine Mining Stats',
  'mining.pools_tab_live': 'Live',
  'mining.pools_tab_upcoming': 'Demnächst',
  'mining.pools_funds': 'Gesamt TVL',
  'mining.pools_funds_tips':
    'Gesamtwert der Grid-Orders, die den Mindestorderwert von $120 erreichen.',
  'mining.pools_mining_funds': 'Mining TVL',
  'mining.mining_apr': 'APY',
  'mining.mining_apr_tips':
    'Geschätzte annualisierte Rendite aus Mining-Belohnungen und Mining-TVL.',
  'mining.view_rule_link': 'Mining Regeln',
  'mining.pools_info_to_confirm': 'Wird noch festgelegt',
  'mining.pools_no_wait': 'Keine Mining-Pools verfügbar',
  'mining.my_mining_funds': 'Meine Mining Mittel',
  'mining.my_mining_rewards': 'Meine Mining Belohnungen',
  'mining.my_th_profit_token_price': 'Letzter Preis',
  'mining.my_th_total_rewards': 'Gesamtbelohnungen',
  'mining.my_th_24h_rewards': '24h Belohnungen',
  'mining.my_grids': 'Mein Mining',
  'mining.only_show_mining_grids': 'Nur Aktiv',
  'mining.my_th_mining_status': 'Mining Status',
  'mining.status_framing': 'Aktiv',
  'mining.status_over_price': 'Außerhalb der Preisspanne',
  'mining.status_mining_over': 'Mining beendet',
  'mining.status_grid_closed': 'Strategie beendet',
  'mining.status_grid_expired': 'Strategie abgelaufen',
  'mining.empty_no_faring_grids': 'Derzeit keine Gridstrategie mit Mining',
  'mining.go_mining_pool': 'Gehe zum Mining Pool',
  'mining.go_mining': 'Mining starten',
  'mining.go_to_grid': 'Zur Gridstrategie',
  'mining.mining_help': 'Mining Guide',
  'mining.mining_available': 'Berechtigt',
  'mining.mining_available_tips': 'Orderwertkriterien erfüllt',
  'mining.mining_unavailable': 'Nicht berechtigt',
  'mining.mining_partially_available': 'Teilweise berechtigt',
  'mining.mining_unavailable_tips': 'Orderwertkriterien nicht erfüllt',
  'mining.mining_preview': 'Mining Vorschau',
  'mining.mining_total_profit': 'Mining Belohnungen',
  'mining.mining_24h_profit': '24h Mining Belohnungen',
  'mining.profit_unable_display': 'N/A',
  'mining.mining_funds': 'Mining Mittel',
  'mining.mining_funds_tips':
    'Der Gesamtwert der Aufträge aus allen Grid-Strategien, die die Mining-Orderwertkriterien für dieses Handelspaar erfüllen.',
  'mining.tab_mining_profit_details': 'Details zur Belohnung',
  'mining.tab_mining_orders': 'Mining Orders',
  'mining.th_rewards': 'Belohnung',
  'mining.th_rewards_origin': 'Belohnungsquelle',
  'mining.th_rewards_origin_tips':
    'Die Mining-Belohnung wird ausgezahlt, wenn der Grid-Order-Preis innerhalb der Belohnungspreisspanne des Orderbuchs liegt (höchster Kaufpreis * 0,99 ~ niedrigster Verkaufspreis * 1,01).',
  'mining.th_rewards_origin_tips_stable':
    'Die Mining-Belohnung wird ausgezahlt, wenn der Grid-Order-Preis innerhalb der Belohnungspreisspanne des Orderbuchs liegt (höchster Kaufpreis ~ niedrigster Verkaufspreis).',
  'mining.th_time': 'Zeit',
  'mining.plan_title': 'ETH/USDC Pool Details',
  'mining.phase_cur': 'Aktuelle Phase',
  'mining.phase_range_N_XX': 'Phase N (XX)',
  'mining.phase_index_N': 'Phase N',
  'mining.phase_reward': 'Tägliche Belohnungen',
  'mining.phase_to_release': 'Wird noch bekannt gegeben',
  'mining.my_rewards': 'Meine Belohnungen',
  'mining.claimable_rewards': 'Verfügbar',
  'mining.locked_rewards': 'Gesperrt',
  'mining.locker_rewards_tips':
    'Mining-Belohnungen können erst beansprucht werden, nachdem die Grid-Strategie 12 Stunden lang aktiv war.',
  'mining.claimed_success': 'Anspruch erfolgreich',
  'mining.claimed_tips':
    'Wird Ihnen in Kürze per interner Überweisung zugesandt',
  'mining.claimed_view_btn': 'Checken gehen',
  'mining.mining_plan': 'Mining Zeitplan',
  'mining.phase_unpublished': 'Wird noch bekannt gegeben',
  'mining.all_pools': 'Alle Pools',
  'notification.limit_desc_SELL_BASE_QUOTE_AMOUNT_PRICE':
    'Verkaufe AMOUNT BASE @ PRICE QUOTE',
  'notification.limit_desc_BUY_BASE_QUOTE_AMOUNT_PRICE':
    'Kaufe AMOUNT BASE @ PRICE QUOTE',
  'notification.stop_limit_desc_SELL_BASE_AMOUNT': 'Verkaufe AMOUNT BASE',
  'notification.stop_limit_desc_BUY_BASE_AMOUNT': 'Kaufe AMOUNT BASE',
  'notification.cancel_grid_desc_PAIR_PRICES': 'PAIR: PRICES',
  'notification.cancel_market_desc_SELL_BASE_QUOTE_AMOUNT':
    'Verkaufe AMOUNT BASE für QUOTE',
  'notification.cancel_market_desc_SELL_BASE_QUOTE_TOTAL':
    'Verkaufe BASE für TOTAL QUOTE',
  'notification.cancel_market_desc_BUY_BASE_QUOTE_AMOUNT':
    'Kaufe AMOUNT BASE mit QUOTE',
  'notification.cancel_market_desc_BUY_BASE_QUOTE_TOTAL':
    'Kaufe BASE mit TOTAL QUOTE',
  'notification.cancel_limit': 'Limit Order storniert',
  'notification.cancel_stop_limit': 'Stop limit order storniert',
  'notification.cancel_market': 'Marktorder storniert',
  'notification.cancel_grid': 'Gridstrategie beendet',
  'notification.cancel_limit_expired': 'Limit order abgelaufen',
  'notification.cancel_stop_limit_expired': 'Stop limit order abgelaufen',
  'notification.cancel_grid_expired': 'Gridstrategie abgelaufen',
  'notification.cancel_limit_order_for_gas_desc':
    'Für Ihre Order ist die Gasgebühr aufgebraucht. Sie wurde teilweise ausgeführt, der Rest wurde storniert.',
  'notification.cancel_limit_order_for_gas_filled_amount': 'Ausgeführt',
  'notification.cancel_limit_order_for_gas_amount': 'Betrag',
  'notification.view_history_orders': 'Orderverlauf anzeigen',
  'notification.cancel_market_for_depth_title':
    'Order teilweise ausgeführt und storniert',
  'notification.price_slippage_protection': 'Schutz gegen Preisabweichungen',
  'notification.price_slippage_protection_desc':
    'DeGate Market Orders enthalten automatisch einen 10%igen Schutz gegen Kursabweichungen, um Verluste bei hoher Volatilität und geringer Liquidität zu begrenzen. Verwenden Sie Limit-Orders, um diesen Schutz zu umgehen.',
  'notification.cancel_market_for_depth_warning':
    'DeGate Market Order führt einen Preisschutzmechanismus ein, der es den Nutzern ermöglicht, Verluste in Marktsituationen mit hoher Preisvolatilität und geringer Liquidität zu reduzieren. Wenn Sie den Preisschutzmechanismus nicht auslösen möchten, verwenden Sie bitte den Limit-Order-Modus.',
  'notification.dca_plan_ended': 'DCA Plan beendet',
  'notification.cancel_dca_desc_PAIR': 'PAIR',
  'notification.trade_limit_partially': 'Limit Order teilweise gefüllt',
  'notification.trade_limit_filled': 'Limit Order ausgeführt',
  'notification.trade_market_partially': 'Markt Order teilweise gefüllt',
  'notification.trade_market_filled': 'Markt Order gefüllt',
  'notification.trade_stop_limit_partially':
    'Stop Limit Order teilweise gefüllt',
  'notification.trade_stop_limit_filled': 'Stop Limit Order gefüllt',
  'notification.mobile_trade_filled_AMOUNT_TOKEN':
    'Order ausgeführt. AMOUNT TOKEN erhalten.',
  'notification.mobile_trade_partially_AMOUNT_TOKEN':
    'Order teilweise gefüllt. AMOUNT TOKEN erhalten.',
  'info.overview': 'Überblick',
  'info.accounts': 'Benutzer insgesamt',
  'info.pairs': 'Handelspaare',
  'info.turnover': 'Gesamtvolumen',
  'info.turnover_24': '24h Volumen',
  'info.dg_supply': 'DG Circulating Supply',
  'info.top_movers_no_increased':
    'Kein Token hat innerhalb von 24 Stunden einen Preisanstieg erfahren',
  'info.top_movers_no_decreased':
    'Kein Token ist innerhalb von 24 Stunden im Preis gesunken',
  'info.top_pairs': 'Top Paare',
  Pair: 'Paar',
  'info.th_change': '24h Veränderung',
  'info.th_l_up_2': '+2% Tiefe',
  'info.th_l_down_2': '-2% Tiefe',
  'info.th_turnover_24': '24h Volumen',
  'info.tvl': 'Total Value Locked',
  'm.home': 'Home',
  'm.grid': 'Grid',
  'm.browser_wallet': 'Browser Wallet',
  'm.choose_pair': 'Paar auswählen',
  'm.orderBook_default': 'Standard',
  'm.orderBook_bids': 'Kauforders',
  'm.orderBook_asks': 'Verkaufsorders',
  'm.decimals': 'Dezimal',
  'm.lowest_price_24h': '24h Tief',
  'm.highest_price_24h': '24h Hoch',
  'm.vol_24h': '24h Vol',
  'm.orderbook_buy': 'Kaufen',
  'm.orderbook_sell': 'Verkaufen',
  'm.go_to_trade': 'Zum Trading gehen',
  'm.choose_token': 'Token auswählen',
  'm.from_address': 'Senderadresse',
  'm.to_address': 'Empfängeradresse',
  'm.transfer_send': 'Senden',
  'm.transfer_receive': 'Empfangen',
  'm.my_grid': 'Meine Gridstrategie',
  'm.grid_profit_24': '24h Profit',
  'm.grid_item_trades_24': '24h Trades',
  'm.grid_profit_total': 'Gesamtprofit',
  'm.grid_over_prices': 'Außerhalb der Preisspanne',
  'm.create_grid': 'Gridstrategie erstellen',
  'm.grid_history': 'Verlauf',
  'm.grid_empty': 'Keine aktive Gridstrategie',
  'm.grid_tutorial': 'Grid Tutorial',
  'm.grid_params_to_manual': 'Parameter nach Manual kopieren',
  'm.balance_err': 'Unzureichendes Guthaben. Verfügbar:',
  'm.preview_grid': 'Preview Orders',
  last_price: 'Letzter Preis',
  'm.grid_desc':
    'Grid-Trading ist eine Handelsstrategie, die Kaufen und Verkaufen innerhalb eines definierten Bereichs automatisiert.',
  'm.view_tutorial': 'Tutorial ansehen',
  'm.grid_profit_tips_sell':
    'Wird berechnet, wenn dieser Verkaufsauftrag vollständig ausgeführt ist.',
  'm.grid_profit_tips_buy':
    'Wird berechnet, wenn diese Kauforder vollständig ausgeführt ist.',
  'm.hot': 'Heiß',
  'm.all': 'Alle',
  'm.vol_24': '24h Vol',
  'm.transfer_t1': 'Intern',
  'm.transfer_t2': 'Transfer',
  'activity.th_date': 'Zeit',
  'activity.th_type': 'Typ',
  'activity.th_fee': 'Gebühr',
  'activity.th_content': 'Inhalt',
  'activity.type_register_token': 'Token Listing',
  'activity.type_register_pair': 'Paar hinzufügen',
  'activity.type_pay_deposit': 'Abrechnung der Einzahlung',
  'activity.type_reset_account': 'Asset Key zurücksetzen',
  on_chain_order_cancellation: 'On-Chain Order Stornierung',
  'activity.count_N': 'Anzahl: N',
  'activity.order_desc_SELL_AMOUNT_BASE_PRICE_QUOTE':
    'SELL AMOUNT BASE @PRICE QUOTE',
  'activity.order_market_desc_SELL_AMOUNT_BASE': 'SELL AMOUNT BASE',
  'activity.reset_status_restting': 'Zurücksetzen',
  'activity.to_trade': 'Handeln',
  'dca.dca_plan': 'DCA Plan',
  'dca.dca_explain': 'Dollar-cost Averaging',
  'dca.daily': 'Täglich',
  'dca.weekly': 'Wöchentlich',
  'dca.custom': 'Benutzerdefiniert',
  'dca.every': 'Jede',
  'dca.amount_per_order': 'Betrag pro Order',
  'dca.price_limit': 'Preislimit',
  'dca.maximum_price': 'Höchstpreis',
  'dca.minimum_price': 'Mindestpreis',
  'dca.number_of_orders': 'Orderanzahl',
  'dca.create_dca_plan': 'DCA Plan erstellen',
  'dca.max_gas_fee_per_order': 'Maximale Gasgebühr pro Order',
  'dca.maximum_plan_order_limit_reached':
    'Die maximale Anzahl an Planorders wurde erreicht.',
  'dca.end_time_should_be_set_after_the_current_time':
    'Die Endzeit sollte nach der aktuellen Zeit liegen',
  'dca.please_enter_amount_per_order':
    'Bitte geben Sie den Betrag pro Order ein',
  'dca.please_enter_maximum_price': 'Bitte geben Sie den Höchstpreis ein',
  'dca.please_enter_minimum_price': 'Bitte geben Sie den Mindestpreis ein',
  'dca.order_placement_failed_open_order_limit_exceeded':
    'Auftragserteilung fehlgeschlagen: Limit für offene Orders überschritten.',
  'dca.total': 'Gesamt',
  'dca.filled': 'Ausgeführt',
  'dca.received': 'Erhalten',
  'dca.time_to_end': 'Zeit bis Ende',
  'dca.cancel_on_chain': 'On-Chain abbrechen',
  'dca.filled_amount': 'Ausgeführt/Menge',
  'dca.status_executed': 'Ausgeführt',
  'dca.status_scheduled': 'Geplant',
  'dca.status_failed': 'Fehlgeschlagen',
  'dca.order_cancled_by_user':
    'Order storniert, weil Benutzer den DCA-Plan beendet hat.',
  'dca.order_cancled_by_access':
    'Order storniert, da Ihr Zugriff auf DeGate eingeschränkt ist.',
  'dca.order_cancled_by_gas':
    'Die Auftragserteilung ist aufgrund unzureichender Gasgebühr fehlgeschlagen.',
  'dca.order_cancled_by_order_book':
    'Die Auftragserteilung ist fehlgeschlagen, da im Orderbuch keine entsprechende Order vorhanden war.',
  'dca.order_cancled_by_balance':
    'Die Auftragserteilung ist aufgrund eines unzureichenden DeGate-Guthabens fehlgeschlagen.',
  'dca.order_cancled_by_min_value':
    'Die Auftragserteilung ist fehlgeschlagen, da der Mindestorderwert von 100 $ nicht erreicht wurde.',
  'dca.order_cancled_by_system_error':
    'Aufgrund eines Systemfehlers ist die Auftragserteilung fehlgeschlagen.',
  'dca.chain_cancel_no_need_tips':
    'Dieser DCA-Plan erfordert keine On-Chain-Stornierung.',
  'dca.end_dca_plan': 'DCA-Plan beenden',
  'dca.all_orders_in_this_dca_plan_will_be_canceled_immediately':
    'Alle Orders in diesem DCA-Plan werden sofort storniert.',
  'dca.no_active_dca_plan': 'Kein aktiver DCA-Plan',
  'dca.time_scheduled': 'Geplante Zeit',
  'campaign.event_period': 'Zeitraum des Events:',
  'campaign.grid2401_time':
    'Januar 22, 2024, 20:00:00 - Januar 29, 2024, 20:00:00 (UTC+8)',
  'campaign.event_has_ended': 'Das Event ist beendet.',
  'campaign.current_apy': 'Aktueller jährlicher Prozentsatz (APY)',
  'campaign.grid_strategy_income':
    'Grid Strategy-Einkommen + Anteil am Preispool',
  'campaign.tvl_participating': 'TVL Beteiligt',
  'campaign.share_of_tvl': 'Anteil von TVL',
  'campaign.my_profit': 'Mein Gewinn',
  'campaign.grid_strategy_profit': 'Gridstrategie Gewinn',
  'campaign.share_of_prize_pool': 'Anteil am Preispool',
  'campaign.grid_strategy_profit_has_been_added_to_your_available_balance':
    'Der Grid-Strategie-Gewinn wurde Ihrem verfügbaren Guthaben hinzugefügt.',
  'campaign.shared_income_from_usdc_prize_pool':
    'Geteiltes Einkommen aus dem USDC-Preispool',
  'campaign.is_black_tips':
    'Sie haben keinen Anspruch auf einen Anteil am Preispool.',
  'campaign.calculating': 'Berechnen',
  'campaign.claim_after_end':
    'Der Preis kann am Ende des Events eingefordert werden.',
  'campaign.how_to_participate': 'So können Sie teilnehmen',
  'campaign.rule':
    'Erstellen Sie eine Grid-Strategie und beteiligen Sie sich anteilig am Preispool.',
  'campaign.step1': '1. Schritt',
  'campaign.step2': '2. Schritt',
  'campaign.step3': '3. Schritt',
  'campaign.grid2401_step1':
    'Bereiten Sie Ihr ETH und USDC vor, indem Sie Guthaben hinzufügen oder handeln',
  'campaign.grid2401_step2_PAIR':
    'Richten Sie eine Gridstrategie für PAIR wie unten beschrieben ein',
  'campaign.grid2401_step2_desc1_pre': 'Preisspanne: Wird noch bekannt gegeben',
  'campaign.grid2401_step2_desc2_pre':
    'Anzahl der Grids: Wird noch bekannt gegeben',
  'campaign.copy_strategy': 'Strategie kopieren',
  'campaign.grid2401_step3':
    'Nach Ende des Events können Sie Ihre Einnahmen auf dieser Eventseite einfordern. Bitte fordern Sie sie innerhalb von 30 Tagen nach Ende des Events ein.',
  'campaign.what_is_grid': 'Was ist Gridstrategie',
  'campaign.notes': 'Bitte beachten Sie vor dem Beitritt',
  'campaign.notes_1_title': 'Teilnahmeberechtigung:',
  'campaign.notes_1_desc':
    'Die Grid-Strategie ist nur zulässig, wenn die Preisspanne und die Anzahl der Grids genau mit den Anforderungen zum Zeitpunkt der Erstellung übereinstimmen.',
  'campaign.notes_2_title': 'Limit:',
  'campaign.notes_3_title': 'Beanspruchen:',
  'campaign.notes_3_desc':
    'Die Preise können am Ende des Events angefordert werden und sind innerhalb von 30 Tagen nach Ende des Events gültig.',
  'campaign.faq': 'FAQ',
  'campaign.grid2401_faq_1': '1. Wie werden Belohnungen berechnet?',
  'campaign.grid2401_faq_2':
    '2. Wo bekomme ich Hilfe bei Fragen zu diesem Event?',
  'campaign.grid2401_faq_3':
    '3. Ich besitze USDT, wie kann ich ETH und USDC erhalten?',
  'campaign.grid2401_faq_4':
    '4. Muss ich für Transaktionen, die über die Grid-Strategie abgeschlossen werden, eine Gebühr bezahlen?',
  'campaign.grid2401_faq_4_res':
    'Bei DeGate sind alle Maker-Aufträge kostenlos. Aufträge, die durch die Grid-Strategie generiert werden, sind alle Maker-Aufträge, daher ist das Einrichten einer Grid-Strategie bei DeGate völlig kostenlos.',
  'campaign.grid2401_faq_5':
    '5. Wird meine Gridstrategie auch nach dem Ende des Events noch Einnahmen generieren?',
  'campaign.grid2401_faq_5_res':
    'Ja, nach dem Ende des Events wird die Strategie weiterhin Einkommen generieren, solange der Preis noch innerhalb Ihres Grid-Strategiebereichs liegt. Nach dem Event können Sie auch die Parameter Ihrer Grid-Strategie anpassen, um eine Strategie zu erstellen, die besser zu Ihren eigenen Präferenzen passt, und weiterhin Einkommen erzielen.',
  'campaign.grid2401_faq_others': 'Weitere Eventdetails',
  'campaign.grid2401_faq_others_1':
    '1. Nur eine einzige Wallet pro Benutzer. Wenn böswilliges Sybil-Reward-Farming erkannt wird, behält sich DeGate das Recht vor, die Rewards eines Teilnehmers zu stornieren.',
  'campaign.grid2401_faq_others_2':
    '2. Während des Events werden auch Grids, die außerhalb des Bereichs liegen, bei der Gewichtungsberechnung berücksichtigt.',
  'campaign.grid2401_faq_others_3':
    '3. DeGate behält sich das Recht vor, das Event in extremen Fällen, z. B. aufgrund von Marktvolatilität, vorzeitig zu beenden.',
  'campaign.grid2401_faq_others_4':
    '4. Belohnungen, die nicht innerhalb von 30 Tagen nach Ende des Events eingefordert werden, verfallen.',
  'campaign.invest_max_5000': 'Maximal $5000 investieren',
  'campaign.invest_mininum': 'Minimum investieren',
  'airdrop.create_airdrop': 'Airdrop erstellen',
  'airdrop.important_note':
    'Wichtig: Jeder kann Airdrops ohne Erlaubnis erstellen',
  'airdrop.my_airdrop': 'Meine Airdrops',
  'airdrop.time_limited': 'Zeitlich befristet',
  'airdrop.no_airdrop': 'Noch kein Airdrop',
  'airdrop.claim_airdrop': 'Airdrop beantragen',
  'airdrop.recipients_number': 'Anzahl der Empfänger',
  'airdrop.total_amount': 'Gesamtbetrag',
  'airdrop.retrieve': 'Abrufen',
  'airdrop.unclaimed': 'Nicht beansprucht',
  'airdrop.retrieve_successful': 'Abruf erfolgreich',
  'airdrop.claim_successful': 'Anspruch erfolgreich',
  'airdrop.retrieve_unclaimed_airdrop': 'Nicht beanspruchten Airdrop abrufen',
  'airdrop.airdrop_token': 'Airdrop Token',
  'airdrop.token_not_meet_criteria':
    'Dieses Token erfüllt nicht die Airdrop-Kriterien',
  'airdrop.airdrop_list': 'Airdrop Liste',
  'airdrop.download_template': 'Template herunterladen',
  'airdrop.click_or_drag_upload_list':
    'Klicken oder ziehen, um Liste hochzuladen',
  'airdrop.validation_passed': 'Bestätigt',
  'airdrop.must_earlier_than_end_time': 'Muss vor der Endzeit sein',
  'airdrop.cannot_more_than_2_years_from_now':
    'Kann nicht mehr als 2 Jahre in der Zukunft liegen',
  'airdrop.cannot_parse_file':
    'Die Datei kann nicht geparst werden. Bitte verwenden Sie die Vorlage.',
  'airdrop.format_requirement_not_met': 'Formatanforderung nicht erfüllt',
  'airdrop.view_error_repost': 'Fehlerbericht anzeigen',
  'airdrop.error_report': 'Fehlerbericht',
  'airdrop.line': 'Linie',
  'airdrop.reason': 'Grund',
  'airdrop.duplicated_address': 'Doppelte Adresse',
  incorrect_address_format: 'Falsches Adressformat',
  'airdrop.incorrect_amount_format': 'Falsches Betragsformat',
  'airdrop.airdrop_plan_created': 'Airdrop Plan erstellt',
  'airdrop.max_50000': 'Max 50000 Adressen',
  'airdrop.upload_file_rule': 'Unterstützt nur CSV.',
  'airdrop.to_check_airdrop_eligibility':
    'Schließen Sie die Initialisierung ab, um Airdrops anzuzeigen',
  'airdrop.complete_initialization_to_claim_airdrops':
    'Schließen Sie die Initialisierung ab, um Airdrops zu beanspruchen',
  'airdrop.complete_initialization_to_view_airdrops':
    'Schließen Sie die Initialisierung ab, um Airdrops anzuzeigen',
  'airdrop.you_are_eligible_for': 'Sie haben Anspruch auf:',
  'airdrop.and_more': 'und mehr',
  'airdrop.congratulations': 'Glückwunsch!',
  'airdrop.airdrop_fee': 'Airdrop Gebühr',
  'countdown.countdown_plan': 'Countdown Plan',
  'countdown.create_countdown_plan': 'Countdown erstellen',
  'countdown.my_countdown_plan': 'Meine Kreationen',
  'countdown.countdown_trading_pair': 'Countdown Handelspaar',
  'countdown.countdown_display': 'Countdown Anzeige',
  'countdown.token_not_meet_criteria':
    'Dieses Token erfüllt nicht die Countdown-Kriterien',
  'countdown.countdown_tips':
    'Der Countdown wird auf der Handelsseite für die ausgewählten Handelspaare angezeigt',
  'countdown.max_30_days': 'Kann nicht mehr als 30 Tage in der Zukunft liegen',
  'countdown.review_countdown_plan': 'Countdown Plan überprüfen',
  'countdown.countdown_fee': 'Countdown Gebühr',
  'countdown.countdown_plan_created': 'Countdown Plan erstellt',
  'countdown.trading_will_start_in': 'Der Handel beginnt in',
  'countdown.trading_will_start_at_YYYY': 'Der Handel beginnt um YYYY',
  'countdown.cannot_earlier_than_current_time':
    'Darf nicht vor der aktuellen Zeit liegen',
  'dca.price_limit_buy_tips':
    'Sobald diese Funktion aktiviert ist, werden Ihre Kaufaufträge nur zu Preisen ausgeführt, die dem Höchstpreis entsprechen oder darunter liegen. Diese Funktion ist mit der Funktion „Null Gebühr“ kompatibel.',
  'dca.price_limit_sell_tips':
    'Sobald diese Funktion aktiviert ist, werden Ihre Verkaufsaufträge nur zu Preisen ausgeführt, die dem Mindestpreis entsprechen oder darüber liegen. Diese Funktion ist mit der Funktion „Null Gebühr“ kompatibel.',
  'dca.zero_fee': 'Keine Gebühr',
  'dca.zero_fee_buy_tips':
    'Wenn die Nullgebühr aktiviert ist, werden DCA-Aufträge als Maker-Only-Limitaufträge verarbeitet. Jeder Kaufpreis wird nach der Platzierung auf den höchsten Gebotspreis im Orderbuch festgelegt. Beachten Sie, dass Ihre Aufträge möglicherweise nicht sofort oder möglicherweise überhaupt nicht ausgeführt werden.',
  'dca.zero_fee_sell_tips':
    'Wenn die Nullgebühr aktiviert ist, werden DCA-Aufträge als Maker-Only-Limitaufträge verarbeitet. Jeder Verkaufspreis wird nach der Platzierung auf den niedrigsten Briefkurs im Orderbuch festgelegt. Beachten Sie, dass Ihre Aufträge möglicherweise nicht sofort oder möglicherweise überhaupt nicht ausgeführt werden.',
  'dca.order_canceled_post_only_buy_failed':
    'Die Auftragserteilung ist fehlgeschlagen, da im Orderbuch keine Kaufaufträge vorliegen. Dadurch konnte der Kaufpreis für Ihre Order nicht festgelegt werden.',
  'dca.order_canceled_post_only_sell_failed':
    'Die Auftragserteilung ist fehlgeschlagen, da im Orderbuch Verkaufsaufträge fehlen. Dadurch konnte der Verkaufspreis Ihrer Order nicht festgelegt werden.',
  start_time_cannot_before_current_time:
    'Die Startzeit kann nicht vor der aktuellen Zeit liegen',
  start_time_must_before_end_time: 'Die Startzeit muss vor der Endzeit liegen',
  list_token: 'Token listen',
  contract_address_does_not_exist: 'Contractadresse existiert nicht',
  token_listed: 'Dieses Token wurde gelistet',
  XXX_is_listed: 'XXX wird gelistet',
  view_progress: 'Fortschritt anzeigen',
  pair_create_tips:
    'Handelspaare können auf DeGate sofort und ohne Zustimmung irgendeiner Partei hinzugefügt werden.',
  base_token: 'Base Token',
  quote_token: 'Quote Token',
  existing_pair: 'Existierendes Paar',
  trade_now: 'Jetzt Handeln',
  pair_XXX_added_successfully: 'XXX erfolgreich hinzugefügt',
  qty_per_grid: 'Menge pro Grid',
  grid_minimum_not_reached: 'Mindestwert nicht erreicht',
  total_profit: 'Gesamtgewinn',
  total_apy: 'Gesamt APY',
  float_profit: 'Float Gewinn',
  grid_profit_24h: '24h Grid Profit',
  pnl: 'PnL',
  eligibility: 'Berechtigung',
  rewards: 'Belohnungen',
  view_mining_statistics: 'Mining Statistiken anzeigen',
  your_entry: 'Fondseinsatz',
  refunded: 'Zurückgegeben',
  large_price_spread: 'Große Preisspanne',
  large_price_spread_tips:
    'Das Orderbuch weist eine große Spanne zwischen dem niedrigsten Verkaufs- und dem höchsten Kaufpreis auf, was ein Verlustrisiko darstellt. Es wird empfohlen, im Dual-Asset-Modus zu investieren.',
  continue_anyway: 'Trotzdem fortfahren',
  insufficient_order_book_liquidity_decrease_investment:
    'Unzureichende Liquidität im Orderbuch. Reduzieren Sie Ihre Investitionen.',
  initial_buy: 'Erstkauf',
  closing_sell: 'Verkaufsabschluss',
  No: 'Nein',
  DCA_TRIGGER_FAIL_TIPS_PRICE_XXX:
    'DCA-Aufträge schlagen fehl, wenn der Preis von <b>$XXX zum Zeitpunkt der Ausführung unter $PRICE</b> fällt.',
  zero_fee: 'Nullgebühr',
  minimum_order_value_is_VALUE: 'Der Mindestorderwert beträgt <b>$VALUE</b>.',
  Note: 'Notiz',
  Continue: 'Fortfahren',
  estimated_apy: 'Geschätzter APY',
  based_on_data_from_last_7_days: 'Basierend auf Daten der letzten 7 Tage',
  top_gainers_24h: '24h Top Gewinner',
  top_losers_24h: '24h Top Verlierer',
  listed_tokens: 'Gelistete Token',
  vol: 'Vol',
  let_s_go: "Los geht's",
  reject: 'Ablehnen',
  maximum_N_due_to_price_ticks: 'Maximales N aufgrund von Preis-Ticks',
  Saved: 'Gespeichert',
  minimum_order_value_$100_$QUOTE:
    'Der Mindestorderwert beträgt <b>$100 $QUOTE</b>',
  minimum_order_value_$AMOUNT_$QUOTE_$100:
    'Der Mindestorderwert beträgt <b>$AMOUNT $QUOTE</b>(~$$100)',
  no_restriction_with_market_order:
    'Keine Einschränkung bei <b>Market Order</b>',
  go_to_market_order: 'Zur Market Order',
  Mining_Eligibility: 'Mining Berechtigung',
  How_to_earn_mining_rewards: 'So verdienen Sie Mining-Belohnungen',
  Order_Value: 'ORDERWERT',
  'mining.mining_tips_BV_BASE_QV_QUOTE':
    'Grid-Orders müssen zum Zeitpunkt der Strategieerstellung mindestens <b>BV BASE</b> oder <b>QV QUOTE</b> sein.',
  'mining.mining_tips_QV_QUOTE':
    'Grid-Orders müssen zum Zeitpunkt der Strategieerstellung mindestens <b>QV QUOTE</b> sein.',
  Mining_Price_Range: 'MINING PREISSPANNE',
  'mining.status_over_price_tips':
    'Die Preise der Grid-Orders müssen innerhalb der <b>Mining-Preisspanne</b> liegen, die vom höchsten Kaufpreis * 0,99 bis zum niedrigsten Verkaufspreis *1,01 im Orderbuch reicht.',
  'mining.status_over_price_tips_stable':
    'Die Preise für Grid-Orders müssen innerhalb der <b>Mining-Preisspanne</b> liegen, die vom höchsten Kaufpreis bis zum niedrigsten Verkaufspreis im Orderbuch reicht.',
  Eligible_for_Mining: 'Zum Mining berechtigt',
  Mining_Satus: 'Mining Status',
  Mining_Satus_Mining: 'Mining',
  Mining_Satus_Standby: 'Standby',
  Mining_Satus_Ineligible: 'Unzulässig',
  mining_price_range: 'Mining Preisspanne',
  rewards_tips_stable:
    'Grid-Orders, die das Kriterium des Mining-Order-Werts bei der Strategieerstellung erfüllen, erhalten Mining-Belohnungen, wenn sie innerhalb der Mining-Preisspanne (höchster Kaufpreis ~ niedrigster Verkaufspreis) liegen.',
  rewards_tips:
    'Grid-Orders, die das Kriterium des Mining-Order-Werts bei der Strategieerstellung erfüllen, erhalten Mining-Belohnungen, wenn sie innerhalb der Mining-Preisspanne liegen (höchster Kaufpreis * 0,99 ~ niedrigster Verkaufspreis * 1,01).',
  wrap: 'wrap',
  Wrap: 'Wrap',
  websites_for_more_information: 'Websites für weitere Informationen:',
  official_site: 'Offizielle Website',
  wrap_site: 'Site einpacken/auspacken',
  tips_third_party_site:
    'Sie sind dabei, DeGate zu verlassen und eine Website eines Drittanbieters aufzurufen:',
  wrap_unwrap: 'Einpacken/Auspacken',
  Receive: 'Erhalten',
  Network: 'Netzwerk',
  Token_Contract: 'Token Contract',
  please_select_network: 'Bitte wählen Sie ein Netzwerk',
  maximum_amount: 'Höchstbetrag',
  send_USDC_to_this_address: 'Senden Sie USDC an diese Adresse',
  arpa_airdrop: '$ARPA Airdrop',
  Failed_to_proceed: 'Fortfahren fehlgeschlagen.',
  Please_select_the_Ethereum_network:
    'Bitte wählen Sie das Ethereum-Netzwerk aus.',
  NATIVE_USDC_ONLY: 'NUR natives USDC Token',
  NEVER_send_bridged_USDC: 'Senden Sie NIEMALS bridged USDC',
  I_understand: 'Ich verstehe',
  recipient_address: 'Empfängeradresse',
  chain_0: 'DeGate',
  chain_1: 'Ethereum',
  chain_17000: 'Ethereum',
  chain_42: 'Kovan',
  chain_42161: 'Arbitrum',
  chain_421614: 'Arbitrum',
  chain_10: 'Optimism',
  chain_11155420: 'Optimism',
  chain_137: 'Polygon',
  chain_80002: 'Polygon',
  scan_1: 'Etherscan',
  scan_17000: 'Etherscan',
  scan_42161: 'Arbiscan',
  scan_421614: 'Arbiscan',
  scan_10: 'Opscan',
  scan_11155420: 'Opscan',
  scan_tips:
    'Die Rollup-Transaktion, die diese Aktion enthält, wurde noch nicht auf Ethereum veröffentlicht. Bis dies der Fall ist, wird DGSCAN diese Aktion <b>NICHT</b> anzeigen.',
  Best_Liquidity: 'Beste Liquidität',
  order_partially_filled: 'Bestellung teilweise ausgeführt',
  order_partially_filled_for_liquidity:
    'Ihre verbleibende Order wurde aufgrund eines plötzlichen Rückgangs der Liquidität im Orderbuch storniert. Diese Schutzmaßnahme verhindert Ausführungen zu ungünstigen Preisen.',
  'orders.export_data_2_year': 'Daten der letzten 2 Jahre exportieren',
  Community: 'Community',
  complete_in_seconds: 'In Sekundenschnelle fertig',
  failed_to_send: 'Senden fehlgeschlagen. Bitte versuchen Sie es erneut.',
  failed_to_send_try_other_networks:
    'Senden fehlgeschlagen. Bitte versuchen Sie es mit anderen Netzwerken.',
  gas_fee_deducted: 'Abgezogene Gasgebühr:',
  sum_XXX: 'Summe XXX',
  chart_control_7d: '7D',
  chart_control_30d: '30D',
  chart_control_all: 'Alle',
  chart_control_day: 'D',
  chart_control_week: 'W',
  chart_control_month: 'M',
  Coming: 'Kommend',
  leave_survey_title: 'Hey, sieht aus, als ob du DeGate verlässt.️',
  leave_survey_subtitle:
    'Helfen Sie uns mit Ihrem Feedback, uns zu verbessern. Wählen Sie alle zutreffenden Antworten aus.',
  leave_survey_not_leaving: 'Ich gehe nicht weg, ich komme zurück, du Dummie.',
  leave_survey_other_is_fine:
    'Binance/OKX/Kraken usw. funktionieren bei mir einwandfrei.',
  leave_survey_bad_experience: 'Mir gefällt das Handelserlebnis nicht.',
  leave_survey_no_yield: 'Ich habe keine Möglichkeiten für Rendite gefunden.',
  leave_survey_no_needed_token:
    'Ich habe die Token, die ich handeln möchte, nicht gefunden.',
  leave_survey_other_reason:
    'Andere (bitte lassen Sie es uns im Feld unten wissen)',
  leave_survey_thanks_for_feedback: 'Vielen Dank für Ihr Feedback',
  Submitted: 'Eingereicht',
  doc_title:
    'DeGate: Dezentrale Orderbuchbörse | Kostenloser Krypto-Trading-Bot auf GRID und DCA',
  doc_desc:
    'DeGate ist eine führende dezentrale Orderbuchbörse, die den Handel mit Hunderten von Kryptowährungen zu niedrigen Gebühren anbietet, mit kostenlosem Limit-Order-Handel, Grid-Trading und DCA-Bots.',
  doc_title_spot: '| Dezentrales Orderbuch | DeGate DEX',
  doc_title_grid: '| Dezentraler Grid-Trading-Bot | DeGate DEX',
  doc_title_dca: '| Dezentraler DCA-Handelsbot | DeGate DEX',

  Notification: '',
  read_all: '',
  important: '',
  general: '',
  view_more: 'Mehr',
  thats_all: '',
  XXX_fund_addition_processing: '',
  add_AMOUNT_XXX_to_DeGate: '',
  XXX_fund_addition_successful: '',
  XXX_send_successful: '',
  send_AMOUNT_XXX_to_DeGate: '',
  send_AMOUNT_XXX_to_Ethereum: '',
  you_have_received_a_new_airdrop: '',
  AMOUNT_XXX_can_be_claimed_after_YYYY_MM_DD: '',
  MARKET_Chart: '',
  grid_free: '',
  maker_free_tips: '',
  Audit: '',
  Tool: '',
  About: '',
};

export default de;
