const ja = {
  language: 'ja-JP',
  'kline.time_Line': '時間',
  'kline.time_1m': '1分',
  'kline.time_3m': '3分',
  'kline.time_5m': '5分',
  'kline.time_15m': '15分',
  'kline.time_30m': '30分',
  'kline.time_1H': '1時間',
  'kline.time_2H': '2時間',
  'kline.time_4H': '4時間',
  'kline.time_6H': '6時間',
  'kline.time_1D': '1日',
  'kline.time_1W': '1週間',
  'kline.time_1M': '1ヶ月',
  'kline.tab_line': 'チャート',
  'kline.tab_depth': '深さ',
  'kline.chartType_Bars': 'バー',
  'kline.chartType_Candles': 'ローソク足',
  'kline.chartType_Hollow_Candles': 'ろうそく足',
  'kline.chartType_Line': 'ライン',
  'kline.chartType_Area': 'エリア',
  'kline.chartType_Heikin_Ashi': '平均足',
  degate_account: 'DeGateアカウント',
  Trade: '取引',
  Order: '注文',
  Grid: 'グリッド戦略',
  Campaign: 'キャンペーン',
  DCA: 'DCA',
  Advanced: '高度な',
  Add: '追加',
  Add_Funds: '資金の追加',
  eth_added_1: '1 ETH 追加済み',
  eth_sent_1: '1 ETH 送信済み',
  Send: '送信',
  Internal_Transfer: '内部転送',
  Miscellaneous: 'その他',
  Bridge: 'ブリッジ',
  Mining: 'マイニング',
  Liquidity_Mining: '流動性マイニング',
  Analytics: '分析',
  Support: 'サポート',
  Help: 'ヘルプ',
  Tips: 'ヒント',
  Statistics: '統計',
  Coming_soon: '近日公開予定',
  Faucet: 'フォーセット',
  more: 'その他',
  hide: '非表示',
  change: '変更',
  'Wrong Network': 'ネットワークが違います',
  avbl: '利用可能残高:',
  insufficient_balance_AAA:
    'あなたのウォレットに十分なAAAがありません。確認して再度お試しください。',
  insufficient_balance: '残高が不足しています',
  wallet_denied_sign: 'メッセージ署名が拒否されました。',
  common_err: '問題が発生しました。後ほどもう一度お試しください。',
  common_err_ledger_version:
    'エラーが発生しました。Ledger Ethereumアプリが最新バージョン（1.9.10以降）であることを確認してください。または、後ほどもう一度お試しください。',
  network_1: 'イーサリアムメインネット',
  network_err: 'ネットワークエラーです。後ほどもう一度お試しください。',
  rate_limit_err: 'アクセス頻度が高すぎます。1分後に再試行してください。',
  error_InsufficientGasFunds: 'ウォレットのガス残高が不足しています',
  notification_transaction_send: 'トランザクションが送信されました',
  view_on_etherscan: 'ブロックチェーンエクスプローラーで見る',
  view_on_explorer: 'アドレスを見る',
  switch_network: 'ネットワークを切り替える',
  switch_to_Arbitrum: '続行するには、Arbitrumに切り替えてください。',
  switch_to_MAINNET_in_metamask: 'MetaMaskでメインネットに切り替えてください',
  switch_to_MAINNET: 'メインネットに切り替えてください',
  switch_network_in_walletconnect:
    'ウォレットに移動し、WalletConnectでネットワークを切り替えてください',
  Retry: '再試行',
  wallet_tips: 'ブラウザウォレットで承認してください',
  wallet_ledger_tips: 'Ledgerハードウェアで承認してください',
  wallet_metamask_tips: 'MetaMaskで承認してください',
  wallet_walletconnect_tips:
    'ウォレットに移動し、WalletConnectで承認してください',
  wallet_cancelled_tips: '署名をキャンセルしました',
  Close: '閉じる',
  copied: 'コピーしました',
  Details: '詳細',
  view_details: '詳細を見る',
  Share: '共有する',
  view_graph: 'チャートで見る',
  Dismiss: '閉じる',
  Cancel: 'キャンセル',
  End: '終了',
  End_grid: '終了',
  Confirm: '確認',
  Cancel_all: 'すべてキャンセル',
  cancel_all_tips: 'すべての未約定注文をキャンセルする',
  Submit: '送信',
  no_data: 'データなし',
  all_data_displayed: 'すべてのデータが表示されています',
  no_data_within_90_days: '90日以内のデータはありません',
  only_display_90_days: '過去90日間のデータのみを表示しています',
  displayed_90_days: '過去90日間のデータを表示しています',
  only_data_beyond_90_days_trade:
    '90日を超えるデータにアクセスするには、「すべて表示」を選択してから「データのエクスポート」機能を使用してください。',
  only_data_beyond_90_days_grid_detail:
    '過去90日を超えるデータの履歴クエリは現在サポートされていません',
  only_data_beyond_90_days_spot_history:
    '90日を超えるデータにアクセスするには、「データのエクスポート」機能を使用してください。',
  View: '表示',
  service_unavailable_for_region_REGION:
    'このサービスはREGIONではご利用いただけません。',
  service_unavailable: 'サービスは利用できません',
  service_error: '後ほどもう一度お試しください',
  service_maintenance: 'このサービスはメンテナンス中です。',
  connect_wallet: 'ウォレットを接続する',
  switch_address: 'アドレスを切り替える',
  wallet_wc: 'WalletConnectに接続しました',
  wallet_ledger: 'Ledgerに接続しました',
  register_dexAccount: '登録する',
  deposit_ETH: 'ETHを追加する',
  initialize: '初期化する',
  initialization: '初期化',
  invalid_signature: '無効な署名',
  possible_cause: '考えられる原因:',
  locale_time_error: 'デバイスの時間が正しくありません。',
  authorization_mode: '認証モード',
  authorization_mode_standard: '署名不要',
  authorization_mode_single_use: '常に署名する',
  turn_on: 'オンにする',
  turn_on_signature_free_mode: '署名不要モードをオンにする',
  signatre_free_mode: '署名不要モード',
  turn_on_signature_free_mode_tips:
    'このモードでは、署名せずに注文することができます。モードを切り替えるには、取引ボタンの下にある「設定」に移動します。',
  turn_on_signature_free_mode_tips_grid:
    'このモードでは、署名せずにグリッド戦略を作成することができます。モードを切り替えるには、取引ボタンの下にある「設定」に移動します。',
  turn_on_signature_free_mode_tips_dca:
    'このモードでは、署名せずにDCAプランを作成することができます。モードを切り替えるには、取引ボタンの下にある「設定」に移動します。',
  yes: 'はい',
  no: 'いいえ',
  free_mode_on: '署名不要モードオン',
  view_balance: '残高を見る',
  delete_asset_key: 'アセットキーを削除する',
  delete_asset_key_desc:
    'ブラウザからアセットキーが削除されると、署名不要モードはオフになります。',
  no_asset_key_tips: 'ブラウザにアセットキーが見つかりません',
  turn_off_standard_mode: '署名不要モードをオフにする',
  reset_asset_key: 'アセットキーをリセットする',
  view_asset_key: 'アセットキーを見る',
  lock_success: 'アセットキーが削除されました',
  reset: 'アセットキーをリセットする',
  delete: '消す',
  withdraw_ETH: 'ETHを送信する',
  transfer_ETH: 'ETHを内部転送する',
  history: '履歴',
  view_history: '履歴で見る',
  internal_transfer: '送金',
  assets_record_link: '履歴',
  other: 'その他',
  login_success: '接続に成功しました',
  Account: 'アカウント',
  Address: 'アドレス',
  Disconnect: '切断',
  copy_address: 'アドレスをコピーする',
  copy_grid: '戦略をコピーする',
  Copy: 'コピーする',
  btn_search: '検索',
  btn_reset: 'リセット',
  btn_confirm: '閉じる',
  btn_max: '最大',
  btn_ok: 'OK',
  spot_trade: 'スポット',
  grid_trade: 'グリッド',
  err_balance_title: '注文に失敗しました',
  err_balance_content:
    '利用可能な残高が不足しています。確認してもう一度お試しください。',
  order_failed: '注文数量が不足しています',
  insufficient_order_value: '注文額不足',
  grid_failed: '作成に失敗しました',
  err_eth_gas: 'イーサリアムネットワークが非常に混雑しています',
  err_insufficient_balance_TOKEN1: 'TOKEN1の残高が不足しています',
  err_insufficient_balance_TOKEN1_TOKEN2:
    'TOKEN1とTOKEN2の残高が不足しています',
  please_add_funds_before_ordering:
    '注文する前に、DeGate残高に資金を追加してください。',
  err_balance_content_spot:
    '残高不足のため、注文の размещение に失敗しました。',
  err_balance_content_grid:
    '残高不足のため、グリッド戦略の作成に失敗しました。',
  trade_min_volume_tips_XXX: '最小XXX',
  grid_min_volume_tips:
    '注文数量が最小額を満たしていません。もう一度お試しください。',
  trade_risk_orders_tips: '未決済注文が多すぎるため、注文を出せません',
  gas_token_tips: 'ガス料金トークンを選択',
  add_favorite_tooltip: 'お気に入りに追加',
  remove_favorite_tooltip: 'お気に入りから削除',
  expire_tips_X: 'この注文はXに期限切れになります。',
  today: '今すぐ',
  now: '今すぐ',
  time_D_day: 'dd',
  time_D_day_H_hour: 'dd hh',
  time_H_hour_M_minute: 'hh mm',
  time_M_minute_S_second: 'mm ss',
  time_S_second: 'ss',
  around: '周辺',
  time_now: '今すぐ',
  time_before: '以前',
  time_before_ago: '前',
  time_1_minute: '1分',
  time_1_hour: '1時間',
  time_1_day: '1日',
  time_1_year: '1年',
  time_M_minutes: 'M分',
  time_M_m: 'mm',
  time_H_hours: 'H時間',
  time_H_h: 'hh',
  time_D_days: 'D日',
  time_Y_years: 'Y年',
  time_Y_y: 'yy',
  fee_change_tips: '価格が更新されました',
  no_pairs: '取引ペアが見つかりません',
  register_new_pair: '新しいペアを追加',
  register_pair: '取引ペアを追加',
  add_pair: 'ペアを追加',
  tips_hide_forever: '再度表示しない',
  token: 'トークン',
  action: 'アクション',
  more_actions: 'その他',
  gas_fee: 'ガス料金',
  'orders.detail_gas': '実際のガス料金',
  trade_fee: '取引手数料',
  about_degate: 'DeGateについて',
  metrics: '指標',
  fees: '料金',
  document: 'ドキュメント',
  join_us: '参加する',
  feedback: 'フィードバック',
  email_optional: 'メールアドレス（オプション）',
  Upload: 'アップロード',
  feedback_upload_tip:
    'フィードバックをお共有ください。添付するには、ファイルをドラッグしてください。',
  feedback_upload_tip_mobile: 'フィードバックをお共有ください。',
  image_upload_tip: 'リリースを追加',
  feedback_success: 'あなたの意見は、私たちに届いています！',
  feedback_success_2: 'ありがとうございました',
  feedback_failed: '送信に失敗しました。後ほどもう一度お試しください。',
  image_upload_rule_1: 'PNG、JPG、JPEGのみサポートされています。',
  image_upload_rule_2: 'ファイルあたりの最大サイズは20MBです。',
  image_upload_rule_3: '最大5ファイル。',
  image_upload_rule_2_3:
    'ファイルあたりの最大サイズは20MBです。最大5ファイル。',
  no_pair: 'トークンペアが見つかりません',
  no_token: 'トークンが見つかりません',
  choose_base_token: '基準トークンを選択',
  choose_quote_token: 'クォートトークンを選択',
  get_test_token: 'テストネットトークンを取得',
  faucet: 'フォーセット',
  expire_in: '有効期限',
  expire_in_empty_err: '数字を入力してください',
  go_back: '戻る',
  max_XXX: '最大XXX',
  min_XXX: '最小XXX',
  fill_in: '入力してください',
  my_balance: 'マイ残高',
  deGate_insufficient_fees:
    'ガス料金の支払いに必要なDeGate残高が不足しています',
  wallet_balance: 'ウォレット残高',
  your_wallet_balance: 'ウォレットの残高',
  degate_balance: 'DeGate残高',
  wallet_insufficient_fees: 'ウォレットの残高が不足しています',
  wallet_insufficient_balance: '残高不足',
  insuffficient_wallet_balance: 'ウォレットの残高が不足しています',
  degate_insufficient_balance: '利用可能な残高が不足しています',
  open_discord: 'Discordコミュニティにアクセス',
  err_valid_until: 'デバイスの現地時間を標準時間に合わせてください',
  tips_gas:
    'このオンチェーントランザクションを実行するためのガス料金は、DeGate残高から直接差し引かれます。',
  maker_free: 'メーカー無料',
  trading_fee_rate: '取引手数料率',
  Free: '無料',
  stop_service_1: 'サイトはメンテナンス中です',
  stop_service_2: '推定復旧時間',
  stop_upgrade: 'テストネットの新しいバージョンは現在移行中です。',
  stop_trading_1: 'システムアップグレード',
  stop_trading_2: '取引は一時的に停止されています',
  sell: '売り',
  buy: '買い',
  SELL: '売却',
  BUY: '購入',
  Sell: '売り',
  Buy: '買い',
  sell_order: '売却注文',
  buy_order: '購入注文',
  edit: '編集',
  status_processing: '処理中',
  status_processed: '保留中',
  status_pending: '保留中',
  status_confirming: '確認中',
  status_success: '成功',
  status_completed: '完了',
  status_failed: '失敗',
  status_speeding_up: '高速化',
  status_canceling: 'キャンセル中',
  status_canceled: 'キャンセル済み',
  in_progress: '実行中',
  limit_order: '指値',
  market_order: '成行',
  stop_limit_order: '逆指値',
  balance: '残高',
  empty_connect: 'まずウォレットを接続してください',
  empty_register: 'まず初期化してください',
  empty_months3: '過去3か月間のデータはありません',
  show_months3: '過去3か月以内のデータのみを表示',
  view_all: 'すべて表示',
  D1: '1日',
  D5: '5日',
  M1: '1か月',
  M3: '3か月',
  M6: '6か月',
  YTD: '年初から今日まで',
  Y1: '1年',
  all: 'すべて',
  paste: '貼り付け',
  clear: 'クリア',
  total: '合計',
  amount: '金額',
  order_amount: '注文数量',
  price: '価格',
  order_total: '合計',
  filledAmount: '金額',
  tradeFilledTotal: '価値',
  orderFilledTotal: '合計',
  filledAmount_amount: '約定/数量',
  profit: '利益',
  incompatible_token:
    'このトークンの技術仕様は、DeGateプロトコルと互換性がありません。',
  next: '次へ',
  token_not_verified: '未確認',
  token_not_verified_tips:
    'コントラクトアドレス、アイコン、シンボルは未確認です。詐欺を避けるため、公式の情報源でコントラクトアドレスを確認してください。',
  token_verified: '確認済み',
  token_verified_tips:
    'コントラクトアドレス、アイコン、シンボルが一致しています。',
  deposit_tips_region:
    '現在、REGIONでDeGateにアクセスしています。資金の追加後は、取引機能と内部転送機能はご利用いただけません。',
  complete_time: '後で完了',
  unable_to_initialize: '初期化できません',
  filter_base: '基準',
  filter_quote: 'クォート',
  filter_type: 'タイプ',
  filter_role: 'ロール',
  option_maker: 'メイカー',
  option_taker: 'テーカー',
  start_data: '開始日',
  end_data: '終了日',
  added_to_favorites: 'お気に入りに追加済み',
  removed_to_favorites: 'お気に入りから削除済み',
  show_recents_50: '最新の50件のデータが表示されています。',
  terms_of_service: '利用規約',
  tips_small_unfilled:
    'システム設計で指定された精度に基づいて、注文の未約定分のわずかな部分がDeGate残高に返金されました。',
  notification: '通知',
  server_message_SystemRecovery:
    'システムの復旧後、注文ステータスが変更されたことをお知らせします。',
  learn_more: '詳細はこちら',
  connect_ledger: 'Ledgerに接続',
  ledger_disconnect:
    '「USBDevice」で「transferOut」の実行に失敗しました：デバイスが切断されました。',
  gas_fee_expired: 'ガス料金の有効期限が切れました。もう一度送信してください。',
  scroll_down_to_refresh: '更新するには、下にスクロールしてください。',
  release_to_refresh_immediately: '更新するには、リリースしてください。',
  no_more: 'これ以上のデータはありません',
  loading: '読み込み中...',
  force_withdrawing_token_tips:
    '強制引き出しリクエストが処理中のため、現在の操作は実行できません。',
  speed_up: '高速化',
  transaction_submitted: 'トランザクションが送信されました',
  tx_speed_up: 'トランザクションの高速化',
  tx_cancel: 'トランザクションのキャンセル',
  none: 'なし',
  Language: '言語',
  page: '/ページ',
  go_to: 'に移動',
  icon_indicators: 'インジケーター',
  icon_back: '戻る',
  icon_forward: '進む',
  icon_full_screen: '全画面表示',
  icon_exit_full_screen: '全画面表示を終了',
  icon_buy_sell_orders: '売買注文',
  icon_buy_orders: '購入注文',
  icon_sell_orders: '売却注文',
  icon_enable: 'クリックして有効にする',
  icon_disable: 'クリックして無効にする',
  icon_copy: 'アドレスをコピー',
  icon_view_explorer: 'ブロックエクスプローラーで表示',
  icon_display_by_profit: '利益順に表示',
  icon_display_by_time: '時間順に表示',
  icon_switch: '切り替え',
  eth_code_tips:
    'イーサリアムのネイティブトークン。トークンコントラクトアドレスはありません。',
  TBD: '後日決定',
  TVL: 'TVL',
  go_to_discord: 'またはDiscordに参加してチケットを作成する',
  release: 'リリース：',
  security: 'セキュリティ',
  colon: '：',
  zero_balance: '残高ゼロ',
  ledger_app_version_tips:
    '署名前にメッセージをプレビューするには、LedgerのEthereumアプリをバージョン1.9.19以上に更新してください。',
  ledger_contract_data_tips:
    'イーサリアムアプリの設定で、ブラインド署名またはコントラクトデータを有効にしてください',
  input_auto_corrected_tooltips:
    '最大桁数を超えたため、入力が自動修正されました',
  maximum_decimal_reached: '最大小数点以下桁数に達しました',
  verify_ownership: '所有権の確認',
  enable_trading: '取引を有効にする',
  learn_more_about_signatures_link: '署名について詳しくはこちら >',
  learn_more_about_signatures: '署名について詳しくはこちら',
  sign: '署名',
  sign_step1: 'ウォレットで完了',
  sign_step2: '2つ目の署名を完了',
  not_now: '後で行う',
  view_on_block_explorer: 'ブロックチェーンエクスプローラーで表示',
  view_in_history: '履歴を表示',
  continue_to_place_order: '注文の размещение を続ける',
  Save: '保存',
  sign_to_view: '表示するには署名してください',
  available_degate_balance: '利用可能なDeGate残高',
  Back: '戻る',
  token_has_not_listed: 'このトークンはDeGateにリストされていません。',
  list_now: '今すぐリストする',
  spread_15: 'スプレッド> 15%',
  connected: '接続済み',
  self_list_token: 'インスタントリスティング',
  claim_REBASE: 'REBASEを請求',
  time: '時間',
  time_updated: '更新時間',
  show_in_X_m: 'X分に表示',
  max_gas: '最大ガス料金',
  total_required: '合計必要額',
  Required: '必要額',
  available_balance: '利用可能な残高',
  please_add_funds: 'DeGate残高に資金を追加してください。',
  Side: 'サイド',
  pending: '保留中',
  active: 'アクティブ',
  ended: '終了',
  name: '名前',
  yield: '利回り',
  time_created: '作成日時',
  time_ended: '終了時間',
  frequency: '頻度',
  chain_cancel: 'オンチェーンでキャンセル',
  status: 'ステータス',
  status_chainCancelProgressing: 'オンチェーンキャンセル中',
  status_chainCancelCompleted: 'オンチェーンキャンセル済み',
  filled_total: '約定/合計',
  start_time: '開始時間',
  end_time: '終了時間',
  Summary: '概要',
  Orders: '注文',
  Tutorial: 'チュートリアル',
  Earn: '獲得する',
  top_winner_24h: '24時間トップランキング',
  ID: 'ID',
  Select: '選択',
  Create: '作成',
  Review: '確認',
  Airdrop: 'エアドロップ',
  Countdown: 'カウントダウン',
  Day: '日',
  Hour: '時間',
  Minute: '分',
  Second: '秒',
  Days: '日数',
  Hours: '時間数',
  Minutes: '分数',
  Seconds: '秒数',
  Claim: '請求する',
  Expired: '期限切れ',
  Claimed: '請求済み',
  Welcome: 'ようこそ',
  gas_tips_for_amount_exceed_6_digits:
    '金額の桁数が6桁の名目制限を超えているため、追加料金が適用されました。',
  input_auto_corrected_minStep_tips:
    '最小精度を満たすように入力が自動修正されました',
  order_max_limit: '上限を超えました',
  order_min_limit: '下限に達していません',
  order_faild_min_limit:
    '注文の размещение に失敗しました：下限に達していません。',
  order_faild_max_limit: '注文の размещение に失敗しました：上限を超えました。',
  disconnect_m: '切断',
  'account.account_manage': 'セキュリティ',
  'account.account_manage_more': '認証モードとアセットキーについて >',
  'account.what_is_asset_key': '認証モードとアセットキーについて',
  'account.total_value': '総額',
  'account.hide_small_balances': '少額残高を非表示',
  'account.add_to_metamask': 'ウォレットにトークンを追加',
  'account.assets_balance_total': '合計',
  'account.assets_balance_available': '利用可能',
  'account.assets_market': '価値',
  'account.transfer_to_degate_balance': 'DeGate残高に追加',
  'account.search_tokens': 'トークンを検索',
  'account.deposit_title':
    'アセットは、分散型DeGateアカウントに入金されます。これらのアセットは、お客様が完全に管理します。',
  'account.deposit_tips': 'これらの資金は、お客様が完全に管理します。',
  'account.deposit_confirm_btn': '追加',
  'account.deposit_approved_btn': '承認済み',
  'account.deposit_1_ETH': 'DeGate残高に1 ETHを追加',
  'account.deposit_status_pending': '保留中',
  'account.deposit_status_pay_pending': '支払い期限',
  'account.deposit_status_pay_waiting': '支払いがブロードキャストされました',
  'account.deposit_status_pay_confirming': '支払い確認中',
  'account.deposit_tips_block':
    'トランザクションはブロックに含まれるのを待っています',
  'account.deposit_status_pay_btn': '支払う',
  'account.pay_deposit_warning':
    '資金の追加には、追加のガス料金が発生する場合があります',
  'account.pay_deposit_warning_tips':
    'DeGateの補助金が完全に使用されているため、ユーザーは資金の追加にかかる費用を負担する必要がある場合があります。',
  'account.deposit_pending_tips':
    '5分以上保留中の場合は、ウォレットでトランザクションを高速化してください。',
  'account.deposit_pending_tips_ledger':
    '5分以上保留中の場合は、トランザクションを高速化してください。',
  'account.deposit_contract_tips_over_AMOUNT':
    'AMOUNT USDを超える資金の追加には、詳細設定の方法が必要です。',
  'account.deposit_contract_tips_only_all':
    '資金の追加には、詳細設定の方法のみがサポートされています',
  'account.suggest_100': '竕･$100を推奨',
  'account.suggest_100_tips':
    '指値注文を出すには、$100を超える金額をお勧めします。',
  'account.deposit_failed': '失敗',
  'account.deposit_failed_tips':
    '資金を追加するためのオンチェーントランザクションが失敗しました。',
  'account.payment_due': '支払い期限',
  'account.payment_due_tips':
    'DeGate残高に資金を入金するには、追加の支払いが必要です。',
  'account.register_token_code_placeholder':
    'コントラクトアドレスを入力してください',
  'account.register_token_code': 'コントラクトアドレス',
  'account.register_token_symbol': 'シンボル',
  'account.register_token_check': 'リスティングの進捗状況を確認する',
  'account.register_token_code_err_added': 'このトークンはリストされています',
  'account.register_token_next_step': '次へ',
  'account.register_token_tips1':
    'オンチェーントークンリスティングには権限は必要ありません。すぐにトークンをリストしてください。',
  'account.register_token_btn': 'トークンをリストする',
  'account.list_token': 'トークンをリストする',
  'account.withdraw_warning_XXX':
    '需要の増加により、現在、資金の送信にはXXXかかります。',
  'account.withdraw_status_pending': '処理中',
  'account.tansferred_1_ETH': '1 ETH転送済み',
  'account.transfer_status_sent': '送信済み',
  'account.transfer_status_received': '受信済み',
  'account.th_me': '自分',
  'account.th_tx_hash': 'トランザクションハッシュ',
  'account.th_time': '時間',
  'account.locked_order': '指値注文',
  Sending: '送信中',
  'account.locked_claimable': '請求可能',
  'account.locked_grid': 'グリッド戦略',
  'account.personal_sign_reason': '考えられる理由',
  'account.personal_sign_reason1':
    '1.MetaMaskはハードウェアウォレットに接続されています',
  'account.personal_sign_reason2': '2.MetaMaskのバージョンが古くなっています',
  'account.personal_sign_reason3': '3.その他',
  'account.personal_sign_btn': 'もう一度サインイン',
  'account.deposit_arrive_in_30s': '約30秒で到着します',
  'account.deposit_arrive_in_30s_s': '約30秒で完了します',
  'account.account_completed_time_XXX': '完了まで約XXX',
  'account.search_result_no_token': 'トークンが見つかりません',
  'account.search_result_invalid_code': '無効なコントラクトアドレスです',
  'account.search_result_not_listed':
    'トークンは現在DeGateに上場されていません',
  'account.search_result_tips_register':
    'トークン上場を完了するには、コントラクトアドレスを入力してください',
  'account.search_result_not_find': 'まだ見つかりませんか？',
  'account.search_pair_tips3': '資産の取引ペアがありません',
  'account.search_pair_tips3_add': 'ペアを追加してください',
  'account.register_token': '許可不要のトークン上場',
  'account.search_again': 'もう一度検索',
  'account.deposit_type': '手法',
  'account.deposit_type_standard': '標準',
  'account.switch_account_tips': '切り替え済み',
  'account.switch_account_tips_register': '最初に初期化してください。',
  'account.initialize_success': '初期化に成功しました',
  'account.approve': '承認',
  'account.reset_USDT': 'USDT承認をリセット',
  'account.reset_USDT_tips':
    '支出限度額が低すぎるため、USDTは承認のリセットが必要です。',
  'account.next_step': '次へ',
  'account.profit_total': '合計利益',
  'account.profit_history': '利益履歴',
  'account.tab_mining_rewards': 'マイニング報酬',
  'account.yield_total': '合計利回り',
  'account.yield_24h': '24時間利回り',
  'account.claimable': '請求可能',
  'account.yield_history': '利回り履歴',
  'account.total_grid_profit': 'グリッド合計利益',
  'account.grid_strategies': 'グリッド戦略',
  'account.total_rewards': '合計報酬',
  'account.rewards_24h': '24時間報酬',
  'account.rewards': '報酬',
  'menu.register_err':
    'あなたのアドレスには、ブロックチェーンの取引記録がありません。オンチェーン取引を完了してから、もう一度お試しください。たとえば、ウォレットへのトークン転送を実行します。',
  'menu.reset_post_success_withOrders':
    'アセットキーのリセットが開始されました。すべての未約定注文とグリッド戦略はキャンセルされました。',
  'menu.reset_post_success': 'アセットキーのリセットが開始されました。',
  'menu.reset_processing_title': 'アセットキーのリセットが進行中です',
  'menu.reset_processing_desc': '完了するまでお待ちください',
  'trade.choose_token': 'トークンを選択',
  'trade.token_info': 'トークン情報',
  'trade.token_address': 'トークンアドレス',
  'trade.price_range_24h': '24時間価格帯',
  'trade.vol_24h': '24時間出来高',
  'trade.item_price_TOKEN': '価格 (TOKEN)',
  'trade.item_amount_TOKEN': '量 (TOKEN)',
  'trade.order_book_title': '注文板',
  'trade.order_book_total': '合計',
  'trade.trade_history_title': '最新の取引',
  'trade.trade_history_time': '時間',
  'trade.market_placeholder_price': '市場価格',
  'trade.what_is_stop_limit': 'ストップリミット注文とは',
  'trade.what_is_stop_limit_link': 'ストップリミット注文とは >',
  'trade.placeholder_total': '合計',
  'trade.more_settings': '設定',
  'trade.expire_in_tips':
    '有効期限が切れると、注文は自動的にキャンセルされます。',
  'trade.period_day_s': '日',
  'trade.period_hour_s': '時間',
  'trade.period_minute_s': '分',
  'trade.period_err_input_tips': '有効な数字を入力してください',
  'trade.post_only_label': 'メーカのみ',
  'trade.post_only_tips':
    'メーカのみモードでは、注文板に入力されるのはメーカ注文のみとなります。注文の一部でもテイカー注文として約定できる場合、注文全体が返却されます。メーカのみモードの注文は、ガス料金や取引手数料は発生しません。',
  'trade.post_only_fail_title': '注文を作成できません',
  'trade.post_only_fail_desc':
    '価格を調整するか、「メーカのみ」モードを無効にしてください。',
  'trade.max_gas_fee_tips':
    '最大ガス料金は、取引決済のオンチェーンコストをカバーし、テイカーが支払います。メーカは無料です。超過料金は払い戻されます。',
  'trade.auto': '自動',
  'trade.custom': 'カスタム',
  'trade.enough_for_XX_trades': 'XX取引に十分',
  'trade.gas_fee_per_trade': '1取引あたりのガス料金',
  'trade.gas_fee_per_trade_tips':
    'テイカーは、オンチェーン決済を容易にするため、取引ごとにガス料金が発生します。コストは、イーサリアムネットワークの状況によって変動します。',
  'trade.max_number_of_trades': '最大取引回数',
  'trade.btn_buy_ETH': 'ETHを購入',
  'trade.btn_sell_ETH': 'ETHを売却',
  'trade.max_buy_fee_deducted_NUM':
    'ガス料金が差し引かれました。最大値はNUMです。',
  'trade.notification_limit_order_title': '指値注文',
  'trade.notification_stop_limit_order_title': 'ストップリミット注文',
  'trade.err_price': '価格を入力してください',
  'trade.err_amount_total': '金額または合計を入力してください',
  'trade.err_amount': '金額を入力してください',
  'trade.err_insufficientFee_title': 'ガス料金不足',
  'trade.err_insufficientFee_desc':
    '最大ガス料金の設定とDeGate残高を確認してください。',
  'trade.cancel_order_success': '注文キャンセル済み',
  'trade.pair_favorite': 'お気に入り',
  'trade.pair_search': 'トークン、コントラクトアドレスを検索',
  'trade.pair_last_price': '価格',
  'trade.pair_change': '変動率',
  'trade.url_parse_err_title': 'このペアは存在しません。',
  'trade.risk_tips': 'リスク警告',
  'trade.base_is_not_default_token_tips':
    'トレードする前に、詐欺を避けるために公式ソースを通じてトークンコントラクトアドレスを確認してください。',
  'trade.chain_cancel': 'オンチェーンで注文をキャンセル',
  'trade.chain_cancel_no_need_tips':
    'この注文はオンチェーンでのキャンセルは必要ありません。',
  'trade.chain_cancel_success': 'リクエストを送信しました',
  'trade.depth_empty': 'まだ注文はありません',
  'trade.depth_empty_asks': '売り注文はありません',
  'trade.depth_empty_bids': '買い注文はありません',
  'trade.depth_empty_tips':
    '注文板に十分な未約定注文がないため、成行注文が失敗しました',
  'trade.history_empty': 'まだ取引はありません',
  'trade.err_price_stable':
    '価格が無効になっています。もう一度お試しください。',
  'trade.price_warning':
    '入力した価格が市場価格から乖離しています。注文する前に確認してください',
  'trade.order_value_tips':
    '最小注文額は<b>QUOTE_A</b>または<b>BASE_A</b>で、MINUSD USDに相当します。この制限を回避するには、成行注文を使用してください。',
  'trade.order_value_tips_quote':
    '最小注文額は<b>QUOTE_A</b>で、MINUSD USDに相当します。この制限を回避するには、成行注文を使用してください。',
  'trade.order_value_tips_stable_quote':
    '最小注文額は<b>QUOTE_A</b>です。この制限を回避するには、成行注文を使用してください。',
  'trade.system_limit': 'システム制限を超えました',
  'trade.stop_limit_untriggered_tips':
    'ストップ価格に達していないため、注文は注文板に提出されていません。',
  'trade.stop_limit_triggered_tips_TIME': '注文はTIMEに注文板に提出されました',
  'trade.flow_of_funds': '資金の流れ',
  'trade.flow_of_funds_tip2':
    '注文が確定しました。注文資金は、ウォレットの残高ではなく、DeGate残高に送られます。',
  'orders.show_current_pair_orders': '他のペアを非表示',
  'orders.orderHistory': '注文履歴',
  'orders.th_time': '時間',
  'orders.th_average_price': '平均価格',
  'orders.th_stop_price': 'ストップ価格',
  'orders.th_limit_price': '指値価格',
  'orders.th_filled_price': '価格',
  'orders.th_filled_amount': '約定済み',
  'orders.th_filled_total': '合計',
  'orders.th_trade_reconciliation': '突合',
  'orders.th_trade_reconciliation_tips':
    'DeGateでのマッチングとオンチェーンでの決済に使用される計算モデルが異なるため、2つの計算結果にわずかな違いが生じる可能性があります。この場合、システムはオンチェーンの値を基準として使用し、DeGate残高の不足分を補います。',
  'orders.hide_cancelled_expired_orders': 'キャンセル/失効したものを非表示',
  'orders.status_open': 'オープン',
  'orders.status_pending': '保留中',
  'orders.status_completed': '約定済み',
  'orders.status_completed_part': '部分的に約定済み',
  'orders.status_expired': '失効',
  'orders.detail_price': '平均/価格',
  'orders.average_price': '平均価格',
  'orders.detail_type': '注文タイプ',
  'orders.detail_trade_fee': '取引手数料：',
  'orders.gas_preAuth': '最大ガス料金：',
  'orders.fee_reconciliation': '突合：',
  'orders.gas_paid': '支払われたガス料金：',
  'orders.gas': 'ガス料金：',
  'orders.trades_N': '取引（N）',
  'orders.detail_filled_total': '合計',
  'orders.detail_filled_detail': '取引詳細',
  'orders.detail_filled_time': '時間',
  'orders.order_maker_free': 'メーカ手数料無料',
  'orders.openOrders_empty': '未約定注文なし',
  'orders.export_orders_1_year': '最近1年間の注文データをエクスポートします。',
  'orders.export_trades_1_year': '最近1年間の取引データをエクスポートします。',
  'orders.export_data': 'データのエクスポート',
  'orders.export': 'エクスポート',
  'orders.export_processing': '処理中です。しばらくお待ちください。',
  'orders.export_tips_100_percent':
    'ファイルは、進捗状況が100%に達するとダウンロードされます',
  'orders.sign_to_view_balance': '残高を表示するにはサインインしてください',
  'orders.sign_to_view_history': '履歴を表示するにはサインインしてください',
  'orders.sign_to_view_security_options':
    'セキュリティオプションを表示するにはサインインしてください',
  'gridTrade.automatic_strategy': '自動',
  'gridTrade.manual_strategy': '手動',
  'gridTrade.placeholder_amount': '金額を入力してください',
  'gridTrade.low_price': '下限',
  'gridTrade.high_price': '上限',
  'gridTrade.initial_investment': '投資額',
  'gridTrade.grid_levels_tips':
    '価格帯内の未約定注文数を決定するために使用されます。',
  'gridTrade.profit_per_grid': 'グリッドあたりの利益',
  'gridTrade.profit_per_grid_tips':
    'グリッド戦略の収益性のための重要なパラメータです。 グリッドあたりの利益 = （高値 - 安値） / 安値。 高値と安値は、グリッド戦略内の2つの隣接するグリッド線の価格を指します。',
  'gridTrade.min_grid_volume_XXX_ETH': 'グリッドあたりの金額：最小XXX ETH',
  'gridTrade.min_grid_volume_err':
    '投資額を増やすか、グリッド数を減らしてください',
  'gridTrade.grid_no_depth_tips_BASE_QUOTE':
    '注文板に十分な注文がないため、このペアのグリッド戦略を作成できません。',
  'gridTrade.grid_to_spot_trade': '現物取引に移動',
  'gridTrade.grid_level_over_err': 'グリッド数を減らしてください',
  'gridTrade.grid_prices_err': '価格帯を広げてください',
  'gridTrade.grid_create_err': 'パラメータを調整して、もう一度お試しください。',
  'gridTrade.tips_grid_profit':
    '利益はDeGate残高に直接入金され、すぐに利用できます。',
  'gridTrade.tips_grid_balance_0_BASE':
    '市場価格の上昇により、このグリッド戦略下のすべての注文が買い注文になりました。したがって、BASEの現在の残高は0になりました。',
  'gridTrade.tips_grid_balance_0_BASE_2':
    '市場価格の上昇により、このグリッド戦略下のすべての注文が買い注文になりました。さらに、これらの注文の一部は部分的に約定されています。したがって、BASEの現在の残高は>0です。',
  'gridTrade.tips_grid_balance_0_QUOTE':
    '市場価格の下落により、このグリッド戦略下のすべての注文が売り注文になりました。したがって、QUOTEの現在の残高は0になりました。',
  'gridTrade.tips_grid_balance_0_QUOTE_2':
    '市場価格の下落により、このグリッド戦略下のすべての注文が売り注文になりました。さらに、これらの注文の一部は部分的に約定されています。したがって、QUOTEの現在の残高は> 0です。',
  'gridTrade.grid_param_err': 'グリッド戦略のパラメータを入力してください',
  'gridTrade.tv_buy': '購入',
  'gridTrade.tv_sell': '売却',
  'gridTrade.tv_waiting': '待機中',
  'gridTrade.chain_cancel_no_need_tips':
    'このグリッド戦略はオンチェーンでのキャンセルは必要ありません。',
  'gridTrade.grid_over_max_number_err':
    '実行中のグリッド戦略の最大数に達したため、新しいグリッドを作成できません。',
  'gridTrade.preview_orders_in_graph': '注文を表示',
  'gridTrade.greate_news': 'グッドニュース：',
  'gridTrade.min_amount_required_XXX': '最低XXXが必要です',
  'gridTrade.highest_grid_apy': '最高グリッドAPY',
  'gridTrade.for_the_last_7_days': '過去7日間',
  'gridTrade.min_investment': '最低投資額',
  'gridTrade.grid_need_XXX': 'グリッドの場合は$XXX',
  'gridTrade.mining_need_XXX': 'マイニングの場合は$XXX',
  'gridTrade.recommended_params_cannot_be_applied':
    '投資額が不足しているため、推奨パラメータを適用できません。手動モードで調整できます。',
  'gridTrade.copy_params_to_manual': 'パラメータを手動にコピー',
  'gridOrders.grid_recents': '私の最新の取引',
  'gridOrders.th_created_time': '作成時間',
  'gridOrders.grid_profit': 'グリッド利益',
  'gridOrders.grid_cancel': '終了',
  open_orders: '未約定注文',
  'gridOrders.tab_history_orders': '約定済み注文',
  'gridOrders.tab_trade_history': '取引履歴',
  'gridOrders.detail_current_balance': '現在残高',
  'gridOrders.detail_ending_balance': '終了残高',
  'gridOrders.detail_ending_balance_tips':
    'グリッド戦略が終了したときのアセット残高。',
  'gridOrders.detail_in_order_funds': '注文中の資金：',
  'gridOrders.detail_on_hold_funds':
    '保留中の資金（部分的に約定された注文から）：',
  'gridOrders.detail_transactions': '約定済み注文数',
  'gridOrders.detail_investment': '初期投資額',
  'gridOrders.detail_running_time': '期間',
  'gridOrders.detail_prices': '価格帯',
  number_of_grids: 'グリッド数',
  'gridOrders.detail_expire_time': '後で期限切れ',
  'gridOrders.detail_expire_time_tooltip':
    'このグリッド戦略内の注文は、有効期限が切れるとキャンセルされます。',
  'gridOrders.detail_valid_period': '有効期限設定',
  'gridOrders.open_orders_sell': '売却',
  'gridOrders.open_orders_buy': '購入',
  'gridOrders.open_orders_index': '#',
  'gridOrders.open_orders_total': '合計',
  'gridOrders.history_orders_filled': '約定済み：',
  'gridOrders.history_orders_price': '価格：',
  'gridOrders.history_orders_time': '時間',
  'gridOrders.history_orders_filled_price': '平均価格',
  'gridOrders.history_orders_filled_amount': '約定済み',
  'gridOrders.history_orders_filled_total': '合計',
  'gridOrders.history_orders_profit_tips':
    '利益は、安く買って高く売るというサイクルを経て価格差から生まれます。例えば、1 ETH を 4000 USDC で購入するグリッド注文が約定した後、グリッド幅が 50 USDC の場合、システムは自動的に 4050 USDC で 1 ETH を売却する注文を新たに発注します。この注文も約定すると、50 USDC の利益が得られます。',
  'gridOrders.history_orders_buy_flip_order_tips_PRICE':
    'PRICE の買い注文が約定した後、利益が表示されます。',
  'gridOrders.history_orders_sell_flip_order_tips_PRICE':
    'PRICE の売り注文が約定した後、利益が表示されます。',
  'gridOrders.m_history_orders_flip_order_tips_PRICE':
    'PRICE の注文は、約定するとここに表示されます',
  'gridOrders.grid_cancel_title': 'グリッド戦略の終了',
  'gridOrders.grid_cancel_content':
    'このグリッド戦略のすべての注文はすぐにキャンセルされます。',
  'gridOrders.grid_cancel_content2':
    '現在、このグリッド戦略でマイニング中です。このグリッド戦略を終了すると、すべてのマイニング報酬が没収され、関連するすべてのグリッド注文はすぐにキャンセルされます。',
  'gridOrders.copy_grid_title': '次のグリッド戦略のパラメータがコピーされます',
  'gridOrders.copy_grid_btn': 'パネルにコピー',
  'gridOrders.copy_grid_success': 'グリッド戦略がコピーされました',
  'gridOrders.grid_init_funds_XXX': '初期投資額: $XXX',
  'gridOrders.grid_init_funds_tips':
    'APYは、グリッド戦略作成時の初期配分額に基づいて計算されます。',
  'gridOrders.tab_m_trade': '取引',
  grid_apy: 'グリッドAPY',
  grid_apy_tips: 'グリッド取引のみによる年換算利益率。フロート利益は除く。',
  'gridOrders.tab_mining_profit': 'マイニングAPY',
  'gridOrders.tab_mining_profit_tips':
    '年率換算された採掘利益は、グリッド・ストラテジーの初期値と期間から計算されます。',
  'gridOrders.mining_rewards': '報酬:',
  'gridOrders.open_orders_empty_tips':
    'データの読み込み中はしばらくお待ちください',
  'gridOrders.market_value': '時価総額:',
  'gridOrders.market_value_details': '詳細',
  'gridOrders.fund_details': '資金詳細',
  'gridOrders.m_in_order_funds': '注文中の資金',
  'gridOrders.m_in_order_funds_tips':
    'このストラテジーのすべての未決済注文に含まれる資金の合計。',
  'gridOrders.m_on_hold_funds': '待機資金',
  'gridOrders.m_on_hold_funds_tips': '部分的に満たされた注文の結果。',
  'gridOrders.initial_value': '初期値',
  'mining.my_title': 'マイ・マイニング・プール',
  'mining.index_desc':
    'グリッド戦略を作成します。流動性のあるマイニング報酬でグリッドの利益を高めましょう。',
  'mining.apply': '新規プール申請',
  'mining.claimable_rewards_box': '請求可能な報酬',
  'mining.rewards_more': 'その他',
  'mining.tab_pools': 'マイニングプール',
  'mining.tab_my': '私のマイニング統計',
  'mining.pools_tab_live': 'ライブ',
  'mining.pools_tab_upcoming': '今後の予定',
  'mining.pools_funds': '合計TVL',
  'mining.pools_funds_tips':
    '最低注文金額120ドルを満たすグリッド注文の合計金額。',
  'mining.pools_mining_funds': 'マイニングTVL',
  'mining.mining_apr': 'APY',
  'mining.mining_apr_tips':
    'マイニング報酬とマイニングTVLから推定される年率収益率。',
  'mining.view_rule_link': 'マイニングルール',
  'mining.pools_info_to_confirm': '未定',
  'mining.pools_no_wait': '利用可能なマイニングプールはありません',
  'mining.my_mining_funds': 'マイ・マイニング・ファンド',
  'mining.my_mining_rewards': '私のマイニング報酬',
  'mining.my_th_profit_token_price': '最新価格',
  'mining.my_th_total_rewards': 'オールタイムリワード',
  'mining.my_th_24h_rewards': '24時間リワード',
  'mining.my_grids': 'マイ・マイニング',
  'mining.only_show_mining_grids': 'アクティブのみ',
  'mining.my_th_mining_status': 'マイニングステータス',
  'mining.status_framing': 'アクティブ',
  'mining.status_over_price': '価格範囲外',
  'mining.status_mining_over': 'マイニング終了',
  'mining.status_grid_closed': 'ストラテジー終了',
  'mining.status_grid_expired': 'ストラテジー終了',
  'mining.empty_no_faring_grids':
    '現在採掘可能なグリッドストラテジーはありません',
  'mining.go_mining_pool': 'マイニングプールへ移動',
  'mining.go_mining': 'マイニングを開始する',
  'mining.go_to_grid': 'グリッド戦略へ',
  'mining.mining_help': 'マイニングガイド',
  'mining.mining_available': '適格',
  'mining.mining_available_tips': '注文金額の基準を満たす',
  'mining.mining_unavailable': '不適格',
  'mining.mining_partially_available': '一部適格',
  'mining.mining_unavailable_tips': '注文価格の基準を満たしていない',
  'mining.mining_preview': 'マイニングプレビュー',
  'mining.mining_total_profit': 'マイニング報酬',
  'mining.mining_24h_profit': '24時間マイニング報酬',
  'mining.profit_unable_display': '該当なし',
  'mining.mining_funds': 'マイニング資金',
  'mining.mining_funds_tips':
    'この取引ペアのマイニング注文額基準を満たすすべてのグリッドストラテジーからの注文額の合計。',
  'mining.tab_mining_profit_details': '報酬詳細',
  'mining.tab_mining_orders': 'マイニング注文',
  'mining.th_rewards': '報酬',
  'mining.th_rewards_origin': '報酬ソース',
  'mining.th_rewards_origin_tips':
    'マイニング報酬は、グリッド注文価格が注文ブックの報酬価格範囲内（買値の最高値 * 0.99 ~ 売値の最安値 *1.01）にある場合に受け取ることができます。',
  'mining.th_rewards_origin_tips_stable':
    'マイニング報酬は、グリッド注文価格がオーダーブックの報酬価格範囲内（最高買い価格～最低売り価格）にあるときに受け取られます。',
  'mining.th_time': '時間',
  'mining.plan_title': 'ETH/USDCプール詳細',
  'mining.phase_cur': '現在のフェーズ',
  'mining.phase_range_N_XX': 'フェーズ N (XX)',
  'mining.phase_index_N': 'フェーズ N',
  'mining.phase_reward': 'デイリー報酬',
  'mining.phase_to_release': '発表予定',
  'mining.my_rewards': 'マイ・リワード',
  'mining.claimable_rewards': '利用可能',
  'mining.locked_rewards': 'ロック',
  'mining.locker_rewards_tips':
    'マイニング報酬は、グリッド・ストラテジーが12時間有効になってから請求できる。',
  'mining.claimed_success': '請求成功',
  'mining.claimed_tips': '内部送金ですぐに送られます。',
  'mining.claimed_view_btn': '確認する',
  'mining.mining_plan': '採掘スケジュール',
  'mining.phase_unpublished': '発表予定',
  'mining.all_pools': 'すべてのプール',
  'notification.limit_desc_SELL_BASE_QUOTE_AMOUNT_PRICE':
    'AMOUNT BASEを@価格で売る',
  'notification.limit_desc_BUY_BASE_QUOTE_AMOUNT_PRICE':
    'AMOUNT BASEの買い @ 価格相場',
  'notification.stop_limit_desc_SELL_BASE_AMOUNT': 'AMOUNT BASEを売る',
  'notification.stop_limit_desc_BUY_BASE_AMOUNT': '数量ベース購入',
  'notification.cancel_grid_desc_PAIR_PRICES': 'ペア：価格',
  'notification.cancel_market_desc_SELL_BASE_QUOTE_AMOUNT':
    '数量ベースを価格で売る',
  'notification.cancel_market_desc_SELL_BASE_QUOTE_TOTAL':
    '合計金額でベースを売る',
  'notification.cancel_market_desc_BUY_BASE_QUOTE_AMOUNT':
    '合計金額でAMOUNT BASEを購入する',
  'notification.cancel_market_desc_BUY_BASE_QUOTE_TOTAL':
    'BASEをTOTAL QUOTEで買う',
  'notification.cancel_limit': '指値注文取消',
  'notification.cancel_stop_limit': '逆指値注文取消',
  'notification.cancel_market': '成行注文取消',
  'notification.cancel_grid': 'グリッド戦略終了',
  'notification.cancel_limit_expired': '指値注文失効',
  'notification.cancel_stop_limit_expired': '逆指値注文失効',
  'notification.cancel_grid_expired': 'グリッド戦略終了',
  'notification.cancel_limit_order_for_gas_desc':
    '注文のガス代がなくなりました。一部注文が成立し、残りはキャンセルされました。',
  'notification.cancel_limit_order_for_gas_filled_amount': '充填',
  'notification.cancel_limit_order_for_gas_amount': '金額',
  'notification.view_history_orders': '注文履歴を見る',
  'notification.cancel_market_for_depth_title':
    'ご注文の一部が埋まり、キャンセルされました。',
  'notification.price_slippage_protection': '価格スリッページ防止機能',
  'notification.price_slippage_protection_desc':
    'DeGateの成行注文には、ボラティリティが高く流動性が低い場合に損失を限定するため、10%の価格スリッページ保護機能が自動的に含まれています。この保護を回避するには、指値注文を使用します。',
  'notification.cancel_market_for_depth_warning':
    'DeGate成行注文は価格保護メカニズムを導入しており、ユーザーは価格のボラティリティが高く、流動性が低い市場状況での損失を抑えることができます。価格保護機能を利用したくない場合は、指値注文をご利用ください。',
  'notification.dca_plan_ended': 'DCAプラン終了',
  'notification.cancel_dca_desc_PAIR': 'ペア',
  'notification.trade_limit_partially': '指値注文一部約定',
  'notification.trade_limit_filled': '指値注文',
  'notification.trade_market_partially': '成行注文が一部成立',
  'notification.trade_market_filled': '成行注文',
  'notification.trade_stop_limit_partially': '指値逆指値注文',
  'notification.trade_stop_limit_filled': '逆指値注文',
  'notification.mobile_trade_filled_AMOUNT_TOKEN':
    '注文が成立した。トークンを受け取った。',
  'notification.mobile_trade_partially_AMOUNT_TOKEN': '注文が一部成立 注文金額',
  'info.overview': '概要',
  'info.accounts': '総ユーザー数',
  'info.pairs': '取引ペア',
  'info.turnover': '全時間取引高',
  'info.turnover_24': '24時間取引量',
  'info.dg_supply': 'DG循環供給',
  'info.top_movers_no_increased': '24時間以内に値上がりしたトークンなし',
  'info.top_movers_no_decreased': '24時間以内に値下がりしたトークンはない',
  'info.top_pairs': '上位ペア',
  Pair: 'ペア',
  'info.th_change': '24時間変化',
  'info.th_l_up_2': '＋2% 深さ',
  'info.th_l_down_2': '-2% 深さ',
  'info.th_turnover_24': '24時間出来高',
  'info.tvl': '合計値 ロック',
  'm.home': 'ホーム',
  'm.grid': 'グリッド',
  'm.browser_wallet': 'ブラウザウォレット',
  'm.choose_pair': 'ペアを選択',
  'm.orderBook_default': 'デフォルト',
  'm.orderBook_bids': '買い注文',
  'm.orderBook_asks': '売り注文',
  'm.decimals': '10進数',
  'm.lowest_price_24h': '24時間安値',
  'm.highest_price_24h': '24時間足高値',
  'm.vol_24h': '24時間足',
  'm.orderbook_buy': '買い',
  'm.orderbook_sell': '売り',
  'm.go_to_trade': '取引に進む',
  'm.choose_token': 'トークンを選択',
  'm.from_address': '送信者アドレス',
  'm.to_address': '受信者アドレス',
  'm.transfer_send': '送信',
  'm.transfer_receive': '受け取る',
  'm.my_grid': '私のグリッド戦略',
  'm.grid_profit_24': '24時間利益',
  'm.grid_item_trades_24': '24時間取引',
  'm.grid_profit_total': '利益合計',
  'm.grid_over_prices': '値幅外',
  'm.create_grid': 'グリッド戦略の作成',
  'm.grid_history': '取引履歴',
  'm.grid_empty': 'アクティブなグリッド戦略なし',
  'm.grid_tutorial': 'グリッドチュートリアル',
  'm.grid_params_to_manual': 'パラメータをマニュアルにコピー',
  'm.balance_err': 'バランス不足 利用可能',
  'm.preview_grid': 'プレビュー注文',
  last_price: '最終価格',
  'm.grid_desc':
    'グリッド取引は、定義された範囲内での売買を自動化する取引戦略です。',
  'm.view_tutorial': 'チュートリアルを見る',
  'm.grid_profit_tips_sell':
    'この売り注文が完全に満たされたときに計算されます。',
  'm.grid_profit_tips_buy':
    'この買い注文が完全に満たされたときに計算されます。',
  'm.hot': 'ホット',
  'm.all': '全てを見る',
  'm.vol_24': '24時間足',
  'm.transfer_t1': '内部',
  'm.transfer_t2': '振替',
  'activity.th_date': '時間',
  'activity.th_type': 'タイプ',
  'activity.th_fee': '料金',
  'activity.th_content': '内容',
  'activity.type_register_token': 'トークン一覧',
  'activity.type_register_pair': 'ペア追加',
  'activity.type_pay_deposit': '入金決済',
  'activity.type_reset_account': 'アセットキーのリセット',
  on_chain_order_cancellation: 'オンチェーン注文キャンセル',
  'activity.count_N': 'カウント N',
  'activity.order_desc_SELL_AMOUNT_BASE_PRICE_QUOTE': '売り注文',
  'activity.order_market_desc_SELL_AMOUNT_BASE': '売り金額ベース',
  'activity.reset_status_restting': 'リセット',
  'activity.to_trade': '取引',
  'dca.dca_plan': 'DCAプラン',
  'dca.dca_explain': 'ドルコスト平均法',
  'dca.daily': '日次',
  'dca.weekly': '週足',
  'dca.custom': 'カスタム',
  'dca.every': '毎',
  'dca.amount_per_order': '注文ごとの金額',
  'dca.price_limit': '価格制限',
  'dca.maximum_price': '最高価格',
  'dca.minimum_price': '最低価格',
  'dca.number_of_orders': '注文数',
  'dca.create_dca_plan': 'DCAプランの作成',
  'dca.max_gas_fee_per_order': '注文あたりの最大ガス料金',
  'dca.maximum_plan_order_limit_reached': 'プランの最大注文数に達しました。',
  'dca.end_time_should_be_set_after_the_current_time':
    '終了時刻は現在時刻より後に設定してください。',
  'dca.please_enter_amount_per_order': '注文ごとの金額を入力してください。',
  'dca.please_enter_maximum_price': '最大価格を入力してください',
  'dca.please_enter_minimum_price': '最低価格を入力してください。',
  'dca.order_placement_failed_open_order_limit_exceeded':
    '注文発注に失敗しました: 未決済注文の上限を超えました。',
  'dca.total': '合計',
  'dca.filled': '注文済み',
  'dca.received': '受信済み',
  'dca.time_to_end': '終了時間',
  'dca.cancel_on_chain': 'キャンセル',
  'dca.filled_amount': '記入/金額',
  'dca.status_executed': '実行済み',
  'dca.status_scheduled': '予約済み',
  'dca.status_failed': '失敗',
  'dca.order_cancled_by_user':
    'ユーザーがDCAプランを終了したため、注文がキャンセルされました。',
  'dca.order_cancled_by_access':
    'DeGateへのアクセスが制限されたため、注文がキャンセルされました。',
  'dca.order_cancled_by_gas': 'ガス料金不足のため、発注に失敗しました。',
  'dca.order_cancled_by_order_book':
    '注文ブックに一致する注文がないため、注文発注に失敗しました。',
  'dca.order_cancled_by_balance':
    'DeGate残高が不足しているため、注文発注に失敗しました。',
  'dca.order_cancled_by_min_value':
    '最低注文金額100ドルを満たしていないため、発注に失敗しました。',
  'dca.order_cancled_by_system_error':
    'システムエラーにより発注に失敗しました。',
  'dca.chain_cancel_no_need_tips':
    'このDCAプランでは、オンチェーンキャンセルは必要ありません。',
  'dca.end_dca_plan': 'DCAプランの終了',
  'dca.all_orders_in_this_dca_plan_will_be_canceled_immediately':
    'このDCAプランの注文はすべて直ちにキャンセルされます。',
  'dca.no_active_dca_plan': 'アクティブなDCAプランはありません。',
  'dca.time_scheduled': '予定時刻',
  'campaign.event_period': 'イベント期間',
  'campaign.grid2401_time':
    '2024年1月22日20:00:00～2024年1月29日20:00:00 (UTC+8)',
  'campaign.event_has_ended': 'イベントは終了しました。',
  'campaign.current_apy': '現在の年率利回り（APY）',
  'campaign.grid_strategy_income':
    'グリッド・ストラテジー・インカム＋賞金プール・シェア',
  'campaign.tvl_participating': 'TVL参加',
  'campaign.share_of_tvl': 'TVLのシェア',
  'campaign.my_profit': '私の利益',
  'campaign.grid_strategy_profit': 'グリッド・ストラテジー利益',
  'campaign.share_of_prize_pool': '賞金プールのシェア',
  'campaign.grid_strategy_profit_has_been_added_to_your_available_balance':
    'グリッド・ストラテジーの利益が利用可能残高に追加されました。',
  'campaign.shared_income_from_usdc_prize_pool': 'USDC賞金プールからの共有収入',
  'campaign.is_black_tips': '賞金プールを共有する資格はありません。',
  'campaign.calculating': '計算',
  'campaign.claim_after_end': '賞金はイベント終了時に請求できます。',
  'campaign.how_to_participate': '参加方法',
  'campaign.rule': 'グリッド戦略を作成し、賞金プールを比例配分します。',
  'campaign.step1': 'ステップ1',
  'campaign.step2': 'ステップ2',
  'campaign.step3': 'ステップ3',
  'campaign.grid2401_step1':
    '資金を追加したり取引したりして、ETHとUSDCを準備する。',
  'campaign.grid2401_step2_PAIR':
    '以下のようにPAIRのグリッド戦略を設定します。',
  'campaign.grid2401_step2_desc1_pre': '価格帯： 発表予定',
  'campaign.grid2401_step2_desc2_pre': 'グリッドの数 未定',
  'campaign.copy_strategy': 'ストラテジーのコピー',
  'campaign.grid2401_step3':
    'イベント終了後、このイベントページで収益を請求することができます。イベント終了後30日以内にご請求ください。',
  'campaign.what_is_grid': 'グリッド戦略とは',
  'campaign.notes': '参加にあたって',
  'campaign.notes_1_title': '参加資格',
  'campaign.notes_1_desc':
    'グリッド・ストラテジーは、価格帯とグリッド数が作成時に要求されたものと全く同じ場合のみ対象となります。',
  'campaign.notes_2_title': '制限',
  'campaign.notes_3_title': '賞金請求',
  'campaign.notes_3_desc':
    '賞金請求はイベント終了時に可能となり、イベント終了後30日以内に請求することができます。',
  'campaign.faq': 'よくある質問',
  'campaign.grid2401_faq_1': '1. 賞金はどのように計算されますか？',
  'campaign.grid2401_faq_2':
    '2. このイベントに関する質問はどこで受け付けていますか？',
  'campaign.grid2401_faq_3':
    '3. USDTを保有していますが、ETHとUSDCはどのように入手できますか？',
  'campaign.grid2401_faq_4':
    '4. グリッド戦略を通じて完了した取引に手数料を支払う必要がありますか？',
  'campaign.grid2401_faq_4_res':
    'DeGateでは、メーカー注文はすべて無料です。グリッドストラテジーで生成される注文は全てメーカー注文ですので、DeGateでのグリッドストラテジーの設定は完全に無料です。',
  'campaign.grid2401_faq_5':
    '5. グリッドストラテジーはイベント終了後も収益を生み出しますか？',
  'campaign.grid2401_faq_5_res':
    'はい、イベント終了後も、価格がストラテジーの範囲内であれば、ストラテジーは収益を生み続けます。また、イベント終了後も、グリッド・ストラテジーのパラメーターを調整することで、よりご自身の好みに合ったストラテジーを作成し、引き続き収益を得ることができます。',
  'campaign.grid2401_faq_others': 'その他のイベント詳細',
  'campaign.grid2401_faq_others_1':
    '1. 1ユーザーにつき1ウォレットのみ。悪質なシビル・リワード・ファーミングが検出された場合、DeGateは参加者のリワードをキャンセルする権利を有します。',
  'campaign.grid2401_faq_others_2':
    '2. イベント期間中、範囲外のグリッドもウェイト計算の一部としてカウントされます。',
  'campaign.grid2401_faq_others_3':
    '3. DeGate は、極端な状況（市場の変動など）において、イベントを早期に終了する権利を留保します。',
  'campaign.grid2401_faq_others_4':
    '4. イベント終了後30日以内に請求されなかった報酬は没収されます。',
  'campaign.invest_max_5000': '最高投資額5,000ドル',
  'campaign.invest_mininum': '最低投資額',
  'airdrop.create_airdrop': 'エアドロップを作成する',
  'airdrop.important_note':
    '重要：誰でも許可なくエアドロップを作成することができます。',
  'airdrop.my_airdrop': 'マイ・エアドロップ',
  'airdrop.time_limited': '期間限定',
  'airdrop.no_airdrop': 'まだエアドロップはありません',
  'airdrop.claim_airdrop': 'エアドロップを申請する',
  'airdrop.recipients_number': '受取人数',
  'airdrop.total_amount': '合計金額',
  'airdrop.retrieve': '回収',
  'airdrop.unclaimed': '未請求',
  'airdrop.retrieve_successful': '回収成功',
  'airdrop.claim_successful': '請求成功',
  'airdrop.retrieve_unclaimed_airdrop': '未請求のエアドロップを検索する',
  'airdrop.airdrop_token': 'エアドロップ・トークン',
  'airdrop.token_not_meet_criteria':
    'このトークンはエアドロップの条件を満たしていません。',
  'airdrop.airdrop_list': 'エアドロップ一覧',
  'airdrop.download_template': 'テンプレートのダウンロード',
  'airdrop.click_or_drag_upload_list':
    'クリックまたはドラッグしてリストをアップロード',
  'airdrop.validation_passed': '有効期限',
  'airdrop.must_earlier_than_end_time': '終了時間前であること',
  'airdrop.cannot_more_than_2_years_from_now': '2年以上先であること',
  'airdrop.cannot_parse_file':
    'ファイルを解析できません。テンプレートをご利用ください。',
  'airdrop.format_requirement_not_met': 'フォーマット要件を満たしていません。',
  'airdrop.view_error_repost': 'エラーレポートを見る',
  'airdrop.error_report': 'エラー・レポート',
  'airdrop.line': 'ライン',
  'airdrop.reason': '理由',
  'airdrop.duplicated_address': '住所の重複',
  incorrect_address_format: '住所の書式が正しくない',
  'airdrop.incorrect_amount_format': '金額形式が正しくない',
  'airdrop.airdrop_plan_created': 'エアドロップ・プランの作成',
  'airdrop.max_50000': '最大50000アドレス',
  'airdrop.upload_file_rule': 'CSVのみ対応',
  'airdrop.to_check_airdrop_eligibility':
    'エアドロップを表示するための初期化完了',
  'airdrop.complete_initialization_to_claim_airdrops':
    'エアドロップ請求初期化完了',
  'airdrop.complete_initialization_to_view_airdrops':
    'エアドロップ閲覧初期化完了',
  'airdrop.you_are_eligible_for': '対象となります：',
  'airdrop.and_more': 'その他',
  'airdrop.congratulations': 'おめでとうございます！',
  'airdrop.airdrop_fee': 'エアドロップ料金',
  'countdown.countdown_plan': 'カウントダウンプラン',
  'countdown.create_countdown_plan': 'カウントダウン作成',
  'countdown.my_countdown_plan': '私の作品',
  'countdown.countdown_trading_pair': 'カウントダウン取引ペア',
  'countdown.countdown_display': 'カウントダウン表示',
  'countdown.token_not_meet_criteria':
    'このトークンはカウントダウンの条件を満たしていません。',
  'countdown.countdown_tips':
    '選択した取引ペアの取引ページにカウントダウンが表示されます。',
  'countdown.max_30_days': '今から30日以内',
  'countdown.review_countdown_plan': 'カウントダウンプラン',
  'countdown.countdown_fee': 'カウントダウン料金',
  'countdown.countdown_plan_created': 'カウントダウンプラン作成',
  'countdown.trading_will_start_in': '取引開始日',
  'countdown.trading_will_start_at_YYYY': '取引開始日時',
  'countdown.cannot_earlier_than_current_time':
    '現在時刻より前に約定することはできません。',
  'dca.price_limit_buy_tips':
    '有効化されると、買い注文は最大価格と同じかそれ以下の価格でのみ執行されます。この機能は手数料ゼロ機能と互換性があります。',
  'dca.price_limit_sell_tips':
    '有効化すると、売り注文は最低価格以上の価格でのみ執行されます。この機能は手数料ゼロ機能と互換性があります。',
  'dca.zero_fee': 'ゼロ・フィー',
  'dca.zero_fee_buy_tips':
    'ゼロフィーを有効にすると、DCA注文はメーカー指値注文として処理されます。発注後、注文ブックで最も高い買値が設定されます。注文がすぐに成立しない、または全く成立しない可能性があることにご留意ください。',
  'dca.zero_fee_sell_tips':
    'ゼロフィーを有効にすると、DCA注文はメーカー指値注文として処理されます。DCA注文はMaker-Onlyの指値注文として処理され、各売値は発注後のオーダーブックにおける最安値の売呼値に設定されます。注文が即時に成立しない、または全く成立しない可能性があることにご留意ください。',
  'dca.order_canceled_post_only_buy_failed':
    '注文ブックに買い注文がないため、注文発注に失敗しました。',
  'dca.order_canceled_post_only_sell_failed':
    '注文ブックに売り注文がないため、注文発注に失敗し、注文の売り価格が設定されない。',
  start_time_cannot_before_current_time:
    '開始時刻が現在時刻より前であることはできません。',
  start_time_must_before_end_time:
    '開始時刻は終了時刻より前でなければなりません。',
  list_token: 'トークン一覧',
  contract_address_does_not_exist: '契約アドレスが存在しません。',
  token_listed: 'このトークンは上場済みです。',
  XXX_is_listed: 'XXXをリストアップ中',
  view_progress: '進捗を見る',
  pair_create_tips: 'DeGateでは、取引ペアの即時追加が可能です。',
  base_token: '基本トークン',
  quote_token: 'クォート・トークン',
  existing_pair: '既存のペア',
  trade_now: '今すぐ取引',
  pair_XXX_added_successfully: 'XXXが正常に追加されました',
  qty_per_grid: 'グリッドあたりの数量',
  grid_minimum_not_reached: '最小値に達しない',
  total_profit: '利益合計',
  total_apy: '合計APY',
  float_profit: 'フロート利益',
  grid_profit_24h: '24時間グリッド利益',
  pnl: 'PnL',
  eligibility: '適格性',
  rewards: '報酬',
  view_mining_statistics: 'マイニング統計を見る',
  your_entry: '資金入力',
  refunded: '返還済み',
  large_price_spread: '大きな価格スプレッド',
  large_price_spread_tips:
    'オーダーブックに最安売り価格と最高買い価格の間に大きなスプレッドがあり、損失のリスクがあります。デュアルアセットモードでの投資を推奨します。',
  continue_anyway: 'それでも続行',
  insufficient_order_book_liquidity_decrease_investment:
    'オーダーブックの流動性が不十分です。投資を減らしてください。',
  initial_buy: '初回買い',
  closing_sell: '売却終了',
  No: 'いいえ',
  DCA_TRIGGER_FAIL_TIPS_PRICE_XXX:
    'DCA注文は、実行時に<b>$XXXの価格が$PRICEを下回る場合</b>に失敗します。',
  zero_fee: 'ゼロ手数料',
  minimum_order_value_is_VALUE: '最小注文額は<b>$VALUE</b>です。',
  Note: '注記',
  Continue: '続行',
  estimated_apy: '推定APY',
  based_on_data_from_last_7_days: '過去7日間のデータに基づく',
  top_gainers_24h: '24時間トップ上昇銘柄',
  top_losers_24h: '24時間トップ下落銘柄',
  listed_tokens: 'リストされたトークン',
  vol: 'ボリューム',
  let_s_go: '行こう',
  reject: '拒否',
  maximum_N_due_to_price_ticks: '価格刻みによる最大N',
  Saved: '保存済み',
  minimum_order_value_$100_$QUOTE: '最小注文額は<b>$100 $QUOTE</b>です。',
  minimum_order_value_$AMOUNT_$QUOTE_$100:
    '最小注文額は<b>$AMOUNT $QUOTE</b>（約$$100）です。',
  no_restriction_with_market_order: '<b>マーケットオーダー</b>では制限なし',
  go_to_market_order: 'マーケットオーダーに進む',
  Mining_Eligibility: 'マイニング適格性',
  How_to_earn_mining_rewards: 'マイニング報酬を得る方法',
  Order_Value: '注文額',
  'mining.mining_tips_BV_BASE_QV_QUOTE':
    'グリッド注文は、戦略作成時に<b>BV BASE</b>または<b>QV QUOTE</b>である必要があります。',
  'mining.mining_tips_QV_QUOTE':
    'グリッド注文は、戦略作成時に<b>QV QUOTE</b>である必要があります。',
  Mining_Price_Range: 'マイニング価格範囲',
  'mining.status_over_price_tips':
    'グリッド注文の価格は、オーダーブック内の最高買い価格 * 0.99から最低売り価格 * 1.01までの<b>マイニング価格範囲</b>内である必要があります。',
  'mining.status_over_price_tips_stable':
    'グリッド注文の価格は、オーダーブック内の最高買い価格から最低売り価格までの<b>マイニング価格範囲</b>内である必要があります。',
  Eligible_for_Mining: 'マイニングに適格',
  Mining_Satus: 'マイニングステータス',
  Mining_Satus_Mining: 'マイニング',
  Mining_Satus_Standby: '待機中',
  Mining_Satus_Ineligible: '非適格',
  mining_price_range: 'マイニング価格範囲',
  rewards_tips_stable:
    '戦略作成時にマイニング注文額の条件を満たしたグリッド注文は、マイニング価格範囲内（最高買い価格～最低売り価格）に収まればマイニング報酬を受け取れます。',
  rewards_tips:
    '戦略作成時にマイニング注文額の条件を満たしたグリッド注文は、マイニング価格範囲内（最高買い価格 * 0.99～最低売り価格 * 1.01）に収まればマイニング報酬を受け取れます。',
  wrap: 'ラップ',
  Wrap: 'ラップ',
  websites_for_more_information: '詳細情報のウェブサイト:',
  official_site: '公式サイト',
  wrap_site: 'ラップ/アンラップサイト',
  tips_third_party_site:
    'DeGateを離れ、サードパーティサイトにアクセスしようとしています:',
  wrap_unwrap: 'ラップ/アンラップ',
  Receive: '受け取る',
  Network: 'ネットワーク',
  Token_Contract: 'トークンコントラクト',
  please_select_network: 'ネットワークを選択してください',
  maximum_amount: '最大金額',
  send_USDC_to_this_address: 'このアドレスにUSDCを送金してください',
  arpa_airdrop: '$ARPAエアドロップ',
  Failed_to_proceed: '処理に失敗しました。',
  Please_select_the_Ethereum_network:
    'Ethereumネットワークを選択してください。',
  NATIVE_USDC_ONLY: 'ネイティブUSDCトークンのみ',
  NEVER_send_bridged_USDC: 'ブリッジされたUSDCを送らないでください',
  I_understand: '理解しました',
  recipient_address: '受取人アドレス',
  chain_0: 'DeGate',
  chain_1: 'Ethereum',
  chain_17000: 'Ethereum',
  chain_42: 'Kovan',
  chain_42161: 'Arbitrum',
  chain_421614: 'Arbitrum',
  chain_10: 'Optimism',
  chain_11155420: 'Optimism',
  chain_137: 'Polygon',
  chain_80002: 'Polygon',
  scan_1: 'Etherscan',
  scan_17000: 'Etherscan',
  scan_42161: 'Arbiscan',
  scan_421614: 'Arbiscan',
  scan_10: 'Opscan',
  scan_11155420: 'Opscan',
  scan_tips:
    'このアクションを含むロールアップトランザクションはまだEthereum上に投稿されていません。それまでは、DGSCANはこのアクションを<b>表示しません</b>。',
  Best_Liquidity: '最高流動性',
  order_partially_filled: '注文が一部のみ約定',
  order_partially_filled_for_liquidity:
    'オーダーブックの流動性が突然低下したため、残りの注文がキャンセルされました。この保護措置により、不利な価格での約定が防止されます。',
  'orders.export_data_2_year': '過去2年間のデータをエクスポート',
  Community: 'コミュニティ',
  complete_in_seconds: '数秒で完了',
  failed_to_send: '送信に失敗しました。再度お試しください。',
  failed_to_send_try_other_networks:
    '送信に失敗しました。他のネットワークを試してください。',
  gas_fee_deducted: 'ガス料金控除済み:',
  sum_XXX: '合計 XXX',
  chart_control_7d: '7日',
  chart_control_30d: '30日',
  chart_control_all: 'すべて',
  chart_control_day: '日',
  chart_control_week: '週',
  chart_control_month: '月',
  Coming: '近日公開',
  leave_survey_title: 'こんにちは、DeGateを離れようとしているようです',
  leave_survey_subtitle:
    'あなたのフィードバックで私たちを改善する手助けをしてください。該当する項目をすべて選択してください。',
  leave_survey_not_leaving:
    '私は離れていません。すぐに戻ってきますよ、バカな！',
  leave_survey_other_is_fine:
    'Binance/OKX/Krakenなどが私には問題なく動作しています。',
  leave_survey_bad_experience: '取引の体験が好きではありません。',
  leave_survey_no_yield: '収益の機会を見つけられませんでした。',
  leave_survey_no_needed_token: '取引したいトークンが見つかりませんでした。',
  leave_survey_other_reason: 'その他（以下のボックスにご記入ください）',
  leave_survey_thanks_for_feedback: 'フィードバックありがとうございます。',
  Submitted: '提出済み',
  doc_title:
    'DeGate: 分散型オーダーブック取引所 | GRIDとDCAで無料の暗号通貨トレーディングボット',
  doc_desc:
    'DeGateは数百種類の暗号通貨を低手数料で取引できるトップの分散型オーダーブック取引所で、無料の指値注文取引、グリッド取引、DCAボットを提供しています。',
  doc_title_spot: '分散型オーダーブックDeGate DEX',
  doc_title_grid: '分散型グリッド取引ボットDeGate DEX',
  doc_title_dca: '分散型DCA取引ボットDeGate DEX',

  Notification: '',
  read_all: '',
  important: '',
  general: '',
  view_more: 'その他',
  thats_all: '',
  XXX_fund_addition_processing: '',
  add_AMOUNT_XXX_to_DeGate: '',
  XXX_fund_addition_successful: '',
  XXX_send_successful: '',
  send_AMOUNT_XXX_to_DeGate: '',
  send_AMOUNT_XXX_to_Ethereum: '',
  you_have_received_a_new_airdrop: '',
  AMOUNT_XXX_can_be_claimed_after_YYYY_MM_DD: '',
  MARKET_Chart: '',
  grid_free: '',
  maker_free_tips: '',
  Audit: '',
  Tool: '',
  About: '',
};

export default ja;
