const ru = {
  language: 'ru-RU',
  'kline.time_Line': 'Время',
  'kline.time_1m': '1м',
  'kline.time_3m': '3м',
  'kline.time_5m': '5м',
  'kline.time_15m': '15м',
  'kline.time_30m': '30м',
  'kline.time_1H': '1ч',
  'kline.time_2H': '2ч',
  'kline.time_4H': '4ч',
  'kline.time_6H': '6ч',
  'kline.time_1D': '1Д',
  'kline.time_1W': '1Н',
  'kline.time_1M': '1М',
  'kline.tab_line': 'График',
  'kline.tab_depth': 'Глубина',
  'kline.chartType_Bars': 'Столбцы',
  'kline.chartType_Candles': 'Свечи',
  'kline.chartType_Hollow_Candles': 'Пустые свечи',
  'kline.chartType_Line': 'Линия',
  'kline.chartType_Area': 'Площадь',
  'kline.chartType_Heikin_Ashi': 'Хейкен Аши',
  degate_account: 'Аккаунт DeGate',
  Trade: 'Торговля',
  Order: 'Заказ',
  Grid: 'Сеточная Grid стратегия',
  Campaign: 'Кампания',
  DCA: 'DCA',
  Advanced: 'Расширенный',
  Add: 'Добавить',
  Add_Funds: 'Добавить средства',
  eth_added_1: 'Добавлено 1 ETH',
  eth_sent_1: 'Отправлено 1 ETH',
  Send: 'Отправить',
  Internal_Transfer: 'Внутренний перевод',
  Miscellaneous: 'Разное',
  Bridge: 'Мост',
  Mining: 'Майнинг',
  Liquidity_Mining: 'Майнинг ликвидности',
  Analytics: 'Аналитика',
  Support: 'Поддержка',
  Help: 'Помощь',
  Tips: 'Совет',
  Statistics: 'Статистика',
  Coming_soon: 'Скоро',
  Faucet: 'Кран',
  more: 'Больше',
  hide: 'Скрыть',
  change: 'Изменить',
  'Wrong Network': 'Неверная сеть',
  avbl: 'Доступно:',
  insufficient_balance_AAA:
    'Недостаточно AAA в вашем кошельке. Пожалуйста, проверьте и попробуйте снова.',
  insufficient_balance: 'Недостаточный баланс',
  wallet_denied_sign: 'Подпись сообщения была отклонена.',
  common_err: 'Что-то пошло не так. Пожалуйста, попробуйте позже.',
  common_err_ledger_version:
    'Произошла ошибка. Убедитесь, что ваше приложение Ledger Ethereum обновлено (1.9.10 или новее), или попробуйте позже.',
  network_1: 'Основная сеть Ethereum',
  network_err: 'Ошибка сети. Пожалуйста, попробуйте позже.',
  rate_limit_err: 'Частота доступа слишком высока, повторите через минуту.',
  error_InsufficientGasFunds: 'Недостаточно газа в кошельке',
  notification_transaction_send: 'Транзакция отправлена',
  view_on_etherscan: 'Посмотреть в Blockchain Explorer',
  view_on_explorer: 'Посмотреть адрес',
  switch_network: 'Переключить сеть',
  switch_to_Arbitrum: 'Переключитесь на Arbitrum для продолжения.',
  switch_to_MAINNET_in_metamask:
    'Пожалуйста, переключитесь на MAINNET в MetaMask',
  switch_to_MAINNET: 'Пожалуйста, переключитесь на MAINNET',
  switch_network_in_walletconnect:
    'Перейдите в кошелек и переключите сеть с WalletConnect',
  Retry: 'Повторить',
  wallet_tips: 'Пожалуйста, подтвердите в браузерном кошельке',
  wallet_ledger_tips: 'Пожалуйста, подтвердите в аппаратном кошельке Ledger',
  wallet_metamask_tips: 'Пожалуйста, подтвердите в MetaMask',
  wallet_walletconnect_tips:
    'Перейдите в кошелек для подтверждения через WalletConnect',
  wallet_cancelled_tips: 'Вы отменили подпись',
  Close: 'Закрыть',
  copied: 'Скопировано',
  Details: 'Детали',
  view_details: 'Посмотреть детали',
  Share: 'Поделиться',
  view_graph: 'Просмотр на графике',
  Dismiss: 'Закрыть',
  Cancel: 'Отмена',
  End: 'Завершить',
  End_grid: 'Завершить',
  Confirm: 'Подтвердить',
  Cancel_all: 'Отменить все',
  cancel_all_tips: 'Отменить все открытые ордера',
  Submit: 'Отправить',
  no_data: 'Нет данных',
  all_data_displayed: 'Все данные отображены',
  no_data_within_90_days: 'Нет данных за последние 90 дней',
  only_display_90_days: 'Отображаются данные только за последние 90 дней',
  displayed_90_days: 'Отображаются данные за последние 90 дней',
  only_data_beyond_90_days_trade:
    'Для доступа к данным за период более 90 дней выберите ""Просмотреть все"", а затем функцию ""Экспорт данных""',
  only_data_beyond_90_days_grid_detail:
    'Исторический запрос данных более чем за последние 90 дней в настоящее время не поддерживается',
  only_data_beyond_90_days_spot_history:
    'Для доступа к данным за более чем 90 дней используйте функцию ""Экспорт данных""',
  View: 'Посмотреть',
  service_unavailable_for_region_REGION: 'Эта услуга недоступна в РЕГИОНЕ.',
  service_unavailable: 'Услуга недоступна',
  service_error: 'Пожалуйста, попробуйте позже',
  service_maintenance: 'Эта услуга проходит техническое обслуживание.',
  connect_wallet: 'Подключить кошелек',
  switch_address: 'Сменить адрес',
  wallet_wc: 'Подключено через WalletConnect',
  wallet_ledger: 'Подключено через Ledger',
  register_dexAccount: 'Регистрация',
  deposit_ETH: 'Добавить ETH',
  initialize: 'Инициализировать',
  initialization: 'Инициализация',
  invalid_signature: 'Неверная подпись',
  possible_cause: 'Возможная причина:',
  locale_time_error: 'Время на вашем устройстве неверно.',
  authorization_mode: 'Режим аутентификации',
  authorization_mode_standard: 'Без подписи',
  authorization_mode_single_use: 'Всегда подписывать',
  turn_on: 'Включить',
  turn_on_signature_free_mode: 'Включить режим Без подписи',
  signatre_free_mode: 'Режим Без подписи',
  turn_on_signature_free_mode_tips:
    'В этом режиме вы можете размещать ордера без подписи. Чтобы сменить режим, перейдите в ""Настройки"" под кнопкой ""Торговля"".',
  turn_on_signature_free_mode_tips_grid:
    'В этом режиме вы можете создавать сеточные Grid стратегии без подписи. Чтобы сменить режим, перейдите в ""Настройки"" под кнопкой ""Торговля"".',
  turn_on_signature_free_mode_tips_dca:
    'В этом режиме вы можете создавать DCA планы без подписи. Чтобы сменить режим, перейдите в ""Настройки"" под кнопкой ""Торговля"".',
  yes: 'Да',
  no: 'Нет',
  free_mode_on: 'Режим Без подписи включен',
  view_balance: 'Просмотреть баланс',
  delete_asset_key: 'Удалить ключ актива',
  delete_asset_key_desc:
    'Режим Без подписи будет отключен после удаления ключа актива из вашего браузера.',
  no_asset_key_tips: 'Ключ актива не найден в вашем браузере',
  turn_off_standard_mode: 'И выключить режим Без подписи',
  reset_asset_key: 'Сбросить ключ актива',
  view_asset_key: 'Просмотреть ключ актива',
  lock_success: 'Ключ актива удален',
  reset: 'Сбросить ключ актива',
  delete: 'Удалить',
  withdraw_ETH: 'Отправить ETH',
  transfer_ETH: 'Внутренний перевод ETH',
  history: 'История',
  view_history: 'Просмотреть в истории',
  internal_transfer: 'Перевод',
  assets_record_link: 'История',
  other: 'Другое',
  login_success: 'Успешное подключение',
  Account: 'Учетная запись',
  Address: 'Адрес',
  Disconnect: 'Отключиться',
  copy_address: 'Скопировать адрес',
  copy_grid: 'Скопировать стратегию',
  Copy: 'Копировать',
  btn_search: 'Поиск',
  btn_reset: 'Сбросить',
  btn_confirm: 'Закрыть',
  btn_max: 'Макс',
  btn_ok: 'ОК',
  spot_trade: 'СПОТ',
  grid_trade: 'GRID',
  err_balance_title: 'Ошибка при размещении ордера',
  err_balance_content:
    'Недостаточно доступного баланса. Пожалуйста, проверьте и попробуйте снова.',
  order_failed: 'Ошибка ордера',
  insufficient_order_value: 'Недостаточная стоимость ордера',
  grid_failed: 'Создание не удалось',
  err_eth_gas: 'Сеть Ethereum сильно перегружена',
  err_insufficient_balance_TOKEN1: 'Недостаточно баланса TOKEN1',
  err_insufficient_balance_TOKEN1_TOKEN2:
    'Недостаточно балансов TOKEN1 и TOKEN2',
  please_add_funds_before_ordering:
    'Пожалуйста, добавьте средства на баланс DeGate перед размещением ордера.',
  err_balance_content_spot:
    'Ошибка размещения ордера из-за недостаточного баланса.',
  err_balance_content_grid:
    'Ошибка создания сеточной Grid стратегии из-за недостаточного баланса.',
  trade_min_volume_tips_XXX: 'Мин XXX',
  grid_min_volume_tips:
    'Количество на ордер не соответствует минимальной сумме. Пожалуйста, попробуйте еще раз.',
  trade_risk_orders_tips:
    'Невозможно разместить ордер, так как у вас слишком много открытых ордеров',
  gas_token_tips: 'Выберите токен для комиссии за газ',
  add_favorite_tooltip: 'Добавить в избранное',
  remove_favorite_tooltip: 'Удалить из избранного',
  expire_tips_X: 'Этот ордер истечет X.',
  today: 'Сейчас',
  now: 'Сейчас',
  time_D_day: 'Дд',
  time_D_day_H_hour: 'Дд Чч',
  time_H_hour_M_minute: 'Чч Мм',
  time_M_minute_S_second: 'Мм Сс',
  time_S_second: 'Сс',
  around: '～',
  time_now: 'сейчас',
  time_before: '',
  time_before_ago: 'назад',
  time_1_minute: '1 минута',
  time_1_hour: '1 час',
  time_1_day: '1 день',
  time_1_year: '1 год',
  time_M_minutes: 'М минут',
  time_M_m: 'Мм',
  time_H_hours: 'Ч часов',
  time_H_h: 'Чч',
  time_D_days: 'Д дней',
  time_Y_years: 'Г лет',
  time_Y_y: 'Гг',
  fee_change_tips: 'Цена обновлена',
  no_pairs: 'Торговая пара не найдена',
  register_new_pair: 'Добавить новую пару',
  register_pair: 'Добавить торговую пару',
  add_pair: 'Добавить пару',
  tips_hide_forever: 'Больше не показывать',
  token: 'Токен',
  action: 'Действие',
  more_actions: 'Больше',
  gas_fee: 'Комиссия за газ',
  'orders.detail_gas': 'Фактическая комиссия за газ',
  trade_fee: 'Торговая комиссия',
  about_degate: 'О DeGate',
  metrics: 'Метрики',
  fees: 'Комиссии',
  document: 'Документы',
  join_us: 'Присоединяйтесь к нам',
  feedback: 'Обратная связь',
  email_optional: 'Ваш электронный адрес (по желанию)',
  Upload: 'Загрузить',
  feedback_upload_tip:
    'Поделитесь своими отзывами. Перетащите файлы для прикрепления.',
  feedback_upload_tip_mobile: 'Поделитесь своими отзывами.',
  image_upload_tip: 'Отпустите, чтобы добавить',
  feedback_success: 'Мы вас слышим!',
  feedback_success_2: 'Спасибо',
  feedback_failed: 'Отправка не удалась. Пожалуйста, попробуйте позже.',
  image_upload_rule_1: 'Поддерживаются только PNG, JPG, JPEG.',
  image_upload_rule_2: 'Максимальный размер – 20 МБ на файл.',
  image_upload_rule_3: 'До 5 файлов.',
  image_upload_rule_2_3: 'Максимальный размер – 20 МБ на файл. До 5 файлов.',
  no_pair: 'Токен пара не найдена',
  no_token: 'Токен не найден',
  choose_base_token: 'Выберите базовый токен',
  choose_quote_token: 'Выберите токен-котировку',
  get_test_token: 'Получить тестовый токен',
  faucet: 'Кран',
  expire_in: 'Истекает через',
  expire_in_empty_err: 'Введите число',
  go_back: 'Вернуться назад',
  max_XXX: 'Макс XXX',
  min_XXX: 'Мин XXX',
  fill_in: 'Заполнить',
  my_balance: 'Мой баланс',
  deGate_insufficient_fees:
    'Недостаточно баланса DeGate для оплаты комиссии за газ',
  wallet_balance: 'Баланс кошелька',
  your_wallet_balance: 'Ваш баланс кошелька',
  degate_balance: 'Баланс DeGate',
  wallet_insufficient_fees: 'Недостаточно баланса в кошельке',
  wallet_insufficient_balance: 'Недостаточный баланс',
  insuffficient_wallet_balance: 'Недостаточно баланса в кошельке',
  degate_insufficient_balance: 'Недостаточно доступного баланса',
  open_discord: 'Перейти в сообщество Discord',
  err_valid_until:
    'Пожалуйста, настройте локальное время на вашем устройстве по стандартному времени',
  tips_gas:
    'Комиссия за газ для этой транзакции будет снята непосредственно с вашего баланса DeGate.',
  maker_free: 'Бесплатно для мейкеров',
  trading_fee_rate: 'Торговая комиссия',
  Free: 'Бесплатно',
  stop_service_1: 'Сайт на техническом обслуживании',
  stop_service_2: 'Оценочное время восстановления',
  stop_upgrade:
    'Новая версия тестовой сети в настоящее время проходит миграцию.',
  stop_trading_1: 'Обновление системы',
  stop_trading_2: 'Торговля временно приостановлена',
  sell: 'продать',
  buy: 'купить',
  SELL: 'ПРОДАТЬ',
  BUY: 'КУПИТЬ',
  Sell: 'Продажа',
  Buy: 'Покупка',
  sell_order: 'Ордер на продажу',
  buy_order: 'Ордер на покупку',
  edit: 'Редактировать',
  status_processing: 'Обработка',
  status_processed: 'В ожидании',
  status_pending: 'В ожидании',
  status_confirming: 'Подтверждение',
  status_success: 'Успех',
  status_completed: 'Завершено',
  status_failed: 'Ошибка',
  status_speeding_up: 'Ускоряется',
  status_canceling: 'Отмена',
  status_canceled: 'Отменено',
  in_progress: 'В процессе',
  limit_order: 'Лимит',
  market_order: 'Рынок',
  stop_limit_order: 'Стоп Лимит',
  balance: 'Баланс',
  empty_connect: 'Сначала подключите кошелек',
  empty_register: 'Сначала инициализируйте',
  empty_months3: 'Нет данных за последние 3 месяца',
  show_months3: 'Показаны данные только за последние 3 месяца',
  view_all: 'Просмотреть все',
  D1: '1Д',
  D5: '5Д',
  M1: '1М',
  M3: '3М',
  M6: '6М',
  YTD: 'С начала года',
  Y1: '1Г',
  all: 'Все',
  paste: 'Вставить',
  clear: 'Очистить',
  total: 'Всего',
  amount: 'Сумма',
  order_amount: 'Сумма ордера',
  price: 'Цена',
  order_total: 'Всего',
  filledAmount: 'Сумма',
  tradeFilledTotal: 'Стоимость',
  orderFilledTotal: 'Всего',
  filledAmount_amount: 'Исполнено/Сумма',
  profit: 'Прибыль',
  incompatible_token:
    'Технические характеристики этого токена несовместимы с протоколом DeGate.',
  next: 'Далее',
  token_not_verified: 'Не подтверждено',
  token_not_verified_tips:
    'Адрес контракта, иконка и символ не подтверждены. Пожалуйста, проверьте адрес контракта через официальные источники, чтобы избежать мошенничества.',
  token_verified: 'Подтверждено',
  token_verified_tips: 'Адрес контракта, иконка и символ совпадают.',
  deposit_tips_region:
    'Обратите внимание, что вы получаете доступ к DeGate в РЕГИОНЕ. Функции торговли и внутреннего перевода недоступны после добавления средств.',
  complete_time: 'Завершить через',
  unable_to_initialize: 'Не удалось инициализировать',
  filter_base: 'База',
  filter_quote: 'Котировка',
  filter_type: 'Тип',
  filter_role: 'Роль',
  option_maker: 'Мейкер',
  option_taker: 'Тейкер',
  start_data: 'Дата начала',
  end_data: 'Дата окончания',
  added_to_favorites: 'Добавлено в избранное',
  removed_to_favorites: 'Удалено из избранного',
  show_recents_50: 'Показаны последние 50 данных.',
  terms_of_service: 'Условия обслуживания',
  tips_small_unfilled:
    'Согласно степени точности, указанной в системном дизайне, небольшая неисполненная часть ордера была возвращена на ваш баланс DeGate.',
  notification: 'Уведомление',
  server_message_SystemRecovery:
    'Пожалуйста, обратите внимание, что после восстановления системы изменились статусы ваших ордеров.',
  learn_more: 'Узнать больше',
  connect_ledger: 'Подключить Ledger',
  ledger_disconnect:
    "Не удалось выполнить 'transferOut' на 'USBDevice': Устройство было отключено.",
  gas_fee_expired:
    'Время действия комиссии за газ истекло. Пожалуйста, отправьте снова.',
  scroll_down_to_refresh: 'Прокрутите вниз, чтобы обновить',
  release_to_refresh_immediately: 'Отпустите, чтобы обновить',
  no_more: 'Данных больше нет',
  loading: 'Загрузка...',
  force_withdrawing_token_tips:
    'Текущая операция не может быть выполнена, так как ваш запрос на принудительный вывод обрабатывается.',
  speed_up: 'Ускорить',
  transaction_submitted: 'Транзакция отправлена',
  tx_speed_up: 'Ускорить транзакцию',
  tx_cancel: 'Отменить транзакцию',
  none: 'Нет',
  Language: 'Язык',
  page: '/Страница',
  go_to: 'Перейти к',
  icon_indicators: 'Индикаторы',
  icon_back: 'Назад',
  icon_forward: 'Вперед',
  icon_full_screen: 'На весь экран',
  icon_exit_full_screen: 'Выйти из полноэкранного режима',
  icon_buy_sell_orders: 'Ордеры на покупку и продажу',
  icon_buy_orders: 'Ордеры на покупку',
  icon_sell_orders: 'Ордеры на продажу',
  icon_enable: 'Нажмите, чтобы включить',
  icon_disable: 'Нажмите, чтобы отключить',
  icon_copy: 'Скопировать адрес',
  icon_view_explorer: 'Просмотреть в Block Explorer',
  icon_display_by_profit: 'Показать по прибыли',
  icon_display_by_time: 'Показать по времени',
  icon_switch: 'Переключить',
  eth_code_tips: 'Родной токен Ethereum. Адреса токен-контракта нет.',
  TBD: 'TBD',
  TVL: 'TVL',
  go_to_discord: 'Или присоединитесь к Discord, чтобы создать тикет',
  release: 'Выпуск:',
  security: 'Безопасность',
  colon: ':',
  zero_balance: 'Нулевой баланс',
  ledger_app_version_tips:
    'Обновите приложение Ethereum на вашем Ledger до версии 1.9.19 или выше, чтобы просмотреть сообщение перед подписанием.',
  ledger_contract_data_tips:
    'Пожалуйста, включите Blind signing или Contract data в настройках приложения Ethereum',
  input_auto_corrected_tooltips:
    'Автоматически исправлено введение после превышения максимального количества цифр',
  maximum_decimal_reached:
    'Достигнуто максимальное количество десятичных знаков',
  verify_ownership: 'Проверить владение',
  enable_trading: 'Включить торговлю',
  learn_more_about_signatures_link: 'Узнать больше о подписях >',
  learn_more_about_signatures: 'Узнать больше о подписях',
  sign: 'Подписать',
  sign_step1: 'Завершить в вашем кошельке',
  sign_step2: 'Завершить 2-ю подпись',
  not_now: 'Не сейчас',
  view_on_block_explorer: 'Просмотреть в Blockchain Explorer',
  view_in_history: 'Просмотреть в истории',
  continue_to_place_order: 'Продолжить для размещения ордера',
  Save: 'Сохранить',
  sign_to_view: 'Подписать для просмотра',
  available_degate_balance: 'Доступный баланс DeGate',
  Back: 'Назад',
  token_has_not_listed: 'Этот токен не был добавлен в DeGate.',
  list_now: 'Добавить сейчас',
  spread_15: 'Спред > 15%',
  connected: 'Подключено',
  self_list_token: 'Мгновенное добавление',
  claim_REBASE: 'Запросить REBASE',
  time: 'Время',
  time_updated: 'Время обновлено',
  show_in_X_m: 'Показать через ~Xm',
  max_gas: 'Макс комиссия за газ',
  total_required: 'Всего необходимо',
  Required: 'Необходимо',
  available_balance: 'Доступный баланс',
  please_add_funds: 'Пожалуйста, добавьте средства на ваш баланс в DeGate.',
  Side: 'Сторона',
  pending: 'Ожидание',
  active: 'Активный',
  ended: 'Завершено',
  name: 'Имя',
  yield: 'Доход',
  time_created: 'Время создания',
  time_ended: 'Время окончания',
  frequency: 'Частота',
  chain_cancel: 'Отменить в сети',
  status: 'Статус',
  status_chainCancelProgressing: 'Отмена в сети',
  status_chainCancelCompleted: 'Отменено в сети',
  filled_total: 'Выполнено/Всего',
  start_time: 'Время начала',
  end_time: 'Время окончания',
  Summary: 'Сводка',
  Orders: 'Заказы',
  Tutorial: 'Учебник',
  Earn: 'Заработок',
  top_winner_24h: 'Рейтинг за 24 часа',
  ID: 'Идентификатор',
  Select: 'Выбрать',
  Create: 'Создать',
  Review: 'Обзор',
  Airdrop: 'Airdrop',
  Countdown: 'Обратный отсчёт',
  Day: 'День',
  Hour: 'Час',
  Minute: 'Минута',
  Second: 'Секунда',
  Days: 'Дни',
  Hours: 'Часы',
  Minutes: 'Минуты',
  Seconds: 'Секунды',
  Claim: 'Получить',
  Expired: 'Истёкший срок',
  Claimed: 'Получено',
  Welcome: 'Добро пожаловать',
  gas_tips_for_amount_exceed_6_digits:
    'Дополнительные сборы применяются, так как сумма превышает номинальный лимит в шесть цифр.',
  input_auto_corrected_minStep_tips:
    'Автоматически исправлено ваше значение для соответствия минимальной точности',
  order_max_limit: 'Превышен максимальный лимит',
  order_min_limit: 'Минимальный лимит не достигнут',
  order_faild_min_limit:
    'Размещение заказа не удалось: минимальный лимит не достигнут.',
  order_faild_max_limit:
    'Размещение заказа не удалось: превышен максимальный лимит.',
  disconnect_m: 'Отключить',
  'account.account_manage': 'Безопасность',
  'account.account_manage_more':
    'О режиме авторизации и ключе активации активов >',
  'account.what_is_asset_key': 'О режиме авторизации и ключе активации активов',
  'account.total_value': 'Общая стоимость',
  'account.hide_small_balances': 'Скрыть малые балансы',
  'account.add_to_metamask': 'Добавить токен в кошелек',
  'account.assets_balance_total': 'Общая сумма',
  'account.assets_balance_available': 'Доступно',
  'account.assets_market': 'Стоимость',
  'account.transfer_to_degate_balance': 'Добавить на баланс DeGate',
  'account.search_tokens': 'Поиск токена',
  'account.deposit_title':
    'Активы будут добавлены на ваш децентрализованный аккаунт DeGate. Вы полностью контролируете эти активы.',
  'account.deposit_tips': 'Вы сохраняете полный контроль над этими средствами.',
  'account.deposit_confirm_btn': 'Добавить',
  'account.deposit_approved_btn': 'Одобрено',
  'account.deposit_1_ETH': 'Добавить 1 ETH на ваш баланс DeGate',
  'account.deposit_status_pending': 'Ожидание',
  'account.deposit_status_pay_pending': 'Платёж должен быть выполнен',
  'account.deposit_status_pay_waiting': 'Платёж передан',
  'account.deposit_status_pay_confirming': 'Подтверждение платежа',
  'account.deposit_tips_block': 'Транзакция ожидает включения в блок',
  'account.deposit_status_pay_btn': 'Оплатить',
  'account.pay_deposit_warning':
    'Добавление средств может сопровождаться дополнительной комиссией за газ',
  'account.pay_deposit_warning_tips':
    'Пользователи могут быть обязаны покрыть расходы на добавление средств, так как субсидии DeGate полностью использованы.',
  'account.deposit_pending_tips':
    'Ускорить транзакцию в вашем кошельке, если она ожидает более 5 минут.',
  'account.deposit_pending_tips_ledger':
    'Ускорить транзакцию, если она ожидает более 5 минут.',
  'account.deposit_contract_tips_over_AMOUNT':
    'Добавление средств свыше AMOUNT USD требует расширенного метода.',
  'account.deposit_contract_tips_only_all':
    'Поддерживается только расширенный метод добавления средств',
  'account.suggest_100': '≥$100 рекомендовано',
  'account.suggest_100_tips':
    'Для размещения лимитного заказа рекомендуется сумма более $100.',
  'account.deposit_failed': 'Ошибка',
  'account.deposit_failed_tips':
    'Транзакция для добавления средств в сети не удалась.',
  'account.payment_due': 'Платёж должен быть выполнен',
  'account.payment_due_tips':
    'Необходим дополнительный платёж для зачисления средств на ваш баланс DeGate.',
  'account.register_token_code_placeholder': 'Введите адрес контракта',
  'account.register_token_code': 'Адрес контракта',
  'account.register_token_symbol': 'Символ',
  'account.register_token_check': 'Проверить процесс листинга',
  'account.register_token_code_err_added':
    'Этот токен находится в процессе листинга',
  'account.register_token_next_step': 'Далее',
  'account.register_token_tips1':
    'Разрешение не требуется для листинга токена в сети. Вы можете сразу перейти к листингу вашего токена.',
  'account.register_token_btn': 'Листинг токена',
  'account.list_token': 'Листинг токена',
  'account.withdraw_warning_XXX':
    'Из-за повышенного спроса отправка средств сейчас занимает ~ XXX.',
  'account.withdraw_status_pending': 'Обработка',
  'account.tansferred_1_ETH': '1 ETH Переведено',
  'account.transfer_status_sent': 'Отправлено',
  'account.transfer_status_received': 'Получено',
  'account.th_me': 'Я',
  'account.th_tx_hash': 'Хэш транзакции',
  'account.th_time': 'Время',
  'account.locked_order': 'Лимитный заказ',
  Sending: 'Отправка',
  'account.locked_claimable': 'Можно получить',
  'account.locked_grid': 'Сеточная стратегия',
  'account.personal_sign_reason': 'Возможные причины',
  'account.personal_sign_reason1': 'MetaMask подключен к аппаратному кошельку',
  'account.personal_sign_reason2': 'Версия MetaMask устарела',
  'account.personal_sign_reason3': 'Другие причины',
  'account.personal_sign_btn': 'Подписать снова',
  'account.deposit_arrive_in_30s': 'Прибытие через ~30 секунд',
  'account.deposit_arrive_in_30s_s': 'Прибытие через ~30 секунд',
  'account.account_completed_time_XXX': 'Завершение через ~XXX',
  'account.search_result_no_token': 'Токен не найден',
  'account.search_result_invalid_code': 'Неверный адрес контракта',
  'account.search_result_not_listed':
    'Токен в настоящее время не включен в список DeGate',
  'account.search_result_tips_register':
    'Вы можете ввести адрес контракта, чтобы завершить листинг токена',
  'account.search_result_not_find': 'Всё ещё не можете найти?',
  'account.search_pair_tips3': 'Нет торговой пары для актива',
  'account.search_pair_tips3_add': 'Пожалуйста, добавьте пару',
  'account.register_token': 'Листинг токенов без разрешения',
  'account.search_again': 'Искать снова',
  'account.deposit_type': 'Метод',
  'account.deposit_type_standard': 'Стандартный',
  'account.switch_account_tips': 'Переключено на',
  'account.switch_account_tips_register':
    'Пожалуйста, сначала инициализируйте.',
  'account.initialize_success': 'Инициализация успешна',
  'account.approve': 'Подтвердить',
  'account.reset_USDT': 'Сбросить подтверждение USDT',
  'account.reset_USDT_tips':
    'USDT требует сброса одобрения, когда лимиты расходов слишком низки.',
  'account.next_step': 'Далее',
  'account.profit_total': 'Общий доход',
  'account.profit_history': 'История прибыли',
  'account.tab_mining_rewards': 'Награды за майнинг',
  'account.yield_total': 'Общий доход',
  'account.yield_24h': 'Доход за 24 часа',
  'account.claimable': 'Доступно для получения',
  'account.yield_history': 'История доходов',
  'account.total_grid_profit': 'Общий доход по сетке',
  'account.grid_strategies': 'Сеточные стратегии',
  'account.total_rewards': 'Общие награды',
  'account.rewards_24h': 'Награды за 24 часа',
  'account.rewards': 'Награды',
  'menu.register_err':
    'Ваш адрес не имеет ни одной записи о транзакциях в блокчейне. Пожалуйста, выполните транзакцию в сети и попробуйте снова. Например, переведите токен на свой кошелек.',
  'menu.reset_post_success_withOrders':
    'Инициализирован сброс ключа активов. Все ваши открытые заказы и сеточные стратегии были отменены.',
  'menu.reset_post_success': 'Инициализирован сброс ключа активов.',
  'menu.reset_processing_title': 'Сброс ключа активов в процессе',
  'menu.reset_processing_desc': 'Пожалуйста, дождитесь завершения',
  'trade.choose_token': 'Выберите токен',
  'trade.token_info': 'Информация о токене',
  'trade.token_address': 'Адрес токена',
  'trade.price_range_24h': 'Диапазон цен за 24 часа',
  'trade.vol_24h': 'Объём за 24 часа',
  'trade.item_price_TOKEN': 'Цена (TOKEN)',
  'trade.item_amount_TOKEN': 'Количество (TOKEN)',
  'trade.order_book_title': 'Книга заказов',
  'trade.order_book_total': 'Общая сумма',
  'trade.trade_history_title': 'Последние сделки',
  'trade.trade_history_time': 'Время',
  'trade.market_placeholder_price': 'Рыночная цена',
  'trade.what_is_stop_limit': 'Что такое Стоп Лимит?',
  'trade.what_is_stop_limit_link': 'Что такое Стоп Лимит?',
  'trade.placeholder_total': 'Общая сумма',
  'trade.more_settings': 'Настройки',
  'trade.expire_in_tips':
    'Ордер будет автоматически отменён после истечения срока.',
  'trade.period_day_s': 'д',
  'trade.period_hour_s': 'ч',
  'trade.period_minute_s': 'мин',
  'trade.period_err_input_tips': 'Пожалуйста, введите допустимое число',
  'trade.post_only_label': 'Только для Мейкера',
  'trade.post_only_tips':
    'Режим ""Только для Мейкера"" гарантирует, что только ордеры Мейкера будут добавлены в книгу ордеров. Если любая часть ордера может быть выполнена как ордер тейкера, то весь ордер будет возвращён. Заказы в режиме ""Только для Мейкера"" не облагаются комиссией за газ или торговлей.',
  'trade.post_only_fail_title': 'Невозможно создать заказ',
  'trade.post_only_fail_desc':
    'Пожалуйста, настройте цену или отключите режим ""Только для Мейкера"".',
  'trade.max_gas_fee_tips':
    'Максимальная комиссия за газ покрывает расходы на выполнение сделок в сети, оплачивается Тейкерами и бесплатна для Мейкеров. Избыточные комиссии возвращаются.',
  'trade.auto': 'Авто',
  'trade.custom': 'Настраиваемый',
  'trade.enough_for_XX_trades': 'Достаточно для ХХ сделок',
  'trade.gas_fee_per_trade': 'Комиссия за газ за сделку',
  'trade.gas_fee_per_trade_tips':
    'Тейкеры несут комиссию за газ за каждую сделку для содействия выполнению в сети, с расходами, которые колеблются в зависимости от условий сети Ethereum.',
  'trade.max_number_of_trades': 'Максимальное количество сделок',
  'trade.btn_buy_ETH': 'Купить ETH',
  'trade.btn_sell_ETH': 'Продать ETH',
  'trade.max_buy_fee_deducted_NUM': 'Взыскана комиссия за газ. Максимум NUM.',
  'trade.notification_limit_order_title': 'Лимитный ордер размещен',
  'trade.notification_stop_limit_order_title': 'Ордер со Стоп Лимитом размещён',
  'trade.err_price': 'Пожалуйста, введите цену',
  'trade.err_amount_total': 'Пожалуйста, введите количество или общую сумму',
  'trade.err_amount': 'Пожалуйста, введите количество',
  'trade.err_insufficientFee_title': 'Недостаточная комиссия за газ',
  'trade.err_insufficientFee_desc':
    'Пожалуйста, проверьте настройки Максимальной комиссии за газ и ваш баланс DeGate.',
  'trade.cancel_order_success': 'Ордер отменён',
  'trade.pair_favorite': 'Избранное',
  'trade.pair_search': 'Поиск токена, адрес контракта',
  'trade.pair_last_price': 'Цена',
  'trade.pair_change': 'Изменение',
  'trade.url_parse_err_title': 'Эта пара не существует.',
  'trade.risk_tips': 'Предупреждение о рисках',
  'trade.base_is_not_default_token_tips':
    'Прежде чем торговать, проверьте адрес контракта токена через официальные источники, чтобы избежать мошенничества.',
  'trade.chain_cancel': 'Отменить ордер в сети',
  'trade.chain_cancel_no_need_tips': 'Этот ордер не требует отмены в сети.',
  'trade.chain_cancel_success': 'Запрос отправлен',
  'trade.depth_empty': 'Ордеров пока нет',
  'trade.depth_empty_asks': 'Нет ордеров на продажу',
  'trade.depth_empty_bids': 'Нет ордеров на покупку',
  'trade.depth_empty_tips':
    'Рыночный ордер не удалось выполнить из-за недостаточного количества открытых заказов в книге заказов',
  'trade.history_empty': 'Сделок пока нет',
  'trade.err_price_stable':
    'Цена стала недействительной. Пожалуйста, попробуйте снова.',
  'trade.price_warning':
    'Цена, которую вы ввели, отклонилась от рыночной, пожалуйста, подтвердите перед размещением ордера',
  'trade.order_value_tips':
    'Минимальное значение ордера составляет <b>QUOTE_A</b> или <b>BASE_A</b>, что эквивалентно MINUSD USD. Используйте рыночный ордер, чтобы обойти это ограничение.',
  'trade.order_value_tips_quote':
    'Минимальное значение ордера составляет <b>QUOTE_A</b>, что эквивалентно MINUSD USD. Используйте рыночный ордер, чтобы обойти это ограничение.',
  'trade.order_value_tips_stable_quote':
    'Минимальное значение ордера составляет <b>QUOTE_A</b>. Используйте рыночный ордер, чтобы обойти это ограничение.',
  'trade.system_limit': 'Превышен системный лимит',
  'trade.stop_limit_untriggered_tips':
    'Ордер не был подан в книгу ордеров, так как стоп-цена не была достигнута.',
  'trade.stop_limit_triggered_tips_TIME':
    'Ордер был подан в книгу ордеров в TIME',
  'trade.flow_of_funds': 'поток средств',
  'trade.flow_of_funds_tip2':
    'Ваш ордер был размещён. Средства с ордера поступят на ваш баланс DeGate, а не на баланс кошелька.',
  'orders.show_current_pair_orders': 'Скрыть другие пары',
  'orders.orderHistory': 'История ордеров',
  'orders.th_time': 'Время',
  'orders.th_average_price': 'Средняя цена',
  'orders.th_stop_price': 'Стоп цена',
  'orders.th_limit_price': 'Лимит цена',
  'orders.th_filled_price': 'Цена',
  'orders.th_filled_amount': 'Заполнено',
  'orders.th_filled_total': 'Всего',
  'orders.th_trade_reconciliation': 'Реконcиляция',
  'orders.th_trade_reconciliation_tips':
    'Обратите внимание, что из-за использования различных моделей расчёта для сопоставления на DeGate и расчётов на блокчейне могут возникнуть незначительные различия в результатах двух расчётов. Если и когда это произойдёт, система будет использовать значение на блокчейне как стандарт и компенсирует любые недостатки на балансе DeGate.',
  'orders.hide_cancelled_expired_orders': 'Скрыть отменённые/истёкшие',
  'orders.status_open': 'Открыт',
  'orders.status_pending': 'Ожидает',
  'orders.status_completed': 'Заполнен',
  'orders.status_completed_part': 'Частично заполнен',
  'orders.status_expired': 'Истёк',
  'orders.detail_price': 'Средняя/Цена',
  'orders.average_price': 'Средняя цена',
  'orders.detail_type': 'Тип ордера',
  'orders.detail_trade_fee': 'Торговая комиссия:',
  'orders.gas_preAuth': 'Максимальная комиссия за газ:',
  'orders.fee_reconciliation': 'Реконcиляция:',
  'orders.gas_paid': 'Оплаченная комиссия за газ:',
  'orders.gas': 'Комиссия за газ:',
  'orders.trades_N': 'Сделки(N)',
  'orders.detail_filled_total': 'Всего',
  'orders.detail_filled_detail': 'Детали сделки',
  'orders.detail_filled_time': 'Время',
  'orders.order_maker_free': 'Комиссия мейкера бесплатна',
  'orders.openOrders_empty': 'Нет открытых ордеров',
  'orders.export_orders_1_year':
    'Экспортировать данные ордеров за последний год.',
  'orders.export_trades_1_year':
    'Экспортировать данные сделок за последний год.',
  'orders.export_data': 'Экспортировать данные',
  'orders.export': 'Экспорт',
  'orders.export_processing': 'Обработка. Пожалуйста, подождите.',
  'orders.export_tips_100_percent':
    'Файл будет загружен, когда прогресс достигнет 100%',
  'orders.sign_to_view_balance': 'Подпишите, чтобы просмотреть баланс',
  'orders.sign_to_view_history': 'Подпишите, чтобы просмотреть историю',
  'orders.sign_to_view_security_options':
    'Подпишите, чтобы просмотреть параметры безопасности',
  'gridTrade.automatic_strategy': 'Авто',
  'gridTrade.manual_strategy': 'Ручной',
  'gridTrade.placeholder_amount': 'Введите сумму',
  'gridTrade.low_price': 'Нижний предел',
  'gridTrade.high_price': 'Верхний предел',
  'gridTrade.initial_investment': 'Инвестиции',
  'gridTrade.grid_levels_tips':
    'Используется для определения количества открытых ордеров в пределах диапазона цен.',
  'gridTrade.profit_per_grid': 'Прибыль на сетку',
  'gridTrade.profit_per_grid_tips':
    'Важный параметр для прибыльности сеточной Grid стратегии. Прибыль на сетку = (Высшая цена - Низшая цена) / Низшая цена. Высшие и низшие цены относятся к ценам двух смежных сеточных линий в пределах сеточной стратегии.',
  'gridTrade.min_grid_volume_XXX_ETH': 'Сумма на сетку: Минимум XXX ETH',
  'gridTrade.min_grid_volume_err':
    'Пожалуйста, увеличьте инвестиции или уменьшите количество сеток',
  'gridTrade.grid_no_depth_tips_BASE_QUOTE':
    'Невозможно создать сеточную стратегию для этой пары из-за недостаточного количества ордеров в книге ордеров.',
  'gridTrade.grid_to_spot_trade': 'Перейти на Спот',
  'gridTrade.grid_level_over_err': 'Пожалуйста, уменьшите количество сеток',
  'gridTrade.grid_prices_err': 'Пожалуйста, расширьте диапазон цен',
  'gridTrade.grid_create_err':
    'Пожалуйста, настройте параметры и попробуйте снова.',
  'gridTrade.tips_grid_profit':
    'Прибыль зачисляется непосредственно на ваш баланс DeGate и доступна немедленно.',
  'gridTrade.tips_grid_balance_0_BASE':
    'Рост рыночной цены привел к тому, что все ордера в пределах этой сеточной стратегии стали ордерами на покупку. Таким образом, текущий баланс BASE теперь равен 0.',
  'gridTrade.tips_grid_balance_0_BASE_2':
    'Рост рыночной цены привел к тому, что все ордера в пределах этой сеточной стратегии стали ордерами на покупку. Кроме того, некоторые из этих ордеров частично выполнены. Таким образом, текущий баланс BASE > 0.',
  'gridTrade.tips_grid_balance_0_QUOTE':
    'Падение рыночной цены привело к тому, что все ордера в пределах этой сеточной стратегии стали ордерами на продажу. Таким образом, текущий баланс QUOTE теперь равен 0.',
  'gridTrade.tips_grid_balance_0_QUOTE_2':
    'Падение рыночной цены привело к тому, что все ордера в пределах этой сеточной стратегии стали ордерами на продажу. Кроме того, некоторые из этих ордеров частично выполнены. Таким образом, текущий баланс QUOTE > 0.',
  'gridTrade.grid_param_err':
    'Пожалуйста, введите параметры сеточной Grid стратегии',
  'gridTrade.tv_buy': 'Купить',
  'gridTrade.tv_sell': 'Продать',
  'gridTrade.tv_waiting': 'Ожидание',
  'gridTrade.chain_cancel_no_need_tips':
    'Эта сеточная Grid стратегия не требует отмены в сети.',
  'gridTrade.grid_over_max_number_err':
    'Достигнуто максимальное количество запущенных сеточных стратегий, невозможно создать новую сетку.',
  'gridTrade.preview_orders_in_graph': 'Показать ордера',
  'gridTrade.greate_news': 'Отличная новость:',
  'gridTrade.min_amount_required_XXX': 'Минимум XXX требуется',
  'gridTrade.highest_grid_apy': 'Самый высокий годовой доход по сетке (APY)',
  'gridTrade.for_the_last_7_days': 'За последние 7 дней',
  'gridTrade.min_investment': 'Мин. Инвестиции',
  'gridTrade.grid_need_XXX': '$XXX на сетку',
  'gridTrade.mining_need_XXX': '$XXX на майнинг',
  'gridTrade.recommended_params_cannot_be_applied':
    'Рекомендованные параметры не могут быть применены из-за недостаточных инвестиций. Вы можете настроить их в ручном режиме.',
  'gridTrade.copy_params_to_manual': 'Скопировать параметры в ручной режим',
  'gridOrders.grid_recents': 'Мои последние сделки',
  'gridOrders.th_created_time': 'Время создания',
  'gridOrders.grid_profit': 'Прибыль по сетке',
  'gridOrders.grid_cancel': 'Завершение',
  open_orders: 'Открытые ордера',
  'gridOrders.tab_history_orders': 'Выполненные ордера',
  'gridOrders.tab_trade_history': 'История сделок',
  'gridOrders.detail_current_balance': 'Текущий баланс',
  'gridOrders.detail_ending_balance': 'Конечный баланс',
  'gridOrders.detail_ending_balance_tips':
    'Баланс активов при закрытии сеточной стратегии.',
  'gridOrders.detail_in_order_funds': 'Средства в ордере:',
  'gridOrders.detail_on_hold_funds':
    'Средства в ожидании (от частично выполненных ордеров):',
  'gridOrders.detail_transactions': 'Количество выполненных ордеров',
  'gridOrders.detail_investment': 'Первоначальные инвестиции',
  'gridOrders.detail_running_time': 'Продолжительность',
  'gridOrders.detail_prices': 'Диапазон цен',
  number_of_grids: 'Количество сеток',
  'gridOrders.detail_expire_time': 'Закончится через',
  'gridOrders.detail_expire_time_tooltip':
    'Ордера в пределах этой сеточной Grid стратегии будут отменены по её окончанию.',
  'gridOrders.detail_valid_period': 'Настройка срока действия',
  'gridOrders.open_orders_sell': 'ПРОДАТЬ',
  'gridOrders.open_orders_buy': 'КУПИТЬ',
  'gridOrders.open_orders_index': '#',
  'gridOrders.open_orders_total': 'Всего',
  'gridOrders.history_orders_filled': 'Выполнено',
  'gridOrders.history_orders_price': 'Цена',
  'gridOrders.history_orders_time': 'Время',
  'gridOrders.history_orders_filled_price': 'Средняя цена',
  'gridOrders.history_orders_filled_amount': 'Выполнено',
  'gridOrders.history_orders_filled_total': 'Общая сумма',
  'gridOrders.history_orders_profit_tips':
    'Прибыль происходит от разницы в цене после цикла покупки по низкой цене и продажи по высокой. Например, после того, как ордер на покупку 1 ETH по цене 4000 USDC будет выполнен, если шаг сетки составляет 50 USDC, система автоматически размещает новый ордер на продажу 1 ETH по цене 4050 USDC Прибыль в размере 50 USDC будет получена, когда этот ордер также будет выполнен',
  'gridOrders.history_orders_buy_flip_order_tips_PRICE':
    'Прибыль будет отображена после выполнения ордера на покупку по цене PRICE',
  'gridOrders.history_orders_sell_flip_order_tips_PRICE':
    'Прибыль будет отображена после выполнения ордера на продажу по цене PRICE',
  'gridOrders.m_history_orders_flip_order_tips_PRICE':
    'Ордер по цене PRICE появится здесь после выполнения',
  'gridOrders.grid_cancel_title': 'Завершить сеточную Grid стратегию',
  'gridOrders.grid_cancel_content':
    'Все ордера в этой сеточной Grid стратегии будут немедленно отменены',
  'gridOrders.grid_cancel_content2':
    'В данный момент вы занимаетесь майнингом по этой сеточной Grid стратегии. Если вы завершите эту сеточную стратегию, вы потеряете все награды за майнинг, и все связанные сеточные ордера будут немедленно отменены',
  'gridOrders.copy_grid_title':
    'Будут скопированы следующие параметры сеточной стратегии',
  'gridOrders.copy_grid_btn': 'Копировать в панель',
  'gridOrders.copy_grid_success': 'Сеточная Grid стратегия скопирована',
  'gridOrders.grid_init_funds_XXX': 'Стоимость первоначальных инвестиций $XXX',
  'gridOrders.grid_init_funds_tips':
    'APY рассчитывается на основе стоимости первоначального распределения на момент создания сеточной стратегии',
  'gridOrders.tab_m_trade': 'Торговля',
  grid_apy: 'Сеточный APY',
  grid_apy_tips:
    'Годовая ставка прибыли только от сеточной торговли Плавающая прибыль не включена',
  'gridOrders.tab_mining_profit': 'Годовая ставка прибыли от майнинга APY',
  'gridOrders.tab_mining_profit_tips':
    'Годовая ставка прибыли от майнинга рассчитывается на основе первоначальной стоимости и продолжительности сеточной стратегии',
  'gridOrders.mining_rewards': 'Награды',
  'gridOrders.open_orders_empty_tips':
    'Пожалуйста, подождите, пока данные загружаются',
  'gridOrders.market_value': 'Рыночная стоимость',
  'gridOrders.market_value_details': 'Детали',
  'gridOrders.fund_details': 'Детали средств',
  'gridOrders.m_in_order_funds': 'Средства в ордере',
  'gridOrders.m_in_order_funds_tips':
    'Общая сумма средств во всех открытых ордерах в рамках этой сеточной Grid стратегии',
  'gridOrders.m_on_hold_funds': 'Средства на удержании',
  'gridOrders.m_on_hold_funds_tips': 'Результат частично выполненных ордеров',
  'gridOrders.initial_value': 'Первоначальная стоимость',
  'mining.my_title': 'Мой майнинговый пул',
  'mining.index_desc':
    'Создайте сеточную Grid стратегию. Увеличьте свою прибыль от сетки с помощью наград за майнинг ликвидности',
  'mining.apply': 'Новая заявка на пул',
  'mining.claimable_rewards_box': 'Доступные награды',
  'mining.rewards_more': 'и другое',
  'mining.tab_pools': 'Пулы для майнинга',
  'mining.tab_my': 'Моя статистика майнинга',
  'mining.pools_tab_live': 'В реальном времени',
  'mining.pools_tab_upcoming': 'Ожидается',
  'mining.pools_funds': 'Общая заблокированная стоимость TVL',
  'mining.pools_funds_tips':
    'Общая стоимость сеточных Grid ордеров, которые соответствуют минимальной стоимости ордера в $120',
  'mining.pools_mining_funds': 'Заблокированные средства для майнинга TVL',
  'mining.mining_apr': 'Годовая ставка прибыли APY',
  'mining.mining_apr_tips':
    'Годовая норма доходности, оцененная на основе наград за майнинг и общей заблокированной стоимости (TVL)',
  'mining.view_rule_link': 'Правила майнинга',
  'mining.pools_info_to_confirm': 'Будет определено',
  'mining.pools_no_wait': 'Нет доступных пулов для майнинга',
  'mining.my_mining_funds': 'Мои средства для майнинга',
  'mining.my_mining_rewards': 'Мои награды за майнинг',
  'mining.my_th_profit_token_price': 'Последняя цена',
  'mining.my_th_total_rewards': 'Всего наград',
  'mining.my_th_24h_rewards': 'Награды за 24 часа',
  'mining.my_grids': 'Мой майнинг',
  'mining.only_show_mining_grids': 'Только активные',
  'mining.my_th_mining_status': 'Статус майнинга',
  'mining.status_framing': 'Активный',
  'mining.status_over_price': 'Вышел за пределы ценового диапазона',
  'mining.status_mining_over': 'Майнинг завершен',
  'mining.status_grid_closed': 'Стратегия завершена',
  'mining.status_grid_expired': 'Стратегия истекла',
  'mining.empty_no_faring_grids':
    'В данный момент нет сеточной Grid стратегии, доступной для майнинга',
  'mining.go_mining_pool': 'Перейти к пулу майнинга',
  'mining.go_mining': 'Начать майнинг',
  'mining.go_to_grid': 'К сеточной Grid стратегии',
  'mining.mining_help': 'Руководство по майнингу',
  'mining.mining_available': 'Соответствует требованиям',
  'mining.mining_available_tips': 'Критерии стоимости ордера выполнены',
  'mining.mining_unavailable': 'Не соответствует требованиям',
  'mining.mining_partially_available': 'Частично соответствует требованиям',
  'mining.mining_unavailable_tips': 'Критерии стоимости Ордера не выполнены',
  'mining.mining_preview': 'Предварительный просмотр майнинга',
  'mining.mining_total_profit': 'Награды за майнинг',
  'mining.mining_24h_profit': 'Награды за 24 часа',
  'mining.profit_unable_display': 'Невозможно отобразить',
  'mining.mining_funds': 'Средства для майнинга',
  'mining.mining_funds_tips':
    'Общая стоимость Ордера со всех Grid стратегий сетки, которые соответствуют критериям стоимости Ордера для данной торговой пары',
  'mining.tab_mining_profit_details': 'Детали вознаграждения',
  'mining.tab_mining_orders': 'Ордера для майнинга',
  'mining.th_rewards': 'Вознаграждение',
  'mining.th_rewards_origin': 'Источник вознаграждения',
  'mining.th_rewards_origin_tips':
    'Вознаграждение за майнинг начисляется, когда цена сеточного ордера находится в пределах диапазона вознаграждения книги ордеров (самая высокая цена покупки * 0.99 ~ самая низкая цена продажи * 1.01)',
  'mining.th_rewards_origin_tips_stable':
    'Вознаграждение за майнинг начисляется, когда цена сеточного ордера находится в пределах диапазона вознаграждения книги ордеров (самая высокая цена покупки ~ самая низкая цена продажи)',
  'mining.th_time': 'Время',
  'mining.plan_title': 'Детали пула ETH/USDC',
  'mining.phase_cur': 'Текущая фаза',
  'mining.phase_range_N_XX': 'Фаза N (XX)',
  'mining.phase_index_N': 'Фаза N',
  'mining.phase_reward': 'Ежедневные вознаграждения',
  'mining.phase_to_release': 'Будет объявлено',
  'mining.my_rewards': 'Мои вознаграждения',
  'mining.claimable_rewards': 'Доступно',
  'mining.locked_rewards': 'Заблокировано',
  'mining.locker_rewards_tips':
    'Вознаграждения за майнинг могут быть получены только после того, как Grid стратегия сетки активна в течение 12 часов',
  'mining.claimed_success': 'Успешно получено',
  'mining.claimed_tips':
    'Будет отправлено вам в ближайшее время через внутренний перевод',
  'mining.claimed_view_btn': 'Проверить',
  'mining.mining_plan': 'График майнинга',
  'mining.phase_unpublished': 'Будет объявлено',
  'mining.all_pools': 'Все пулы',
  'notification.limit_desc_SELL_BASE_QUOTE_AMOUNT_PRICE':
    'Продать КОЛИЧЕСТВО БАЗОВОЙ @ ЦЕНУ КОТИРУЕМОЙ',
  'notification.limit_desc_BUY_BASE_QUOTE_AMOUNT_PRICE':
    'Купить КОЛИЧЕСТВО БАЗОВОЙ @ ЦЕНУ КОТИРУЕМОЙ',
  'notification.stop_limit_desc_SELL_BASE_AMOUNT': 'Продать КОЛИЧЕСТВО БАЗОВОЙ',
  'notification.stop_limit_desc_BUY_BASE_AMOUNT': 'Купить КОЛИЧЕСТВО БАЗОВОЙ',
  'notification.cancel_grid_desc_PAIR_PRICES': 'ПАРА: ЦЕНЫ',
  'notification.cancel_market_desc_SELL_BASE_QUOTE_AMOUNT':
    'Продать КОЛИЧЕСТВО БАЗОВОЙ за КОТИРУЕМУЮ',
  'notification.cancel_market_desc_SELL_BASE_QUOTE_TOTAL':
    'Продать БАЗОВУЮ за ОБЩУЮ КОТИРУЕМУЮ',
  'notification.cancel_market_desc_BUY_BASE_QUOTE_AMOUNT':
    'Купить КОЛИЧЕСТВО БАЗОВОЙ за КОТИРУЕМУЮ',
  'notification.cancel_market_desc_BUY_BASE_QUOTE_TOTAL':
    'Купить БАЗОВУЮ за ОБЩУЮ КОТИРУЕМУЮ',
  'notification.cancel_limit': 'Лимитный ордер отменен',
  'notification.cancel_stop_limit': 'Стоп-лимитный ордер отменен',
  'notification.cancel_market': 'Рыночный ордер отменен',
  'notification.cancel_grid': 'Стратегия сетки завершена',
  'notification.cancel_limit_expired': 'Лимитный ордер истек',
  'notification.cancel_stop_limit_expired': 'Стоп-Лимитный ордер истек',
  'notification.cancel_grid_expired': 'Стратегия сетки истекла',
  'notification.cancel_limit_order_for_gas_desc':
    'Ваш ордер закончился из-за недостаточной платы за газ. Он был частично выполнен, а остаток отменен',
  'notification.cancel_limit_order_for_gas_filled_amount': 'Заполнено',
  'notification.cancel_limit_order_for_gas_amount': 'Количество',
  'notification.view_history_orders': 'Просмотреть историю Ордеров',
  'notification.cancel_market_for_depth_title':
    'Ордер частично выполнен и отменен',
  'notification.price_slippage_protection': 'Защита от проскальзывания цены',
  'notification.price_slippage_protection_desc':
    'Рыночные ордера DeGate автоматически включают защиту от проскальзывания цены на 10% для ограничения убытков во время высокой волатильности и низкой ликвидности. Используйте лимитные ордера, чтобы обойти эту защиту',
  'notification.cancel_market_for_depth_warning':
    'Рыночный ордер DeGate внедряет механизм защиты цены, позволяя пользователям уменьшить убытки в условиях высокой волатильности и низкой ликвидности. Если вы не хотите активировать механизм защиты цены, используйте режим лимитного ордера',
  'notification.dca_plan_ended': 'План DCA завершен',
  'notification.cancel_dca_desc_PAIR': 'ПАРА',
  'notification.trade_limit_partially': 'Лимитный ордер частично выполнен',
  'notification.trade_limit_filled': 'Лимитный ордер выполнен',
  'notification.trade_market_partially': 'Рыночный ордер частично выполнен',
  'notification.trade_market_filled': 'Рыночный ордер выполнен',
  'notification.trade_stop_limit_partially':
    'Стоп-лимитный ордер частично выполнен',
  'notification.trade_stop_limit_filled': 'Стоп-лимитный ордер выполнен',
  'notification.mobile_trade_filled_AMOUNT_TOKEN':
    'Ордер выполнен. Получено КОЛИЧЕСТВО ТОКЕНА',
  'notification.mobile_trade_partially_AMOUNT_TOKEN':
    'Ордер частично выполнен. Получено КОЛИЧЕСТВО ТОКЕНА',
  'info.overview': 'Обзор',
  'info.accounts': 'Общее количество пользователей',
  'info.pairs': 'Торговые пары',
  'info.turnover': 'Объем за все время',
  'info.turnover_24': 'Объем за 24 часа',
  'info.dg_supply': 'Циркулирующий запас DG',
  'info.top_movers_no_increased':
    'Ни один токен не увеличился в цене за 24 часа',
  'info.top_movers_no_decreased':
    'Ни один токен не уменьшился в цене за 24 часа',
  'info.top_pairs': 'Топовые пары',
  Pair: 'Пара',
  'info.th_change': 'Изменение за 24 часа',
  'info.th_l_up_2': '+2% Глубина',
  'info.th_l_down_2': '-2% Глубина',
  'info.th_turnover_24': 'Объем за 24 часа',
  'info.tvl': 'Общая заблокированная стоимость',
  'm.home': 'Главная',
  'm.grid': 'Сетка',
  'm.browser_wallet': 'Браузерный кошелек',
  'm.choose_pair': 'Выбрать пару',
  'm.orderBook_default': 'По умолчанию',
  'm.orderBook_bids': 'Ордера на покупку',
  'm.orderBook_asks': 'Ордера на продажу',
  'm.decimals': 'Десятичные',
  'm.lowest_price_24h': 'Мин. цена за 24 часа',
  'm.highest_price_24h': 'Макс. цена за 24 часа',
  'm.vol_24h': 'Объем за 24 часа',
  'm.orderbook_buy': 'Купить',
  'm.orderbook_sell': 'Продать',
  'm.go_to_trade': 'Перейти к торговле',
  'm.choose_token': 'Выбрать токен',
  'm.from_address': 'Адрес отправителя',
  'm.to_address': 'Адрес получателя',
  'm.transfer_send': 'Отправить',
  'm.transfer_receive': 'Получить',
  'm.my_grid': 'Моя Grid стратегия сетки',
  'm.grid_profit_24': 'Прибыль за 24 часа',
  'm.grid_item_trades_24': 'Торги за 24 часа',
  'm.grid_profit_total': 'Общая прибыль',
  'm.grid_over_prices': 'Вне диапазона цен',
  'm.create_grid': 'Создать сеточную Grid стратегию',
  'm.grid_history': 'История',
  'm.grid_empty': 'Нет активной стратегии сетки',
  'm.grid_tutorial': 'Руководство по Grid сетке',
  'm.grid_params_to_manual': 'Копировать параметры в ручной режим',
  'm.balance_err': 'Недостаточно средств. Доступно:',
  'm.preview_grid': 'Предварительный просмотр ордеров',
  last_price: 'Последняя цена',
  'm.grid_desc':
    'Торговля по Grid сетке — это торговая стратегия, которая автоматизирует покупку и продажу в определенном диапазоне',
  'm.view_tutorial': 'Просмотреть руководство',
  'm.grid_profit_tips_sell':
    'Будет рассчитано, когда этот ордер на продажу будет полностью выполнен',
  'm.grid_profit_tips_buy':
    'Будет рассчитано, когда этот ордер на покупку будет полностью выполнен',
  'm.hot': 'Горячее',
  'm.all': 'Просмотреть все',
  'm.vol_24': 'Объем за 24 часа',
  'm.transfer_t1': 'Внутренний',
  'm.transfer_t2': 'Перевод',
  'activity.th_date': 'Время',
  'activity.th_type': 'Тип',
  'activity.th_fee': 'Комиссия',
  'activity.th_content': 'Содержание',
  'activity.type_register_token': 'Листинг токенов',
  'activity.type_register_pair': 'Добавление пары',
  'activity.type_pay_deposit': 'Рассчет депозита',
  'activity.type_reset_account': 'Сброс ключа актива',
  on_chain_order_cancellation: 'Отмена ордера в блокчейне',
  'activity.count_N': 'Количество: N',
  'activity.order_desc_SELL_AMOUNT_BASE_PRICE_QUOTE':
    'ПРОДАТЬ КОЛИЧЕСТВО БАЗОВОЙ за ЦЕНУ КОТИРОВОК',
  'activity.order_market_desc_SELL_AMOUNT_BASE': 'ПРОДАТЬ КОЛИЧЕСТВО БАЗОВОЙ',
  'activity.reset_status_restting': 'Сброс',
  'activity.to_trade': 'Торговля',
  'dca.dca_plan': 'План DCA',
  'dca.dca_explain': 'Средневзвешенная стоимость доллара',
  'dca.daily': 'Ежедневно',
  'dca.weekly': 'Еженедельно',
  'dca.custom': 'Индивидуально',
  'dca.every': 'Каждый',
  'dca.amount_per_order': 'Сумма за ордер',
  'dca.price_limit': 'Ценовой лимит',
  'dca.maximum_price': 'Максимальная цена',
  'dca.minimum_price': 'Минимальная цена',
  'dca.number_of_orders': 'Количество ордеров',
  'dca.create_dca_plan': 'Создать план DCA',
  'dca.max_gas_fee_per_order': 'Максимальная плата за газ за ордер',
  'dca.maximum_plan_order_limit_reached':
    'Достигнут максимальный лимит ордеров по плану',
  'dca.end_time_should_be_set_after_the_current_time':
    'Время завершения должно быть установлено после текущего времени',
  'dca.please_enter_amount_per_order': 'Пожалуйста, введите сумму за ордер',
  'dca.please_enter_maximum_price': 'Пожалуйста, введите максимальную цену',
  'dca.please_enter_minimum_price': 'Пожалуйста, введите минимальную цену',
  'dca.order_placement_failed_open_order_limit_exceeded':
    'Размещение ордера не удалось: превышен лимит открытых ордеров',
  'dca.total': 'Всего',
  'dca.filled': 'Выполнено',
  'dca.received': 'Получено',
  'dca.time_to_end': 'Время до завершения',
  'dca.cancel_on_chain': 'Отменить в блокчейне',
  'dca.filled_amount': 'Заполнено/Количество',
  'dca.status_executed': 'Выполнено',
  'dca.status_scheduled': 'Запланировано',
  'dca.status_failed': 'Неудача',
  'dca.order_cancled_by_user':
    'Ордер отменен, так как пользователь завершил план DCA',
  'dca.order_cancled_by_access':
    'Ордер отменен, так как ваш доступ к DeGate ограничен',
  'dca.order_cancled_by_gas':
    'Размещение ордера не удалось из-за недостаточной платы за газ',
  'dca.order_cancled_by_order_book':
    'Размещение ордера не удалось из-за отсутствия подходящего ордера в ордербуке',
  'dca.order_cancled_by_balance':
    'Размещение ордера не удалось из-за недостаточного баланса DeGate',
  'dca.order_cancled_by_min_value':
    'Размещение ордера не удалось, так как минимальная стоимость ордера не достигнута',
  'dca.order_cancled_by_system_error':
    'Размещение ордера не удалось из-за системной ошибки',
  'dca.chain_cancel_no_need_tips':
    'Этот план DCA не требует отмены в блокчейне',
  'dca.end_dca_plan': 'Завершить план DCA',
  'dca.all_orders_in_this_dca_plan_will_be_canceled_immediately':
    'Все ордера в этом плане DCA будут немедленно отменены',
  'dca.no_active_dca_plan': 'Нет активного плана DCA',
  'dca.time_scheduled': 'Запланированное время',
  'campaign.event_period': 'Период события:',
  'campaign.grid2401_time':
    '22 января 2024, 20:00:00 - 29 января 2024, 20:00:00 (UTC+8)',
  'campaign.event_has_ended': 'Событие завершено',
  'campaign.current_apy': 'Текущая годовая процентная доходность (APY)',
  'campaign.grid_strategy_income':
    'Доход от стратегии сетки + Доля в призовом фонде',
  'campaign.tvl_participating': 'TVL в участии',
  'campaign.share_of_tvl': 'Доля TVL',
  'campaign.my_profit': 'Моя прибыль',
  'campaign.grid_strategy_profit': 'Прибыль от стратегии сетки',
  'campaign.share_of_prize_pool': 'Доля в призовом фонде',
  'campaign.grid_strategy_profit_has_been_added_to_your_available_balance':
    'Прибыль от Grid стратегии сетки добавлена к вашему доступному балансу',
  'campaign.shared_income_from_usdc_prize_pool':
    'Совместный доход из призового фонда USDC',
  'campaign.is_black_tips': 'Вы не имеете права на участие в призовом фонде',
  'campaign.calculating': 'Расчет',
  'campaign.claim_after_end': 'Приз можно получить в конце события',
  'campaign.how_to_participate': 'Как участвовать',
  'campaign.rule':
    'Создайте Grid стратегию сетки и делите призовой фонд пропорционально',
  'campaign.step1': 'Шаг 1',
  'campaign.step2': 'Шаг 2',
  'campaign.step3': 'Шаг 3',
  'campaign.grid2401_step1':
    'Подготовьте свой ETH и USDC, добавив средства или торгуя',
  'campaign.grid2401_step2_PAIR':
    'Настройте Grid стратегию сетки для ПАРЫ, как указано ниже',
  'campaign.grid2401_step2_desc1_pre': 'Диапазон цен: Будет объявлен',
  'campaign.grid2401_step2_desc2_pre': 'Количество сеток: Будет объявлено',
  'campaign.copy_strategy': 'Копировать стратегию',
  'campaign.grid2401_step3':
    'После завершения события вы можете получить свои доходы на этой странице события. Пожалуйста, получите их в течение 30 дней после завершения события',
  'campaign.what_is_grid': 'Что такое Grid стратегия сетки',
  'campaign.notes': 'Пожалуйста, обратите внимание перед присоединением',
  'campaign.notes_1_title': 'Право на участие:',
  'campaign.notes_1_desc':
    'Стратегия сетки действительна только если диапазон цен и количество сеток точно соответствуют требованиям на момент создания',
  'campaign.notes_2_title': 'Лимит:',
  'campaign.notes_3_title': 'Получение:',
  'campaign.notes_3_desc':
    'Приз можно получить в конце события и действителен для получения в течение 30 дней после окончания события',
  'campaign.faq': 'Часто задаваемые вопросы',
  'campaign.grid2401_faq_1': '1. Как рассчитываются награды?',
  'campaign.grid2401_faq_2':
    '2. Где я могу получить помощь по вопросам этого события?',
  'campaign.grid2401_faq_3':
    '3. У меня есть USDT, как я могу получить ETH и USDC?',
  'campaign.grid2401_faq_4':
    '4. Нужно ли платить комиссию за транзакции, выполненные через стратегию грида? В DeGate все ордера Maker бесплатны. Ордеры, создаваемые стратегией грида, являются ордерами Maker, поэтому настройка стратегии грида в DeGate полностью бесплатна',
  'campaign.grid2401_faq_4_res':
    'В DeGate все ордера Maker бесплатны. Ордеры, создаваемые стратегией сетки, являются ордерами Maker, поэтому настройка стратегии сетки в DeGate полностью бесплатна.',
  'campaign.grid2401_faq_5':
    '5. Будет ли моя Grid стратегия cетки продолжать приносить доход после окончания события? Да, после окончания события, если цена остается в пределах вашей стратегии сетки, стратегия будет продолжать приносить доход. После события вы также можете настроить параметры вашей стратегии грида, чтобы создать стратегию, которая больше соответствует вашим предпочтениям, и продолжать зарабатывать доход',
  'campaign.grid2401_faq_5_res':
    'Да, после окончания события, если цена остается в пределах вашей стратегии сетки, стратегия будет продолжать приносить доход. После события вы также можете настроить параметры вашей стратегии грида, чтобы создать стратегию, которая больше соответствует вашим предпочтениям, и продолжать зарабатывать доход',
  'campaign.grid2401_faq_others': 'Другие детали события',
  'campaign.grid2401_faq_others_1':
    '1. Только один кошелек на пользователя. Если будет обнаружено мошенничество с наградами, DeGate оставляет за собой право аннулировать награды участника',
  'campaign.grid2401_faq_others_2':
    '2. Во время события, сетки, которые выходят за пределы диапазона, также будут учитываться при расчете веса',
  'campaign.grid2401_faq_others_3':
    '3. DeGate оставляет за собой право завершить событие досрочно в экстренных случаях, например, из-за рыночной волатильности',
  'campaign.grid2401_faq_others_4':
    '4. Награды, не востребованные в течение 30 дней после окончания события, будут аннулированы',
  'campaign.invest_max_5000': 'Максимальная инвестиция $5000',
  'campaign.invest_mininum': 'Минимальная инвестиция',
  'airdrop.create_airdrop': 'Создать аирдроп',
  'airdrop.important_note':
    'Важно: любой может создавать аирдропы без разрешения',
  'airdrop.my_airdrop': 'Мои аирдропы',
  'airdrop.time_limited': 'Ограничено по времени',
  'airdrop.no_airdrop': 'Аирдропа еще нет',
  'airdrop.claim_airdrop': 'Получить аирдроп',
  'airdrop.recipients_number': 'Количество получателей',
  'airdrop.total_amount': 'Общая сумма',
  'airdrop.retrieve': 'Извлечь',
  'airdrop.unclaimed': 'Не востребованные',
  'airdrop.retrieve_successful': 'Извлечение успешно',
  'airdrop.claim_successful': 'Получение успешно',
  'airdrop.retrieve_unclaimed_airdrop': 'Извлечь не востребованный аирдроп',
  'airdrop.airdrop_token': 'Токен аирдропа',
  'airdrop.token_not_meet_criteria':
    'Этот токен не соответствует критериям аирдропа',
  'airdrop.airdrop_list': 'Список аирдропов',
  'airdrop.download_template': 'Скачать шаблон',
  'airdrop.click_or_drag_upload_list':
    'Нажмите или перетащите для загрузки списка',
  'airdrop.validation_passed': 'Проверено',
  'airdrop.must_earlier_than_end_time': 'Должно быть до времени окончания',
  'airdrop.cannot_more_than_2_years_from_now':
    'Не может быть более чем через 2 года',
  'airdrop.cannot_parse_file':
    'Не удалось разобрать файл. Пожалуйста, используйте шаблон.',
  'airdrop.format_requirement_not_met': 'Не выполнены требования формата',
  'airdrop.view_error_repost': 'Просмотреть отчет об ошибках',
  'airdrop.error_report': 'Отчет об ошибках',
  'airdrop.line': 'Строка',
  'airdrop.reason': 'Причина',
  'airdrop.duplicated_address': 'Дублированный адрес',
  incorrect_address_format: 'Неправильный формат адреса',
  'airdrop.incorrect_amount_format': 'Неправильный формат суммы',
  'airdrop.airdrop_plan_created': 'План аирдропа создан',
  'airdrop.max_50000': 'Макс. 50000 адресов',
  'airdrop.upload_file_rule': 'Поддерживаются только CSV.',
  'airdrop.to_check_airdrop_eligibility':
    'Завершите инициализацию, чтобы просмотреть аирдропы',
  'airdrop.complete_initialization_to_claim_airdrops':
    'Завершите инициализацию, чтобы получить аирдропы',
  'airdrop.complete_initialization_to_view_airdrops':
    'Завершите инициализацию, чтобы просмотреть аирдропы',
  'airdrop.you_are_eligible_for': 'Вы имеете право на:',
  'airdrop.and_more': 'и другое',
  'airdrop.congratulations': 'Поздравляем!',
  'airdrop.airdrop_fee': 'Комиссия за аирдроп',
  'countdown.countdown_plan': 'План обратного отсчета',
  'countdown.create_countdown_plan': 'Создать обратный отсчет',
  'countdown.my_countdown_plan': 'Созданы мной',
  'countdown.countdown_trading_pair': 'Торговая пара обратного отсчета',
  'countdown.countdown_display': 'Отображение обратного отсчета',
  'countdown.token_not_meet_criteria':
    'Этот токен не соответствует критериям обратного отсчета',
  'countdown.countdown_tips':
    'Обратный отсчет будет отображаться на торговой странице для выбранных торговых пар',
  'countdown.max_30_days': 'Не может быть более чем через 30 дней',
  'countdown.review_countdown_plan': 'Просмотреть план обратного отсчета',
  'countdown.countdown_fee': 'Комиссия за обратный отсчет',
  'countdown.countdown_plan_created': 'План обратного отсчета создан',
  'countdown.trading_will_start_in': 'Торговля начнется через',
  'countdown.trading_will_start_at_YYYY': 'Торговля начнется в YYYY',
  'countdown.cannot_earlier_than_current_time':
    'Не может быть до текущего времени',
  'dca.price_limit_buy_tips':
    'После активации ваши ордера на покупку будут исполняться только по ценам, равным или ниже максимальной цены. Эта функция совместима с функцией нулевой комиссии.',
  'dca.price_limit_sell_tips':
    'После активации ваши ордера на продажу будут исполняться только по ценам, равным или выше минимальной цены. Эта функция совместима с функцией нулевой комиссии.',
  'dca.zero_fee': 'Нулевая комиссия',
  'dca.zero_fee_buy_tips':
    'При включенной нулевой комиссии, ордера DCA будут обрабатываться как ордера только для Maker. Каждая цена покупки будет установлена на самой высокой цене бидов в книге ордеров после размещения. Имейте в виду, что ваши ордера могут быть не выполнены сразу или вообще не выполнены.',
  'dca.zero_fee_sell_tips':
    'При включенной нулевой комиссии, ордера DCA будут обрабатываться как ордера только для Maker. Каждая цена продажи будет установлена на самой низкой цене спроса в книге ордеров после размещения. Имейте в виду, что ваши ордера могут быть не выполнены сразу или вообще не выполнены.',
  'dca.order_canceled_post_only_buy_failed':
    'Размещение ордера не удалось, так как в книге ордеров нет ордеров на покупку, что мешает установлению цены покупки вашего ордера.',
  'dca.order_canceled_post_only_sell_failed':
    'Размещение ордера не удалось, так как в книге ордеров нет ордеров на продажу, что мешает установлению цены продажи вашего ордера.',
  start_time_cannot_before_current_time:
    'Время начала не может быть до текущего времени',
  start_time_must_before_end_time:
    'Время начала должно быть до времени окончания',
  list_token: 'Список токенов',
  contract_address_does_not_exist: 'Адрес контракта не существует',
  token_listed: 'Этот токен был добавлен',
  XXX_is_listed: 'XXX добавляется',
  view_progress: 'Просмотреть прогресс',
  pair_create_tips:
    'Торговые пары могут быть мгновенно добавлены на DeGate без одобрения какой-либо стороны.',
  base_token: 'Основной токен',
  quote_token: 'Токен котировок',
  existing_pair: 'Существующая пара',
  trade_now: 'Торговать сейчас',
  pair_XXX_added_successfully: 'XXX успешно добавлен',
  qty_per_grid: 'Количество за сетку',
  grid_minimum_not_reached: 'Минимум не достигнут',
  total_profit: 'Общая прибыль',
  total_apy: 'Общий APY',
  float_profit: 'Плавающая прибыль',
  grid_profit_24h: 'Прибыль от сетки за 24 ч',
  pnl: 'Доход/Убыток',
  eligibility: 'Право на участие',
  rewards: 'Винаграда',
  view_mining_statistics: 'Просмотреть статистику майнинга',
  your_entry: 'Вклад средств',
  refunded: 'Возвращено',
  large_price_spread: 'Большой спред цен',
  large_price_spread_tips:
    'Книга ордеров показывает большой спред между самой низкой ценой продажи и самой высокой ценой покупки, что несет риск убытков. Рекомендуется инвестировать в режиме Dual Asset.',
  continue_anyway: 'Продолжить все равно',
  insufficient_order_book_liquidity_decrease_investment:
    'Недостаток ликвидности книги ордеров. Уменьшите инвестиции.',
  initial_buy: 'Начальная покупка',
  closing_sell: 'Закрытие продажи',
  No: 'Нет',
  DCA_TRIGGER_FAIL_TIPS_PRICE_XXX:
    'Ордера DCA будут неудачными, если цена <b>$XXX упадет ниже $PRICE</b> на момент исполнения.',
  zero_fee: 'Нулевая комиссия',
  minimum_order_value_is_VALUE:
    'Минимальная сумма ордера составляет <b>$VALUE</b>.',
  Note: 'Примечание',
  Continue: 'Продолжить',
  estimated_apy: 'Оценочный APY',
  based_on_data_from_last_7_days: 'На основе данных за последние 7 дней',
  top_gainers_24h: 'Топ роста за 24 часа',
  top_losers_24h: 'Топ падения за 24 часа',
  listed_tokens: 'Перечисленные токены',
  vol: 'Объем',
  let_s_go: 'Вперед',
  reject: 'Отклонить',
  maximum_N_due_to_price_ticks: 'Максимум N из-за ценовых тиков',
  Saved: 'Сохранено',
  minimum_order_value_$100_$QUOTE:
    'Минимальная сумма ордера составляет <b>$100 $QUOTE</b>',
  minimum_order_value_$AMOUNT_$QUOTE_$100:
    'Минимальная сумма ордера составляет <b>$AMOUNT $QUOTE</b> (~$$100)',
  no_restriction_with_market_order:
    'Нет ограничений для <b>рыночного ордера</b>',
  go_to_market_order: 'Перейти к рыночному ордеру',
  Mining_Eligibility: 'Право на майнинг',
  How_to_earn_mining_rewards: 'Как заработать награды за майнинг',
  Order_Value: 'СУММА ОРДЕРА',
  'mining.mining_tips_BV_BASE_QV_QUOTE':
    'Ордеры сетки должны быть не менее <b>BV BASE</b> или <b>QV QUOTE</b> на момент создания стратегии.',
  'mining.mining_tips_QV_QUOTE':
    'Ордеры сетки должны быть не менее <b>QV QUOTE</b> на момент создания стратегии.',
  Mining_Price_Range: 'ЦЕНОВОЙ ДИАПАЗОН МАЙНИНГА',
  'mining.status_over_price_tips':
    'Цены ордеров сетки должны быть в пределах <b>ценового диапазона майнинга</b>, который составляет от самой высокой цены покупки * 0.99 до самой низкой цены продажи * 1.01 в книге ордеров.',
  'mining.status_over_price_tips_stable':
    'Цены ордеров сетки должны быть в пределах <b>ценового диапазона майнинга</b>, который составляет от самой высокой цены покупки до самой низкой цены продажи в книге ордеров.',
  Eligible_for_Mining: 'Доступен для майнинга',
  Mining_Satus: 'Статус майнинга',
  Mining_Satus_Mining: 'Майнинг',
  Mining_Satus_Standby: 'Ожидание',
  Mining_Satus_Ineligible: 'Не доступно',
  mining_price_range: 'Ценовой диапазон майнинга',
  rewards_tips_stable:
    'Ордера сетки, которые соответствуют критерию стоимости ордера для майнинга на момент создания стратегии, получат вознаграждения за майнинг, если они попадают в ценовой диапазон майнинга (максимальная цена покупки ~ минимальная цена продажи).',
  rewards_tips:
    'Ордера сетки, которые соответствуют критерию стоимости ордера для майнинга на момент создания стратегии, получат вознаграждения за майнинг, если они попадают в ценовой диапазон майнинга (максимальная цена покупки * 0.99 ~ минимальная цена продажи * 1.01).',
  wrap: 'обернуть',
  Wrap: 'Обернуть',
  websites_for_more_information:
    'Вебсайты для получения дополнительной информации:',
  official_site: 'Официальный сайт',
  wrap_site: 'Сайт обертки/развертывания',
  tips_third_party_site:
    'Вы собираетесь покинуть DeGate и перейти на сторонний сайт:',
  wrap_unwrap: 'Обертка/Развертывание',
  Receive: 'Получить',
  Network: 'Сеть',
  Token_Contract: 'Контракт токена',
  please_select_network: 'Пожалуйста, выберите сеть',
  maximum_amount: 'Максимальная сумма',
  send_USDC_to_this_address: 'Отправить USDC на этот адрес',
  arpa_airdrop: '$ARPA Аирдроп',
  Failed_to_proceed: 'Не удалось продолжить.',
  Please_select_the_Ethereum_network: 'Пожалуйста, выберите сеть Ethereum.',
  NATIVE_USDC_ONLY: 'Только нативный токен USDC',
  NEVER_send_bridged_USDC: 'НИКОГДА не отправляйте USDC через мост',
  I_understand: 'Я понимаю',
  recipient_address: 'Адрес получателя',
  chain_0: 'DeGate',
  chain_1: 'Ethereum',
  chain_17000: 'Ethereum',
  chain_42: 'Kovan',
  chain_42161: 'Arbitrum',
  chain_421614: 'Arbitrum',
  chain_10: 'Optimism',
  chain_11155420: 'Optimism',
  chain_137: 'Polygon',
  chain_80002: 'Polygon',
  scan_1: 'Etherscan',
  scan_17000: 'Etherscan',
  scan_42161: 'Arbiscan',
  scan_421614: 'Arbiscan',
  scan_10: 'Opscan',
  scan_11155420: 'Opscan',
  scan_tips:
    'Транзакция в Rollup, содержащая это действие, еще не была опубликована на Ethereum. Пока это не произойдет, DGSCAN <b>НЕ</b> отобразит это действие.',
  Best_Liquidity: 'Лучшая ликвидность',
  order_partially_filled: 'Ордер частично выполнен',
  order_partially_filled_for_liquidity:
    'Ваш оставшийся ордер был отменен из-за резкого падения ликвидности в ордербуке. Эта защитная мера предотвращает выполнение по неблагоприятным ценам.',
  'orders.export_data_2_year': 'Экспорт данных за последние 2 года',
  Community: 'Сообщество',
  complete_in_seconds: 'Завершение за несколько секунд',
  failed_to_send: 'Не удалось отправить. Пожалуйста, попробуйте снова.',
  failed_to_send_try_other_networks:
    'Не удалось отправить. Попробуйте другие сети.',
  gas_fee_deducted: 'Комиссия за газ снята:',
  sum_XXX: 'Сумма XXX',
  chart_control_7d: '7 дней',
  chart_control_30d: '30 дней',
  chart_control_all: 'все',
  chart_control_day: 'Д',
  chart_control_week: 'Н',
  chart_control_month: 'М',
  Coming: 'Скоро',
  leave_survey_title: 'Привет, похоже, вы покидаете DeGate.️',
  leave_survey_subtitle:
    'Пожалуйста, помогите нам стать лучше, оставив отзыв. Выберите все, что применимо.',
  leave_survey_not_leaving: 'Я не ухожу, я вернусь, глупый.',
  leave_survey_other_is_fine:
    'Binance/OKX/Kraken и т. д. работают хорошо для меня.',
  leave_survey_bad_experience: 'Мне не нравится торговый опыт.',
  leave_survey_no_yield: 'Я не нашел никаких возможностей для дохода.',
  leave_survey_no_needed_token: 'Я не нашел токены, которые хочу торговать.',
  leave_survey_other_reason: 'Другие (пожалуйста, сообщите нам в поле ниже)',
  leave_survey_thanks_for_feedback: 'Спасибо за ваш отзыв',
  Submitted: 'Отправлено',
  doc_title:
    'DeGate: Децентрализованная биржа с книгой ордеров | Бесплатный крипто-трейдинг бот на GRID и DCA',
  doc_desc:
    'DeGate — это ведущая децентрализованная биржа с ордер-буком, предлагающая торговлю сотнями криптовалют с низкими комиссиями, бесплатную торговлю лимитными ордерами, сеточными Grid стратегиями и ботами DCA.',
  doc_title_spot: 'Децентрализованный ордер-бук | DeGate DEX',
  doc_title_grid: 'Децентрализованный Grid Торговый Бот| DeGate DEX',
  doc_title_dca: 'Децентрализованный DCA Торговый Бот | DeGate DEX',

  Notification: '',
  read_all: '',
  important: '',
  general: '',
  view_more: '',
  thats_all: '',
  XXX_fund_addition_processing: '',
  add_AMOUNT_XXX_to_DeGate: '',
  XXX_fund_addition_successful: '',
  XXX_send_successful: '',
  send_AMOUNT_XXX_to_DeGate: '',
  send_AMOUNT_XXX_to_Ethereum: '',
  you_have_received_a_new_airdrop: '',
  AMOUNT_XXX_can_be_claimed_after_YYYY_MM_DD: '',
  MARKET_Chart: '',
  grid_free: '',
  maker_free_tips: '',
  Audit: '',
  Tool: '',
  About: '',
};

export default ru;
