const en = {
  language: 'tr-TR',
  'kline.time_Line': 'Zaman',
  'kline.time_1m': '1d',
  'kline.time_3m': '3d',
  'kline.time_5m': '5d',
  'kline.time_15m': '15d',
  'kline.time_30m': '30d',
  'kline.time_1H': '1S',
  'kline.time_2H': '2S',
  'kline.time_4H': '4S',
  'kline.time_6H': '6S',
  'kline.time_1D': '1G',
  'kline.time_1W': '1H',
  'kline.time_1M': '1A',
  'kline.tab_line': 'Grafik',
  'kline.tab_depth': 'Derinlik',
  'kline.chartType_Bars': 'Çubuklar',
  'kline.chartType_Candles': 'Mumlar',
  'kline.chartType_Hollow_Candles': 'Boş Mumlar',
  'kline.chartType_Line': 'Çizgi',
  'kline.chartType_Area': 'Alan',
  'kline.chartType_Heikin_Ashi': 'Heikin Ashi',
  degate_account: 'DeGate Hesabı',
  Trade: 'Ticaret',
  Order: 'Emir',
  Grid: 'Grid Stratejisi',
  Campaign: 'Kampanya',
  DCA: 'DCA',
  Advanced: 'Gelişmiş',
  Add: 'Ekle',
  Add_Funds: 'Fon Ekle',
  eth_added_1: '1 ETH Eklendi',
  eth_sent_1: '1 ETH Gönderildi',
  Send: 'Gönder',
  Internal_Transfer: 'İç Transfer',
  Miscellaneous: 'Çeşitli',
  Bridge: 'Köprü',
  Mining: 'Madencilik',
  Liquidity_Mining: 'Likidite Madenciliği',
  Analytics: 'Analiz',
  Support: 'Destek',
  Help: 'Yardım',
  Tips: 'İpucu',
  Statistics: 'İstatistikler',
  Coming_soon: 'Yakında Geliyor',
  Faucet: 'Musluk (Faucet)',
  more: 'Daha Fazla',
  hide: 'Gizle',
  change: 'Değiştir',
  'Wrong Network': 'Yanlış Ağ',
  avbl: 'Mevcut:',
  insufficient_balance_AAA:
    'Cüzdanınızda yeterli AAA yok. Lütfen kontrol edip tekrar deneyin.',
  insufficient_balance: 'Yetersiz bakiye',
  wallet_denied_sign: 'Mesaj imzası reddedildi.',
  common_err: 'Bir şeyler ters gitti. Lütfen daha sonra tekrar deneyin.',
  common_err_ledger_version:
    'Bir hata oluştu. Ledger Ethereum uygulamanızın güncel olduğundan (1.9.10 veya üstü) emin olun veya daha sonra tekrar deneyin.',
  network_1: 'Ethereum ana ağı',
  network_err: 'Ağ hatası. Lütfen daha sonra tekrar deneyin.',
  rate_limit_err:
    'Erişim sıklığı çok yüksek, lütfen bir dakika içinde tekrar deneyin.',
  error_InsufficientGasFunds: 'Cüzdanda yeterli Gas yok',
  notification_transaction_send: 'İşlem gönderildi',
  view_on_etherscan: "Blockchain Explorer'da Görüntüle",
  view_on_explorer: 'Adresi Görüntüle',
  switch_network: 'Ağ Değiştir',
  switch_to_Arbitrum: "Devam etmek için Arbitrum'a geçin.",
  switch_to_MAINNET_in_metamask: "Lütfen MetaMask'te ANA AĞA geçin",
  switch_to_MAINNET: 'Lütfen ANA AĞA geçin',
  switch_network_in_walletconnect:
    'Cüzdanınıza gidip WalletConnect ile ağı değiştirin',
  Retry: 'Tekrar Dene',
  wallet_tips: 'Lütfen tarayıcı cüzdanında onaylayın',
  wallet_ledger_tips: 'Lütfen Ledger donanımında onaylayın',
  wallet_metamask_tips: "Lütfen MetaMask'te onaylayın",
  wallet_walletconnect_tips:
    'Lütfen cüzdanınıza gidip WalletConnect ile onaylayın',
  wallet_cancelled_tips: 'İmza iptal edildi',
  Close: 'Kapat',
  copied: 'Kopyalandı',
  Details: 'Detaylar',
  view_details: 'Detayları Görüntüle',
  Share: 'Paylaş',
  view_graph: 'Grafikte Görüntüle',
  Dismiss: 'Reddet',
  Cancel: 'İptal',
  End: 'Sonlandır',
  End_grid: 'Sonlandır',
  Confirm: 'Onayla',
  Cancel_all: 'Tümünü İptal Et',
  cancel_all_tips: 'Açık tüm emirleri iptal et',
  Submit: 'Gönder',
  no_data: 'Veri yok',
  all_data_displayed: 'Tüm veriler görüntülendi',
  no_data_within_90_days: 'Son 90 gün içinde veri yok',
  only_display_90_days: 'Sadece son 90 gün içindeki veriler görüntüleniyor',
  displayed_90_days: 'Son 90 gün içindeki veriler görüntüleniyor',
  only_data_beyond_90_days_trade:
    '90 gün öncesindeki verilere erişmek için "Tümünü Görüntüle" seçeneğini seçip "Export Data" fonksiyonunu kullanın',
  only_data_beyond_90_days_grid_detail:
    'Son 90 gün öncesine ait veri sorgusu şu anda desteklenmemektedir',
  only_data_beyond_90_days_spot_history:
    '90 gün öncesindeki verilere erişmek için "Veri İhracı" fonksiyonunu kullanın',
  View: 'Görüntüle',
  service_unavailable_for_region_REGION: 'Bu hizmet BÖLGEDE mevcut değil.',
  service_unavailable: 'Hizmet kullanılamıyor',
  service_error: 'Lütfen daha sonra tekrar deneyin',
  service_maintenance: 'Bu hizmet bakımda.',
  connect_wallet: 'Cüzdanı Bağla',
  switch_address: 'Adres Değiştir',
  wallet_wc: 'WalletConnect ile Bağlandı',
  wallet_ledger: 'Ledger ile Bağlandı',
  register_dexAccount: 'Kayıt Ol',
  deposit_ETH: 'ETH Ekle',
  initialize: 'Başlat',
  initialization: 'Başlatma',
  invalid_signature: 'Geçersiz İmza',
  possible_cause: 'Olası neden:',
  locale_time_error: 'Yerel cihaz saatiniz doğru değil.',
  authorization_mode: 'Kimlik Doğrulama Modu',
  authorization_mode_standard: 'İmzasız',
  authorization_mode_single_use: 'Her Zaman İmza',
  turn_on: 'Aç',
  turn_on_signature_free_mode: 'İmzasız modu aç',
  signatre_free_mode: 'İmzasız Mod',
  turn_on_signature_free_mode_tips:
    'Bu modda, imza olmadan emir verebilirsiniz. Modu değiştirmek için Ticaret Butonunun altındaki "Ayarlar"a gidin.',
  turn_on_signature_free_mode_tips_grid:
    'Bu modda, imza olmadan grid stratejileri oluşturabilirsiniz. Modu değiştirmek için Ticaret Butonunun altındaki "Ayarlar"a gidin.',
  turn_on_signature_free_mode_tips_dca:
    'Bu modda, imza olmadan DCA planları oluşturabilirsiniz. Modu değiştirmek için Ticaret Butonunun altındaki "Ayarlar"a gidin.',
  yes: 'Evet',
  no: 'Hayır',
  free_mode_on: 'İmzasız Mod Açık',
  view_balance: 'Bakiyeyi Görüntüle',
  delete_asset_key: 'Varlık Anahtarını Sil',
  delete_asset_key_desc:
    'Varlık Anahtarı tarayıcınızdan silindiğinde İmzasız mod kapanacaktır.',
  no_asset_key_tips: 'Tarayıcınızda Varlık Anahtarı bulunamadı',
  turn_off_standard_mode: 'Ve İmzasız modu kapat',
  reset_asset_key: 'Varlık Anahtarını Sıfırla',
  view_asset_key: 'Varlık Anahtarını Görüntüle',
  lock_success: 'Varlık Anahtarı Silindi',
  reset: 'Varlık Anahtarını Sıfırla',
  delete: 'Sil',
  withdraw_ETH: 'ETH Gönder',
  transfer_ETH: 'ETH İç Transfer',
  history: 'Geçmiş',
  view_history: 'Geçmişte Görüntüle',
  internal_transfer: 'Transfer',
  assets_record_link: 'Geçmiş',
  other: 'Diğer',
  login_success: 'Bağlantı Başarılı',
  Account: 'Hesap',
  Address: 'Adres',
  Disconnect: 'Bağlantıyı Kes',
  copy_address: 'Adresi Kopyala',
  copy_grid: 'Stratejiyi Kopyala',
  Copy: 'Kopyala',
  btn_search: 'Ara',
  btn_reset: 'Sıfırla',
  btn_confirm: 'Kapat',
  btn_max: 'Max',
  btn_ok: 'Tamam',
  spot_trade: 'SPOT',
  grid_trade: 'GRID',
  err_balance_title: 'Emir Verilemedi',
  err_balance_content:
    'Yetersiz mevcut bakiye. Lütfen kontrol edip tekrar deneyin.',
  order_failed: 'Emir Başarısız',
  insufficient_order_value: 'Yetersiz Emir Değeri',
  grid_failed: 'Oluşturma Başarısız',
  err_eth_gas: 'Ethereum ağı aşırı yoğun',
  err_insufficient_balance_TOKEN1: 'Yetersiz TOKEN1 bakiyesi',
  err_insufficient_balance_TOKEN1_TOKEN2:
    'Yetersiz TOKEN1 ve TOKEN2 bakiyeleri',
  please_add_funds_before_ordering:
    'Emir vermeden önce DeGate Bakiyenize fon ekleyin.',
  err_balance_content_spot: 'Yetersiz bakiye nedeniyle emir verilemedi.',
  err_balance_content_grid:
    'Yetersiz bakiye nedeniyle grid stratejisi oluşturulamadı.',
  trade_min_volume_tips_XXX: 'Min XXX',
  grid_min_volume_tips:
    'Emir başına miktar minimum tutarı karşılamıyor. Lütfen tekrar deneyin.',
  trade_risk_orders_tips: 'Çok fazla açık emriniz olduğu için emir verilemiyor',
  gas_token_tips: 'Gas ücreti tokenini seç',
  add_favorite_tooltip: 'Favorilere ekle',
  remove_favorite_tooltip: 'Favorilerden çıkar',
  expire_tips_X: 'Bu emir X tarihinde sona erecek.',
  today: 'Şimdi',
  now: 'Şimdi',
  time_D_day: 'Dd',
  time_D_day_H_hour: 'Dd Ss',
  time_H_hour_M_minute: 'Ss Dk',
  time_M_minute_S_second: 'Dk Sn',
  time_S_second: 'Sn',
  around: 'ï½ž',
  time_now: 'şimdi',
  time_before: '',
  time_before_ago: 'önce',
  time_1_minute: '1 dakika',
  time_1_hour: '1 saat',
  time_1_day: '1 gün',
  time_1_year: '1 yıl',
  time_M_minutes: 'M dakika',
  time_M_m: 'Dk',
  time_H_hours: 'S saat',
  time_H_h: 'Ss',
  time_D_days: 'G gün',
  time_Y_years: 'Y yıl',
  time_Y_y: 'Yy',
  fee_change_tips: 'Fiyat Güncellendi',
  no_pairs: 'Ticaret Çifti Bulunamadı',
  register_new_pair: 'Yeni Çift Ekle',
  register_pair: 'Ticaret Çifti Ekle',
  add_pair: 'Çift Ekle',
  tips_hide_forever: 'Bir daha gösterme',
  token: 'Token',
  action: 'Eylem',
  more_actions: 'Daha Fazla',
  gas_fee: 'Gas Ücreti',
  'orders.detail_gas': 'Gerçek Gas Ücreti',
  trade_fee: 'Ticaret Ücreti',
  about_degate: 'DeGate Hakkında',
  metrics: 'Metrikler',
  fees: 'Ücretler',
  document: 'Belgeler',
  join_us: 'Bize Katılın',
  feedback: 'Geri Bildirim',
  email_optional: 'E-posta adresiniz (Opsiyonel)',
  Upload: 'Yükle',
  feedback_upload_tip:
    'Geri bildiriminizi paylaşın. Dosyaları eklemek için sürükleyin.',
  feedback_upload_tip_mobile: 'Geri bildiriminizi paylaşın.',
  image_upload_tip: 'Ekleme için bırakın',
  feedback_success: 'Sizi net ve açık şekilde duyuyoruz!',
  feedback_success_2: 'Teşekkür ederiz',
  feedback_failed: 'Gönderim başarısız oldu. Lütfen daha sonra tekrar deneyin.',
  image_upload_rule_1: 'Sadece PNG, JPG, JPEG desteklenir.',
  image_upload_rule_2: "Dosya başına maksimum boyut 20MB'dir.",
  image_upload_rule_3: 'Maksimum 5 dosya.',
  image_upload_rule_2_3: 'Dosya başına maksimum boyut 20MB. Maksimum 5 dosya.',
  no_pair: 'Token Çifti Bulunamadı',
  no_token: 'Token Bulunamadı',
  choose_base_token: 'Ana Tokeni Seç',
  choose_quote_token: 'Teklif Tokenini Seç',
  get_test_token: 'Testnet Tokeni Al',
  faucet: 'Musluk (Faucet)',
  expire_in: 'Süresi doluyor',
  expire_in_empty_err: 'Lütfen bir sayı girin',
  go_back: 'Geri Dön',
  max_XXX: 'Max XXX',
  min_XXX: 'Min XXX',
  fill_in: 'Doldur',
  my_balance: 'Bakiyem',
  deGate_insufficient_fees: 'Gas Ücretini Ödemek İçin Yetersiz DeGate Bakiyesi',
  wallet_balance: 'Cüzdan Bakiyesi',
  your_wallet_balance: 'Cüzdanınızdaki Bakiye',
  degate_balance: 'DeGate Bakiyesi',
  wallet_insufficient_fees: 'Cüzdanda Yetersiz Bakiye',
  wallet_insufficient_balance: 'Yetersiz bakiye',
  insuffficient_wallet_balance: 'Cüzdanda Yetersiz Bakiye',
  degate_insufficient_balance: 'Yetersiz mevcut bakiye',
  open_discord: 'Discord Topluluğuna Katıl',
  err_valid_until: 'Lütfen yerel saati cihazınızdaki standart zamana ayarlayın',
  tips_gas:
    'Bu zincir üstü işlemi yürütmek için gas ücreti doğrudan DeGate bakiyenizden düşülecektir.',
  maker_free: 'Piyasa Yapıcılara Ücretsiz',
  trading_fee_rate: 'Ticaret Ücreti Oranı',
  Free: 'Ücretsiz',
  stop_service_1: 'Site bakımda',
  stop_service_2: 'Tahmini Kurtarma Süresi',
  stop_upgrade:
    "Testnet'in yeni versiyonu şu anda göç işlemi gerçekleştiriyor.",
  stop_trading_1: 'Sistem Yükseltmesi',
  stop_trading_2: 'Ticaret geçici olarak durduruldu',
  sell: 'sat',
  buy: 'al',
  SELL: 'SAT',
  BUY: 'AL',
  Sell: 'Sat',
  Buy: 'Al',
  sell_order: 'Satış Emri',
  buy_order: 'Alım Emri',
  edit: 'Düzenle',
  status_processing: 'İşleniyor',
  status_processed: 'Bekliyor',
  status_pending: 'Bekliyor',
  status_confirming: 'Onaylanıyor',
  status_success: 'Başarılı',
  status_completed: 'Kesinleşti',
  status_failed: 'Başarısız',
  status_speeding_up: 'Hızlandırılıyor',
  status_canceling: 'İptal ediliyor',
  status_canceled: 'İptal edildi',
  in_progress: 'Devam Ediyor',
  limit_order: 'Limit',
  market_order: 'Piyasa',
  stop_limit_order: 'Stop Limit',
  balance: 'Bakiye',
  empty_connect: 'Lütfen önce cüzdanı bağlayın',
  empty_register: 'Lütfen önce başlatın',
  empty_months3: 'Son 3 aya ait veri yok',
  show_months3: 'Sadece son 3 aydaki veriler gösteriliyor',
  view_all: 'Hepsini Gör',
  D1: '1G',
  D5: '5G',
  M1: '1A',
  M3: '3A',
  M6: '6A',
  YTD: 'YTD',
  Y1: '1Y',
  all: 'Tümü',
  paste: 'Yapıştır',
  clear: 'Temizle',
  total: 'Toplam',
  amount: 'Tutar',
  order_amount: 'Emir Tutarı',
  price: 'Fiyat',
  order_total: 'Toplam',
  filledAmount: 'Miktar',
  tradeFilledTotal: 'Değer',
  orderFilledTotal: 'Toplam',
  filledAmount_amount: 'Doldurulan/Miktar',
  profit: 'Kâr',
  incompatible_token:
    'Bu tokenin teknik özellikleri DeGate protokolü ile uyumlu değil.',
  next: 'Sonraki',
  token_not_verified: 'Doğrulanmadı',
  token_not_verified_tips:
    'Kontrat adresi, Simge ve Sembol doğrulanmadı. Dolandırıcılıklardan kaçınmak için kontrat adresini resmi kaynaklardan kontrol edin.',
  token_verified: 'Doğrulandı',
  token_verified_tips: 'Kontrat adresi, Simge ve Sembol eşleşiyor.',
  deposit_tips_region:
    "Lütfen BÖLGEDE DeGate'e eriştiğinizi unutmayın. Fon eklemesinden sonra ticaret ve iç transfer özellikleri kullanılamaz.",
  complete_time: 'Tamamla',
  unable_to_initialize: 'Başlatılamıyor',
  filter_base: 'Temel',
  filter_quote: 'Teklif',
  filter_type: 'Tür',
  filter_role: 'Rol',
  option_maker: 'Piyasa Yapıcı',
  option_taker: 'Piyasa Alıcı',
  start_data: 'Başlangıç Tarihi',
  end_data: 'Bitiş Tarihi',
  added_to_favorites: 'Favorilere eklendi',
  removed_to_favorites: 'Favorilerden çıkarıldı',
  show_recents_50: 'Son 50 veri gösterildi.',
  terms_of_service: 'Hizmet Şartları',
  tips_small_unfilled:
    'Sistem tasarımında belirtilen hassasiyet derecelerine göre, doldurulmayan küçük bir emir kısmı DeGate Bakiyenize iade edilmiştir.',
  notification: 'Bildirim',
  server_message_SystemRecovery:
    'Sistem kurtarıldıktan sonra emir durumlarınızda değişiklikler olduğunu lütfen unutmayın.',
  learn_more: 'Daha Fazla Bilgi Edinin',
  connect_ledger: "Ledger'ı Bağlayın",
  ledger_disconnect:
    "USBDevice' üzerinde 'transferOut' işlemi başarısız oldu: Cihaz bağlantısı kesildi.",
  gas_fee_expired: 'Gas ücreti süresi doldu. Lütfen tekrar gönderin.',
  scroll_down_to_refresh: 'Yenilemek için aşağı kaydırın',
  release_to_refresh_immediately: 'Yenilemek için bırakın',
  no_more: 'Daha fazla veri yok',
  loading: 'Yükleniyor...',
  force_withdrawing_token_tips:
    'Zorla çekim talebiniz işlenirken mevcut işlem gerçekleştirilemiyor.',
  speed_up: 'Hızlandır',
  transaction_submitted: 'İşlem Gönderildi',
  tx_speed_up: 'İşlemi Hızlandır',
  tx_cancel: 'İşlemi İptal Et',
  none: 'Hiçbiri',
  Language: 'Dil',
  page: '/Sayfa',
  go_to: 'Git',
  icon_indicators: 'Göstergeler',
  icon_back: 'Geri',
  icon_forward: 'İleri',
  icon_full_screen: 'Tam ekran',
  icon_exit_full_screen: 'Tam ekrandan çık',
  icon_buy_sell_orders: 'Alım ve Satım Emirleri',
  icon_buy_orders: 'Alım Emirleri',
  icon_sell_orders: 'Satım Emirleri',
  icon_enable: 'Etkinleştirmek için tıklayın',
  icon_disable: 'Devre dışı bırakmak için tıklayın',
  icon_copy: 'Adresi kopyala',
  icon_view_explorer: "Blok Gezgini'nde Görüntüle",
  icon_display_by_profit: 'Kâra göre görüntüle',
  icon_display_by_time: 'Zamana göre görüntüle',
  icon_switch: 'Değiştir',
  eth_code_tips: "Ethereum'un yerel tokeni. Token kontrat adresi yok.",
  TBD: 'Belirlenecek',
  TVL: 'Toplam Kilitli Değer (TVL)',
  go_to_discord: "Ya da Bilet Oluşturmak için Discord'a Katıl",
  release: 'Yayın:',
  security: 'Güvenlik',
  colon: ':',
  zero_balance: 'Sıfır Bakiye',
  ledger_app_version_tips:
    "İmzalama öncesi mesajı önizlemek için Ledger'inizin Ethereum uygulamasını 1.9.19 veya üstü sürüme güncelleyin.",
  ledger_contract_data_tips:
    'Ethereum uygulama ayarlarında Kör imzalamayı veya Kontrat verilerini etkinleştirin',
  input_auto_corrected_tooltips:
    'Maksimum hane sayısını aştığınız için girdiniz otomatik düzeltildi',
  maximum_decimal_reached: 'Maksimum ondalık basamak sayısına ulaşıldı',
  verify_ownership: 'Sahipliği Doğrula',
  enable_trading: 'Ticareti Etkinleştir',
  learn_more_about_signatures_link: 'İmzalar hakkında daha fazla bilgi >',
  learn_more_about_signatures: 'İmzalar hakkında daha fazla bilgi',
  sign: 'İmzala',
  sign_step1: 'Cüzdanınızda Tamamlayın',
  sign_step2: '2. İmzayı Tamamla',
  not_now: 'Şimdi Değil',
  view_on_block_explorer: "Blockchain Explorer'da Görüntüle",
  view_in_history: 'Geçmişte Görüntüle',
  continue_to_place_order: 'Emir Vermeye Devam Et',
  Save: 'Kaydet',
  sign_to_view: 'Görüntülemek için imzala',
  available_degate_balance: 'Mevcut DeGate Bakiyesi',
  Back: 'Geri',
  token_has_not_listed: "Bu token DeGate'te listelenmedi.",
  list_now: 'Şimdi Listele',
  spread_15: 'Fark > 15%',
  connected: 'Bağlandı',
  self_list_token: 'Anında Listeleme',
  claim_REBASE: 'REBASE Talep Et',
  time: 'Zaman',
  time_updated: 'Zaman Güncellendi',
  show_in_X_m: '~Xm içinde göster',
  max_gas: 'Maksimum Gas Ücreti',
  total_required: 'Gerekli toplam',
  Required: 'Gerekli',
  available_balance: 'Mevcut Bakiye',
  please_add_funds: 'Lütfen DeGate Bakiyenize fon ekleyin.',
  Side: 'Taraf',
  pending: 'Beklemede',
  active: 'Aktif',
  ended: 'Bitti',
  name: 'Ad',
  yield: 'Getiri',
  time_created: 'Oluşturma Zamanı',
  time_ended: 'Bitiş Zamanı',
  frequency: 'Frekans',
  chain_cancel: 'Zincir Üzerinde İptal',
  status: 'Durum',
  status_chainCancelProgressing: 'Zincir Üzerinde İptal Ediliyor',
  status_chainCancelCompleted: 'Zincir Üzerinde İptal Edildi',
  filled_total: 'Doldurulan/Toplam',
  start_time: 'Başlangıç Zamanı',
  end_time: 'Bitiş Zamanı',
  Summary: 'Özet',
  Orders: 'Emirler',
  Tutorial: 'Kılavuz',
  Earn: 'Kazanç',
  top_winner_24h: '24 saatlik En Yüksek Sıralamalar',
  ID: 'ID',
  Select: 'Seç',
  Create: 'Oluştur',
  Review: 'İncele',
  Airdrop: 'Airdrop',
  Countdown: 'Geri Sayım',
  Day: 'Gün',
  Hour: 'Saat',
  Minute: 'Dakika',
  Second: 'Saniye',
  Days: 'Günler',
  Hours: 'Saatler',
  Minutes: 'Dakikalar',
  Seconds: 'Saniyeler',
  Claim: 'Talep Et',
  Expired: 'Süresi Doldu',
  Claimed: 'Talep Edildi',
  Welcome: 'Hoş Geldiniz',
  gas_tips_for_amount_exceed_6_digits:
    'Miktar için haneler nominal sınır olan altı haneyi aştığı için ek ücretler uygulanmıştır.',
  input_auto_corrected_minStep_tips:
    'Minimum hassasiyeti karşılamak için girdiniz otomatik düzeltildi',
  order_max_limit: 'Maksimum sınır aşıldı',
  order_min_limit: 'Minimum sınır karşılanmadı',
  order_faild_min_limit:
    'Emir verme başarısız oldu: Minimum sınır karşılanmadı.',
  order_faild_max_limit: 'Emir verme başarısız oldu: Maksimum sınır aşıldı.',
  disconnect_m: 'Bağlantıyı Kes',
  'account.account_manage': 'Güvenlik',
  'account.account_manage_more':
    'Kimlik Doğrulama Modu ve Varlık Anahtarı Hakkında >',
  'account.what_is_asset_key':
    'Kimlik Doğrulama Modu ve Varlık Anahtarı Hakkında',
  'account.total_value': 'Toplam Değer',
  'account.hide_small_balances': 'Küçük Bakiyeleri Gizle',
  'account.add_to_metamask': 'Tokeni Cüzdana Ekle',
  'account.assets_balance_total': 'Toplam',
  'account.assets_balance_available': 'Mevcut',
  'account.assets_market': 'Değer',
  'account.transfer_to_degate_balance': 'DeGate Bakiyesine Ekle',
  'account.search_tokens': 'Token ara',
  'account.deposit_title':
    'Varlıklar merkeziyetsiz DeGate hesabınıza yatırılacaktır. Bu varlıkların tam kontrolü sizde olacaktır.',
  'account.deposit_tips': 'Bu fonların tam kontrolü sizde kalır.',
  'account.deposit_confirm_btn': 'Ekle',
  'account.deposit_approved_btn': 'Onaylandı',
  'account.deposit_1_ETH': 'DeGate Bakiyenize 1 ETH Ekleyin',
  'account.deposit_status_pending': 'Beklemede',
  'account.deposit_status_pay_pending': 'Ödeme Bekliyor',
  'account.deposit_status_pay_waiting': 'Ödeme Yayınlandı',
  'account.deposit_status_pay_confirming': 'Ödeme Onaylanıyor',
  'account.deposit_tips_block': 'İşlem blok eklenmesini bekliyor',
  'account.deposit_status_pay_btn': 'Öde',
  'account.pay_deposit_warning': 'Fon eklemek ek gas ücretine tabi olabilir',
  'account.pay_deposit_warning_tips':
    "DeGate'in sübvansiyonları tamamen kullanıldığından kullanıcıların fon ekleme maliyetini karşılaması gerekebilir.",
  'account.deposit_pending_tips':
    'İşlem 5 dakikadan uzun süre bekliyorsa cüzdanınızda işlemi hızlandırın.',
  'account.deposit_pending_tips_ledger':
    'İşlem 5 dakikadan uzun süre bekliyorsa hızlandırın.',
  'account.deposit_contract_tips_over_AMOUNT':
    'Fon eklemeleri AMOUNT USD üzerinde olduğunda Gelişmiş yöntem gereklidir.',
  'account.deposit_contract_tips_only_all':
    'Sadece Gelişmiş fon ekleme yöntemi desteklenir',
  'account.suggest_100': 'â‰¥$100 önerilir',
  'account.suggest_100_tips':
    "Limit emri vermek için $100'ün üzerinde bir miktar önerilir.",
  'account.deposit_failed': 'Başarısız',
  'account.deposit_failed_tips':
    'Zincir üstü fon ekleme işlemi başarısız oldu.',
  'account.payment_due': 'Ödeme Bekliyor',
  'account.payment_due_tips':
    'Fonların DeGate Bakiyenize eklenmesi için ek ödeme gereklidir.',
  'account.register_token_code_placeholder': 'Kontrat adresini girin',
  'account.register_token_code': 'Kontrat Adresi',
  'account.register_token_symbol': 'Sembol',
  'account.register_token_check': 'Listeleme İlerlemesini Kontrol Et',
  'account.register_token_code_err_added': 'Bu token listeleniyor',
  'account.register_token_next_step': 'Sonraki',
  'account.register_token_tips1':
    'Zincir üstü token listeleme için izin gerekmez. Lütfen tokeninizi hızlıca listeleyin.',
  'account.register_token_btn': 'Token Listele',
  'account.list_token': 'Token Listele',
  'account.withdraw_warning_XXX':
    'Artan talep nedeniyle fon gönderme şu anda ~ XXX sürmektedir.',
  'account.withdraw_status_pending': 'İşleniyor',
  'account.tansferred_1_ETH': '1 ETH Transfer Edildi',
  'account.transfer_status_sent': 'Gönderildi',
  'account.transfer_status_received': 'Alındı',
  'account.th_me': 'Ben',
  'account.th_tx_hash': "İşlem Hash'i",
  'account.th_time': 'Zaman',
  'account.locked_order': 'Limit Emri',
  Sending: 'Gönderiliyor',
  'account.locked_claimable': 'Talep Edilebilir',
  'account.locked_grid': 'Grid Stratejisi',
  'account.personal_sign_reason': 'Olası Nedenler',
  'account.personal_sign_reason1': '1. MetaMask bir donanım cüzdanına bağlı',
  'account.personal_sign_reason2': '2. MetaMask sürümü güncel değil',
  'account.personal_sign_reason3': '3. Diğer',
  'account.personal_sign_btn': 'Tekrar İmzala',
  'account.deposit_arrive_in_30s': '~30 saniye içinde ulaşır',
  'account.deposit_arrive_in_30s_s': '~ 30 saniye içinde ulaşır',
  'account.account_completed_time_XXX': '~XXX içinde tamamlanır',
  'account.search_result_no_token': 'Token bulunamadı',
  'account.search_result_invalid_code': 'Geçersiz kontrat adresi',
  'account.search_result_not_listed': "Token şu anda DeGate'te listelenmemiş",
  'account.search_result_tips_register':
    'Token listelemesini tamamlamak için kontrat adresini girebilirsiniz',
  'account.search_result_not_find': 'Hala bulunamıyor mu?',
  'account.search_pair_tips3': 'Varlık için ticaret çifti yok',
  'account.search_pair_tips3_add': 'Lütfen çift ekleyin',
  'account.register_token': 'İzin Gerektirmeyen Token Listeleme',
  'account.search_again': 'Tekrar Ara',
  'account.deposit_type': 'Yöntem',
  'account.deposit_type_standard': 'Standart',
  'account.switch_account_tips': 'Şuna Geçildi',
  'account.switch_account_tips_register': 'Lütfen önce başlatın.',
  'account.initialize_success': 'Başlatma Başarılı',
  'account.approve': 'Onayla',
  'account.reset_USDT': 'USDT Onayını Sıfırla',
  'account.reset_USDT_tips':
    'USDT, harcama limitleri çok düşük olduğunda onaylamanın sıfırlanmasını gerektirir.',
  'account.next_step': 'Sonraki',
  'account.profit_total': 'Toplam Kâr',
  'account.profit_history': 'Kâr Geçmişi',
  'account.tab_mining_rewards': 'Madencilik Ödülleri',
  'account.yield_total': 'Toplam Getiri',
  'account.yield_24h': '24 saatlik Getiri',
  'account.claimable': 'Talep Edilebilir',
  'account.yield_history': 'Getiri Geçmişi',
  'account.total_grid_profit': 'Toplam Grid Kârı',
  'account.grid_strategies': 'Grid Stratejileri',
  'account.total_rewards': 'Toplam Ödüller',
  'account.rewards_24h': '24 saatlik Ödüller',
  'account.rewards': 'Ödüller',
  'menu.register_err':
    'Adresinizde herhangi bir blockchain işlem kaydı yok. Lütfen zincir üstü bir işlem yapın ve tekrar deneyin. Örneğin, cüzdanınıza bir token transferi gerçekleştirin.',
  'menu.reset_post_success_withOrders':
    'Varlık Anahtarı sıfırlama başlatıldı. Tüm açık emirleriniz ve grid stratejileriniz iptal edildi.',
  'menu.reset_post_success': 'Varlık Anahtarı sıfırlama başlatıldı.',
  'menu.reset_processing_title': 'Varlık Anahtarı sıfırlaması devam ediyor',
  'menu.reset_processing_desc': 'Lütfen tamamlanmasını bekleyin',
  'trade.choose_token': 'Token Seç',
  'trade.token_info': 'Token Bilgisi',
  'trade.token_address': 'Token Adresi',
  'trade.price_range_24h': '24 saatlik Fiyat Aralığı',
  'trade.vol_24h': '24 saatlik Hacim',
  'trade.item_price_TOKEN': 'Fiyat (TOKEN)',
  'trade.item_amount_TOKEN': 'Miktar (TOKEN)',
  'trade.order_book_title': 'Emir Defteri',
  'trade.order_book_total': 'Toplam',
  'trade.trade_history_title': 'Son İşlemler',
  'trade.trade_history_time': 'Zaman',
  'trade.market_placeholder_price': 'Piyasa Fiyatı',
  'trade.what_is_stop_limit': 'Stop Limit Nedir',
  'trade.what_is_stop_limit_link': 'Stop Limit Nedir >',
  'trade.placeholder_total': 'Toplam',
  'trade.more_settings': 'Ayarlar',
  'trade.expire_in_tips':
    'Emir süresi dolduktan sonra otomatik olarak iptal edilecektir.',
  'trade.period_day_s': 'g',
  'trade.period_hour_s': 's',
  'trade.period_minute_s': 'd',
  'trade.period_err_input_tips': 'Lütfen geçerli bir sayı girin',
  'trade.post_only_label': 'Sadece Piyasa Yapıcı',
  'trade.post_only_tips':
    'Sadece Piyasa Yapıcı modu, yalnızca Piyasa Yapıcı emirlerinin emir defterine girmesini sağlar. Emir herhangi bir şekilde Piyasa Alıcı olarak doldurulursa, tüm emir iade edilir. Sadece Piyasa Yapıcı modunda verilen emirler gas ücreti veya ticaret ücreti içermez.',
  'trade.post_only_fail_title': 'Emir Yaratılamıyor',
  'trade.post_only_fail_desc':
    'Lütfen fiyatı ayarlayın veya "Yalnızca Piyasa Yapıcı" modunu devre dışı bırakın.',
  'trade.max_gas_fee_tips':
    'Maksimum Gas Ücreti, ticaret işlemleri için zincir üstü maliyetleri kapsar, Piyasa Alıcılar tarafından ödenir ve Piyasa Yapıcılar için ücretsizdir. Artık ücretler iade edilir.',
  'trade.auto': 'Otomatik',
  'trade.custom': 'Özel',
  'trade.enough_for_XX_trades': 'XX işlem için yeterli',
  'trade.gas_fee_per_trade': 'İşlem başına Gas ücreti',
  'trade.gas_fee_per_trade_tips':
    'Piyasa Alıcılar, zincir üstü yerleşimi kolaylaştırmak için her işlem başına gas ücreti öder, maliyetler Ethereum ağının koşullarına bağlı olarak değişir.',
  'trade.max_number_of_trades': 'Maksimum işlem sayısı',
  'trade.btn_buy_ETH': 'ETH Satın Al',
  'trade.btn_sell_ETH': 'ETH Sat',
  'trade.max_buy_fee_deducted_NUM': 'Gas ücreti düşüldü. Maksimum NUM.',
  'trade.notification_limit_order_title': 'Limit Emri Verildi',
  'trade.notification_stop_limit_order_title': 'Stop Limit Emri Verildi',
  'trade.err_price': 'Lütfen fiyatı girin',
  'trade.err_amount_total': 'Lütfen miktarı veya toplamı girin',
  'trade.err_amount': 'Lütfen bir miktar girin',
  'trade.err_insufficientFee_title': 'Yetersiz Gas Ücreti',
  'trade.err_insufficientFee_desc':
    'Lütfen Maksimum Gas Ücreti ayarınızı ve DeGate Bakiyenizi kontrol edin.',
  'trade.cancel_order_success': 'Emir İptal Edildi',
  'trade.pair_favorite': 'Favori',
  'trade.pair_search': 'Token, kontrat adresi ara',
  'trade.pair_last_price': 'Fiyat',
  'trade.pair_change': 'Değişim',
  'trade.url_parse_err_title': 'Bu çift mevcut değil.',
  'trade.risk_tips': 'Risk Uyarısı',
  'trade.base_is_not_default_token_tips':
    'Ticaret öncesinde dolandırıcılıklardan kaçınmak için token kontrat adresini resmi kaynaklardan doğrulayın.',
  'trade.chain_cancel': 'Zincir Üzerinde Emri İptal Et',
  'trade.chain_cancel_no_need_tips': 'Bu emir zincir üstü iptal gerektirmez.',
  'trade.chain_cancel_success': 'İstek gönderildi',
  'trade.depth_empty': 'Henüz emir yok',
  'trade.depth_empty_asks': 'Satış emirleri yok',
  'trade.depth_empty_bids': 'Alım emirleri yok',
  'trade.depth_empty_tips':
    'Emir defterinde yeterli açık emir olmadığı için piyasa emri başarısız oldu',
  'trade.history_empty': 'Henüz ticaret yok',
  'trade.err_price_stable': 'Fiyat geçersiz oldu. Lütfen tekrar deneyin.',
  'trade.price_warning':
    'Girdiğiniz fiyat piyasa fiyatından sapmış, lütfen emir vermeden önce onaylayın',
  'trade.order_value_tips':
    "Minimum emir değeri <b>QUOTE_A</b> veya <b>BASE_A</b>, MINUSD USD'ye eşittir. Bu kısıtlamayı aşmak için piyasa emrini kullanın.",
  'trade.order_value_tips_quote':
    "Minimum emir değeri <b>QUOTE_A</b>, MINUSD USD'ye eşittir. Bu kısıtlamayı aşmak için piyasa emrini kullanın.",
  'trade.order_value_tips_stable_quote':
    'Minimum emir değeri <b>QUOTE_A</b>. Bu kısıtlamayı aşmak için piyasa emrini kullanın.',
  'trade.system_limit': 'Sistem sınırı aşıldı',
  'trade.stop_limit_untriggered_tips':
    'Emir emir defterine gönderilmedi çünkü durdurma fiyatına ulaşılmadı.',
  'trade.stop_limit_triggered_tips_TIME':
    'Emir şu saatte emir defterine gönderildi: TIME',
  'trade.flow_of_funds': 'fon akışı',
  'trade.flow_of_funds_tip2':
    'Emiriniz verildi. Emir fonları cüzdan bakiyeniz yerine DeGate Bakiyenize gidecek.',
  'orders.show_current_pair_orders': 'Diğer Çiftleri Gizle',
  'orders.orderHistory': 'Emir Geçmişi',
  'orders.th_time': 'Zaman',
  'orders.th_average_price': 'Ortalama Fiyat',
  'orders.th_stop_price': 'Durdurma Fiyatı',
  'orders.th_limit_price': 'Limit Fiyatı',
  'orders.th_filled_price': 'Fiyat',
  'orders.th_filled_amount': 'Doldurulan',
  'orders.th_filled_total': 'Toplam',
  'orders.th_trade_reconciliation': 'Uzlaştırma',
  'orders.th_trade_reconciliation_tips':
    'DeGate üzerinde eşleştirme ve zincir üzerindeki hesaplaşma için farklı hesaplama modelleri kullanıldığı için iki hesaplama sonucunda ufak farklılıklar olabilir. Bu durumda, sistem zincir üzerindeki değeri standart olarak alacak ve DeGate Bakiyesindeki eksiklikleri telafi edecektir.',
  'orders.hide_cancelled_expired_orders': 'İptal edilen/süresi dolanları gizle',
  'orders.status_open': 'Açık',
  'orders.status_pending': 'Beklemede',
  'orders.status_completed': 'Dolduruldu',
  'orders.status_completed_part': 'Kısmen Dolduruldu',
  'orders.status_expired': 'Süresi Doldu',
  'orders.detail_price': 'Ortalama/Fiyat',
  'orders.average_price': 'Ortalama Fiyat',
  'orders.detail_type': 'Emir Türü',
  'orders.detail_trade_fee': 'Ticaret Ücreti:',
  'orders.gas_preAuth': 'Maksimum Gas Ücreti:',
  'orders.fee_reconciliation': 'Uzlaştırma:',
  'orders.gas_paid': 'Ödenen Gas Ücreti:',
  'orders.gas': 'Gas Ücreti:',
  'orders.trades_N': 'İşlemler(N)',
  'orders.detail_filled_total': 'Toplam',
  'orders.detail_filled_detail': 'İşlem Detayları',
  'orders.detail_filled_time': 'Zaman',
  'orders.order_maker_free': 'Piyasa Yapıcı ücreti yok',
  'orders.openOrders_empty': 'Açık emir yok',
  'orders.export_orders_1_year': 'Son 1 yıla ait emir verilerini dışa aktar.',
  'orders.export_trades_1_year':
    'Son 1 yıla ait ticaret verilerini dışa aktar.',
  'orders.export_data': 'Verileri Dışa Aktar',
  'orders.export': 'Dışa Aktar',
  'orders.export_processing': 'İşleniyor. Lütfen bekleyin.',
  'orders.export_tips_100_percent':
    "İlerleme %100'e ulaştığında dosya indirilecek.",
  'orders.sign_to_view_balance': 'Bakiyeyi görüntülemek için imzala',
  'orders.sign_to_view_history': 'Geçmişi görüntülemek için imzala',
  'orders.sign_to_view_security_options':
    'Güvenlik seçeneklerini görüntülemek için imzala',
  'gridTrade.automatic_strategy': 'Otomatik',
  'gridTrade.manual_strategy': 'Manuel',
  'gridTrade.placeholder_amount': 'Bir miktar girin',
  'gridTrade.low_price': 'Alt Sınır',
  'gridTrade.high_price': 'Üst Sınır',
  'gridTrade.initial_investment': 'Yatırım',
  'gridTrade.grid_levels_tips':
    'Fiyat aralığındaki açık emir sayısını belirlemek için kullanılır.',
  'gridTrade.profit_per_grid': 'Grid Başına Kâr',
  'gridTrade.profit_per_grid_tips':
    'Grid Stratejisinin kârlılığı için önemli bir parametredir. Grid Başına Kâr = (Yüksek Fiyat - Düşük Fiyat) / Düşük Fiyat. Yüksek ve düşük fiyatlar, grid stratejisindeki iki bitişik grid hattının fiyatlarını ifade eder.',
  'gridTrade.min_grid_volume_XXX_ETH': 'Grid Başına Miktar: Min XXX ETH',
  'gridTrade.min_grid_volume_err':
    'Lütfen yatırımı artırın veya grid sayısını azaltın',
  'gridTrade.grid_no_depth_tips_BASE_QUOTE':
    'Bu çift için grid stratejisi oluşturulamaz çünkü emir defterinde yeterli emir yok.',
  'gridTrade.grid_to_spot_trade': "Spot'a Git",
  'gridTrade.grid_level_over_err': 'Lütfen grid sayısını azaltın',
  'gridTrade.grid_prices_err': 'Lütfen fiyat aralığını genişletin',
  'gridTrade.grid_create_err':
    'Lütfen parametreleri ayarlayın ve tekrar deneyin.',
  'gridTrade.tips_grid_profit':
    'Kârlar doğrudan DeGate Bakiyenize aktarılır ve hemen kullanılabilir.',
  'gridTrade.tips_grid_balance_0_BASE':
    'Piyasa fiyatındaki yükseliş, bu grid stratejisi altındaki tüm emirlerin alım emirlerine dönüşmesine neden oldu. Bu nedenle, mevcut BASE bakiyesi artık 0.',
  'gridTrade.tips_grid_balance_0_BASE_2':
    'Piyasa fiyatındaki yükseliş, bu grid stratejisi altındaki tüm emirlerin alım emirlerine dönüşmesine neden oldu. Ayrıca, bu emirlerin bazıları kısmen dolduruldu. Bu nedenle, mevcut BASE bakiyesi >0.',
  'gridTrade.tips_grid_balance_0_QUOTE':
    'Piyasa fiyatındaki düşüş, bu grid stratejisi altındaki tüm emirlerin satış emirlerine dönüşmesine neden oldu. Bu nedenle, mevcut QUOTE bakiyesi artık 0.',
  'gridTrade.tips_grid_balance_0_QUOTE_2':
    'Piyasa fiyatındaki düşüş, bu grid stratejisi altındaki tüm emirlerin satış emirlerine dönüşmesine neden oldu. Ayrıca, bu emirlerin bazıları kısmen dolduruldu. Bu nedenle, mevcut QUOTE bakiyesi >0.',
  'gridTrade.grid_param_err': 'Lütfen grid stratejisi parametrelerini girin',
  'gridTrade.tv_buy': 'Al',
  'gridTrade.tv_sell': 'Sat',
  'gridTrade.tv_waiting': 'bekliyor',
  'gridTrade.chain_cancel_no_need_tips':
    'Bu grid stratejisi için zincir üzerinde iptal gerekmez.',
  'gridTrade.grid_over_max_number_err':
    'Maksimum çalışan grid stratejisi sayısına ulaşıldı, yeni grid oluşturulamıyor.',
  'gridTrade.preview_orders_in_graph': 'Emirleri Göster',
  'gridTrade.greate_news': 'Harika haber:',
  'gridTrade.min_amount_required_XXX': 'Minimum XXX gerekli',
  'gridTrade.highest_grid_apy': 'En Yüksek Grid Yıllık Getiri Oranı',
  'gridTrade.for_the_last_7_days': 'Son 7 günde',
  'gridTrade.min_investment': 'Min. Yatırım',
  'gridTrade.grid_need_XXX': 'Grid için $XXX',
  'gridTrade.mining_need_XXX': 'Madencilik için $XXX',
  'gridTrade.recommended_params_cannot_be_applied':
    'Yetersiz yatırım nedeniyle önerilen parametreler uygulanamıyor. Manuel modda ayarlayabilirsiniz.',
  'gridTrade.copy_params_to_manual': 'Parametreleri Manuele Kopyala',
  'gridOrders.grid_recents': 'En Son İşlemlerim',
  'gridOrders.th_created_time': 'Oluşturulma Zamanı',
  'gridOrders.grid_profit': 'Grid Kârı',
  'gridOrders.grid_cancel': 'Bitiş',
  open_orders: 'Açık Emirler',
  'gridOrders.tab_history_orders': 'Doldurulan Emirler',
  'gridOrders.tab_trade_history': 'İşlem Geçmişi',
  'gridOrders.detail_current_balance': 'Mevcut Bakiye',
  'gridOrders.detail_ending_balance': 'Bakiye Bitişi',
  'gridOrders.detail_ending_balance_tips':
    'Grid stratejisi kapatıldığında varlık bakiyesi.',
  'gridOrders.detail_in_order_funds': 'Emirdeki Fonlar:',
  'gridOrders.detail_on_hold_funds':
    'Beklemedeki Fonlar (kısmen doldurulan emirlerden):',
  'gridOrders.detail_transactions': 'Doldurulan Emir Sayısı',
  'gridOrders.detail_investment': 'İlk Yatırım',
  'gridOrders.detail_running_time': 'Süre',
  'gridOrders.detail_prices': 'Fiyat Aralığı',
  number_of_grids: 'Grid Sayısı',
  'gridOrders.detail_expire_time': 'Süresi doluyor',
  'gridOrders.detail_expire_time_tooltip':
    'Bu grid stratejisi içindeki emirler, süresi dolduğunda iptal edilecektir.',
  'gridOrders.detail_valid_period': 'Sona Erme Ayarı',
  'gridOrders.open_orders_sell': 'SAT',
  'gridOrders.open_orders_buy': 'AL',
  'gridOrders.open_orders_index': '#',
  'gridOrders.open_orders_total': 'Toplam',
  'gridOrders.history_orders_filled': 'Doldurulan:',
  'gridOrders.history_orders_price': 'Fiyat:',
  'gridOrders.history_orders_time': 'Zaman',
  'gridOrders.history_orders_filled_price': 'Ortalama Fiyat',
  'gridOrders.history_orders_filled_amount': 'Doldurulan',
  'gridOrders.history_orders_filled_total': 'Toplam',
  'gridOrders.history_orders_profit_tips':
    "Kâr, düşük fiyattan alım ve yüksek fiyattan satım döngüsünden elde edilir. Örneğin, 1 ETH'yi 4000 USDC fiyatından satın almak için bir grid emri doldurulduktan sonra, grid aralığı 50 USDC ise sistem otomatik olarak 1 ETH'yi 4050 USDC fiyatından satmak için yeni bir emir verecektir. Bu emir de doldurulduğunda 50 USDC kâr elde edilecektir.",
  'gridOrders.history_orders_buy_flip_order_tips_PRICE':
    'PRICE fiyatındaki alım emri doldurulduktan sonra kâr gösterilecektir.',
  'gridOrders.history_orders_sell_flip_order_tips_PRICE':
    'PRICE fiyatındaki satış emri doldurulduktan sonra kâr gösterilecektir.',
  'gridOrders.m_history_orders_flip_order_tips_PRICE':
    'PRICE fiyatındaki emir doldurulduğunda burada görünecektir',
  'gridOrders.grid_cancel_title': 'Grid Stratejisini Sonlandır',
  'gridOrders.grid_cancel_content':
    'Bu grid stratejisindeki tüm emirler hemen iptal edilecektir.',
  'gridOrders.grid_cancel_content2':
    'Bu Grid Stratejisi ile madencilik yapıyorsunuz. Bu Grid Stratejisini sonlandırırsanız, tüm madencilik ödüllerinden vazgeçeceksiniz ve ilişkili tüm grid emirleri hemen iptal edilecektir.',
  'gridOrders.copy_grid_title':
    'Aşağıdaki grid stratejisi parametreleri kopyalanacak',
  'gridOrders.copy_grid_btn': 'Panoya Kopyala',
  'gridOrders.copy_grid_success': 'Grid Stratejisi Kopyalandı',
  'gridOrders.grid_init_funds_XXX': 'Başlangıç yatırımının değeri: $XXX',
  'gridOrders.grid_init_funds_tips':
    'Yıllık Getiri Oranları grid stratejisinin oluşturulma anındaki başlangıç tahsisi değerine göre hesaplanır.',
  'gridOrders.tab_m_trade': 'Ticaret',
  grid_apy: 'Grid Yıllık Getiri Oranı',
  grid_apy_tips:
    'Sadece grid ticareti ile elde edilen yıllık kâr oranı. Fiyat hareketindeki kâr hariç.',
  'gridOrders.tab_mining_profit': 'Madencilik Yıllık Getiri Oranı',
  'gridOrders.tab_mining_profit_tips':
    'Yıllık madencilik kârları, Grid Stratejisinin başlangıç değeri ve süresine göre hesaplanır.',
  'gridOrders.mining_rewards': 'Ödüller:',
  'gridOrders.open_orders_empty_tips': 'Veriler yüklenirken lütfen bekleyin',
  'gridOrders.market_value': 'Piyasa Değeri:',
  'gridOrders.market_value_details': 'Detaylar',
  'gridOrders.fund_details': 'Fon Detayları',
  'gridOrders.m_in_order_funds': 'Emirdeki Fonlar',
  'gridOrders.m_in_order_funds_tips':
    'Bu grid stratejisi altındaki tüm açık emirlerdeki toplam fonlar.',
  'gridOrders.m_on_hold_funds': 'Beklemedeki Fonlar',
  'gridOrders.m_on_hold_funds_tips': 'Kısmen doldurulan emirlerin sonucu.',
  'gridOrders.initial_value': 'Başlangıç Değeri',
  'mining.my_title': 'Madencilik Havuzum',
  'mining.index_desc':
    'Grid Stratejisi Oluşturun. Likidite madenciliği ödülleriyle grid kârınızı artırın.',
  'mining.apply': 'Yeni Havuz Başvurusu',
  'mining.claimable_rewards_box': 'Talep Edilebilir Ödüller',
  'mining.rewards_more': 've daha fazlası',
  'mining.tab_pools': 'Madencilik Havuzları',
  'mining.tab_my': 'Madencilik İstatistiklerim',
  'mining.pools_tab_live': 'Canlı',
  'mining.pools_tab_upcoming': 'Yaklaşan',
  'mining.pools_funds': 'Toplam Kilitli Değer (TVL)',
  'mining.pools_funds_tips':
    '$120 minimum emir değerini karşılayan grid emirlerinin toplam değeri.',
  'mining.pools_mining_funds': 'Madencilik TVL',
  'mining.mining_apr': 'Yıllık Getiri Oranı',
  'mining.mining_apr_tips':
    "Madencilik ödülleri ve madencilik TVL'sinden tahmini yıllık getiri oranı.",
  'mining.view_rule_link': 'Madencilik Kuralları',
  'mining.pools_info_to_confirm': 'Belirlenecek',
  'mining.pools_no_wait': 'Kullanılabilir madencilik havuzu yok',
  'mining.my_mining_funds': 'Madencilik Fonlarım',
  'mining.my_mining_rewards': 'Madencilik Ödüllerim',
  'mining.my_th_profit_token_price': 'Son Fiyat',
  'mining.my_th_total_rewards': 'Tüm Zamanların Ödülleri',
  'mining.my_th_24h_rewards': '24 saatlik Ödüller',
  'mining.my_grids': 'Madenciliğim',
  'mining.only_show_mining_grids': 'Yalnızca Aktif',
  'mining.my_th_mining_status': 'Madencilik Durumu',
  'mining.status_framing': 'Aktif',
  'mining.status_over_price': 'Fiyat Aralığının Dışında',
  'mining.status_mining_over': 'Madencilik Sona Erdi',
  'mining.status_grid_closed': 'Strateji Sona Erdi',
  'mining.status_grid_expired': 'Strateji Süresi Doldu',
  'mining.empty_no_faring_grids':
    'Şu anda madenciliği yapılabilecek grid stratejisi yok',
  'mining.go_mining_pool': 'Madencilik Havuzuna Git',
  'mining.go_mining': 'Madenciliği Başlat',
  'mining.go_to_grid': 'Grid Stratejisine Git',
  'mining.mining_help': 'Madencilik Kılavuzu',
  'mining.mining_available': 'Uygun',
  'mining.mining_available_tips': 'Emir değeri kriterleri karşılandı',
  'mining.mining_unavailable': 'Uygun Değil',
  'mining.mining_partially_available': 'Kısmen Uygun',
  'mining.mining_unavailable_tips': 'Emir değeri kriterleri karşılanmadı',
  'mining.mining_preview': 'Madencilik Önizlemesi',
  'mining.mining_total_profit': 'Madencilik Ödülleri',
  'mining.mining_24h_profit': '24 saatlik Madencilik Ödülleri',
  'mining.profit_unable_display': 'Yok',
  'mining.mining_funds': 'Madencilik Fonları',
  'mining.mining_funds_tips':
    'Bu ticaret çifti için madencilik emir değeri kriterlerini karşılayan tüm grid stratejilerinin toplam emir değeri.',
  'mining.tab_mining_profit_details': 'Ödül Detayları',
  'mining.tab_mining_orders': 'Madencilik Emirleri',
  'mining.th_rewards': 'Ödül',
  'mining.th_rewards_origin': 'Ödül Kaynağı',
  'mining.th_rewards_origin_tips':
    'Madencilik ödülü, grid emri fiyatı, emir defterinin ödül fiyat aralığında (en yüksek alım fiyatı * 0.99 ~ en düşük satış fiyatı * 1.01) olduğunda alınır.',
  'mining.th_rewards_origin_tips_stable':
    'Madencilik ödülü, grid emri fiyatı, emir defterinin ödül fiyat aralığında (en yüksek alım fiyatı ~ en düşük satış fiyatı) olduğunda alınır.',
  'mining.th_time': 'Zaman',
  'mining.plan_title': 'ETH/USDC Havuz Detayları',
  'mining.phase_cur': 'Mevcut Aşama',
  'mining.phase_range_N_XX': 'Aşama N (XX)',
  'mining.phase_index_N': 'Aşama N',
  'mining.phase_reward': 'Günlük Ödüller',
  'mining.phase_to_release': 'Duyurulacak',
  'mining.my_rewards': 'Ödüllerim',
  'mining.claimable_rewards': 'Kullanılabilir',
  'mining.locked_rewards': 'Kilitli',
  'mining.locker_rewards_tips':
    'Grid Stratejisi 12 saat aktif olduktan sonra madencilik ödülleri talep edilebilir.',
  'mining.claimed_success': 'Talep Başarılı',
  'mining.claimed_tips':
    'Kısa süre içinde iç transfer yoluyla size gönderilecektir',
  'mining.claimed_view_btn': 'Kontrol Et',
  'mining.mining_plan': 'Madencilik Programı',
  'mining.phase_unpublished': 'Duyurulacak',
  'mining.all_pools': 'Tüm Havuzlar',
  'notification.limit_desc_SELL_BASE_QUOTE_AMOUNT_PRICE':
    'AMOUNT BASE @ PRICE QUOTE miktarında Satış',
  'notification.limit_desc_BUY_BASE_QUOTE_AMOUNT_PRICE':
    'AMOUNT BASE @ PRICE QUOTE miktarında Alış',
  'notification.stop_limit_desc_SELL_BASE_AMOUNT': 'AMOUNT BASE Sat',
  'notification.stop_limit_desc_BUY_BASE_AMOUNT': 'AMOUNT BASE Al',
  'notification.cancel_grid_desc_PAIR_PRICES': 'ÇİFT: FİYATLAR',
  'notification.cancel_market_desc_SELL_BASE_QUOTE_AMOUNT':
    'QUOTE karşılığında AMOUNT BASE Sat',
  'notification.cancel_market_desc_SELL_BASE_QUOTE_TOTAL':
    'QUOTE karşılığında BASE Sat',
  'notification.cancel_market_desc_BUY_BASE_QUOTE_AMOUNT':
    'QUOTE karşılığında AMOUNT BASE Al',
  'notification.cancel_market_desc_BUY_BASE_QUOTE_TOTAL':
    'TOTAL QUOTE karşılığında BASE Al',
  'notification.cancel_limit': 'Limit emri iptal edildi',
  'notification.cancel_stop_limit': 'Stop limit emri iptal edildi',
  'notification.cancel_market': 'Piyasa emri iptal edildi',
  'notification.cancel_grid': 'Grid stratejisi sona erdi',
  'notification.cancel_limit_expired': 'Limit emrinin süresi doldu',
  'notification.cancel_stop_limit_expired': 'Stop limit emrinin süresi doldu',
  'notification.cancel_grid_expired': 'Grid stratejisinin süresi doldu',
  'notification.cancel_limit_order_for_gas_desc':
    'Emirinizin gas ücreti tükendi. Kısmen dolduruldu ve kalan iptal edildi.',
  'notification.cancel_limit_order_for_gas_filled_amount': 'Dolduruldu',
  'notification.cancel_limit_order_for_gas_amount': 'Miktar',
  'notification.view_history_orders': 'Emir Geçmişini Görüntüle',
  'notification.cancel_market_for_depth_title':
    'Emir Kısmen Dolduruldu ve İptal Edildi',
  'notification.price_slippage_protection': 'Fiyat Kayması Koruması',
  'notification.price_slippage_protection_desc':
    'DeGate piyasa emirleri, yüksek volatilite ve düşük likidite sırasında kayıpları sınırlamak için %10 fiyat kayması koruması içerir. Bu korumayı aşmak için limit emirlerini kullanın.',
  'notification.cancel_market_for_depth_warning':
    'DeGate piyasa emri, kullanıcılara yüksek fiyat oynaklığı ve düşük likidite durumlarında kayıpları azaltma imkânı sunan bir fiyat koruma mekanizması getiriyor. Fiyat koruma mekanizmasını tetiklemek istemiyorsanız, limit emir modunu kullanın.',
  'notification.dca_plan_ended': 'DCA planı sona erdi',
  'notification.cancel_dca_desc_PAIR': 'ÇİFT',
  'notification.trade_limit_partially': 'Limit emri kısmen dolduruldu',
  'notification.trade_limit_filled': 'Limit emri dolduruldu',
  'notification.trade_market_partially': 'Piyasa emri kısmen dolduruldu',
  'notification.trade_market_filled': 'Piyasa emri dolduruldu',
  'notification.trade_stop_limit_partially':
    'Stop limit emri kısmen dolduruldu',
  'notification.trade_stop_limit_filled': 'Stop limit emri dolduruldu',
  'notification.mobile_trade_filled_AMOUNT_TOKEN':
    'Emir dolduruldu. AMOUNT TOKEN alındı.',
  'notification.mobile_trade_partially_AMOUNT_TOKEN':
    'Emir kısmen dolduruldu. AMOUNT TOKEN alındı.',
  'info.overview': 'Genel Bakış',
  'info.accounts': 'Toplam Kullanıcı',
  'info.pairs': 'Ticaret Çiftleri',
  'info.turnover': 'Tüm Zamanların Hacmi',
  'info.turnover_24': '24 saatlik Hacim',
  'info.dg_supply': 'DG Dolaşımdaki Arz',
  'info.top_movers_no_increased': 'Son 24 saat içinde fiyatı artan token yok',
  'info.top_movers_no_decreased': 'Son 24 saat içinde fiyatı düşen token yok',
  'info.top_pairs': 'En İyi Çiftler',
  Pair: 'Çift',
  'info.th_change': '24 saatlik Değişim',
  'info.th_l_up_2': '+%2 Derinlik',
  'info.th_l_down_2': '-%2 Derinlik',
  'info.th_turnover_24': '24 saatlik Hacim',
  'info.tvl': 'Toplam Kilitli Değer',
  'm.home': 'Ana Sayfa',
  'm.grid': 'Grid',
  'm.browser_wallet': 'Tarayıcı Cüzdanı',
  'm.choose_pair': 'Çift Seç',
  'm.orderBook_default': 'Varsayılan',
  'm.orderBook_bids': 'Alım Emirleri',
  'm.orderBook_asks': 'Satış Emirleri',
  'm.decimals': 'Ondalık',
  'm.lowest_price_24h': '24 saatlik En Düşük',
  'm.highest_price_24h': '24 saatlik En Yüksek',
  'm.vol_24h': '24 saatlik Hacim',
  'm.orderbook_buy': 'Al',
  'm.orderbook_sell': 'Sat',
  'm.go_to_trade': 'Ticarete Git',
  'm.choose_token': 'Token Seç',
  'm.from_address': 'Gönderen Adresi',
  'm.to_address': 'Alıcı Adresi',
  'm.transfer_send': 'Gönder',
  'm.transfer_receive': 'Al',
  'm.my_grid': 'Grid Stratejim',
  'm.grid_profit_24': '24 saatlik Kâr',
  'm.grid_item_trades_24': '24 saatlik İşlemler',
  'm.grid_profit_total': 'Toplam Kâr',
  'm.grid_over_prices': 'Fiyat Aralığının Dışında',
  'm.create_grid': 'Grid Stratejisi Oluştur',
  'm.grid_history': 'Geçmiş',
  'm.grid_empty': 'Aktif grid stratejisi yok',
  'm.grid_tutorial': 'Grid Kılavuzu',
  'm.grid_params_to_manual': 'Parametreleri Manuele Kopyala',
  'm.balance_err': 'Yetersiz bakiye. Mevcut:',
  'm.preview_grid': 'Emirleri Önizle',
  last_price: 'Son Fiyat',
  'm.grid_desc':
    'Grid ticareti, tanımlanmış bir aralık içinde alım ve satımı otomatikleştiren bir ticaret stratejisidir.',
  'm.view_tutorial': 'Kılavuzu Görüntüle',
  'm.grid_profit_tips_sell':
    'Bu satış emri tamamen doldurulduğunda hesaplanacaktır.',
  'm.grid_profit_tips_buy':
    'Bu alım emri tamamen doldurulduğunda hesaplanacaktır.',
  'm.hot': 'Popüler',
  'm.all': 'Tümünü Görüntüle',
  'm.vol_24': '24 saatlik Hacim',
  'm.transfer_t1': 'Dahili',
  'm.transfer_t2': 'Transfer',
  'activity.th_date': 'Zaman',
  'activity.th_type': 'Tür',
  'activity.th_fee': 'Ücret',
  'activity.th_content': 'İçerik',
  'activity.type_register_token': 'Token Listeleme',
  'activity.type_register_pair': 'Çift Ekleme',
  'activity.type_pay_deposit': 'Mevduat Hesaplaşması',
  'activity.type_reset_account': 'Varlık Anahtarını Sıfırla',
  on_chain_order_cancellation: 'Zincir Üzerinde Emir İptali',
  'activity.count_N': 'Sayı: N',
  'activity.order_desc_SELL_AMOUNT_BASE_PRICE_QUOTE':
    'PRICE QUOTE FİYATINDA AMOUNT BASE SATIŞ',
  'activity.order_market_desc_SELL_AMOUNT_BASE': 'AMOUNT BASE SATIŞ',
  'activity.reset_status_restting': 'Sıfırlanıyor',
  'activity.to_trade': 'Ticaret',
  'dca.dca_plan': 'DCA Planı',
  'dca.dca_explain': 'Dolar Maliyet Ortalaması (DCA)',
  'dca.daily': 'Günlük',
  'dca.weekly': 'Haftalık',
  'dca.custom': 'Özel',
  'dca.every': 'Her',
  'dca.amount_per_order': 'Emir Başına Miktar',
  'dca.price_limit': 'Fiyat Limiti',
  'dca.maximum_price': 'Maksimum Fiyat',
  'dca.minimum_price': 'Minimum Fiyat',
  'dca.number_of_orders': 'Emir Sayısı',
  'dca.create_dca_plan': 'DCA Planı Oluştur',
  'dca.max_gas_fee_per_order': 'Emir Başına Maksimum Gas Ücreti',
  'dca.maximum_plan_order_limit_reached':
    'Plan emirlerinin maksimum sayısına ulaşıldı.',
  'dca.end_time_should_be_set_after_the_current_time':
    'Bitiş Zamanı şu andan sonra ayarlanmalıdır',
  'dca.please_enter_amount_per_order': 'Lütfen Emir Başına Miktar girin',
  'dca.please_enter_maximum_price': 'Lütfen Maksimum Fiyat girin',
  'dca.please_enter_minimum_price': 'Lütfen Minimum Fiyat girin',
  'dca.order_placement_failed_open_order_limit_exceeded':
    'Emir verme başarısız oldu: açık emir limiti aşıldı.',
  'dca.total': 'Toplam',
  'dca.filled': 'Dolduruldu',
  'dca.received': 'Alındı',
  'dca.time_to_end': 'Bitişe Kalan Zaman',
  'dca.cancel_on_chain': 'Zincir Üzerinde İptal',
  'dca.filled_amount': 'Doldurulan/Miktar',
  'dca.status_executed': 'Gerçekleştirildi',
  'dca.status_scheduled': 'Planlandı',
  'dca.status_failed': 'Başarısız',
  'dca.order_cancled_by_user':
    'Kullanıcı DCA planını sonlandırdığı için emir iptal edildi.',
  'dca.order_cancled_by_access':
    'DeGate erişiminiz kısıtlandığı için emir iptal edildi.',
  'dca.order_cancled_by_gas':
    'Yetersiz gas ücreti nedeniyle emir verme başarısız oldu.',
  'dca.order_cancled_by_order_book':
    'Emir defterinde eşleşen bir emir olmadığı için emir verme başarısız oldu.',
  'dca.order_cancled_by_balance':
    'Yetersiz DeGate Bakiyesi nedeniyle emir verme başarısız oldu.',
  'dca.order_cancled_by_min_value':
    '$100 minimum emir değeri karşılanmadığı için emir verme başarısız oldu.',
  'dca.order_cancled_by_system_error':
    'Sistem hatası nedeniyle emir verme başarısız oldu.',
  'dca.chain_cancel_no_need_tips':
    'Bu DCA planı için zincir üstü iptal gerekmez.',
  'dca.end_dca_plan': 'DCA Planını Sonlandır',
  'dca.all_orders_in_this_dca_plan_will_be_canceled_immediately':
    'Bu DCA planındaki tüm emirler hemen iptal edilecektir.',
  'dca.no_active_dca_plan': 'Aktif bir DCA Planı yok',
  'dca.time_scheduled': 'Planlanan Zaman',
  'campaign.event_period': 'Etkinlik Süresi:',
  'campaign.grid2401_time':
    '22 Ocak 2024, 20:00:00 - 29 Ocak 2024, 20:00:00 (UTC+8)',
  'campaign.event_has_ended': 'Etkinlik sona erdi.',
  'campaign.current_apy': 'Mevcut Yıllık Getiri Oranı (APY)',
  'campaign.grid_strategy_income':
    'Grid Stratejisi Geliri + Ödül Havuzundan Pay',
  'campaign.tvl_participating': 'Katılan TVL',
  'campaign.share_of_tvl': 'TVL Payı',
  'campaign.my_profit': 'Kârım',
  'campaign.grid_strategy_profit': 'Grid Stratejisi Kârı',
  'campaign.share_of_prize_pool': 'Ödül Havuzundan Pay',
  'campaign.grid_strategy_profit_has_been_added_to_your_available_balance':
    'Grid stratejisi kârı mevcut bakiyenize eklendi.',
  'campaign.shared_income_from_usdc_prize_pool':
    'USDC Ödül Havuzundan paylaşılan gelir',
  'campaign.is_black_tips': 'Ödül havuzundan pay almaya uygun değilsiniz.',
  'campaign.calculating': 'Hesaplanıyor',
  'campaign.claim_after_end': 'Ödül etkinlik sonunda talep edilebilir',
  'campaign.how_to_participate': 'Nasıl Katılabilirim',
  'campaign.rule':
    'Grid stratejisi oluşturun ve ödül havuzunda orantılı olarak pay alın.',
  'campaign.step1': 'Adım 1',
  'campaign.step2': 'Adım 2',
  'campaign.step3': 'Adım 3',
  'campaign.grid2401_step1':
    "ETH ve USDC'nizi fon ekleyerek veya ticaret yaparak hazır hale getirin",
  'campaign.grid2401_step2_PAIR':
    'Aşağıda belirtilen şekilde PAIR için bir grid stratejisi kurun',
  'campaign.grid2401_step2_desc1_pre': 'Fiyat aralığı: Duyurulacak',
  'campaign.grid2401_step2_desc2_pre': 'Grid sayısı: Duyurulacak',
  'campaign.copy_strategy': 'Stratejiyi kopyala',
  'campaign.grid2401_step3':
    'Etkinlik sona erdikten sonra kazançlarınızı bu etkinlik sayfasından talep edebilirsiniz. Lütfen etkinlik bitiminden itibaren 30 gün içinde talep edin.',
  'campaign.what_is_grid': 'Grid Stratejisi Nedir',
  'campaign.notes': 'Katılmadan önce lütfen not edin',
  'campaign.notes_1_title': 'Uygunluk:',
  'campaign.notes_1_desc':
    'Grid stratejisi, yalnızca oluşturulma anındaki fiyat aralığı ve grid sayısı tam olarak gerektiği gibi olduğunda uygundur.',
  'campaign.notes_2_title': 'Sınırlama:',
  'campaign.notes_3_title': 'Talep:',
  'campaign.notes_3_desc':
    'Ödül talebi, etkinlik sonunda kullanılabilir olacak ve etkinlik bitiminden itibaren 30 gün içinde geçerli olacaktır.',
  'campaign.faq': 'SSS',
  'campaign.grid2401_faq_1': '1. Ödüller nasıl hesaplanır?',
  'campaign.grid2401_faq_2':
    '2. Bu etkinlik hakkında sorularım için nereden yardım alabilirim?',
  'campaign.grid2401_faq_3':
    '3. USDT tutuyorum, nasıl ETH ve USDC elde edebilirim?',
  'campaign.grid2401_faq_4':
    '4. Grid stratejisi ile tamamlanan işlemler için ücret ödemem gerekiyor mu?',
  'campaign.grid2401_faq_4_res':
    "DeGate'te tüm Piyasa Yapıcı emirleri ücretsizdir. Grid stratejisi tarafından üretilen tüm emirler Piyasa Yapıcı emirleridir, bu nedenle DeGate'te bir grid stratejisi kurmak tamamen ücretsizdir.",
  'campaign.grid2401_faq_5':
    '5. Etkinlik bittikten sonra grid stratejim hala gelir sağlar mı?',
  'campaign.grid2401_faq_5_res':
    'Evet, etkinlik sona erdikten sonra, fiyat grid stratejinizin aralığında kaldığı sürece strateji gelir sağlamaya devam edecektir. Etkinlikten sonra, grid stratejinizin parametrelerini de ayarlayabilir, kendi tercihleriniz doğrultusunda daha uygun bir strateji oluşturabilir ve gelir elde etmeye devam edebilirsiniz.',
  'campaign.grid2401_faq_others': 'Diğer etkinlik detayları',
  'campaign.grid2401_faq_others_1':
    '1. Her kullanıcı için yalnızca bir cüzdan. Kötü niyetli sybil ödül farmı tespit edilirse, DeGate katılımcının ödüllerini iptal etme hakkını saklı tutar.',
  'campaign.grid2401_faq_others_2':
    '2. Etkinlik sırasında, aralığın dışındaki gridler de ağırlık hesaplamasına dahil edilecektir.',
  'campaign.grid2401_faq_others_3':
    '3. DeGate, aşırı durumlarda, örneğin piyasa oynaklığı durumunda, etkinliği erken bitirme hakkını saklı tutar.',
  'campaign.grid2401_faq_others_4':
    '4. Etkinlik sona erdikten sonra 30 gün içinde talep edilmeyen ödüller iptal edilecektir.',
  'campaign.invest_max_5000': 'Maksimum $5000 Yatırım Yapın',
  'campaign.invest_mininum': 'Minimum Yatırım',
  'airdrop.create_airdrop': 'Airdrop Oluştur',
  'airdrop.important_note': 'Önemli: Herkes izin almadan airdrop oluşturabilir',
  'airdrop.my_airdrop': 'Airdroplarım',
  'airdrop.time_limited': 'Süre sınırlı',
  'airdrop.no_airdrop': 'Henüz airdrop yok',
  'airdrop.claim_airdrop': 'Airdrop Talep Et',
  'airdrop.recipients_number': 'Alıcı Sayısı',
  'airdrop.total_amount': 'Toplam Miktar',
  'airdrop.retrieve': 'Geri Al',
  'airdrop.unclaimed': 'Talep Edilmemiş',
  'airdrop.retrieve_successful': 'Başarıyla Geri Alındı',
  'airdrop.claim_successful': 'Başarıyla Talep Edildi',
  'airdrop.retrieve_unclaimed_airdrop': "Talep Edilmemiş Airdrop'u Geri Al",
  'airdrop.airdrop_token': 'Airdrop Tokeni',
  'airdrop.token_not_meet_criteria': 'Bu token, airdrop kriterlerine uymuyor',
  'airdrop.airdrop_list': 'Airdrop Listesi',
  'airdrop.download_template': 'Şablonu İndir',
  'airdrop.click_or_drag_upload_list':
    'Listeyi yüklemek için tıklayın veya sürükleyin',
  'airdrop.validation_passed': 'Doğrulandı',
  'airdrop.must_earlier_than_end_time': 'Bitiş saatinden önce olmalıdır',
  'airdrop.cannot_more_than_2_years_from_now':
    'Şu andan itibaren 2 yıldan fazla olamaz',
  'airdrop.cannot_parse_file': 'Dosya işlenemiyor. Lütfen şablonu kullanın.',
  'airdrop.format_requirement_not_met': 'Format gereksinimi karşılanmadı',
  'airdrop.view_error_repost': 'Hata Raporunu Görüntüle',
  'airdrop.error_report': 'Hata Raporu',
  'airdrop.line': 'Satır',
  'airdrop.reason': 'Sebep',
  'airdrop.duplicated_address': 'Yinelenen adres',
  incorrect_address_format: 'Hatalı adres formatı',
  'airdrop.incorrect_amount_format': 'Hatalı miktar formatı',
  'airdrop.airdrop_plan_created': 'Airdrop planı oluşturuldu',
  'airdrop.max_50000': 'Maksimum 50000 adres',
  'airdrop.upload_file_rule': 'Sadece CSV desteklenir.',
  'airdrop.to_check_airdrop_eligibility':
    'Airdropları görüntülemek için başlatmayı tamamlayın',
  'airdrop.complete_initialization_to_claim_airdrops':
    'Airdropları talep etmek için başlatmayı tamamlayın',
  'airdrop.complete_initialization_to_view_airdrops':
    'Airdropları görüntülemek için başlatmayı tamamlayın',
  'airdrop.you_are_eligible_for': 'Şunlara uygunsunuz:',
  'airdrop.and_more': 've daha fazlası',
  'airdrop.congratulations': 'Tebrikler!',
  'airdrop.airdrop_fee': 'Airdrop Ücreti',
  'countdown.countdown_plan': 'Geri Sayım Planı',
  'countdown.create_countdown_plan': 'Geri Sayım Oluştur',
  'countdown.my_countdown_plan': 'Oluşturduklarım',
  'countdown.countdown_trading_pair': 'Geri Sayım Ticaret Çifti',
  'countdown.countdown_display': 'Geri Sayım Görünümü',
  'countdown.token_not_meet_criteria':
    'Bu token geri sayım kriterlerine uymuyor',
  'countdown.countdown_tips':
    'Geri sayım, seçilen ticaret çiftleri için ticaret sayfasında görüntülenecektir',
  'countdown.max_30_days': 'Şu andan itibaren 30 günden fazla olamaz',
  'countdown.review_countdown_plan': 'Geri Sayım Planını İncele',
  'countdown.countdown_fee': 'Geri Sayım Ücreti',
  'countdown.countdown_plan_created': 'Geri sayım planı oluşturuldu',
  'countdown.trading_will_start_in': 'Ticaret şu zamanda başlayacak',
  'countdown.trading_will_start_at_YYYY': "Ticaret YYYY'de başlayacak",
  'countdown.cannot_earlier_than_current_time': 'Şu andan önce olamaz',
  'dca.price_limit_buy_tips':
    'Etkinleştirildiğinde, alım emirleriniz yalnızca maksimum fiyat veya altında gerçekleştirilecektir. Bu işlev, Sıfır Ücret özelliği ile uyumludur.',
  'dca.price_limit_sell_tips':
    'Etkinleştirildiğinde, satış emirleriniz yalnızca minimum fiyat veya üzerinde gerçekleştirilecektir. Bu işlev, Sıfır Ücret özelliği ile uyumludur.',
  'dca.zero_fee': 'Sıfır Ücret',
  'dca.zero_fee_buy_tips':
    'Sıfır Ücret etkinleştirildiğinde, DCA emirleri yalnızca Piyasa Yapıcı modunda limit emirleri olarak işlenecektir. Her alım fiyatı, yerleştirildikten sonra emir defterindeki en yüksek teklif fiyatı olarak ayarlanacaktır. Emirlerinizin hemen doldurulmayabileceğini veya hiç doldurulamayabileceğini unutmayın.',
  'dca.zero_fee_sell_tips':
    'Sıfır Ücret etkinleştirildiğinde, DCA emirleri yalnızca Piyasa Yapıcı modunda limit emirleri olarak işlenecektir. Her satış fiyatı, yerleştirildikten sonra emir defterindeki en düşük satış fiyatı olarak ayarlanacaktır. Emirlerinizin hemen doldurulmayabileceğini veya hiç doldurulamayabileceğini unutmayın.',
  'dca.order_canceled_post_only_buy_failed':
    'Alım emrinizin fiyatının belirlenmesi durdu çünkü emir defterinde alım emri yok.',
  'dca.order_canceled_post_only_sell_failed':
    'Satış emrinizin fiyatının belirlenmesi durdu çünkü emir defterinde satış emri yok.',
  start_time_cannot_before_current_time:
    'Başlangıç zamanı şu andan önce olamaz',
  start_time_must_before_end_time:
    'Başlangıç zamanı, bitiş zamanından önce olmalıdır',
  list_token: 'Token Listele',
  contract_address_does_not_exist: 'Kontrat adresi mevcut değil',
  token_listed: 'Bu token listelendi',
  XXX_is_listed: 'XXX listeleniyor',
  view_progress: 'İlerlemeyi görüntüle',
  pair_create_tips:
    "Ticaret çiftleri DeGate'te herhangi bir onay gerektirmeden anında eklenebilir.",
  base_token: 'Ana Token',
  quote_token: 'Teklif Tokeni',
  existing_pair: 'Mevcut çift',
  trade_now: 'Şimdi Ticaret Yap',
  pair_XXX_added_successfully: 'XXX başarıyla eklendi',
  qty_per_grid: 'Grid Başına Miktar',
  grid_minimum_not_reached: 'Minimum karşılanmadı',
  total_profit: 'Toplam Kâr',
  total_apy: 'Toplam APY',
  float_profit: 'Yüzer Kâr',
  grid_profit_24h: '24 saatlik Grid Kârı',
  pnl: 'PnL (Kar/Zarar)',
  eligibility: 'Uygunluk',
  rewards: 'Ödüller',
  view_mining_statistics: 'Madencilik İstatistiklerini Görüntüle',
  your_entry: 'Fon girişi',
  refunded: 'İade Edildi',
  large_price_spread: 'Büyük Fiyat Farkı',
  large_price_spread_tips:
    'Emir defteri, en düşük satış ve en yüksek alım fiyatları arasında büyük bir fark gösteriyor, bu da kayıp riskini artırıyor. İkili Varlık modunda yatırım yapmanız önerilir.',
  continue_anyway: 'Yine de Devam Et',
  insufficient_order_book_liquidity_decrease_investment:
    'Yetersiz emir defteri likiditesi. Yatırımı azaltın.',
  initial_buy: 'İlk Alım',
  closing_sell: 'Son Satış',
  No: 'Hayır',
  DCA_TRIGGER_FAIL_TIPS_PRICE_XXX:
    "DCA emirleri, <b>$XXX fiyatı $PRICE'ın altına düşerse</b> başarısız olur.",
  zero_fee: 'Sıfır Ücret',
  minimum_order_value_is_VALUE: 'Minimum emir değeri <b>$VALUE</b>.',
  Note: 'Not',
  Continue: 'Devam Et',
  estimated_apy: 'Tahmini APY',
  based_on_data_from_last_7_days: 'Son 7 günün verilerine dayanmaktadır',
  top_gainers_24h: '24 saatlik En Yüksek Kazananlar',
  top_losers_24h: '24 saatlik En Büyük Kaybedenler',
  listed_tokens: 'Listelenen Tokenler',
  vol: 'Hacim',
  let_s_go: 'Hadi Gidelim',
  reject: 'Reddet',
  maximum_N_due_to_price_ticks: 'Fiyat kademeleri nedeniyle maksimum N',
  Saved: 'Kaydedildi',
  minimum_order_value_$100_$QUOTE: 'Minimum emir değeri <b>$100 $QUOTE</b>',
  minimum_order_value_$AMOUNT_$QUOTE_$100:
    'Minimum emir değeri <b>$AMOUNT $QUOTE</b>(~$$100)',
  no_restriction_with_market_order: '<b>piyasa emri</b> ile kısıtlama yok',
  go_to_market_order: 'Piyasa Emrine Git',
  Mining_Eligibility: 'Madencilik Uygunluğu',
  How_to_earn_mining_rewards: 'Madencilik ödüllerini nasıl kazanabilirim',
  Order_Value: 'EMİR DEĞERİ',
  'mining.mining_tips_BV_BASE_QV_QUOTE':
    'Grid emirleri, strateji oluşturulurken en az <b>BV BASE</b> veya <b>QV QUOTE</b> olmalıdır.',
  'mining.mining_tips_QV_QUOTE':
    'Grid emirleri, strateji oluşturulurken en az <b>QV QUOTE</b> olmalıdır.',
  Mining_Price_Range: 'MADENCİLİK FİYAT ARALIĞI',
  'mining.status_over_price_tips':
    'Grid emir fiyatları, emir defterindeki en yüksek alım fiyatı * 0.99 ile en düşük satış fiyatı * 1.01 arasındaki <b>madencilik fiyat aralığı</b> içinde olmalıdır.',
  'mining.status_over_price_tips_stable':
    'Grid emir fiyatları, emir defterindeki en yüksek alım fiyatı ile en düşük satış fiyatı arasındaki <b>madencilik fiyat aralığı</b> içinde olmalıdır.',
  Eligible_for_Mining: 'Madencilik İçin Uygun',
  Mining_Satus: 'Madencilik Durumu',
  Mining_Satus_Mining: 'Madencilik',
  Mining_Satus_Standby: 'Beklemede',
  Mining_Satus_Ineligible: 'Uygun Değil',
  mining_price_range: 'Madencilik Fiyat Aralığı',
  rewards_tips_stable:
    'Strateji oluşturulurken madencilik emir değeri kriterlerini karşılayan grid emirleri, madencilik fiyat aralığına (en yüksek alım fiyatı ~ en düşük satış fiyatı) düştüklerinde madencilik ödülleri kazanacaktır.',
  rewards_tips:
    'Strateji oluşturulurken madencilik emir değeri kriterlerini karşılayan grid emirleri, madencilik fiyat aralığına (en yüksek alım fiyatı * 0.99 ~ en düşük satış fiyatı * 1.01) düştüklerinde madencilik ödülleri kazanacaktır.',
  wrap: 'sar (wrap)',
  Wrap: 'Sar (Wrap)',
  websites_for_more_information: 'Daha fazla bilgi için web siteleri:',
  official_site: 'Resmi Site',
  wrap_site: 'Sarma/Açma (Wrap/Unwrap) Sitesi',
  tips_third_party_site:
    "DeGate'ten çıkıp üçüncü parti bir siteye girmek üzeresiniz:",
  wrap_unwrap: 'Sarma/Açma (Wrap/Unwrap)',
  Receive: 'Al',
  Network: 'Ağ',
  Token_Contract: 'Token Kontratı',
  please_select_network: 'Lütfen ağ seçin',
  maximum_amount: 'Maksimum Miktar',
  send_USDC_to_this_address: 'Bu adrese USDC gönderin',
  arpa_airdrop: '$ARPA Airdrop',
  Failed_to_proceed: 'İşleme devam edilemedi.',
  Please_select_the_Ethereum_network: 'Lütfen Ethereum ağını seçin.',
  NATIVE_USDC_ONLY: 'Yalnızca Yerel USDC token',
  NEVER_send_bridged_USDC: 'ASLA köprülenmiş USDC göndermeyin',
  I_understand: 'Anladım',
  recipient_address: 'Alıcı Adresi',
  chain_0: 'DeGate',
  chain_1: 'Ethereum',
  chain_17000: 'Ethereum',
  chain_42: 'Kovan',
  chain_42161: 'Arbitrum',
  chain_421614: 'Arbitrum',
  chain_10: 'Optimism',
  chain_11155420: 'Optimism',
  chain_137: 'Polygon',
  chain_80002: 'Polygon',
  scan_1: 'Etherscan',
  scan_17000: 'Etherscan',
  scan_42161: 'Arbiscan',
  scan_421614: 'Arbiscan',
  scan_10: 'Opscan',
  scan_11155420: 'Opscan',
  scan_tips:
    "Bu işlemi içeren rollup işlemi henüz Ethereum'a gönderilmedi. Gönderilene kadar, DGSCAN bu işlemi <b>GÖSTERMİYOR</b>.",
  Best_Liquidity: 'En İyi Likidite',
  order_partially_filled: 'Emir Kısmen Dolduruldu',
  order_partially_filled_for_liquidity:
    'Emir defterindeki likidite düşüşü nedeniyle kalan emriniz iptal edildi. Bu koruma önlemi, olumsuz fiyatlarla dolumu önler.',
  'orders.export_data_2_year': 'Son 2 yılın verilerini dışa aktar',
  Community: 'Topluluk',
  complete_in_seconds: 'Saniyeler içinde tamamlayın',
  failed_to_send: 'Gönderilemedi. Lütfen tekrar deneyin.',
  failed_to_send_try_other_networks:
    'Gönderilemedi. Lütfen diğer ağları deneyin.',
  gas_fee_deducted: 'Gas ücreti düşüldü:',
  sum_XXX: 'Toplam XXX',
  chart_control_7d: '7G',
  chart_control_30d: '30G',
  chart_control_all: 'tümü',
  chart_control_day: 'G',
  chart_control_week: 'H',
  chart_control_month: 'A',
  Coming: 'Yakında',
  leave_survey_title: "Hey, DeGate'ten çıkıyorsun gibi görünüyor.",
  leave_survey_subtitle:
    'Lütfen geri bildiriminizle bize daha iyi olmamızda yardımcı olun. Uygun olan tüm seçenekleri seçin.',
  leave_survey_not_leaving: 'Ayrılmıyorum, geri döneceğim seni komik şey.',
  leave_survey_other_is_fine:
    'Binance/OKX/Kraken vb. benim için gayet iyi çalışıyor.',
  leave_survey_bad_experience: 'Ticaret deneyimini beğenmedim.',
  leave_survey_no_yield: 'Getiri fırsatları bulamadım.',
  leave_survey_no_needed_token: 'Ticaret yapmak istediğim tokenleri bulamadım.',
  leave_survey_other_reason: 'Diğerleri (lütfen aşağıdaki kutuda belirtin)',
  leave_survey_thanks_for_feedback: 'Geri bildiriminiz için teşekkürler',
  Submitted: 'Gönderildi',
  doc_title:
    'DeGate: Merkeziyetsiz Emir Defteri Borsası | GRID ve DCA Üzerinde Ücretsiz Kripto Ticaret Botu',
  doc_desc:
    'DeGate, yüzlerce kripto para için düşük ücretli ticaret sunan, ücretsiz limit emir ticareti, grid ticareti ve DCA botlarına sahip en iyi merkeziyetsiz emir defteri borsasıdır.',
  doc_title_spot: '| Merkeziyetsiz Emir Defteri | DeGate DEX',
  doc_title_grid: '| Merkeziyetsiz Grid Ticaret Botu | DeGate DEX',
  doc_title_dca: '| Merkeziyetsiz DCA Ticaret Botu | DeGate DEX',

  Notification: '',
  read_all: '',
  important: '',
  general: '',
  view_more: '',
  thats_all: '',
  XXX_fund_addition_processing: '',
  add_AMOUNT_XXX_to_DeGate: '',
  XXX_fund_addition_successful: '',
  XXX_send_successful: '',
  send_AMOUNT_XXX_to_DeGate: '',
  send_AMOUNT_XXX_to_Ethereum: '',
  you_have_received_a_new_airdrop: '',
  AMOUNT_XXX_can_be_claimed_after_YYYY_MM_DD: '',
  MARKET_Chart: '',
  grid_free: '',
  maker_free_tips: '',
  Audit: '',
  Tool: '',
  About: '',
};
export default en;
