const uk = {
  language: 'ukr-UKR',
  'kline.time_Line': 'Час',
  'kline.time_1m': '1хв',
  'kline.time_3m': '3хв',
  'kline.time_5m': '5хв',
  'kline.time_15m': '15хв',
  'kline.time_30m': '30хв',
  'kline.time_1H': '1Г',
  'kline.time_2H': '2Г',
  'kline.time_4H': '4Г',
  'kline.time_6H': '6Г',
  'kline.time_1D': '1Д',
  'kline.time_1W': '1Т',
  'kline.time_1M': '1М',
  'kline.tab_line': 'Графік',
  'kline.tab_depth': 'Глибина',
  'kline.chartType_Bars': 'Бари',
  'kline.chartType_Candles': 'Свічки',
  'kline.chartType_Hollow_Candles': 'Порожні свічки',
  'kline.chartType_Line': 'Лінія',
  'kline.chartType_Area': 'Область',
  'kline.chartType_Heikin_Ashi': 'Хейкен Аші',
  degate_account: 'DeGate аккаунт',
  Trade: 'Торгівля',
  Order: 'Ордер',
  Grid: 'Сіткова Grid стратегія',
  Campaign: 'Кампанія',
  DCA: 'DCA',
  Advanced: 'Продвинута',
  Add: 'Додати',
  Add_Funds: 'Додати кошти',
  eth_added_1: '1 ETH додано',
  eth_sent_1: '1 ETH відправлено',
  Send: 'Відправити',
  Internal_Transfer: 'Внутрішній переказ',
  Miscellaneous: 'Різне',
  Bridge: 'Міст',
  Mining: 'Майнінг',
  Liquidity_Mining: 'Майнінг ліквидності',
  Analytics: 'Аналітика',
  Support: 'Підтримка',
  Help: 'Допомога',
  Tips: 'Порада',
  Statistics: 'Статистика',
  Coming_soon: 'Скоро',
  Faucet: 'Кран',
  more: 'Більше',
  hide: 'Сховати',
  change: 'Змінити',
  'Wrong Network': 'Невірна мережа',
  avbl: 'Доступно:',
  insufficient_balance_AAA:
    'У вашому гаманці недостатньо AAA. Будь ласка, перевірте і спробуйте ще раз.',
  insufficient_balance: 'Недостатній баланс',
  wallet_denied_sign: 'Підпис повідомлення було відхилено.',
  common_err: 'Щось пішло не так. Будь ласка, спробуйте пізніше.',
  common_err_ledger_version:
    'Виникла помилка. Будь ласка, переконайтесь, що ваш додаток Ledger Ethereum оновлений (1.9.10 або новіший), або спробуйте ще раз пізніше.',
  network_1: 'Головна мережа Ethereum',
  network_err: 'Помилка мережі. Будь ласка, спробуйте пізніше.',
  rate_limit_err:
    'Частота доступу занадто висока, будь ласка, повторіть через хвилину.',
  error_InsufficientGasFunds: 'Недостатньо газу у гаманці',
  notification_transaction_send: 'Транзакцію надіслано',
  view_on_etherscan: 'Переглянути в Blockchain Explorer',
  view_on_explorer: 'Переглянути адресу',
  switch_network: 'Перемкнути мережу',
  switch_to_Arbitrum: 'Перемкніться на Arbitrum, щоб продовжити.',
  switch_to_MAINNET_in_metamask:
    'Будь ласка, перемкніться на MAINNET у MetaMask',
  switch_to_MAINNET: 'Будь ласка, перемкніться на MAINNET',
  switch_network_in_walletconnect:
    'Перейдіть до гаманця і перемкніть мережу з WalletConnect',
  Retry: 'Повторити',
  wallet_tips: 'Будь ласка, підтвердіть у браузерному гаманці',
  wallet_ledger_tips: 'Будь ласка, підтвердіть у апаратному гаманці Ledger',
  wallet_metamask_tips: 'Будь ласка, підтвердіть у MetaMask',
  wallet_walletconnect_tips:
    'Перейдіть до гаманця для підтвердження через WalletConnect',
  wallet_cancelled_tips: 'Ви скасували підпис',
  Close: 'Закрити',
  copied: 'Скопійовано',
  Details: 'Деталі',
  view_details: 'Переглянути деталі',
  Share: 'Поділитися',
  view_graph: 'Переглянути на графіку',
  Dismiss: 'Закрити',
  Cancel: 'Скасувати',
  End: 'Завершити',
  End_grid: 'Завершити',
  Confirm: 'Підтвердити',
  Cancel_all: 'Скасувати всі',
  cancel_all_tips: 'Скасувати всі відкриті ордери',
  Submit: 'Надіслати',
  no_data: 'Немає даних',
  all_data_displayed: 'Усі дані показано',
  no_data_within_90_days: 'Дані за останні 90 днів відсутні',
  only_display_90_days: 'Показуються дані лише за останні 90 днів',
  displayed_90_days: 'Показуються дані за останні 90 днів',
  only_data_beyond_90_days_trade:
    'Для доступу до даних за період понад 90 днів виберіть ""Переглянути всі"", а потім функцію ""Експорт даних"',
  only_data_beyond_90_days_grid_detail:
    'Запит історичних даних понад останні 90 днів наразі не підтримується',
  only_data_beyond_90_days_spot_history:
    'Для доступу до даних понад 90 днів скористайтесь функцією ""Експорт даних"',
  View: 'Переглянути',
  service_unavailable_for_region_REGION: 'Ця послуга недоступна в РЕГІОНІ.',
  service_unavailable: 'Послуга недоступна',
  service_error: 'Будь ласка, спробуйте ще раз пізніше',
  service_maintenance: 'Ця послуга наразі проходить технічне обслуговування.',
  connect_wallet: 'Підключити гаманець',
  switch_address: 'Змінити адресу',
  wallet_wc: 'Підключено через WalletConnect',
  wallet_ledger: 'Підключено через Ledger',
  register_dexAccount: 'Реєстрація',
  deposit_ETH: 'Додати ETH',
  initialize: 'Ініціалізувати',
  initialization: 'Ініціалізація',
  invalid_signature: 'Невірний підпис',
  possible_cause: 'Можлива причина:',
  locale_time_error: 'Час на вашому пристрої неправильний.',
  authorization_mode: 'Режим автентифікації',
  authorization_mode_standard: 'Без підпису',
  authorization_mode_single_use: 'Завжди підписувати',
  turn_on: 'Увімкнути',
  turn_on_signature_free_mode: 'Увімкнути режим Без підпису',
  signatre_free_mode: 'Режим Без підпису',
  turn_on_signature_free_mode_tips:
    'У цьому режимі ви можете розміщувати ордери без підпису. Щоб змінити режим, перейдіть у ""Налаштування"" під кнопкою ""Торгівля"".',
  turn_on_signature_free_mode_tips_grid:
    'У цьому режимі ви можете створювати стратегії Grid сітки без підпису. Щоб змінити режим, перейдіть у ""Налаштування"" під кнопкою ""Торгівля"".',
  turn_on_signature_free_mode_tips_dca:
    'У цьому режимі ви можете створювати плани DCA без підпису. Щоб змінити режим, перейдіть у ""Налаштування"" під кнопкою ""Торгівля"".',
  yes: 'Так',
  no: 'Ні',
  free_mode_on: 'Режим Без підпису увімкнено',
  view_balance: 'Переглянути баланс',
  delete_asset_key: 'Видалити ключ активу',
  delete_asset_key_desc:
    'Режим Без підпису буде вимкнено після видалення ключа активу з вашого браузера.',
  no_asset_key_tips: 'Ключ активу не знайдено у вашому браузері',
  turn_off_standard_mode: 'І вимкнути режим Без підпису',
  reset_asset_key: 'Скинути ключ активу',
  view_asset_key: 'Переглянути ключ активу',
  lock_success: 'Ключ активу видалено',
  reset: 'Скинути ключ активу',
  delete: 'Видалити',
  withdraw_ETH: 'Надіслати ETH',
  transfer_ETH: 'Внутрішній переказ ETH',
  history: 'Історія',
  view_history: 'Переглянути в історії',
  internal_transfer: 'Переклад',
  assets_record_link: 'Історія',
  other: 'Інше',
  login_success: 'Успішне підключення',
  Account: 'Обліковий запис',
  Address: 'Адреса',
  Disconnect: 'Відключитися',
  copy_address: 'Скопіювати адресу',
  copy_grid: 'Скопіювати стратегію',
  Copy: 'Копіювати',
  btn_search: 'Пошук',
  btn_reset: 'Скинути',
  btn_confirm: 'Закрити',
  btn_max: 'Макс',
  btn_ok: 'ОК',
  spot_trade: 'СПОТ',
  grid_trade: 'GRID',
  err_balance_title: 'Помилка при розміщенні ордера',
  err_balance_content:
    'Недостатньо доступного балансу. Будь ласка, перевірте і спробуйте ще раз.',
  order_failed: 'Помилка ордера',
  insufficient_order_value: 'Недостатня вартість ордера',
  grid_failed: 'Створення не вдалося',
  err_eth_gas: 'Мережа Ethereum сильно перевантажена',
  err_insufficient_balance_TOKEN1: 'Недостатньо балансу TOKEN1',
  err_insufficient_balance_TOKEN1_TOKEN2:
    'Недостатньо балансів TOKEN1 і TOKEN2',
  please_add_funds_before_ordering:
    'Будь ласка, додайте кошти на баланс DeGate перед розміщенням ордера.',
  err_balance_content_spot:
    'Помилка розміщення ордера через недостатній баланс.',
  err_balance_content_grid:
    'Помилка створення стратегії Grid сітки через недостатній баланс.',
  trade_min_volume_tips_XXX: 'Мін XXX',
  grid_min_volume_tips:
    'Кількість на ордер не відповідає мінімальній сумі. Будь ласка, спробуйте ще раз.',
  trade_risk_orders_tips:
    'Неможливо розмістити ордер, оскільки у вас занадто багато відкритих ордерів',
  gas_token_tips: 'Виберіть токен для комісії за газ',
  add_favorite_tooltip: 'Додати в обране',
  remove_favorite_tooltip: 'Видалити з обраного',
  expire_tips_X: 'Цей ордер закінчується X.',
  today: 'Зараз',
  now: 'Зараз',
  time_D_day: 'Дд',
  time_D_day_H_hour: 'Дд Гг',
  time_H_hour_M_minute: 'Гг Хх',
  time_M_minute_S_second: 'Хх Сс',
  time_S_second: 'Сс',
  around: '～',
  time_now: 'зараз',
  time_before: '',
  time_before_ago: 'тому',
  time_1_minute: '1 хвилина',
  time_1_hour: '1 година',
  time_1_day: '1 день',
  time_1_year: '1 рік',
  time_M_minutes: 'М хвилин',
  time_M_m: 'Хх',
  time_H_hours: 'Г годин',
  time_H_h: 'Гг',
  time_D_days: 'Д днів',
  time_Y_years: 'Р років',
  time_Y_y: 'Рр',
  fee_change_tips: 'Ціна оновлена',
  no_pairs: 'Торгова пара не знайдена',
  register_new_pair: 'Додати нову пару',
  register_pair: 'Додати торгову пару',
  add_pair: 'Додати пару',
  tips_hide_forever: 'Більше не показувати',
  token: 'Токен',
  action: 'Дія',
  more_actions: 'Більше',
  gas_fee: 'Комісія за газ',
  'orders.detail_gas': 'Фактична комісія за газ',
  trade_fee: 'Торгова комісія',
  about_degate: 'Про DeGate',
  metrics: 'Показники',
  fees: 'Комісії',
  document: 'Документи',
  join_us: 'Приєднуйтесь до нас',
  feedback: 'Відгук',
  email_optional: 'Ваша електронна адреса (необов’язково)',
  Upload: 'Завантажити',
  feedback_upload_tip:
    'Поділіться своїми відгуками. Перетягніть файли для прикріплення.',
  feedback_upload_tip_mobile: 'Поділіться своїми відгуками.',
  image_upload_tip: 'Відпустіть, щоб додати',
  feedback_success: 'Ми чуємо вас чітко і ясно!',
  feedback_success_2: 'Дякуємо',
  feedback_failed:
    'Відправка не вдалася. Будь ласка, спробуйте ще раз пізніше.',
  image_upload_rule_1: 'Підтримуються лише PNG, JPG, JPEG.',
  image_upload_rule_2: 'Максимальний розмір – 20 МБ на файл.',
  image_upload_rule_3: 'До 5 файлів.',
  image_upload_rule_2_3: 'Максимальний розмір – 20 МБ на файл. До 5 файлів.',
  no_pair: 'Токен пара не знайдена',
  no_token: 'Токен не знайдено',
  choose_base_token: 'Виберіть базовий токен',
  choose_quote_token: 'Виберіть токен-котирування',
  get_test_token: 'Отримати тестовий токен',
  faucet: 'Кран',
  expire_in: 'Закінчується через',
  expire_in_empty_err: 'Введіть число',
  go_back: 'Повернутися назад',
  max_XXX: 'Макс XXX',
  min_XXX: 'Мін XXX',
  fill_in: 'Заповнити',
  my_balance: 'Мій баланс',
  deGate_insufficient_fees:
    'Недостатньо балансу DeGate для сплати комісії за газ',
  wallet_balance: 'Баланс гаманця',
  your_wallet_balance: 'Ваш баланс гаманця',
  degate_balance: 'Баланс DeGate',
  wallet_insufficient_fees: 'Недостатньо балансу в гаманці',
  wallet_insufficient_balance: 'Недостатній баланс',
  insuffficient_wallet_balance: 'Недостатньо балансу в гаманці',
  degate_insufficient_balance: 'Недостатньо доступного балансу',
  open_discord: 'Перейти в спільноту Discord',
  err_valid_until:
    'Будь ласка, налаштуйте локальний час відповідно до стандартного часу на вашому пристрої',
  tips_gas:
    'Комісія за газ для цієї транзакції буде стягнута безпосередньо з вашого балансу DeGate.',
  maker_free: 'Безкоштовно для мейкерів',
  trading_fee_rate: 'Ставка торгової комісії',
  Free: 'Безкоштовно',
  stop_service_1: 'Сайт перебуває на технічному обслуговуванні',
  stop_service_2: 'Оцінковий час відновлення',
  stop_upgrade:
    'Нова версія тестової мережі наразі перебуває на стадії міграції.',
  stop_trading_1: 'Оновлення системи',
  stop_trading_2: 'Торгівля тимчасово припинена',
  sell: 'продати',
  buy: 'купити',
  SELL: 'ПРОДАТИ',
  BUY: 'КУПИТИ',
  Sell: 'Продаж',
  Buy: 'Купівля',
  sell_order: 'Продажний ордер',
  buy_order: 'Купівельний ордер',
  edit: 'Редагувати',
  status_processing: 'Обробка',
  status_processed: 'Очікує',
  status_pending: 'Очікує',
  status_confirming: 'Підтвердження',
  status_success: 'Успіх',
  status_completed: 'Завершено',
  status_failed: 'Помилка',
  status_speeding_up: 'Прискорюється',
  status_canceling: 'Скасовується',
  status_canceled: 'Скасовано',
  in_progress: 'Виконується',
  limit_order: 'Ліміт',
  market_order: 'Ринок',
  stop_limit_order: 'Стоп Ліміт',
  balance: 'Баланс',
  empty_connect: 'Спочатку підключіть гаманець',
  empty_register: 'Спочатку ініціалізуйте',
  empty_months3: 'Немає даних за останні 3 місяці',
  show_months3: 'Показано дані тільки за останні 3 місяці',
  view_all: 'Переглянути всі',
  D1: '1Д',
  D5: '5Д',
  M1: '1М',
  M3: '3М',
  M6: '6М',
  YTD: 'З початку року',
  Y1: '1Р',
  all: 'Усі',
  paste: 'Вставити',
  clear: 'Очистити',
  total: 'Всього',
  amount: 'Сума',
  order_amount: 'Сума ордера',
  price: 'Ціна',
  order_total: 'Всього',
  filledAmount: 'Сума',
  tradeFilledTotal: 'Вартість',
  orderFilledTotal: 'Всього',
  filledAmount_amount: 'Виконано/Сума',
  profit: 'Прибуток',
  incompatible_token:
    'Технічні характеристики цього токена не сумісні з протоколом DeGate.',
  next: 'Далі',
  token_not_verified: 'Не перевірено',
  token_not_verified_tips:
    'Адреса контракту, іконка та символ не перевірені. Будь ласка, перевірте адресу контракту через офіційні джерела, щоб уникнути шахрайства.',
  token_verified: 'Перевірено',
  token_verified_tips: 'Адреса контракту, іконка та символ збігаються.',
  deposit_tips_region:
    'Зверніть увагу, що ви отримуєте доступ до DeGate у РЕГІОНІ. Функції торгівлі та внутрішнього переказу недоступні після додавання коштів.',
  complete_time: 'Завершено через',
  unable_to_initialize: 'Неможливо ініціалізувати',
  filter_base: 'База',
  filter_quote: 'Котирування',
  filter_type: 'Тип',
  filter_role: 'Роль',
  option_maker: 'Мейкер',
  option_taker: 'Тейкер',
  start_data: 'Дата початку',
  end_data: 'Дата закінчення',
  added_to_favorites: 'Додано в обране',
  removed_to_favorites: 'Видалено з обраного',
  show_recents_50: 'Відображено останні 50 даних.',
  terms_of_service: 'Умови обслуговування',
  tips_small_unfilled:
    'Згідно з рівнем точності, зазначеним у системному дизайні, невелика невиконана частина ордера була повернена на ваш баланс DeGate.',
  notification: 'Сповіщення',
  server_message_SystemRecovery:
    'Будь ласка, зверніть увагу, що після відновлення системи змінилися статуси ваших ордерів.',
  learn_more: 'Дізнатися більше',
  connect_ledger: 'Підключити Ledger',
  ledger_disconnect:
    "Не вдалося виконати 'transferOut' на 'USBDevice': Пристрій був відключений.",
  gas_fee_expired:
    'Термін дії комісії за газ закінчився. Будь ласка, надішліть знову.',
  scroll_down_to_refresh: 'Прокрутіть вниз, щоб оновити',
  release_to_refresh_immediately: 'Відпустіть, щоб оновити',
  no_more: 'Більше немає даних',
  loading: 'Завантаження...',
  force_withdrawing_token_tips:
    'Поточну операцію неможливо виконати, оскільки ваш запит на примусовий вихід обробляється.',
  speed_up: 'Прискорити',
  transaction_submitted: 'Транзакція відправлена',
  tx_speed_up: 'Прискорити транзакцію',
  tx_cancel: 'Скасувати транзакцію',
  none: 'Немає',
  Language: 'Мова',
  page: '/Сторінка',
  go_to: 'Перейти до',
  icon_indicators: 'Індикатори',
  icon_back: 'Назад',
  icon_forward: 'Вперед',
  icon_full_screen: 'На весь екран',
  icon_exit_full_screen: 'Вийти з повноекранного режиму',
  icon_buy_sell_orders: 'Ордери на купівлю та продаж',
  icon_buy_orders: 'Ордери на купівлю',
  icon_sell_orders: 'Ордери на продаж',
  icon_enable: 'Натисніть, щоб увімкнути',
  icon_disable: 'Натисніть, щоб вимкнути',
  icon_copy: 'Скопіювати адресу',
  icon_view_explorer: 'Переглянути в Block Explorer',
  icon_display_by_profit: 'Відображати за прибутком',
  icon_display_by_time: 'Відображати за часом',
  icon_switch: 'Перемкнути',
  eth_code_tips: 'Рідний токен Ethereum. Адреси токену контракту немає.',
  TBD: 'TBD',
  TVL: 'TVL',
  go_to_discord: 'Або приєднайтесь до Discord, щоб створити заявку',
  release: 'Випуск:',
  security: 'Безпека',
  colon: ':',
  zero_balance: 'Нульовий баланс',
  ledger_app_version_tips:
    'Оновіть Ethereum-додаток вашого Ledger до версії 1.9.19 або вище, щоб переглянути повідомлення перед підписанням.',
  ledger_contract_data_tips:
    'Будь ласка, увімкніть Blind signing або Contract data в налаштуваннях додатка Ethereum',
  input_auto_corrected_tooltips:
    'Автоматично скориговано введення після перевищення максимальної кількості цифр',
  maximum_decimal_reached: 'Досягнуто максимальну кількість десяткових знаків',
  verify_ownership: 'Перевірка власності',
  enable_trading: 'Увімкнути торгівлю',
  learn_more_about_signatures_link: 'Дізнатись більше про підписи >',
  learn_more_about_signatures: 'Дізнатись більше про підписи',
  sign: 'Підписати',
  sign_step1: 'Завершити у вашому гаманці',
  sign_step2: 'Завершити 2-й підпис',
  not_now: 'Не зараз',
  view_on_block_explorer: 'Переглянути в Blockchain Explorer',
  view_in_history: 'Переглянути в історії',
  continue_to_place_order: 'Продовжити для розміщення ордера',
  Save: 'Зберегти',
  sign_to_view: 'Підписати для перегляду',
  available_degate_balance: 'Доступний баланс DeGate',
  Back: 'Назад',
  token_has_not_listed: 'Цей токен не був доданий у DeGate.',
  list_now: 'Додати зараз',
  spread_15: 'Спред > 15%',
  connected: 'Підключено',
  self_list_token: 'Миттєве додавання',
  claim_REBASE: 'Вимагати REBASE',
  time: 'Час',
  time_updated: 'Час оновлено',
  show_in_X_m: 'Показати через ~Xm',
  max_gas: 'Макс комісія за газ',
  total_required: 'Загалом потрібно',
  Required: 'Потрібно',
  available_balance: 'Доступний баланс',
  please_add_funds: 'Будь ласка, додайте кошти на ваш баланс у DeGate.',
  Side: 'Сторона',
  pending: 'Очікується',
  active: 'Активний',
  ended: 'Завершено',
  name: "Ім'я",
  yield: 'Дохід',
  time_created: 'Час створення',
  time_ended: 'Час завершення',
  frequency: 'Частота',
  chain_cancel: 'Скасувати в мережі',
  status: 'Статус',
  status_chainCancelProgressing: 'Скасування в мережі',
  status_chainCancelCompleted: 'Скасовано в мережі',
  filled_total: 'Виконано/Всього',
  start_time: 'Час початку',
  end_time: 'Час завершення',
  Summary: 'Підсумок',
  Orders: 'Замовлення',
  Tutorial: 'Підручник',
  Earn: 'Заробіток',
  top_winner_24h: 'Рейтинг за 24 години',
  ID: 'Ідентифікатор',
  Select: 'Вибрати',
  Create: 'Створити',
  Review: 'Огляд',
  Airdrop: 'Airdrop',
  Countdown: 'Зворотний відлік',
  Day: 'День',
  Hour: 'Година',
  Minute: 'Хвилина',
  Second: 'Секунда',
  Days: 'Дні',
  Hours: 'Години',
  Minutes: 'Хвилини',
  Seconds: 'Секунди',
  Claim: 'Отримати',
  Expired: 'Закінчений термін дії',
  Claimed: 'Отримано',
  Welcome: 'Ласкаво просимо',
  gas_tips_for_amount_exceed_6_digits:
    'Додаткові збори застосовуються, оскільки сума перевищує номінальний ліміт у шість цифр.',
  input_auto_corrected_minStep_tips:
    'Автоматично виправлено ваш введення для відповідності мінімальній точності',
  order_max_limit: 'Перевищено максимальний ліміт',
  order_min_limit: 'Не досягнуто мінімального ліміту',
  order_faild_min_limit:
    'Розміщення замовлення не вдалося: не досягнуто мінімального ліміту.',
  order_faild_max_limit:
    'Розміщення замовлення не вдалося: перевищено максимальний ліміт.',
  disconnect_m: 'Відключити',
  'account.account_manage': 'Безпека',
  'account.account_manage_more':
    'Про режим авторизації та ключ активації активів >',
  'account.what_is_asset_key':
    'Про режим авторизації та ключ активації активів',
  'account.total_value': 'Загальна вартість',
  'account.hide_small_balances': 'Приховати малі баланси',
  'account.add_to_metamask': 'Додати токен у гаманець',
  'account.assets_balance_total': 'Загальна сума',
  'account.assets_balance_available': 'Доступно',
  'account.assets_market': 'Вартість',
  'account.transfer_to_degate_balance': 'Додати на баланс DeGate',
  'account.search_tokens': 'Пошук токена',
  'account.deposit_title':
    'Активи будуть додані на ваш децентралізований обліковий запис DeGate. Ви повністю контролюєте ці активи.',
  'account.deposit_tips': 'Ви зберігаєте повний контроль над цими коштами.',
  'account.deposit_confirm_btn': 'Додати',
  'account.deposit_approved_btn': 'Схвалено',
  'account.deposit_1_ETH': 'Додати 1 ETH на ваш баланс DeGate',
  'account.deposit_status_pending': 'Очікується',
  'account.deposit_status_pay_pending': 'Платіж належить',
  'account.deposit_status_pay_waiting': 'Платіж переданий',
  'account.deposit_status_pay_confirming': 'Підтвердження платежу',
  'account.deposit_tips_block': 'Транзакція очікує на включення у блок',
  'account.deposit_status_pay_btn': 'Оплатити',
  'account.pay_deposit_warning':
    'Додавання коштів може супроводжуватися додатковою комісією за газ',
  'account.pay_deposit_warning_tips':
    'Користувачі можуть бути змушені покрити витрати на додавання коштів, оскільки субсидії DeGate були повністю використані.',
  'account.deposit_pending_tips':
    'Прискорити транзакцію у вашому гаманці, якщо вона очікує більше 5 хвилин.',
  'account.deposit_pending_tips_ledger':
    'Прискорити транзакцію, якщо вона очікує більше 5 хвилин.',
  'account.deposit_contract_tips_over_AMOUNT':
    'Додавання коштів понад AMOUNT USD вимагає розширеного методу.',
  'account.deposit_contract_tips_only_all':
    'Підтримується тільки розширений метод додавання коштів',
  'account.suggest_100': '≥$100 рекомендовано',
  'account.suggest_100_tips':
    'Для розміщення лімітного замовлення рекомендується сума понад $100.',
  'account.deposit_failed': 'Помилка',
  'account.deposit_failed_tips':
    'Транзакція для додавання коштів у мережі не вдалася.',
  'account.payment_due': 'Платіж належить бути виконаним',
  'account.payment_due_tips':
    'Потрібно додатковий платіж для зарахування коштів на ваш баланс DeGate.',
  'account.register_token_code_placeholder': 'Введіть адресу контракту',
  'account.register_token_code': 'Адреса контракту',
  'account.register_token_symbol': 'Символ',
  'account.register_token_check': 'Перевірити процес лістингу',
  'account.register_token_code_err_added':
    'Цей токен знаходиться в процесі лістингу',
  'account.register_token_next_step': 'Далі',
  'account.register_token_tips1':
    'Дозвіл не потрібен для лістингу токена в мережі. Ви можете відразу перейти до лістингу вашого токена.',
  'account.register_token_btn': 'Лістинг токена',
  'account.list_token': 'Лістинг токена',
  'account.withdraw_warning_XXX':
    'Через підвищений попит відправка коштів зараз займає ~ XXX.',
  'account.withdraw_status_pending': 'Обробка',
  'account.tansferred_1_ETH': '1 ETH Переведено',
  'account.transfer_status_sent': 'Відправлено',
  'account.transfer_status_received': 'Отримано',
  'account.th_me': 'Я',
  'account.th_tx_hash': 'Хеш транзакції',
  'account.th_time': 'Час',
  'account.locked_order': 'Лімітне замовлення',
  Sending: 'Відправлення',
  'account.locked_claimable': 'Можна отримати',
  'account.locked_grid': 'Сіткова стратегія',
  'account.personal_sign_reason': 'Можливі причини',
  'account.personal_sign_reason1': 'MetaMask підключений до апаратного гаманця',
  'account.personal_sign_reason2': 'Версія MetaMask застаріла',
  'account.personal_sign_reason3': 'Інші причини',
  'account.personal_sign_btn': 'Підписати знову',
  'account.deposit_arrive_in_30s': 'Прибуття через ~30 секунд',
  'account.deposit_arrive_in_30s_s': 'Прибуття через ~30 секунд',
  'account.account_completed_time_XXX': 'Завершення через ~XXX',
  'account.search_result_no_token': 'Токен не знайдено',
  'account.search_result_invalid_code': 'Невірна адреса контракту',
  'account.search_result_not_listed':
    'Токен наразі не включено до списку DeGate',
  'account.search_result_tips_register':
    'Ви можете ввести адресу контракту для завершення лістингу токену',
  'account.search_result_not_find': 'Все ще не можете знайти?',
  'account.search_pair_tips3': 'Немає торгової пари для активу',
  'account.search_pair_tips3_add': 'Будь ласка, додайте пару',
  'account.register_token': 'Лістинг токенів без дозволу',
  'account.search_again': 'Пошук знову',
  'account.deposit_type': 'Метод',
  'account.deposit_type_standard': 'Стандартний',
  'account.switch_account_tips': 'Переключено на',
  'account.switch_account_tips_register': 'Спочатку необхідно ініціалізувати.',
  'account.initialize_success': 'Ініціалізація успішна',
  'account.approve': 'Підтвердити',
  'account.reset_USDT': 'Скинути підтверження USDT',
  'account.reset_USDT_tips':
    'USDT вимагає скидання підтверження, коли ліміти витрат занадто низькі.',
  'account.next_step': 'Далі',
  'account.profit_total': 'Загальний прибуток',
  'account.profit_history': 'Історія прибутку',
  'account.tab_mining_rewards': 'Нагороди за майнінг',
  'account.yield_total': 'Загальний дохід',
  'account.yield_24h': 'Дохід за 24 години',
  'account.claimable': 'Можна отримати',
  'account.yield_history': 'Історія доходів',
  'account.total_grid_profit': 'Загальний прибуток за сіткою',
  'account.grid_strategies': 'Сіткові стратегії',
  'account.total_rewards': 'Загальні нагороди',
  'account.rewards_24h': 'Нагороди за 24 години',
  'account.rewards': 'Нагороди',
  'menu.register_err':
    'Ваша адреса не має жодного запису про транзакції в блокчейні. Будь ласка, виконайте транзакцію в мережі та спробуйте ще раз. Наприклад, переведіть токен на свій гаманець.',
  'menu.reset_post_success_withOrders':
    'Ініційовано скидання ключа активів. Усі ваші відкриті замовлення та сіткові стратегії були скасовані.',
  'menu.reset_post_success': 'Ініційовано скидання ключа активів.',
  'menu.reset_processing_title': 'Скидання ключа активів в процесі',
  'menu.reset_processing_desc': 'Будь ласка, зачекайте завершення',
  'trade.choose_token': 'Виберіть токен',
  'trade.token_info': 'Інформація про токен',
  'trade.token_address': 'Адреса токену',
  'trade.price_range_24h': 'Діапазон ціни за 24 години',
  'trade.vol_24h': 'Обсяг за 24 години',
  'trade.item_price_TOKEN': 'Ціна (TOKEN)',
  'trade.item_amount_TOKEN': 'Кількість (TOKEN)',
  'trade.order_book_title': 'Книга замовлень',
  'trade.order_book_total': 'Загальна сума',
  'trade.trade_history_title': 'Останні угоди',
  'trade.trade_history_time': 'Час',
  'trade.market_placeholder_price': 'Ринкова ціна',
  'trade.what_is_stop_limit': 'Що таке Стоп Ліміт?',
  'trade.what_is_stop_limit_link': 'Що таке Стоп Ліміт?',
  'trade.placeholder_total': 'Загальна сума',
  'trade.more_settings': 'Налаштування',
  'trade.expire_in_tips':
    'Ордер буде автоматично скасовано після закінчення терміну дії.',
  'trade.period_day_s': 'д',
  'trade.period_hour_s': 'год',
  'trade.period_minute_s': 'хв',
  'trade.period_err_input_tips': 'Будь ласка, введіть дійсне число',
  'trade.post_only_label': 'Тільки для Мейкера',
  'trade.post_only_tips':
    'Режим ""Тільки для Мейкера"" гарантує, що тільки ордера Мейкера будуть додані в книгу замовлень. Якщо будь-яка частина ордера може бути виконана як замовлення тейкера, то весь ордер буде повернуто. Замовлення в режимі ""Тільки для Мейкера"" не стягують комісію за газ або торгівлю.',
  'trade.post_only_fail_title': 'Неможливо створити замовлення',
  'trade.post_only_fail_desc':
    'Будь ласка, налаштуйте ціну або вимкніть режим ""Тільки для Мейкера"".',
  'trade.max_gas_fee_tips':
    'Максимальна комісія за газ покриває витрати на виконання угод в мережі, сплачується Тейкерами і безкоштовна для Мейкерів. Надлишкові комісії повертаються.',
  'trade.auto': 'Авто',
  'trade.custom': 'Налаштування',
  'trade.enough_for_XX_trades': 'Достатньо для ХХ угод',
  'trade.gas_fee_per_trade': 'Комісія за газ за угоду',
  'trade.gas_fee_per_trade_tips':
    'Тейкери сплачують комісію за газ за кожну угоду для сприяння виконанню в мережі, з витратами, що коливаються в залежності від умов мережі Ethereum.',
  'trade.max_number_of_trades': 'Максимальна кількість угод',
  'trade.btn_buy_ETH': 'Купити ETH',
  'trade.btn_sell_ETH': 'Продати ETH',
  'trade.max_buy_fee_deducted_NUM': 'Вирахувано комісію за газ. Максимум NUM.',
  'trade.notification_limit_order_title': 'Розміщено лімітний ордер',
  'trade.notification_stop_limit_order_title':
    'Розміщено ордер зі Стоп Лімітом',
  'trade.err_price': 'Будь ласка, введіть ціну',
  'trade.err_amount_total': 'Будь ласка, введіть кількість або загальну суму',
  'trade.err_amount': 'Будь ласка, введіть кількість',
  'trade.err_insufficientFee_title': 'Недостатня комісія за газ',
  'trade.err_insufficientFee_desc':
    'Будь ласка, перевірте налаштування Максимальної комісії за газ та ваш баланс DeGate.',
  'trade.cancel_order_success': 'Ордер скасовано',
  'trade.pair_favorite': 'Обране',
  'trade.pair_search': 'Пошук токену, адреса контракту',
  'trade.pair_last_price': 'Ціна',
  'trade.pair_change': 'Зміна',
  'trade.url_parse_err_title': 'Ця пара не існує.',
  'trade.risk_tips': 'Попередження про ризик',
  'trade.base_is_not_default_token_tips':
    'Перш ніж торгувати, перевірте адресу контракту токену через офіційні джерела, щоб уникнути шахрайства.',
  'trade.chain_cancel': 'Скасувати ордер в мережі',
  'trade.chain_cancel_no_need_tips':
    'Цей ордер не потребує скасування в мережі.',
  'trade.chain_cancel_success': 'Запит відправлено',
  'trade.depth_empty': 'Ордерів поки немає',
  'trade.depth_empty_asks': 'Немає ордерів на продаж',
  'trade.depth_empty_bids': 'Немає ордерів на купівлю',
  'trade.depth_empty_tips':
    'Ринковий ордер не вдалося виконати через недостатню кількість відкритих замовлень у книзі замовлень',
  'trade.history_empty': 'Угод поки що немає',
  'trade.err_price_stable':
    'Ціна стала недійсною. Будь ласка, спробуйте ще раз.',
  'trade.price_warning':
    'Ціна, яку ви ввели, відхилилася від ринкової, будь ласка, підтвердіть перед розміщенням ордеру',
  'trade.order_value_tips':
    'Мінімальне значення ордеру становить <b>QUOTE_A</b> або <b>BASE_A</b>, що еквівалентно MINUSD USD. Використовуйте ринковий ордер, щоб обійти це обмеження.',
  'trade.order_value_tips_quote':
    'Мінімальне значення ордеру становить <b>QUOTE_A</b>, що еквівалентно MINUSD USD. Використовуйте ринковий ордер, щоб обійти це обмеження.',
  'trade.order_value_tips_stable_quote':
    'Мінімальне значення ордеру становить <b>QUOTE_A</b>. Використовуйте ринковий ордер, щоб обійти це обмеження.',
  'trade.system_limit': 'Перевищено системний ліміт',
  'trade.stop_limit_untriggered_tips':
    'Ордер не був поданий до книги ордерів, оскільки стоп-ціна не була досягнута.',
  'trade.stop_limit_triggered_tips_TIME':
    'Ордер був поданий до книги ордерів о TIME',
  'trade.flow_of_funds': 'потік коштів',
  'trade.flow_of_funds_tip2':
    'Ваш ордер був розміщений. Кошти з ордеру перейдуть на ваш баланс DeGate, а не на баланс гаманця.',
  'orders.show_current_pair_orders': 'Сховати інші пари',
  'orders.orderHistory': 'Історія ордерів',
  'orders.th_time': 'Час',
  'orders.th_average_price': 'Середня ціна',
  'orders.th_stop_price': 'Стоп ціна',
  'orders.th_limit_price': 'Ліміт ціна',
  'orders.th_filled_price': 'Ціна',
  'orders.th_filled_amount': 'Заповнено',
  'orders.th_filled_total': 'Всього',
  'orders.th_trade_reconciliation': 'Реконcиляція',
  'orders.th_trade_reconciliation_tips':
    'Зверніть увагу, що через використання різних моделей розрахунків для відповідності на DeGate і розрахунків на блокчейні можуть виникнути незначні відмінності в результатах двох розрахунків. Якщо і коли це станеться, система використовуватиме значення на блокчейні як стандарт і компенсує будь-які недоліки на балансі DeGate.',
  'orders.hide_cancelled_expired_orders': 'Сховати скасовані/закінчені',
  'orders.status_open': 'Відкритий',
  'orders.status_pending': 'Очікує',
  'orders.status_completed': 'Заповнений',
  'orders.status_completed_part': 'Частково заповнений',
  'orders.status_expired': 'Закінчився',
  'orders.detail_price': 'Середня/Ціна',
  'orders.average_price': 'Середня ціна',
  'orders.detail_type': 'Тип ордера',
  'orders.detail_trade_fee': 'Торгова комісія:',
  'orders.gas_preAuth': 'Максимальна комісія за газ:',
  'orders.fee_reconciliation': 'Реконcиляція:',
  'orders.gas_paid': 'Сплачена комісія за газ:',
  'orders.gas': 'Комісія за газ:',
  'orders.trades_N': 'Угоди(N)',
  'orders.detail_filled_total': 'Всього',
  'orders.detail_filled_detail': 'Деталі угоди',
  'orders.detail_filled_time': 'Час',
  'orders.order_maker_free': 'Комісія мейкера безкоштовна',
  'orders.openOrders_empty': 'Немає відкритих ордерів',
  'orders.export_orders_1_year': 'Експортувати дані ордерів за останній рік.',
  'orders.export_trades_1_year': 'Експортувати дані угод за останній рік.',
  'orders.export_data': 'Експортувати дані',
  'orders.export': 'Експорт',
  'orders.export_processing': 'Обробка. Будь ласка, зачекайте.',
  'orders.export_tips_100_percent':
    'Файл буде завантажено, коли прогрес досягне 100%',
  'orders.sign_to_view_balance': 'Підпишіть, щоб переглянути баланс',
  'orders.sign_to_view_history': 'Підпишіть, щоб переглянути історію',
  'orders.sign_to_view_security_options':
    'Підпишіть, щоб переглянути параметри безпеки',
  'gridTrade.automatic_strategy': 'Авто',
  'gridTrade.manual_strategy': 'Ручний',
  'gridTrade.placeholder_amount': 'Введіть суму',
  'gridTrade.low_price': 'Нижня межа',
  'gridTrade.high_price': 'Верхня межа',
  'gridTrade.initial_investment': 'Інвестиції',
  'gridTrade.grid_levels_tips':
    'Використовується для визначення кількості відкритих ордерів у межах діапазону цін.',
  'gridTrade.profit_per_grid': 'Прибуток на сітку',
  'gridTrade.profit_per_grid_tips':
    'Важливий параметр для прибутковості сіткової Grid стратегії. Прибуток на сітку = (Вища ціна - Нижча ціна) / Нижча ціна. Вищі та нижчі ціни відносяться до цін двох суміжних сіткових ліній у межах сіткової стратегії.',
  'gridTrade.min_grid_volume_XXX_ETH': 'Сума на сітку: Мінімум XXX ETH',
  'gridTrade.min_grid_volume_err':
    'Будь ласка, збільште інвестиції або зменште кількість сіток',
  'gridTrade.grid_no_depth_tips_BASE_QUOTE':
    'Неможливо створити сіткову стратегію для цієї пари через недостатню кількість ордерів у книзі ордерів.',
  'gridTrade.grid_to_spot_trade': 'Перейти до Споту',
  'gridTrade.grid_level_over_err': 'Будь ласка, зменшіть кількість сіток',
  'gridTrade.grid_prices_err': 'Будь ласка, розширте діапазон цін',
  'gridTrade.grid_create_err':
    'Будь ласка, налаштуйте параметри та спробуйте ще раз.',
  'gridTrade.tips_grid_profit':
    'Прибуток зараховується безпосередньо на ваш баланс DeGate і доступний негайно.',
  'gridTrade.tips_grid_balance_0_BASE':
    'Зростання ринкової ціни призвело до того, що всі ордери в межах цієї сіткової стратегії стали ордерами на купівлю. Таким чином, поточний баланс BASE тепер дорівнює 0.',
  'gridTrade.tips_grid_balance_0_BASE_2':
    'Зростання ринкової ціни призвело до того, що всі ордери в межах цієї сіткової стратегії стали ордерами на купівлю. Крім того, деякі з цих ордерів частково виконані. Таким чином, поточний баланс BASE > 0.',
  'gridTrade.tips_grid_balance_0_QUOTE':
    'Зниження ринкової ціни призвело до того, що всі ордери в межах цієї сіткової стратегії стали ордерами на продаж. Таким чином, поточний баланс QUOTE тепер дорівнює 0.',
  'gridTrade.tips_grid_balance_0_QUOTE_2':
    'Зниження ринкової ціни призвело до того, що всі ордери в межах цієї сіткової стратегії стали ордерами на продаж. Крім того, деякі з цих ордерів частково виконані. Таким чином, поточний баланс QUOTE > 0.',
  'gridTrade.grid_param_err':
    'Будь ласка, введіть параметри сіткової Grid стратегії',
  'gridTrade.tv_buy': 'Купити',
  'gridTrade.tv_sell': 'Продати',
  'gridTrade.tv_waiting': 'Очікування',
  'gridTrade.chain_cancel_no_need_tips':
    'Ця сіткова Grid стратегія не потребує скасування в мережі.',
  'gridTrade.grid_over_max_number_err':
    'Досягнуто максимальну кількість запущених сіткових стратегій, неможливо створити нову сітку.',
  'gridTrade.preview_orders_in_graph': 'Показати ордери',
  'gridTrade.greate_news': 'Чудова новина:',
  'gridTrade.min_amount_required_XXX': 'Мінімум XXX потрібно',
  'gridTrade.highest_grid_apy': 'Найвищий річний прибуток по сітці (APY)',
  'gridTrade.for_the_last_7_days': 'За останні 7 днів',
  'gridTrade.min_investment': 'Мін. Інвестиції',
  'gridTrade.grid_need_XXX': '$XXX на сітку',
  'gridTrade.mining_need_XXX': '$XXX на майнінг',
  'gridTrade.recommended_params_cannot_be_applied':
    'Рекомендовані параметри не можуть бути застосовані через недостатні інвестиції. Ви можете налаштувати їх в ручному режимі.',
  'gridTrade.copy_params_to_manual': 'Скопіювати параметри в ручний режим',
  'gridOrders.grid_recents': 'Мої останні угоди',
  'gridOrders.th_created_time': 'Час створення',
  'gridOrders.grid_profit': 'Прибуток за сіткою',
  'gridOrders.grid_cancel': 'Завершення',
  open_orders: 'Відкриті ордери',
  'gridOrders.tab_history_orders': 'Виконані ордери',
  'gridOrders.tab_trade_history': 'Історія угод',
  'gridOrders.detail_current_balance': 'Поточний баланс',
  'gridOrders.detail_ending_balance': 'Кінцевий баланс',
  'gridOrders.detail_ending_balance_tips':
    'Баланс активів при закритті сіткової стратегії.',
  'gridOrders.detail_in_order_funds': 'Кошти в ордері:',
  'gridOrders.detail_on_hold_funds':
    'Кошти в очікуванні (від частково виконаних ордерів):',
  'gridOrders.detail_transactions': 'Кількість виконаних ордерів',
  'gridOrders.detail_investment': 'Початкові інвестиції',
  'gridOrders.detail_running_time': 'Тривалість',
  'gridOrders.detail_prices': 'Діапазон цін',
  number_of_grids: 'Кількість сіток',
  'gridOrders.detail_expire_time': 'Закінчиться через',
  'gridOrders.detail_expire_time_tooltip':
    'Ордери в межах цієї сіткової Grid стратегії будуть скасовані після її закінчення.',
  'gridOrders.detail_valid_period': 'Налаштування терміну дії',
  'gridOrders.open_orders_sell': 'ПРОДАТИ',
  'gridOrders.open_orders_buy': 'КУПИТИ',
  'gridOrders.open_orders_index': '#',
  'gridOrders.open_orders_total': 'Всього',
  'gridOrders.history_orders_filled': 'Виконано',
  'gridOrders.history_orders_price': 'Ціна',
  'gridOrders.history_orders_time': 'Час',
  'gridOrders.history_orders_filled_price': 'Середня ціна',
  'gridOrders.history_orders_filled_amount': 'Виконано',
  'gridOrders.history_orders_filled_total': 'Загальна сума',
  'gridOrders.history_orders_profit_tips':
    'Прибуток походить від різниці в ціні після циклу покупки за низькою ціною та продажу за високою. Наприклад, після того, як ордер на покупку 1 ETH за ціною 4000 USDC буде виконано, якщо інтервал між сітками становить 50 USDC, система автоматично розмістить новий ордер на продаж 1 ETH за ціною 4050 USDC Прибуток у розмірі 50 USDC буде отримано, коли цей ордер також буде виконаний',
  'gridOrders.history_orders_buy_flip_order_tips_PRICE':
    'Прибуток буде відображено після виконання ордера на покупку за ціною PRICE',
  'gridOrders.history_orders_sell_flip_order_tips_PRICE':
    'Прибуток буде відображено після виконання ордера на продаж за ціною PRICE',
  'gridOrders.m_history_orders_flip_order_tips_PRICE':
    "Ордер за ціною PRICE з'явиться тут після виконання",
  'gridOrders.grid_cancel_title': 'Завершити сіткову Grid стратегію',
  'gridOrders.grid_cancel_content':
    'Усі ордери в цій сітковій Grid стратегії будуть негайно скасовані',
  'gridOrders.grid_cancel_content2':
    "На даний момент ви займаєтесь майнінгом за цією сітковою Grid стратегією. Якщо ви завершите цю сіткову стратегію, ви втратите всі винагороди за майнінг, і всі пов'язані сіткові ордери будуть негайно скасовані",
  'gridOrders.copy_grid_title':
    'Будуть скопійовані наступні параметри сіткової стратегії',
  'gridOrders.copy_grid_btn': 'Копіювати до панелі',
  'gridOrders.copy_grid_success': 'Сіткова Grid стратегія скопійована',
  'gridOrders.grid_init_funds_XXX': 'Вартість початкових інвестицій $XXX',
  'gridOrders.grid_init_funds_tips':
    'APY розраховується на основі вартості початкового розподілу на момент створення сіткової стратегії',
  'gridOrders.tab_m_trade': 'Торгівля',
  grid_apy: 'Сітковий APY',
  grid_apy_tips:
    'Годова ставка прибутку лише від сіткової торгівлі Плаваючий прибуток не включений',
  'gridOrders.tab_mining_profit': 'Годова ставка прибутку від майнінгу APY',
  'gridOrders.tab_mining_profit_tips':
    'Годова ставка прибутку від майнінгу розраховується на основі початкової вартості та тривалості сіткової стратегії',
  'gridOrders.mining_rewards': 'Винагороди',
  'gridOrders.open_orders_empty_tips':
    'Будь ласка, зачекайте, поки дані завантажуються',
  'gridOrders.market_value': 'Ринкова вартість',
  'gridOrders.market_value_details': 'Деталі',
  'gridOrders.fund_details': 'Деталі коштів',
  'gridOrders.m_in_order_funds': 'Кошти в ордері',
  'gridOrders.m_in_order_funds_tips':
    'Загальна сума коштів у всіх відкритих ордерах у межах цієї сіткової Grid стратегії',
  'gridOrders.m_on_hold_funds': 'Кошти на утриманні',
  'gridOrders.m_on_hold_funds_tips': 'Результат частково виконаних ордерів',
  'gridOrders.initial_value': 'Початкова вартість',
  'mining.my_title': 'Мій пул майнінгу',
  'mining.index_desc':
    'Створіть сіткову Grid стратегію. Збільште свій прибуток від сітки за допомогою винагород за майнінг ліквідності',
  'mining.apply': 'Нова заявка на пул',
  'mining.claimable_rewards_box': 'Винагороди, які можна отримати',
  'mining.rewards_more': 'та інше',
  'mining.tab_pools': 'Пули для майнінгу',
  'mining.tab_my': 'Моя статистика майнінгу',
  'mining.pools_tab_live': 'У реальному часі',
  'mining.pools_tab_upcoming': 'Очікується',
  'mining.pools_funds': 'Загальна заблокована вартість TVL',
  'mining.pools_funds_tips':
    'Загальна вартість сіткових Grid ордерів, які відповідають мінімальній вартості ордера у $120',
  'mining.pools_mining_funds': 'Заблоковані кошти для майнінгу TVL',
  'mining.mining_apr': 'Годова ставка прибутку APY',
  'mining.mining_apr_tips':
    'Річна норма прибутковості, оцінена на основі винагороди за майнінг і загальної заблокованої вартості (TVL)',
  'mining.view_rule_link': 'Правила майнінгу',
  'mining.pools_info_to_confirm': 'Буде визначено',
  'mining.pools_no_wait': 'Немає доступних пулів для майнінгу',
  'mining.my_mining_funds': 'Мої кошти для майнінгу',
  'mining.my_mining_rewards': 'Мої винагороди за майнінг',
  'mining.my_th_profit_token_price': 'Остання ціна',
  'mining.my_th_total_rewards': 'Всього винагород',
  'mining.my_th_24h_rewards': 'Винагороди за 24 години',
  'mining.my_grids': 'Мій майнінг',
  'mining.only_show_mining_grids': 'Лише активні',
  'mining.my_th_mining_status': 'Статус майнінгу',
  'mining.status_framing': 'Активний',
  'mining.status_over_price': 'Вийшов за межі цінового діапазону',
  'mining.status_mining_over': 'Майнінг завершено',
  'mining.status_grid_closed': 'Стратегія завершена',
  'mining.status_grid_expired': 'Стратегія закінчилася',
  'mining.empty_no_faring_grids':
    'На даний момент немає сіткової Grid стратегії, доступної для майнінгу',
  'mining.go_mining_pool': 'Перейти до пулу майнінгу',
  'mining.go_mining': 'Почати майнінг',
  'mining.go_to_grid': 'До сіткової Grid стратегії',
  'mining.mining_help': 'Посібник з майнінгу',
  'mining.mining_available': 'Відповідає вимогам',
  'mining.mining_available_tips': 'Критерії вартості ордера виконані',
  'mining.mining_unavailable': 'Не відповідає вимогам',
  'mining.mining_partially_available': 'Частково відповідає вимогам',
  'mining.mining_unavailable_tips': 'Критерії вартості Ордеру не виконані',
  'mining.mining_preview': 'Попередній перегляд майнінгу',
  'mining.mining_total_profit': 'Винагороди за майнінг',
  'mining.mining_24h_profit': 'Винагороди за 24 години',
  'mining.profit_unable_display': 'Неможливо показати',
  'mining.mining_funds': 'Кошти для майнінгу',
  'mining.mining_funds_tips':
    'Загальна вартість Ордерів з усіх Grid стратегій сітки, що відповідають критеріям вартості Ордеру для цієї торгової пари',
  'mining.tab_mining_profit_details': 'Деталі винагороди',
  'mining.tab_mining_orders': 'Ордера для майнінгу',
  'mining.th_rewards': 'Винагорода',
  'mining.th_rewards_origin': 'Джерело винагороди',
  'mining.th_rewards_origin_tips':
    'Винагорода за майнінг нараховується, коли ціна сіткового Grid ордеру знаходиться в межах діапазону винагороди книги ордерів (найвища ціна купівлі * 0.99 ~ найнижча ціна продажу * 1.01)',
  'mining.th_rewards_origin_tips_stable':
    'Винагорода за майнінг нараховується, коли ціна сіткового ордеру знаходиться в межах діапазону винагороди книги ордерів (найвища ціна купівлі ~ найнижча ціна продажу)',
  'mining.th_time': 'Час',
  'mining.plan_title': 'Деталі пулу ETH/USDC',
  'mining.phase_cur': 'Поточна фаза',
  'mining.phase_range_N_XX': 'Фаза N (XX)',
  'mining.phase_index_N': 'Фаза N',
  'mining.phase_reward': 'Щоденні винагороди',
  'mining.phase_to_release': 'Буде оголошено',
  'mining.my_rewards': 'Мої винагороди',
  'mining.claimable_rewards': 'Доступно',
  'mining.locked_rewards': 'Заблоковано',
  'mining.locker_rewards_tips':
    'Винагороди за майнінг можуть бути отримані лише після того, як Grid стратегія сітки активна протягом 12 годин',
  'mining.claimed_success': 'Успішно отримано',
  'mining.claimed_tips':
    'Буде надіслано вам найближчим часом через внутрішній переказ',
  'mining.claimed_view_btn': 'Перевірити',
  'mining.mining_plan': 'Графік майнінгу',
  'mining.phase_unpublished': 'Буде оголошено',
  'mining.all_pools': 'Всі пули',
  'notification.limit_desc_SELL_BASE_QUOTE_AMOUNT_PRICE':
    'Продати КІЛЬКІСТЬ БАЗОВОЇ @ ЦІНУ КОТИРОВАНОЇ',
  'notification.limit_desc_BUY_BASE_QUOTE_AMOUNT_PRICE':
    'Купити КІЛЬКІСТЬ БАЗОВОЇ @ ЦІНУ КОТИРОВАНОЇ',
  'notification.stop_limit_desc_SELL_BASE_AMOUNT': 'Продати КІЛЬКІСТЬ БАЗОВОЇ',
  'notification.stop_limit_desc_BUY_BASE_AMOUNT': 'Купити КІЛЬКІСТЬ БАЗОВОЇ',
  'notification.cancel_grid_desc_PAIR_PRICES': 'ПАРА: ЦІНИ',
  'notification.cancel_market_desc_SELL_BASE_QUOTE_AMOUNT':
    'Продати КІЛЬКІСТЬ БАЗОВОЇ за КОТИРОВАНУ',
  'notification.cancel_market_desc_SELL_BASE_QUOTE_TOTAL':
    'Продати БАЗОВУ за ЗАГАЛЬНУ КОТИРОВАНУ',
  'notification.cancel_market_desc_BUY_BASE_QUOTE_AMOUNT':
    'Купити КІЛЬКІСТЬ БАЗОВОЇ за КОТИРОВАНУ',
  'notification.cancel_market_desc_BUY_BASE_QUOTE_TOTAL':
    'Купити БАЗОВУ за ЗАГАЛЬНУ КОТИРОВАНУ',
  'notification.cancel_limit': 'Лімітний ордер скасовано',
  'notification.cancel_stop_limit': 'Стоп-лімітний ордер скасовано',
  'notification.cancel_market': 'Ринковий ордер скасовано',
  'notification.cancel_grid': 'Стратегію сітки завершено',
  'notification.cancel_limit_expired': 'Лімітний ордер закінчився',
  'notification.cancel_stop_limit_expired': 'Стоп-лімітний ордер закінчився',
  'notification.cancel_grid_expired': 'Стратегія сітки завершилася',
  'notification.cancel_limit_order_for_gas_desc':
    'Ваш ордер закінчився через недостатню плату за газ. Він був частково виконаний, а залишок скасовано',
  'notification.cancel_limit_order_for_gas_filled_amount': 'Заповнено',
  'notification.cancel_limit_order_for_gas_amount': 'Кількість',
  'notification.view_history_orders': 'Переглянути історію Ордерів',
  'notification.cancel_market_for_depth_title':
    'Ордер частково виконаний і скасований',
  'notification.price_slippage_protection': 'Захист від проковзування ціни',
  'notification.price_slippage_protection_desc':
    'Ринкові ордера DeGate автоматично включають 10% захисту від проковзування ціни для обмеження втрат під час високої волатильності та низької ліквідності. Використовуйте лімітні ордера, щоб уникнути цього захисту',
  'notification.cancel_market_for_depth_warning':
    'Ринковий ордер DeGate впроваджує механізм захисту ціни, дозволяючи користувачам зменшити втрати в умовах високої волатильності та низької ліквідності. Якщо ви не хочете запускати механізм захисту ціни, використовуйте режим лімітного ордера',
  'notification.dca_plan_ended': 'DCA план завершено',
  'notification.cancel_dca_desc_PAIR': 'ПАРА',
  'notification.trade_limit_partially': 'Лімітний ордер частково виконаний',
  'notification.trade_limit_filled': 'Лімітний ордер виконаний',
  'notification.trade_market_partially': 'Ринковий ордер частково виконаний',
  'notification.trade_market_filled': 'Ринковий ордер виконаний',
  'notification.trade_stop_limit_partially':
    'Стоп-лімітний ордер частково виконаний',
  'notification.trade_stop_limit_filled': 'Стоп-лімітний ордер виконаний',
  'notification.mobile_trade_filled_AMOUNT_TOKEN':
    'Ордер виконано. Отримано КІЛЬКІСТЬ ТОКЕНА',
  'notification.mobile_trade_partially_AMOUNT_TOKEN':
    'Ордер частково виконано. Отримано КІЛЬКІСТЬ ТОКЕНА',
  'info.overview': 'Огляд',
  'info.accounts': 'Загальна кількість користувачів',
  'info.pairs': 'Торгові пари',
  'info.turnover': 'Обсяг за весь час',
  'info.turnover_24': 'Обсяг за 24 години',
  'info.dg_supply': 'Циркулюючий запас DG',
  'info.top_movers_no_increased':
    'Жоден токен не збільшився в ціні протягом 24 годин',
  'info.top_movers_no_decreased':
    'Жоден токен не зменшився в ціні протягом 24 годин',
  'info.top_pairs': 'Топ пари',
  Pair: 'Пара',
  'info.th_change': 'Зміна за 24 години',
  'info.th_l_up_2': '+2% Глибина',
  'info.th_l_down_2': '-2% Глибина',
  'info.th_turnover_24': 'Обсяг за 24 години',
  'info.tvl': 'Загальна заблокована вартість',
  'm.home': 'Головна',
  'm.grid': 'Сітка',
  'm.browser_wallet': 'Браузерний гаманець',
  'm.choose_pair': 'Вибрати пару',
  'm.orderBook_default': 'За замовчуванням',
  'm.orderBook_bids': 'Ордери на купівлю',
  'm.orderBook_asks': 'Ордери на продаж',
  'm.decimals': 'Десяткові',
  'm.lowest_price_24h': 'Мін. Ціна за 24 години',
  'm.highest_price_24h': 'Макс. Ціна за 24 години',
  'm.vol_24h': 'Обсяг за 24 години',
  'm.orderbook_buy': 'Купити',
  'm.orderbook_sell': 'Продати',
  'm.go_to_trade': 'Перейти до торгівлі',
  'm.choose_token': 'Вибрати токен',
  'm.from_address': 'Адреса відправника',
  'm.to_address': 'Адреса одержувача',
  'm.transfer_send': 'Надіслати',
  'm.transfer_receive': 'Отримати',
  'm.my_grid': 'Моя Grid стратегія сітки',
  'm.grid_profit_24': 'Прибуток за 24 години',
  'm.grid_item_trades_24': 'Торги за 24 години',
  'm.grid_profit_total': 'Загальний прибуток',
  'm.grid_over_prices': 'Поза діапазоном цін',
  'm.create_grid': 'Створити сіткову Grid стратегію',
  'm.grid_history': 'Історія',
  'm.grid_empty': 'Немає активної стратегії сітки',
  'm.grid_tutorial': 'Посібник по Grid сітці',
  'm.grid_params_to_manual': 'Копіювати параметри в ручний режим',
  'm.balance_err': 'Недостатньо коштів. Доступно:',
  'm.preview_grid': 'Попередній перегляд ордерів',
  last_price: 'Остання ціна',
  'm.grid_desc':
    'Торгівля за Grid сіткою – це торговельна стратегія, яка автоматизує купівлю та продаж у визначеному діапазоні',
  'm.view_tutorial': 'Переглянути посібник',
  'm.grid_profit_tips_sell':
    'Буде розраховано, коли цей ордер на продаж буде повністю виконано',
  'm.grid_profit_tips_buy':
    'Буде розраховано, коли цей ордер на купівлю буде повністю виконано',
  'm.hot': 'Гаряче',
  'm.all': 'Переглянути всі',
  'm.vol_24': 'Обсяг за 24 години',
  'm.transfer_t1': 'Внутрішній',
  'm.transfer_t2': 'Переказ',
  'activity.th_date': 'Час',
  'activity.th_type': 'Тип',
  'activity.th_fee': 'Комісія',
  'activity.th_content': 'Вміст',
  'activity.type_register_token': 'Листинг токенів',
  'activity.type_register_pair': 'Додавання пари',
  'activity.type_pay_deposit': 'Розрахунок депозиту',
  'activity.type_reset_account': 'Скидання ключа активу',
  on_chain_order_cancellation: 'Скасування ордера в блокчейні',
  'activity.count_N': 'Кількість: N',
  'activity.order_desc_SELL_AMOUNT_BASE_PRICE_QUOTE':
    'ПРОДАТИ КІЛЬКІСТЬ БАЗОВОЇ за ЦІНУ КОТИРОВАНОЇ',
  'activity.order_market_desc_SELL_AMOUNT_BASE': 'ПРОДАТИ КІЛЬКІСТЬ БАЗОВОЇ',
  'activity.reset_status_restting': 'Скидання',
  'activity.to_trade': 'Торгівля',
  'dca.dca_plan': 'План DCA',
  'dca.dca_explain': 'Середньозважена вартість долара',
  'dca.daily': 'Щодня',
  'dca.weekly': 'Щотижня',
  'dca.custom': 'Індивідуально',
  'dca.every': 'Кожен',
  'dca.amount_per_order': 'Сума на ордер',
  'dca.price_limit': 'Ціновий ліміт',
  'dca.maximum_price': 'Максимальна ціна',
  'dca.minimum_price': 'Мінімальна ціна',
  'dca.number_of_orders': 'Кількість ордерів',
  'dca.create_dca_plan': 'Створити план DCA',
  'dca.max_gas_fee_per_order': 'Максимальна плата за газ за ордер',
  'dca.maximum_plan_order_limit_reached':
    'Максимальна кількість ордерів у плані досягнута',
  'dca.end_time_should_be_set_after_the_current_time':
    'Час завершення має бути встановлений після поточного часу',
  'dca.please_enter_amount_per_order': 'Будь ласка, введіть суму за ордер',
  'dca.please_enter_maximum_price': 'Будь ласка, введіть максимальну ціну',
  'dca.please_enter_minimum_price': 'Будь ласка, введіть мінімальну ціну',
  'dca.order_placement_failed_open_order_limit_exceeded':
    'Розміщення ордера не вдалося: перевищено ліміт відкритих ордерів',
  'dca.total': 'Загалом',
  'dca.filled': 'Виконано',
  'dca.received': 'Отримано',
  'dca.time_to_end': 'Час до завершення',
  'dca.cancel_on_chain': 'Скасувати в блокчейні',
  'dca.filled_amount': 'Заповнено/Кількість',
  'dca.status_executed': 'Виконано',
  'dca.status_scheduled': 'Заплановано',
  'dca.status_failed': 'Не вдалося',
  'dca.order_cancled_by_user':
    'Ордер скасовано, оскільки користувач завершив план DCA',
  'dca.order_cancled_by_access':
    'Ордер скасовано, оскільки ваш доступ до DeGate обмежено',
  'dca.order_cancled_by_gas':
    'Розміщення ордера не вдалося через недостатню плату за газ',
  'dca.order_cancled_by_order_book':
    'Розміщення ордера не вдалося через відсутність відповідного ордера в ордербуку',
  'dca.order_cancled_by_balance':
    'Розміщення ордера не вдалося через недостатній баланс DeGate',
  'dca.order_cancled_by_min_value':
    'Розміщення ордера не вдалося, оскільки мінімальна вартість ордера не досягнута',
  'dca.order_cancled_by_system_error':
    'Розміщення ордера не вдалося через системну помилку',
  'dca.chain_cancel_no_need_tips':
    'Цей план DCA не потребує скасування в блокчейні',
  'dca.end_dca_plan': 'Завершити план DCA',
  'dca.all_orders_in_this_dca_plan_will_be_canceled_immediately':
    'Всі ордери в цьому плані DCA будуть негайно скасовані',
  'dca.no_active_dca_plan': 'Немає активного плану DCA',
  'dca.time_scheduled': 'Запланований час',
  'campaign.event_period': 'Період події:',
  'campaign.grid2401_time':
    '22 січня 2024, 20:00:00 - 29 січня 2024, 20:00:00 (UTC+8)',
  'campaign.event_has_ended': 'Подія завершена',
  'campaign.current_apy': 'Поточна річна відсоткова дохідність (APY)',
  'campaign.grid_strategy_income':
    'Дохід від стратегії сітки + Частка в призовому фонді',
  'campaign.tvl_participating': 'TVL в участі',
  'campaign.share_of_tvl': 'Частка TVL',
  'campaign.my_profit': 'Мій прибуток',
  'campaign.grid_strategy_profit': 'Прибуток від стратегії сітки',
  'campaign.share_of_prize_pool': 'Частка призового фонду',
  'campaign.grid_strategy_profit_has_been_added_to_your_available_balance':
    'Прибуток від Grid стратегії сітки додано до вашого доступного балансу',
  'campaign.shared_income_from_usdc_prize_pool':
    'Спільний дохід з призового фонду USDC',
  'campaign.is_black_tips': 'Ви не маєте права на частку в призовому фонді',
  'campaign.calculating': 'Розрахунок',
  'campaign.claim_after_end': 'Приз можна отримати наприкінці події',
  'campaign.how_to_participate': 'Як взяти участь',
  'campaign.rule':
    'Створіть Grid стратегію сітки і розділіть призовий фонд пропорційно',
  'campaign.step1': 'Крок 1',
  'campaign.step2': 'Крок 2',
  'campaign.step3': 'Крок 3',
  'campaign.grid2401_step1':
    'Підготуйте свій ETH та USDC, додавши кошти або торгуючи',
  'campaign.grid2401_step2_PAIR':
    'Налаштуйте Grid стратегію сітки для ПАРИ, як зазначено нижче',
  'campaign.grid2401_step2_desc1_pre': 'Діапазон цін: Буде оголошено',
  'campaign.grid2401_step2_desc2_pre': 'Кількість сіток: Буде оголошено',
  'campaign.copy_strategy': 'Копіювати стратегію',
  'campaign.grid2401_step3':
    'Після закінчення події ви можете отримати свої заробітки на цій сторінці події. Будь ласка, отримайте протягом 30 днів після закінчення події',
  'campaign.what_is_grid': 'Що таке Grid стратегія сітки',
  'campaign.notes': 'Будь ласка, зверніть увагу перед приєднанням',
  'campaign.notes_1_title': 'Право на участь:',
  'campaign.notes_1_desc':
    'Стратегія сітки є дійсною тільки якщо діапазон цін і кількість сіток точно відповідають вимогам під час створення',
  'campaign.notes_2_title': 'Ліміт:',
  'campaign.notes_3_title': 'Отримання:',
  'campaign.notes_3_desc':
    'Отримання призу буде можливе наприкінці події і дійсне для отримання протягом 30 днів після закінчення події',
  'campaign.faq': 'Запитання й відповіді',
  'campaign.grid2401_faq_1': '1. Як розраховуються винагороди?',
  'campaign.grid2401_faq_2':
    '2. Де я можу отримати допомогу з питаннями по цій події?',
  'campaign.grid2401_faq_3': '3. У мене є USDT, як я можу отримати ETH і USDC?',
  'campaign.grid2401_faq_4':
    '4. Чи потрібно сплачувати комісію за транзакції, виконані через стратегію сітки? В DeGate всі ордери Maker безкоштовні. Ордера, згенеровані стратегією сітки, є ордерами Maker, тому налаштування стратегії сітки в DeGate повністю безкоштовне.',
  'campaign.grid2401_faq_4_res':
    'В DeGate всі ордери Maker безкоштовні. Ордери, які створюються за допомогою стратегії сітки, є ордерами Maker, тому налаштування стратегії сітки в DeGate повністю безкоштовне.',
  'campaign.grid2401_faq_5':
    '5. Чи буде моя Grid стратегія сітки генерувати дохід після закінчення події? Так, після закінчення події, поки ціна залишається в межах вашої стратегії сітки, стратегія продовжуватиме генерувати дохід. Після події ви також можете налаштувати параметри вашої стратегії сітки, щоб створити стратегію, яка більше відповідає вашим уподобанням, і продовжувати заробляти дохід.',
  'campaign.grid2401_faq_5_res':
    'Так, після закінчення події, поки ціна залишається в межах вашої стратегії сітки, стратегія продовжуватиме генерувати дохід. Після події ви також можете налаштувати параметри вашої стратегії сітки, щоб створити стратегію, яка більше відповідає вашим уподобанням, і продовжувати заробляти дохід.',
  'campaign.grid2401_faq_others': 'Інші деталі події',
  'campaign.grid2401_faq_others_1':
    '1. Лише один гаманець на користувача. Якщо буде виявлено зловмисний фарминг винагород, DeGate залишає за собою право скасувати винагороди учасника.',
  'campaign.grid2401_faq_others_2':
    '2. Під час події, сітки, які виходять за межі, також будуть враховані при розрахунку ваги.',
  'campaign.grid2401_faq_others_3':
    '3. DeGate залишає за собою право завершити подію раніше в екстремальних випадках, наприклад, через ринкову волатильність.',
  'campaign.grid2401_faq_others_4':
    '4. Винагороди, не заявлені протягом 30 днів після закінчення події, будуть анульовані.',
  'campaign.invest_max_5000': 'Максимальна сума інвестицій $5000',
  'campaign.invest_mininum': 'Мінімальна сума інвестицій',
  'airdrop.create_airdrop': 'Створити аірдроп',
  'airdrop.important_note':
    'Важливо: будь-хто може створювати аірдропи без дозволу',
  'airdrop.my_airdrop': 'Мої аірдропи',
  'airdrop.time_limited': 'Обмежений час',
  'airdrop.no_airdrop': 'Ще немає аірдропу',
  'airdrop.claim_airdrop': 'Одержати аірдроп',
  'airdrop.recipients_number': 'Кількість отримувачів',
  'airdrop.total_amount': 'Загальна сума',
  'airdrop.retrieve': 'Витягнути',
  'airdrop.unclaimed': 'Неотримані',
  'airdrop.retrieve_successful': 'Витягнення успішне',
  'airdrop.claim_successful': 'Одержання успішне',
  'airdrop.retrieve_unclaimed_airdrop': 'Витягнути неотриманий аірдроп',
  'airdrop.airdrop_token': 'Токен аірдропу',
  'airdrop.token_not_meet_criteria':
    'Цей токен не відповідає критеріям аірдропу',
  'airdrop.airdrop_list': 'Список аірдропів',
  'airdrop.download_template': 'Завантажити шаблон',
  'airdrop.click_or_drag_upload_list':
    'Клацніть або перетягніть, щоб завантажити список',
  'airdrop.validation_passed': 'Верифіковано',
  'airdrop.must_earlier_than_end_time': 'Має бути до кінцевого часу',
  'airdrop.cannot_more_than_2_years_from_now':
    'Не може бути більше ніж через 2 роки',
  'airdrop.cannot_parse_file':
    'Не вдалося розібрати файл. Будь ласка, використовуйте шаблон.',
  'airdrop.format_requirement_not_met': 'Форматні вимоги не виконані',
  'airdrop.view_error_repost': 'Переглянути звіт про помилки',
  'airdrop.error_report': 'Звіт про помилки',
  'airdrop.line': 'Лінія',
  'airdrop.reason': 'Причина',
  'airdrop.duplicated_address': 'Дубльована адреса',
  incorrect_address_format: 'Неправильний формат адреси',
  'airdrop.incorrect_amount_format': 'Неправильний формат суми',
  'airdrop.airdrop_plan_created': 'План аірдропу створено',
  'airdrop.max_50000': 'Макс. 50000 адрес',
  'airdrop.upload_file_rule': 'Підтримується тільки CSV.',
  'airdrop.to_check_airdrop_eligibility':
    'Завершіть ініціалізацію, щоб переглянути аірдропи',
  'airdrop.complete_initialization_to_claim_airdrops':
    'Завершіть ініціалізацію, щоб одержати аірдропи',
  'airdrop.complete_initialization_to_view_airdrops':
    'Завершіть ініціалізацію, щоб переглянути аірдропи',
  'airdrop.you_are_eligible_for': 'Ви маєте право на:',
  'airdrop.and_more': 'та інше',
  'airdrop.congratulations': 'Вітаємо!',
  'airdrop.airdrop_fee': 'Комісія за аірдроп',
  'countdown.countdown_plan': 'План зворотного відліку',
  'countdown.create_countdown_plan': 'Створити зворотний відлік',
  'countdown.my_countdown_plan': 'Створені мною',
  'countdown.countdown_trading_pair': 'Торговий пара зворотного відліку',
  'countdown.countdown_display': 'Відображення зворотного відліку',
  'countdown.token_not_meet_criteria':
    'Цей токен не відповідає критеріям зворотного відліку',
  'countdown.countdown_tips':
    'Зворотний відлік відображатиметься на торговій сторінці для вибраних торгових пар',
  'countdown.max_30_days': 'Не може бути більше ніж через 30 днів',
  'countdown.review_countdown_plan': 'Переглянути план зворотного відліку',
  'countdown.countdown_fee': 'Комісія за зворотний відлік',
  'countdown.countdown_plan_created': 'План зворотного відліку створено',
  'countdown.trading_will_start_in': 'Торгівля розпочнеться через',
  'countdown.trading_will_start_at_YYYY': 'Торгівля розпочнеться в YYYY',
  'countdown.cannot_earlier_than_current_time':
    'Не може бути до поточного часу',
  'dca.price_limit_buy_tips':
    'Після активації ваші ордери на покупку будуть виконані лише за цінами, рівними або нижчими за максимальну ціну. Ця функціональність сумісна з функцією нульової комісії.',
  'dca.price_limit_sell_tips':
    'Після активації ваші ордери на продаж будуть виконані лише за цінами, рівними або вищими за мінімальну ціну. Ця функціональність сумісна з функцією нульової комісії.',
  'dca.zero_fee': 'Нульова комісія',
  'dca.zero_fee_buy_tips':
    'При увімкненій нульовій комісії, ордери DCA обробляються як ордери тільки для Maker. Кожна ціна покупки буде встановлена на найвищій ціні запиту в ордерній книзі після розміщення. Зверніть увагу, що ваші ордери можуть не бути виконані відразу або взагалі не бути виконані.',
  'dca.zero_fee_sell_tips':
    'При увімкненій нульовій комісії, ордери DCA обробляються як ордери тільки для Maker. Кожна ціна продажу буде встановлена на найнижчій ціні пропозиції в ордерній книзі після розміщення. Зверніть увагу, що ваші ордери можуть не бути виконані відразу або взагалі не бути виконані.',
  'dca.order_canceled_post_only_buy_failed':
    'Розміщення ордера не вдалося, оскільки ордерна книга не має ордерів на покупку, що зупиняє встановлення ціни покупки вашого ордера.',
  'dca.order_canceled_post_only_sell_failed':
    'Розміщення ордера не вдалося, оскільки ордерна книга не має ордерів на продаж, що зупиняє встановлення ціни продажу вашого ордера.',
  start_time_cannot_before_current_time:
    'Час початку не може бути до поточного часу',
  start_time_must_before_end_time: 'Час початку має бути до часу закінчення',
  list_token: 'Список токенів',
  contract_address_does_not_exist: 'Адреса контракту не існує',
  token_listed: 'Цей токен був перерахований',
  XXX_is_listed: 'XXX перераховується',
  view_progress: 'Переглянути прогрес',
  pair_create_tips:
    'Торгові пари можуть бути миттєво додані на DeGate без затвердження будь-якої сторони.',
  base_token: 'Основний токен',
  quote_token: 'Токен котирування',
  existing_pair: 'Існуюча пара',
  trade_now: 'Торгувати зараз',
  pair_XXX_added_successfully: 'XXX успішно додано',
  qty_per_grid: 'Кількість за сітку',
  grid_minimum_not_reached: 'Мінімум не досягнуто',
  total_profit: 'Загальний прибуток',
  total_apy: 'Загальний APY',
  float_profit: 'Плаваючий прибуток',
  grid_profit_24h: '24 годинний прибуток від сітки',
  pnl: 'Дохід/Збиток',
  eligibility: 'Право на участь',
  rewards: 'Винагороди',
  view_mining_statistics: 'Переглянути статистику майнінгу',
  your_entry: 'Внесок коштів',
  refunded: 'Повернуто',
  large_price_spread: 'Великий спред цін',
  large_price_spread_tips:
    'Ордерна книга показує великий спред між найнижчою ціною продажу та найвищою ціною покупки, що несе ризик втрат. Рекомендується інвестувати з режимом Dual Asset.',
  continue_anyway: 'Продовжити все ж таки',
  insufficient_order_book_liquidity_decrease_investment:
    'Нестача ліквідності ордерної книги. Зменшити інвестиції.',
  initial_buy: 'Початкова покупка',
  closing_sell: 'Закриття продажу',
  No: 'Ні',
  DCA_TRIGGER_FAIL_TIPS_PRICE_XXX:
    'Ордери DCA зазнають невдачі, якщо ціна <b>$XXX впаде нижче $PRICE</b> під час виконання.',
  zero_fee: 'Нульова комісія',
  minimum_order_value_is_VALUE:
    'Мінімальна сума ордера становить <b>$VALUE</b>.',
  Note: 'Примітка',
  Continue: 'Продовжити',
  estimated_apy: 'Оцінений APY',
  based_on_data_from_last_7_days: 'На основі даних останніх 7 днів',
  top_gainers_24h: 'Топ зросту за 24 години',
  top_losers_24h: 'Топ з падіння за 24 години',
  listed_tokens: 'Перераховані токени',
  vol: 'Обсяг',
  let_s_go: 'Рушаймо',
  reject: 'Відхилити',
  maximum_N_due_to_price_ticks: 'Максимум N через цінові тики',
  Saved: 'Збережено',
  minimum_order_value_$100_$QUOTE:
    'Мінімальна сума ордера становить <b>$100 $QUOTE</b>',
  minimum_order_value_$AMOUNT_$QUOTE_$100:
    'Мінімальна сума ордера становить <b>$AMOUNT $QUOTE</b> (~$$100)',
  no_restriction_with_market_order:
    'Немає обмежень для <b>ринкового ордера</b>',
  go_to_market_order: 'Перейти до ринкового ордера',
  Mining_Eligibility: 'Право на майнінг',
  How_to_earn_mining_rewards: 'Як заробити винагороди за майнінг',
  Order_Value: 'СУМА ОРДЕРА',
  'mining.mining_tips_BV_BASE_QV_QUOTE':
    'Ордери сітки повинні бути не менше ніж <b>BV BASE</b> або <b>QV QUOTE</b> на момент створення стратегії.',
  'mining.mining_tips_QV_QUOTE':
    'Ордери сітки повинні бути не менше ніж <b>QV QUOTE</b> на момент створення стратегії.',
  Mining_Price_Range: 'ЦІНОВИЙ ДІАПАЗОН МАЙНІНГУ',
  'mining.status_over_price_tips':
    'Ціни ордерів сітки повинні бути в межах <b>цінового діапазону майнінгу</b>, який складає від найвищої ціни покупки * 0.99 до найнижчої ціни продажу * 1.01 в ордерній книзі.',
  'mining.status_over_price_tips_stable':
    'Ціни ордерів сітки повинні бути в межах <b>цінового діапазону майнінгу</b>, який складає від найвищої ціни покупки до найнижчої ціни продажу в ордерній книзі.',
  Eligible_for_Mining: 'Доступний для майнінгу',
  Mining_Satus: 'Статус майнінгу',
  Mining_Satus_Mining: 'Майнінг',
  Mining_Satus_Standby: 'Очікування',
  Mining_Satus_Ineligible: 'Не дозволено',
  mining_price_range: 'Ціновий діапазон майнінгу',
  rewards_tips_stable:
    'Ордера сітки, які відповідають критерію вартості ордера для майнінгу на момент створення стратегії, отримають винагороди за майнінг, якщо вони потрапляють в ціновий діапазон майнінгу (найвища ціна покупки ~ найнижча ціна продажу).',
  rewards_tips:
    'Ордера сітки, які відповідають критерію вартості ордера для майнінгу на момент створення стратегії, отримають винагороди за майнінг, якщо вони потрапляють в ціновий діапазон майнінгу (найвища ціна покупки * 0.99 ~ найнижча ціна продажу * 1.01).',
  wrap: 'обгорнути',
  Wrap: 'Обгорнути',
  websites_for_more_information:
    'Вебсайти для отримання додаткової інформації:',
  official_site: 'Офіційний сайт',
  wrap_site: 'Сайт обгортання/розгортання',
  tips_third_party_site:
    'Ви збираєтеся залишити DeGate і перейти на сторонній сайт:',
  wrap_unwrap: 'Обгортання/розгортання',
  Receive: 'Отримати',
  Network: 'Мережа',
  Token_Contract: 'Контракт токена',
  please_select_network: 'Будь ласка, виберіть мережу',
  maximum_amount: 'Максимальна сума',
  send_USDC_to_this_address: 'Відправити USDC на цю адресу',
  arpa_airdrop: '$ARPA Аірдроп',
  Failed_to_proceed: 'Не вдалося продовжити.',
  Please_select_the_Ethereum_network: 'Будь ласка, виберіть мережу Ethereum.',
  NATIVE_USDC_ONLY: 'Тільки нативний токен USDC',
  NEVER_send_bridged_USDC: 'НІКОЛИ не відправляйте USDC через міст',
  I_understand: 'Я розумію',
  recipient_address: 'Адреса отримувача',
  chain_0: 'DeGate',
  chain_1: 'Ethereum',
  chain_17000: 'Ethereum',
  chain_42: 'Kovan',
  chain_42161: 'Arbitrum',
  chain_421614: 'Arbitrum',
  chain_10: 'Optimism',
  chain_11155420: 'Optimism',
  chain_137: 'Polygon',
  chain_80002: 'Polygon',
  scan_1: 'Etherscan',
  scan_17000: 'Etherscan',
  scan_42161: 'Arbiscan',
  scan_421614: 'Arbiscan',
  scan_10: 'Opscan',
  scan_11155420: 'Opscan',
  scan_tips:
    'Транзакція у Rollup, що містить цю дію, ще не була опублікована на Ethereum. Поки це не станеться, DGSCAN <b>НЕ</b> відобразить цю дію.',
  Best_Liquidity: 'Найкраща ліквідність',
  order_partially_filled: 'Ордер частково виконано',
  order_partially_filled_for_liquidity:
    'Ваш залишившийся ордер було скасовано через раптове падіння ліквідності в ордер-буці. Це захисний захід, який запобігає виконанню за несприятливими цінами.',
  'orders.export_data_2_year': 'Експортувати дані за останні 2 роки',
  Community: 'Спільнота',
  complete_in_seconds: 'Завершити за кілька секунд',
  failed_to_send: 'Не вдалося надіслати. Будь ласка, спробуйте ще раз.',
  failed_to_send_try_other_networks:
    'Не вдалося надіслати. Будь ласка, спробуйте інші мережі.',
  gas_fee_deducted: 'Комісія за газ знята:',
  sum_XXX: 'Сума XXX',
  chart_control_7d: '7 днів',
  chart_control_30d: '30 днів',
  chart_control_all: 'всі',
  chart_control_day: 'Д',
  chart_control_week: 'Т',
  chart_control_month: 'М',
  Coming: 'Прийдуть',
  leave_survey_title: 'Привіт, виглядає так, ніби ви залишаєте DeGate.️',
  leave_survey_subtitle:
    'Будь ласка, допоможіть нам стати кращими, заповнивши відгук. Виберіть все, що підходить.',
  leave_survey_not_leaving: 'Я не залишаю, я повернусь, дурнику.',
  leave_survey_other_is_fine: 'Binance/OKX/Kraken тощо працює добре для мене.',
  leave_survey_bad_experience: 'Мені не подобається торговий досвід.',
  leave_survey_no_yield: 'Я не знайшов жодних можливостей для прибутку.',
  leave_survey_no_needed_token: 'Я не знайшов токени, які хочу торгувати.',
  leave_survey_other_reason: 'Інше (будь ласка, повідомте нас у полі нижче)',
  leave_survey_thanks_for_feedback: 'Дякуємо за ваш відгук',
  Submitted: 'Відправлено',
  doc_title:
    'DeGate: Децентралізована біржа з книгою ордерів| Безкоштовний крипто-трейдинг бот на GRID і DCA',
  doc_desc:
    'DeGate — це провідна децентралізована біржа з , яка пропонує торгівлю сотнями криптовалют з низькими комісіями, безкоштовну торгівлю лімітними ордерами, сітковими Grid стратегіями та ботами DCA.',
  doc_title_spot: 'Децентралізований ордер-бук | DeGate DEX',
  doc_title_grid: 'Децентралізований Grid Торговий Бот | DeGate DEX',
  doc_title_dca: 'Децентралізований DCA Торговий Бот | DeGate DEX',

  Notification: '',
  read_all: '',
  important: '',
  general: '',
  view_more: 'Більше',
  thats_all: '',
  XXX_fund_addition_processing: '',
  add_AMOUNT_XXX_to_DeGate: '',
  XXX_fund_addition_successful: '',
  XXX_send_successful: '',
  send_AMOUNT_XXX_to_DeGate: '',
  send_AMOUNT_XXX_to_Ethereum: '',
  you_have_received_a_new_airdrop: '',
  AMOUNT_XXX_can_be_claimed_after_YYYY_MM_DD: '',
  MARKET_Chart: '',
  grid_free: '',
  maker_free_tips: '',
  Audit: '',
  Tool: '',
  About: '',
};
export default uk;
