const en = {
  language: 'de-DE',
  choose_token: 'Token Auswählen',
  recipient: 'Empfänger',
  recent: 'Aktuell',
  price: 'Preis',
  amount: 'Betrag',
  available: 'Verfügbar',
  gas_fee: 'Gasgebühr',
  Send: 'Senden',
  Send_ETH: 'ETH Senden',
  Internal_Transfer: 'Interner Transfer',
  transfer_tips:
    'Token an eine andere Adresse innerhalb des DeGate-Protokolls übertragen.',
  transfer_ETH: 'Interner Transfer ETH',
  btn_max: 'Max',
  degate_insufficient_balance: 'Unzureichendes Guthaben',
  max_digits_exceeded: 'Maximale Stellenzahl überschritten',
  wallet_insufficient_balance: 'Unzureichendes Guthaben in Wallet',
  deGate_insufficient_fees:
    'Unzureichendes DeGate-Guthaben zur Bezahlung der Gasgebühr',
  token_search_placeholder: 'Token suchen, contract Adresse',
  token: 'Token',
  degate_balance: 'DeGate Guthaben',
  tips_gas:
    'Die Gasgebühr für die Ausführung dieser On-Chain-Transaktion wird direkt von Ihrem DeGate-Guthaben abgezogen.',
  tips_gas2:
    'Die Gasgebühr deckt die On-Chain-Kosten für Handelsabwicklungen. Überschüssige Gebühren werden zurückerstattet.',
  Close: 'Schließen',
  Help: 'Hilfe',
  no_token: 'Token nicht gefunden',
  Cancel: 'Abbrechen',
  go_back: 'Zurückgehen',
  Back: 'Zurück',
  copied: 'Kopiert',
  Confirm: 'Bestätigen',
  Create: 'Erstellen',
  Abort: 'Abbrechen',
  btn_confirm: 'Schließen',
  btn_got_it: 'Verstanden',
  wallet_cancelled_tips: 'Sie haben die Signatur storniert',
  connect_ledger: 'Ledger verbinden',
  ledger_disconnect:
    "Fehler bei der Ausführung von 'transferOut' auf 'USBDevice': Die Verbindung zum Gerät wurde unterbrochen.",
  wallet_tips: 'Bitte mit Browser Wallet genehmigen',
  wallet_ledger_tips: 'Bitte mit Ledger Hardware genehmigen',
  wallet_metamask_tips: 'Bitte in Metamask genehmigen',
  wallet_walletconnect_tips:
    'Bitte gehen Sie zu Ihrer Wallet, um Walletconnect zu genehmigen',
  view_asset_key: 'Asset Key anzeigen',
  export_key_warning:
    'Ein Verlust des Asset Keys kann zu Vermögensverlusten führen. Bitte bewahren Sie den Schlüssel sicher auf.',
  export_key_confirm_btn: 'Weiter zur Ansicht',
  btn_buy_ETH: 'ETH Kaufen',
  btn_sell_ETH: 'ETH Verkaufen',
  around: '～',
  need_help: 'Hilfe',
  time_now: 'Jetzt',
  time_1_minute: '1 Minute',
  time_1_hour: '1 Stunde',
  time_1_day: '1 Tag',
  time_1_year: '1 Jahr',
  time_M_minutes: 'M Minuten',
  time_M_m: 'Mm',
  time_H_hours: 'M Stunden',
  time_H_h: 'Hh',
  time_D_days: 'D Tage',
  time_D_d: 'Dd',
  time_Y_years: 'Y Jahre',
  time_Y_y: 'Yy',
  personal_sign_reason: 'Mögliche Gründe',
  personal_sign_reason1: '1. MetaMask ist mit einer Hardware Wallet verbunden',
  personal_sign_reason2: '2. MetaMask Version ist veraltet',
  personal_sign_reason3: '3. Andere',
  personal_sign_btn: 'Erneut signen',
  switch_wallet: 'Account wechseln',
  switch_walletConnect_tips1:
    'Wenn Sie zu einem anderen Konto in derselben Wallet-Software wechseln möchten, führen Sie dies bitte direkt aus der Wallet aus und brechen Sie diese Anfrage ab.',
  switch_walletConnect_tips2:
    'Wenn Sie WalletConnect über eine andere Wallet-Software verwenden möchten, trennt das System zunächst die bestehende Verbindung.',
  switch_walletConnect_continue: 'Trennen und fortfahren',
  switch_metamask_tips:
    'Bitte gehen Sie zu MetaMask, um Ihr Konto zu wechseln.',
  switch_browser_wallet_tips: 'Bitte wechseln Sie das Konto im Browser-Wallet.',
  period_expired: 'Abgelaufen',
  period_D_day_H_hour: 'Dd Hh',
  period_H_hour_M_minute: 'Hh Mm',
  login_success: 'Erfolgreich verbunden',
  advanced: 'Erweitert',
  edit: 'Bearbeiten',
  save: 'Speichern',
  speed_up: 'Beschleunigen',
  continue: 'Fortsetzen',
  Submit: 'Einreichen',
  icon_copy: 'Adresse kopieren',
  icon_view_explorer: 'Im Block Explorer anzeigen',
  upcoming_lock_tips:
    'Aufgrund Inaktivität wird der Signaturfreie Modus zu Ihrer Sicherheit deaktiviert.',
  auto_locked_tips:
    'Zu Ihrer Sicherheit wurde der signaturfreie Modus nach 15 Minuten Inaktivität deaktiviert.',
  keep: 'Behalten',
  turn_off_now: 'Ausschalten',
  turn_on: 'Anschalten',
  turn_on_signature_free_mode: 'Signaturfreien Modus anschalten',
  turn_on_signature_free_mode_success: 'Signaturfreier Modus angeschaltet',
  max_XXX: 'Max XXX',
  min_XXX: 'Min XXX',
  common_err: 'Irgendetwas ist schiefgelaufen. Versuchen Sie es später erneut.',
  input_auto_corrected_tips:
    'Automatische Korrektur Ihrer Eingabe nach Überschreiten der maximalen Ziffernanzahl',
  maximum_decimal_reached: 'Maximale Dezimalstellen erreicht',
  verify_ownership: 'Eigentümerschaft bestätigen',
  execute: 'Ausführen',
  sign_step1: 'In Ihrer Wallet abschließen',
  sign_step2: '2. Signatur abschließen',
  sign_step3: '3. Signatur abschließen',
  place_order: 'Order aufgeben',
  create_spot_order: 'Order aufgeben',
  create_grid_strategy: 'Gridstrategie erstellen',
  create_DCA_plan: 'DCA Plan erstellen',
  cancel_order: 'Order abbrechen',
  end_grid_strategy: 'Gridstrategie beenden',
  end_DCA: 'DCA Plan beenden',
  complete_in_seconds: 'In Sekunden erledigt',
  complete_in: 'Erledigt in',
  me: 'Ich',
  eth_code_tips: 'Nativer Token von Ethereum. Keine Token-Vertragsadresse.',
  total: 'Gesamt',
  order_amount: 'Orderbetrag',
  operation_has_expired: 'Der Vorgang ist abgelaufen',
  Approve: 'Genehmigen',
  tips_hide_forever: 'Nicht mehr anzeigen',
  Tips: 'Tipp',
  Note: 'Notiz',
  Summary: 'Zusammenfassung',
  Orders: 'Orders',
  Side: 'Seite',
  Sell: 'Verkaufen',
  Buy: 'Kaufen',
  now: 'Jetzt',
  order_type: 'Auftragstyp',
  limit_order: 'Limit',
  market_order: 'Market',
  required: 'Erforderlich',
  check_address_format: 'Adressformat prüfen',
  start_time: 'Startzeit',
  end_time: 'Endzeit',
  None: 'Keine',
  time_out: 'Zeitüberschreitung. Bitte versuchen Sie es erneut.',
  deposit_ETH: 'ETH hinzufügen',
  'grid.confirm_grid': 'Gridstrategie bestätigen',
  'grid.initial_investment': 'Investment',
  'grid.price_range': 'Preisspanne',
  'grid.grid_level': 'Anzahl der Grids',
  'grid.grid_volume': 'Menge pro Grid',
  'grid.profit_per_grid': 'Profit pro Grid',
  'grid.expired_in': 'Läuft ab in',
  'grid.replace_modal_title': 'Gridstrategie aktualisiert',
  'grid.replace_modal_content':
    'Aufgrund der jüngsten Änderungen im Orderbuch wurde die ursprüngliche Gridstrategie wie folgt aktualisiert.',
  'grid.replace_modal_pre': 'Davor',
  'grid.replace_modal_next': 'Danach',
  'grid.replace_modal_err':
    'Unzureichendes Guthaben zum Erstellen der Gridstrategie. Bitte kehren Sie zurück, um die Gridparameter zu bearbeiten.',
  'ledger.connect_rule_1': '1. Verbinden Sie Ledger mit Ihrem Gerät',
  'ledger.connect_rule_2': '2. Im Ledger freischalten',
  'ledger.connect_rule_3': '3. Ethereum-App in Ledger öffnen',
  'ledger.connect_rule_4':
    '4. Stellen Sie sicher, dass Blind Signing/Contract Data und Browser Support aktiviert sind',
  'ledger.unable_to_approve': 'Genehmigung nicht möglich',
  'ledger.webusb_1tab_tips_desc_1':
    'Dieser Browser unterstützt nur einen einzigen „Browser-Tab“ für die Ledger-Genehmigung. Genehmigung nicht möglich, da ein anderer Tab diese Funktion nutzt.',
  'ledger.webusb_1tab_tips_desc_2':
    'Bitte versuchen Sie, das Ledger erneut anzuschließen, um den Vorgang neu zu starten.',
  'ledger.locked_tips':
    'Bitte entsperren Sie Ledger, öffnen Sie die Ethereum-App und genehmigen Sie.',
  'ledger.account_not_match':
    'Falsches Ledger-Wallet erkannt. Bitte stellen Sie eine Verbindung zum richtigen Ledger her.',
  'ledger.ledger_choose_address': 'Wählen Sie eine Adresse',
  'ledger.address': 'Adresse',
  'ledger.connect': 'Verbinden',
  'ledger.un_supported_title':
    'Ledger Wallet Verbindung wird vom aktuellen Browser nicht unterstützt',
  'ledger.un_supported_desc':
    'Wir empfehlen die Verwendung der Browser Chrome und Edge.',
  'ledger.confirm_gas_fee': 'Gasgebühr bestätigen',
  'ledger.confirm_gas_fee_desc':
    'Sie sind dabei, eine Transaktion auf Ethereum einzuleiten. Bitte bestätigen Sie:',
  'ledger.max_gas_fee': 'Maximale Gasgebühr',
  'ledger.edit_gas_fee': 'Gasgebühr bearbeiten',
  'ledger.max_fee': 'Gaspreis (Gwei)',
  'ledger.max_base_fee': 'Maximale Base Fee (Gwei)',
  'ledger.max_base_fee_tips':
    'Wenn Ihre Transaktion in den Block aufgenommen wird, wird Ihnen die Differenz zwischen Ihrer maximalen Base Fee und der tatsächlichen Base Fee zurückerstattet.',
  'ledger.priority_fee': 'Prioritätsgebühr (Gwei)',
  'ledger.priority_fee_tips':
    'Die Prioritätsgebühr (auch „Miner-Trinkgeld“ genannt) geht direkt an die Miner und bietet ihnen einen Anreiz, Ihrer Transaktion Priorität einzuräumen.',
  'ledger.gas_limit': 'Gaslimit:',
  'ledger.tx_speed_up_title': 'Transaktion beschleunigen',
  'ledger.tx_speed_up_desc':
    'Sie sind dabei, eine Transaktion auf Ethereum zu beschleunigen. Bitte bestätigen Sie:',
  'ledger.tx_cancel_title': 'Transaktion abbrechen',
  'ledger.tx_cancel_desc':
    'Sie sind dabei, eine Transaktion auf Ethereum abzubrechen, bitte bestätigen Sie:',
  'ledger.fee_minimum_xxx': 'Kann nicht weniger sein als XXX',
  'ledger.ledger_app_version_tips':
    'Aktualisieren Sie die Ethereum-App Ihres Ledgers auf Version 1.9.19 oder höher, um vor dem Signieren eine Vorschau der Nachricht anzuzeigen.',
  'operations.register_pair': 'Handelspaar hinzufügen',
  'operations.chain_cancel': 'Order on-chain abbrechen',
  'operations.chain_cancel_title':
    'Diese Anfrage zum abbrechen der Order wird on-chain veröffentlicht, um die Stornierung der Order zu garantieren.',
  'operations.chain_cancel_confirm': 'Stornierung bestätigen',
  'operations.chain_cancel_confirm_tips':
    'Bei einer On-Chain-Stornierung fällt eine Gasgebühr an. Möchten Sie fortfahren?',
  'operations.chain_cancel_grid_text_N':
    '<b>N orders</b> in dieser Gridstrategie werden zur On-Chain-Stornierung übermittelt.',
  'operations.chain_cancel_grid_gas_AMOUNT_ETH':
    'Bitte bestätigen Sie noch einmal die On-Chain-Stornierungsgasgebühr von <b>AMOUNT ETH</b>.',
  'operations.claim_title': 'Belohnungen anfordern',
  'operations.claim_desc':
    'Die Belohnungen werden Ihrem DeGate-Guthaben per interner Überweisung gutgeschrieben, wobei die Gasgebühren direkt von der Belohnung abgezogen werden.',
  'operations.claim_desc_others':
    'Dieser Anspruch wird durch eine interne Überweisung Ihrem DeGate-Guthaben gutgeschrieben.',
  'operations.claim_rewards': 'Verfügbare Belohnungen',
  'operations.claim_err_amount':
    'Nicht genügenden Betrag für Anspruch verfügbar',
  'operations.claim': 'Anspruch',
  'operations.Claimable': 'beanspruchbar',
  'operations.Unclaimed': 'Nicht beansprucht',
  'operations.claim_mining_rewards': 'Beanspruchen Sie Mining-Belohnungen',
  'operations.claim_rewards_desc':
    'Die Belohnungen werden nach Abzug der Gasgebühren auf Ihren Account überwiesen',
  'operations.pay_deposit': 'Abwicklung',
  'operations.pay_deposit_title': 'Ausstehende Zahlung',
  'operations.pay_deposit_desc_XXX_ETH':
    'Sie haben eine ausstehende Fondseinzahlung von XXX ETH.',
  'operations.pay_deposit_select_account': 'Bezahlen von',
  Wallet_Balance: 'Wallet-Guthaben',
  'operations.pay_deposit_tips_XXX_ETH': 'Bezahle XXX ETH',
  'operations.reset_account': 'Asset Key zurücksetzen',
  'operations.reset_desc':
    'Der Asset-Key befindet sich im Cache Ihres Browsers. Wenn die Sicherheit Ihrer lokalen Umgebung fraglich ist, setzen Sie den Asset-Key bitte zurück.',
  'operations.reset_warning':
    'Sämtliche Vorgänge wie Handeln, Senden oder internes Übertragen werden während der Zurücksetzung ausgesetzt.',
  'operations.reset_estimated_time': 'Geschätzte Zeit',
  'operations.reset_order_tips':
    'Sobald der Reset eingeleitet ist, werden alle offenen Aufträge und Grid-Strategien storniert.',
  'operations.reset_order_tips_btn2': 'Abbrechen',
  'operations.claim_dg_rewards': 'DG Belohnungen beanspruchen',
  'operations.claim_REBASE': 'REBASE beanspruchen',
  'operations.claim_REBASE_desc':
    'REBASE wird per interner Überweisung an Ihr DeGate-Guthaben gesendet.',
  'operations.claim_REBASE_tips':
    'Nicht beanspruchte REBASE werden bei der Ertragsberechnung berücksichtigt.',
  'operations.view_yield_history': 'Renditehistorie anzeigen',
  'operations.cancel_orders_on_chain': 'Orders on-chain canceln',
  'operations.chain_cancel_dca_text_N':
    '<b>N Orders</b> in diesem DCA-Plan werden zur On-Chain-Stornierung übermittelt.',
  'operations.confirm_cancel_gas_AMOUNT_ETH':
    'Bitte bestätigen Sie die On-Chain-Stornierungsgasgebühr von <b>AMOUNT ETH</b> noch einmal.',
  'trade.confirm_order': 'Auftrag bestätigen',
  'trade.stop_limit_order': 'Stop Limit',
  'trade.stop_price': 'Preis Stop',
  'trade.limit_price': 'Limit Preis',
  'trade.market_price': 'Marktpreis',
  'trade.total': 'Gesamt',
  'trade.pay': 'Bezahlen',
  'trade.receive': 'Erhalten',
  'trade.hide_pair_confirm': 'Für dieses Paar nicht mehr anzeigen',
  'trade.pay_the_following_amount_to_place_order':
    'Zahlen Sie den folgenden Betrag, um die Order aufzugeben:',
  'trade.flow_of_funds': 'Geldfluss',
  'trade.flow_of_funds_tip2':
    'Ihre Order wurde aufgegeben. Orderbeträge werden Ihrem DeGate-Guthaben und nicht Ihrem Wallet-Guthaben gutgeschrieben.',
  'trade.pay_to_place_order': 'Bezahlen, um Order aufzugeben',
  'trade.pay_xxx_USDC_to_place_order': 'xxx USDC bezahlen um Order aufzugeben',
  'trade.deposit_type': 'Methode',
  'trade.deposit_type_standard': 'Standard',
  'transfer.transfer_1_eth_ACCOUNT': 'Überweisen Sie 1 ETH an',
  'transfer.internal_transfer_address_new_tips':
    'Diese Adresse hat keinen vorherigen DeGate-Verlauf. Für die Übertragung an diese Adresse fallen zusätzliche Gasgebühren an.',
  address_placeholder: 'Adresse eingeben',
  'transfer.to_new_account_tips':
    'Diese Adresse hat keinen vorherigen DeGate-Verlauf. Da der erste Vermögenswertempfang eine zusätzliche On-Chain-Datennutzung auslöst, fallen bei der Durchführung dieser internen Übertragung zusätzliche Gasgebühren an.',
  'transfer.confirm_internal_transfer': 'Interne Überweisung bestätigen',
  'transfer.internal_transfer_address_oneself_tips':
    'Eine interne Überweisung an Sie selbst wird nicht unterstützt.',
  'transfer.transfer_max_err_XXX_USDT':
    'Interne Überweisungen sind auf XXX USDT pro Überweisung begrenzt',
  'transfer.before': 'Bevor',
  'transfer.after': 'Danach',
  'transfer.recipient_cex_warning':
    'Achtung: Bitte überweisen Sie nicht an eine Centralized Exchange. Sie verlieren das Geld.',
  'withdraw.withdraw_max_tips': 'Systemlimit überschritten',
  'dca.confirm_dca_plan': 'DCA-Plan bestätigen',
  'dca.number_of_orders': 'Anzahl der Orders',
  'dca.amount_per_order': 'Menge pro Order',
  'dca.time_scheduled': 'Geplante Zeit',
  'dca.creating_the_plan': 'Erstellen des Plans...',
  'dca.maximum_price': 'Maximaler Preis',
  'dca.minimum_price': 'Minimaler Preis',
  'dca.do_not_close': 'Schließen oder aktualisieren Sie diese Seite NICHT.',
  'dca.frequency': 'Frequenz',
  total_amount: 'Gesamtmenge',
  'dca.daily': 'Täglich',
  'dca.weekly': 'Wöchentlich',
  'dca.every': 'Jede',
  'airdrop.review_airdrop': 'Airdrop bewerten',
  'airdrop.create_airdrop': 'Airdrop erstellen',
  'airdrop.recipients_number': 'Anzahl der Empfänger',
  'airdrop.airdrop_fee': 'Airdrop Gebühr',
  'airdrop.pay_airdrop_fee': 'Airdropgebühr bezahlen',
  'airdrop.send_airdrop_token': 'Airdrop Token schicken',
  'airdrop.claim_airdrop': 'Airdrop claimen',
  'airdrop.retrieve': 'Abrufen',
  'countdown.create_countdown_plan': 'Countdown-Plan erstellen',
  'countdown.countdown_display': 'Countdown Display',
  'countdown.max_30_days': 'Kann nicht mehr als 30 Tage in der Zukunft liegen',
  'countdown.review_countdown_plan': 'Countdown-Plan überprüfen',
  'countdown.countdown_fee': 'Countdown Gebühr',
  grid_slippage_over_2_tips_SLIPPAGE_QUOTE_BASE:
    'Das System tauscht zunächst mithilfe einer Marktorder einen Teil von QUOTE gegen BASE mit einer geschätzten Slippage von SLIPPAGE.',
  grid_slippage_over_5_tips_SLIPPAGE_QUOTE_BASE:
    'Das System tauscht zunächst einen Teil von QUOTE gegen BASE unter Verwendung einer Marktorder mit einer geschätzten Slippage von SLIPPAGE. Es wird empfohlen, im Dual Asset-Modus zu investieren.',
  connected: 'Verbunden',
  browser_wallet: 'Browser Wallet',
  Convert_to_YYY: 'Konvertieren in YYY',
  sell_XXX_to_YYY: 'Möchten Sie Ihr XXX zum Marktpreis in YYY verkaufen?',
  you_sell: 'Du verkaufst',
  you_receive: 'Du erhältst',
  est_slippage: 'Geschätzte Slippage',
  No: 'No',
  closing_sell: 'Verkaufsabschluss',
  connect_wallet: 'Wallet verbinden',
  Add: 'Hinzufügen',
  Add_Funds: 'Guthaben hinzufügen',
  send_USDC_to_this_address: 'Senden Sie USDC an diese Adresse',
  Failed_to_proceed: 'Fortfahren fehlgeschlagen.',
  Please_select_the_Ethereum_network:
    'Bitte wählen Sie das Ethereum-Netzwerk aus.',
  NATIVE_USDC_ONLY: 'NUR natives USDC-Token',
  NEVER_send_bridged_USDC: 'Senden Sie NIEMALS bridged USDC',
  Network: 'Netzwerk',
  Arrival_Time: 'Ankunftszeit',
  Token_Contract: 'Token Contract',
  please_select_network: 'Bitte wählen Sie ein Netzwerk',
  maximum_amount: 'Maximaler Betrag',
  Select: 'Auswählen',
  cannot_send_to_yourself:
    'Sie können innerhalb des DeGate-Netzwerks kein Geld an sich selbst senden.',
  max_amount_exceeded: 'Maximalbetrag überschritten',
  do_not_trasnfer_to_cex:
    'Bitte <b>KEINE</b> Überweisungen an Centralized Exchanges durchführen. Es besteht die Gefahr eines Geldverlusts. Sie könnten Ihr Geld verlieren.',
  I_understand: 'Ich verstehe',
  Continue: 'Fortfahren',
  chain_0: 'DeGate',
  chain_1: 'Ethereum',
  chain_17000: 'Ethereum',
  chain_42: 'Kovan',
  chain_42161: 'Arbitrum',
  chain_421614: 'Arbitrum',
  chain_10: 'Optimism',
  chain_11155420: 'Optimism',
  chain_137: 'Polygon',
  chain_80002: 'Polygon',
  deposit_tips_region:
    'Bitte beachten Sie, dass Sie auf DeGate in REGION zugreifen. Die Handels- und internen Überweisungsfunktionen sind nach der Einzahlung des Guthabens nicht mehr verfügbar.',
  deposit_1_ETH: 'Fügen Sie Ihrem DeGate-Guthaben 1 ETH hinzu',
  'account.deposit_contract_tips_over_AMOUNT':
    'Für Fondserhöhungen über AMOUNT USD ist die Advanced Methode erforderlich.',
  'account.deposit_contract_tips_only_all':
    'Es wird nur die Advanced Methode für Fondserhöhungen unterstützt.',
  Approved: 'Genehmigt',
  Deposit: 'Hinzufügen',
  'account.deposit_tips': 'Sie behalten die volle Kontrolle über diese Gelder.',
  'account.deposit_arrive_in_30s_s': 'Ankunft in ca. 30 Sekunden',
  reset_approval_USDT: 'USDT-Genehmigung zurücksetzen',
  reset_approval_USDT_tips:
    'USDT erfordert eine Zurücksetzung der Genehmigung, wenn die Ausgabenlimits zu niedrig sind.',
  token_has_not_listed: 'Dieses Token ist nicht auf DeGate gelistet.',
  list_now: 'Jetzt listen',
  Retry: 'Wiederholen',
  switch_network: 'Netzwerk wechseln',
  switch_to_MAINNET_in_metamask: 'Bitte wechseln Sie in MetaMask zu MAINNET',
  switch_to_MAINNET: 'Bitte wechseln Sie zu MAINNET',
  'account.pay_deposit_warning':
    'Beim Aufladen von Guthaben können zusätzliche Gasgebühren anfallen.',
  send_method: 'Methode',
  Economy: 'Wirtschaft',
  Fast: 'Schnell',
  Instant: 'Sofort',
  less_than_X_hours: '< X Stunden',
  less_than_1_hour: '< 1 Stunde',
  Economy_tips:
    'DeGate verarbeitet Sendeanfragen mindestens alle 4 Stunden, oft sogar früher. Wenn beispielsweise ein anderer Benutzer einen Fast Send initiiert, wird Ihre Economy Send-Anfrage ebenfalls sofort verarbeitet.',
  wrap: 'wrap',
  just_a_moment: 'Einen Augenblick',
  wait_confirmation_from_wallet: 'Warte auf die Bestätigung vom Wallet',
  s: 's',
  doc_title:
    'DeGate: Dezentrale Orderbuchbörse | Kostenloser Krypto-Trading-Bot auf GRID und DCA',
  doc_desc:
    'DeGate ist eine führende dezentrale Orderbuchbörse, die den Handel mit Hunderten von Kryptowährungen zu niedrigen Gebühren anbietet, mit kostenlosem Limit-Order-Handel, Grid-Trading und DCA-Bots.',
  doc_title_spot: '| Dezentrales Orderbuch | DeGate DEX',
  doc_title_grid: '| Dezentraler Grid-Trading-Bot | DeGate DEX',
  doc_title_dca: '| Dezentraler DCA-Handelsbot | DeGate DEX',

  view_asset_key_tips:
    '<div>Hier sind die Details Ihres Asset-Keys. <strong>Geben Sie ihn NICHT</strong> an Dritte weiter, um einen möglichen Vermögensverlust zu verhindern.</div>',
  personal_sign_tips:
    '<div>MetaMask fordert Sie auf, erneut mit der Methode <i>Persönliche Signatur</i> zu signen</div>',
  sign_and_open_free_mode_tips:
    'Eine Signatur ist nicht erforderlich, da nach dieser Aktion der signaturfreie Modus aktiviert wird.<br/><br/>Um den Modus zu wechseln, navigieren Sie zu &quot;Einstellungen&quot; unter der Schaltfläche „Handeln“.',
  'trade.i_understand': '<span>Ich verstehe die </span>',
  'trade.flow_of_funds_tips':
    '<h3>Geldfluss</h3>Gelder gehen auf Ihr DeGate-Guthaben, nicht auf Ihr Wallet-Guthaben.<br/><br/><h3>Über das DeGate-Guthaben</h3>Das DeGate-Guthaben stellt den Wert dar, den Benutzer im DeGate-Smart-Contract halten.<br/>Dank des vollständig dezentralisierten DeGate-Smart-Contracts behalten Benutzer die vollständige Kontrolle über ihr DeGate-Guthaben.',
};
export default en;
