const ja = {
  language: 'ja-JP',
  choose_token: 'トークンを選択',
  recipient: '受取人',
  recent: '最近',
  price: '価格',
  amount: '金額',
  available: '利用可能',
  gas_fee: 'ガス料金',
  Send: '送信',
  Send_ETH: 'ETH を送信',
  Internal_Transfer: '内部転送',
  transfer_tips: 'DeGate プロトコル内の別のアドレスにトークンを転送します。',
  transfer_ETH: 'ETH を内部転送',
  btn_max: '最大',
  degate_insufficient_balance: '残高不足',
  max_digits_exceeded: '桁数オーバー',
  wallet_insufficient_balance: 'ウォレット内の残高不足',
  deGate_insufficient_fees:
    'ガス料金を支払うのに十分な DeGate 残高がありません',
  token_search_placeholder: 'トークン、コントラクトアドレスを検索',
  token: 'トークン',
  degate_balance: 'DeGate 残高',
  tips_gas:
    'このオンチェーントランザクションのガス料金は、DeGate 残高から直接差し引かれます。',
  tips_gas2:
    'ガス料金は、取引決済のオンチェーンコストをカバーします。余剰料金は返金されます。',
  Close: '閉じる',
  Help: 'ヘルプ',
  no_token: 'トークンが見つかりません',
  Cancel: 'キャンセル',
  go_back: '戻る',
  Back: '戻る',
  copied: 'コピーしました',
  Confirm: '確認',
  Create: '作成',
  Abort: '中止',
  btn_confirm: '閉じる',
  btn_got_it: 'わかりました',
  wallet_cancelled_tips: '署名がキャンセルされました',
  connect_ledger: 'Ledgerを接続してください',
  ledger_disconnect:
    "USBDevice'の'transferOut'を実行できませんでした：デバイスが切断されました。",
  wallet_tips: 'ブラウザウォレットで承認してください',
  wallet_ledger_tips: 'Ledgerハードウェアで承認してください',
  wallet_metamask_tips: 'MetaMaskで承認してください',
  wallet_walletconnect_tips:
    'WalletConnectでウォレットに移動して承認してください',
  view_asset_key: 'アセットキーを表示',
  export_key_warning:
    'アセットキーが漏洩すると、資産が失われる可能性があります。安全に保管してください。',
  export_key_confirm_btn: '表示を続行',
  btn_buy_ETH: 'ETHを購入',
  btn_sell_ETH: 'ETHを売却',
  around: '周辺',
  need_help: 'ヘルプ',
  time_now: '今',
  time_1_minute: '1分',
  time_1_hour: '1時間',
  time_1_day: '1日',
  time_1_year: '1年',
  time_M_minutes: 'M分',
  time_M_m: 'Mm',
  time_H_hours: 'H時間',
  time_H_h: 'Hh',
  time_D_days: 'D日',
  time_D_d: 'Dd',
  time_Y_years: 'Y年',
  time_Y_y: 'Yy',
  personal_sign_reason: '可能な理由',
  personal_sign_reason1:
    '1. MetaMaskがハードウェアウォレットに接続されています',
  personal_sign_reason2: '2. MetaMaskのバージョンが古いです',
  personal_sign_reason3: '3. その他',
  personal_sign_btn: '再度署名',
  switch_wallet: 'アカウントを切り替え',
  switch_walletConnect_tips1:
    '同じウォレットソフトウェア内で別のアカウントに切り替えたい場合は、ウォレットから直接実行し、このリクエストをキャンセルしてください。',
  switch_walletConnect_tips2:
    'WalletConnectを別のウォレットソフトウェアで使用する場合、システムは既存の接続から切断します。',
  switch_walletConnect_continue: '切断して続行',
  switch_metamask_tips: 'MetaMaskでアカウントを切り替えてください。',
  switch_browser_wallet_tips:
    'ブラウザウォレットでアカウントを切り替えてください。',
  period_expired: '期限切れ',
  period_D_day_H_hour: 'Dd Hh',
  period_H_hour_M_minute: 'Hh Mm',
  login_success: '接続成功',
  advanced: '詳細',
  edit: '編集',
  save: '保存',
  speed_up: '取引速度を上げる',
  continue: '続行',
  Submit: '送信',
  icon_copy: 'アドレスをコピー',
  icon_view_explorer: 'ブロックエクスプローラーで表示',
  upcoming_lock_tips:
    '不活発な期間のため、署名なしモードがセキュリティのためにオフになります。',
  auto_locked_tips:
    'セキュリティのため、署名なしモードが15分の不活発後にオフになります。',
  keep: '保持',
  turn_off_now: '今すぐオフにする',
  turn_on: 'オフにする',
  turn_on_signature_free_mode: '署名なしモードをオンにする',
  turn_on_signature_free_mode_success: '署名・フリー・モード・オン',
  max_XXX: '最大 XXX',
  min_XXX: '最小 XXX',
  common_err: '何かがうまくいかなかった。後で再試行してください。',
  input_auto_corrected_tips: '最大桁数を超えたため、入力を自動修正しました',
  maximum_decimal_reached: '最大小数点数に達しました',
  verify_ownership: '所有権を確認',
  execute: '実行',
  sign_step1: 'ウォレットで完了',
  sign_step2: '第2署名を完了',
  sign_step3: '第3署名を完了',
  place_order: '注文を出す',
  create_spot_order: '注文を出す',
  create_grid_strategy: 'グリッド戦略を作成',
  create_DCA_plan: 'DCAプランを作成',
  cancel_order: '注文をキャンセル',
  end_grid_strategy: 'グリッド戦略を終了',
  end_DCA: 'DCAプランを終了',
  complete_in_seconds: '秒で完了',
  complete_in: '内訳',
  me: '私',
  eth_code_tips: 'ETHアセットキー',
  total: '合計',
  order_amount: '注文額',
  operation_has_expired: '操作が期限切れになりました',
  Approve: '承認',
  tips_hide_forever: '再表示しない',
  Tips: 'ヒント',
  Note: 'ノート',
  Summary: '概要',
  Orders: '注文',
  Side: 'サイド',
  Sell: '売却',
  Buy: '購入',
  now: '今',
  order_type: '注文タイプ',
  limit_order: 'リミット',
  market_order: 'マーケット',
  required: '必要',
  check_address_format: 'アドレス形式を確認',
  start_time: '開始時間',
  end_time: '終了時間',
  None: 'なし',
  time_out: 'タイムアウト。再試行してください。',
  deposit_ETH: 'ETHを追加',
  'grid.confirm_grid': 'グリッド戦略を確認',
  'grid.initial_investment': '投資',
  'grid.price_range': '価格範囲',
  'grid.grid_level': 'グリッド数',
  'grid.grid_volume': 'グリッドごとの数量',
  'grid.profit_per_grid': 'グリッドごとの利益',
  'grid.expired_in': '期限内',
  'grid.replace_modal_title': 'グリッド戦略が更新されました',
  'grid.replace_modal_content':
    '最近の注文簿の変更により、元のグリッド戦略が次のように更新されました。',
  'grid.replace_modal_pre': '前',
  'grid.replace_modal_next': '後',
  'grid.replace_modal_err':
    'グリッド戦略を作成するための残高が不足しています。グリッドパラメータを編集するために戻ってください。',
  'ledger.connect_rule_1': '1. Ledgerをデバイスに接続してください',
  'ledger.connect_rule_2': '2. Ledgerでロックを解除してください',
  'ledger.connect_rule_3': '3. Ledgerでイーサリアムアプリを開いてください',
  'ledger.connect_rule_4':
    '4. Blind Signing/Contract DataとBrowser Supportが有効になっていることを確認してください',
  'ledger.unable_to_approve': '承認できません',
  'ledger.webusb_1tab_tips_desc_1':
    'このブラウザはLedger承認のための単一の「ブラウザタブ」のみをサポートしています。別のタブがこの機能を使用しているため、承認できません。',
  'ledger.webusb_1tab_tips_desc_2':
    'Ledgerを再接続して操作を再起動してください。',
  'ledger.locked_tips':
    'Ledgerを解除し、イーサリアムアプリを開き、承認してください。',
  'ledger.account_not_match':
    '誤ったLedgerウォレットが検出されました。正しいLedgerに接続してください。',
  'ledger.ledger_choose_address': 'アドレスを選択',
  'ledger.address': 'アドレス',
  'ledger.connect': '接続',
  'ledger.un_supported_title':
    'Ledgerウォレット接続は現在のブラウザでサポートされていません',
  'ledger.un_supported_desc': 'ChromeまたはEdgeブラウザの使用をお勧めします。',
  'ledger.confirm_gas_fee': 'ガス料金を確認',
  'ledger.confirm_gas_fee_desc':
    'イーサリアムで取引を開始しようとしています。確認してください：',
  'ledger.max_gas_fee': '最大ガス料金',
  'ledger.edit_gas_fee': 'ガス料金を編集',
  'ledger.max_fee': 'ガス価格（Gwei）',
  'ledger.max_base_fee': '最大ベース料金（Gwei）',
  'ledger.max_base_fee_tips':
    '取引がブロックに含まれると、最大ベース料金と実際のベース料金の間の差額は返金されます。',
  'ledger.priority_fee': '優先料金（Gwei）',
  'ledger.priority_fee_tips':
    '優先料金（別名「マイナーのチップ」）は、マイナーに直接支払い、取引を優先するように促します。',
  'ledger.gas_limit': 'ガスリミット：',
  'ledger.tx_speed_up_title': '取引をスピードアップ',
  'ledger.tx_speed_up_desc':
    'イーサリアムで取引をスピードアップしようとしています。確認してください：',
  'ledger.tx_cancel_title': '取引をキャンセル',
  'ledger.tx_cancel_desc':
    'イーサリアムで取引をキャンセルしようとしています。確認してください：',
  'ledger.fee_minimum_xxx': 'XXX未満にはできません',
  'ledger.ledger_app_version_tips':
    'Ledgerのイーサリアムアプリをバージョン1.9.19以上に更新して、署名前にメッセージをプレビューしてください。',
  'operations.register_pair': '取引ペアを追加',
  'operations.chain_cancel': 'オンチェーンで注文をキャンセル',
  'operations.chain_cancel_title':
    'この注文キャンセルリクエストは、注文のキャンセルを保証するためにオンチェーンに投稿されます。',
  'operations.chain_cancel_confirm': 'キャンセルを確認',
  'operations.chain_cancel_confirm_tips':
    'オンチェーンキャンセルにはガス料金がかかります。続行しますか？',
  'operations.chain_cancel_grid_text_N':
    'このグリッド戦略の<b>N件</b>の注文がオンチェーンキャンセルのために提出されます。',
  'operations.chain_cancel_grid_gas_AMOUNT_ETH':
    'オンチェーンキャンセルのガス料金<b>AMOUNT ETH</b>を再確認してください。',
  'operations.claim_title': '報酬を請求',
  'operations.claim_desc':
    '報酬は内部転送を介してDeGate残高にクレジットされ、ガス料金は報酬額から直接差し引かれます。',
  'operations.claim_desc_others':
    'この請求は、内部転送を通じてDeGate残高にクレジットされます。',
  'operations.claim_rewards': '利用可能な報酬',
  'operations.claim_err_amount': '請求可能額が不足しています',
  'operations.claim': '請求',
  'operations.Claimable': '請求可能',
  'operations.Unclaimed': '未請求',
  'operations.claim_mining_rewards': 'マイニング報酬を請求',
  'operations.claim_rewards_desc':
    '報酬はガス料金を差し引いた後にアカウントに送信されます',
  'operations.pay_deposit': '決済',
  'operations.pay_deposit_title': '保留中の支払い',
  'operations.pay_deposit_desc_XXX_ETH': 'XXX ETHの資金追加が保留中です。',
  'operations.pay_deposit_select_account': '支払い元',
  Wallet_Balance: 'ウォレット残高',
  'operations.pay_deposit_tips_XXX_ETH': 'XXX ETHを支払う',
  'operations.reset_account': 'リセットアセットキー',
  'operations.reset_desc':
    'アセットキーはブラウザキャッシュにあります。ローカル環境のセキュリティに疑問がある場合は、アセットキーをリセットしてください。',
  'operations.reset_warning':
    'リセット中は、取引、送信、内部転送などのすべての操作が一時停止します。',
  'operations.reset_estimated_time': '推定時間',
  'operations.reset_order_tips':
    'リセットが開始されると、すべてのオープン注文とグリッド戦略がキャンセルされます。',
  'operations.reset_order_tips_btn2': 'キャンセル',
  'operations.claim_dg_rewards': 'DG報酬を請求',
  'operations.claim_REBASE': 'REBASEを請求',
  'operations.claim_REBASE_desc':
    'REBASEは内部転送でDeGate残高に送信されます。',
  'operations.claim_REBASE_tips': '未請求のREBASEは収益計算に含まれます。',
  'operations.view_yield_history': '収益履歴を表示',
  'operations.cancel_orders_on_chain': 'オンチェーンで注文をキャンセル',
  'operations.chain_cancel_dca_text_N':
    'このDCAプランの<b>N件</b>の注文がオンチェーンキャンセルのために提出されます。',
  'operations.confirm_cancel_gas_AMOUNT_ETH':
    'オンチェーンキャンセルのガス料金<b>AMOUNT ETH</b>を再確認してください。',
  'trade.confirm_order': '注文を確認',
  'trade.stop_limit_order': 'ストップリミット',
  'trade.stop_price': 'ストップ価格',
  'trade.limit_price': 'リミット価格',
  'trade.market_price': 'マーケット価格',
  'trade.total': '合計',
  'trade.pay': '支払う',
  'trade.receive': '受け取る',
  'trade.hide_pair_confirm': 'このペアに対して再表示しない',
  'trade.pay_the_following_amount_to_place_order': '注文を出すために支払う額：',
  'trade.flow_of_funds': '資金の流れ',
  'trade.flow_of_funds_tip2':
    '注文が出されました。注文の資金はウォレット残高ではなく、DeGate残高に入ります。',
  'trade.pay_to_place_order': '注文を出すために支払う',
  'trade.pay_xxx_USDC_to_place_order': '注文を出すためにxxx USDCを支払う',
  'trade.deposit_type': '方法',
  'trade.deposit_type_standard': '標準',
  'transfer.transfer_1_eth_ACCOUNT': '1 ETHを転送',
  'transfer.internal_transfer_address_new_tips':
    'このアドレスには以前のDeGate履歴がありません。このアドレスへの転送には追加のガス料金がかかります。',
  address_placeholder: 'アドレスを入力',
  'transfer.to_new_account_tips':
    'このアドレスには以前のDeGate履歴がありません。最初のアセット受取により追加のオンチェーンクリアデータが使用され、この内部転送には追加のガス料金がかかります。',
  'transfer.confirm_internal_transfer': '内部転送を確認',
  'transfer.internal_transfer_address_oneself_tips':
    '自分自身への内部転送はサポートされていません。',
  'transfer.transfer_max_err_XXX_USDT':
    '内部転送はXXX USDTまで制限されています',
  'transfer.before': '前',
  'transfer.after': '後',
  'transfer.recipient_cex_warning':
    '警告：中央集権型取引所に転送しないでください。資金を失う可能性があります。',
  'withdraw.withdraw_max_tips': 'システム制限を超えました',
  'dca.confirm_dca_plan': 'DCAプランを確認',
  'dca.number_of_orders': '注文数',
  'dca.amount_per_order': '注文ごとの額',
  'dca.time_scheduled': '予定時間',
  'dca.creating_the_plan': 'プランを作成中...',
  'dca.maximum_price': '最大価格',
  'dca.minimum_price': '最小価格',
  'dca.do_not_close': 'このページを閉じたり、リフレッシュしないでください。',
  'dca.frequency': '頻度',
  total_amount: '総額',
  'dca.daily': '毎日',
  'dca.weekly': '毎週',
  'dca.every': '毎',
  'airdrop.review_airdrop': 'エアドロップをレビュー',
  'airdrop.create_airdrop': 'エアドロップを作成',
  'airdrop.recipients_number': '受取人数',
  'airdrop.airdrop_fee': 'エアドロップ料金',
  'airdrop.pay_airdrop_fee': 'エアドロップ料金を支払う',
  'airdrop.send_airdrop_token': 'エアドロップトークンを送信',
  'airdrop.claim_airdrop': 'エアドロップを請求',
  'airdrop.retrieve': '取り戻す',
  'countdown.create_countdown_plan': 'カウントダウンプランを作成',
  'countdown.countdown_display': 'カウントダウン表示',
  'countdown.max_30_days': '30日以内でなければなりません',
  'countdown.review_countdown_plan': 'カウントダウンプランをレビュー',
  'countdown.countdown_fee': 'カウントダウン料金',
  grid_slippage_over_2_tips_SLIPPAGE_QUOTE_BASE:
    'システムは最初に市場注文を使用して、QUOTEの一部をBASEに交換し、推定スリッページをSLIPPAGEとします。',
  grid_slippage_over_5_tips_SLIPPAGE_QUOTE_BASE:
    'デュアルアセットモードでの投資をお勧めします。',
  connected: '接続済み',
  browser_wallet: 'ブラウザウォレット',
  Convert_to_YYY: 'YYYに変換',
  sell_XXX_to_YYY: 'XXXをマーケット価格でYYYに売却しますか？',
  you_sell: 'あなたは売却します',
  you_receive: '受け取る',
  est_slippage: '推定スリッページ',
  No: 'いいえ',
  closing_sell: '売却を閉じる',
  connect_wallet: 'ウォレットを接続',
  Add: '追加',
  Add_Funds: '資金を追加',
  send_USDC_to_this_address: 'このアドレスにUSDCを送信',
  Failed_to_proceed: '進行に失敗しました。',
  Please_select_the_Ethereum_network:
    'イーサリアムネットワークを選択してください。',
  NATIVE_USDC_ONLY: 'ネイティブUSDCトークンのみ',
  NEVER_send_bridged_USDC: 'ブリッジされたUSDCは絶対に送信しないでください',
  Network: 'ネットワーク',
  Arrival_Time: '到着時間',
  Token_Contract: 'トークン契約',
  please_select_network: 'ネットワークを選択してください',
  maximum_amount: '最大額',
  Select: '選択',
  cannot_send_to_yourself: '自分自身に転送できません（DeGateネットワーク内）',
  max_amount_exceeded: '最大額を超えました',
  do_not_trasnfer_to_cex:
    '中央集権型取引所に転送しないでください。資金を失う可能性があります。',
  I_understand: '理解しました',
  Continue: '続行',
  chain_0: 'DeGate',
  chain_1: 'イーサリアム',
  chain_17000: 'イーサリアム',
  chain_42: 'Kovan',
  chain_42161: 'Arbitrum',
  chain_421614: 'Arbitrum',
  chain_10: 'Optimism',
  chain_11155420: 'Optimism',
  chain_137: 'Polygon',
  chain_80002: 'Polygon',
  deposit_tips_region:
    'DeGateにアクセスしている地域に注意してください。取引および内部転送機能は資金追加後に利用できません。',
  deposit_1_ETH: 'DeGate残高に1 ETHを追加',
  'account.deposit_contract_tips_over_AMOUNT':
    '資金追加がAMOUNT USDを超える場合は、高度な方法が必要です。',
  'account.deposit_contract_tips_only_all':
    '高度な方法でのみ資金追加がサポートされています',
  Approved: '承認済み',
  Deposit: '追加',
  'account.deposit_tips': 'これらの資金の完全な保管を維持します。',
  'account.deposit_arrive_in_30s_s': '約30秒で到着',
  reset_approval_USDT: 'USDT承認のリセット',
  reset_approval_USDT_tips:
    'USDTの消費制限が低すぎる場合、承認のリセットが必要です。',
  token_has_not_listed: 'このトークンはDeGateにリストされていません。',
  list_now: '今すぐリスト',
  Retry: '再試行',
  switch_network: 'ネットワークを切り替え',
  switch_to_MAINNET_in_metamask: 'MetaMaskでMAINNETに切り替えてください',
  switch_to_MAINNET: 'MAINNETに切り替えてください',
  'account.pay_deposit_warning':
    '資金追加には追加のガス料金がかかる場合があります',
  send_method: '方法',
  Economy: '標準',
  Fast: '速い',
  Instant: '即時',
  less_than_X_hours: '< X 時間',
  less_than_1_hour: '< 1 時間',
  Economy_tips:
    'DeGateは少なくとも4時間ごとに送信リクエストを処理しますが、多くの場合、それ以前に処理されます。たとえば、他のユーザーが高速送信を開始した場合、あなたのエコノミー送信リクエストもすぐに処理されます。',
  wrap: 'ラップ',
  just_a_moment: '少々お待ちください',
  wait_confirmation_from_wallet: 'ウォレットからの確認を待っています',
  s: 's',
  doc_title:
    'DeGate: 分散型オーダーブック取引所 | GRIDとDCAの無料暗号取引ボット',
  doc_desc:
    'DeGateは、数百種類の暗号通貨を低手数料で取引できるトップの分散型オーダーブック取引所であり、無料のリミットオーダー取引、グリッド取引、DCAボットを提供しています。',
  doc_title_spot: '分散型オーダーブックDeGate DEX',
  doc_title_grid: '分散型グリッド取引ボットDeGate DEX',
  doc_title_dca: '分散型DCA取引ボットDeGate DEX',

  view_asset_key_tips:
    '<div>MetaMaskが<i>パーソナルサイン</i>メソッドで再度サインするよう要求しています</div>',
  personal_sign_tips:
    '<div>MetaMaskが<i>パーソナルサイン</i>メソッドで再度サインするよう要求しています</div>',
  sign_and_open_free_mode_tips:
    'この操作の後、署名なしモードが有効になるため、サインは不要です。<br/><br/>モードを切り替えるには、トレードボタンの下にある「設定」に移動してください。',
  'trade.i_understand': '<span>理解しましたﾂ</span>',
  'trade.flow_of_funds_tips':
    '<h3>資金の流れ</h3>資金はあなたのウォレットバランスではなく、DeGateバランスへ送られます。<br/><br/><h3>DeGateバランスについて</h3>DeGateバランスは、ユーザーがDeGateスマートコントラクト内で保持する価値を表します。<br/>ユーザーは、完全に分散化されたDeGateスマートコントラクトのおかげで、DeGateバランスの完全な管理権を持っています。',
};

export default ja;
