const ru = {
  language: 'ru-RU',
  choose_token: 'Выбрать токен',
  recipient: 'Получатель',
  recent: 'Недавние',
  price: 'Цена',
  amount: 'Сумма',
  available: 'Доступно',
  gas_fee: 'Комиссия за газ',
  Send: 'Отправить',
  Send_ETH: 'Отправить ETH',
  Internal_Transfer: 'Внутренний перевод',
  transfer_tips: 'Перевести токен на другой адрес в рамках DeGate Protocol',
  transfer_ETH: 'Внутренний перевод ETH',
  btn_max: 'Максимум',
  degate_insufficient_balance: 'Недостаточно средств',
  max_digits_exceeded: 'Превышено максимальное количество цифр',
  wallet_insufficient_balance: 'Недостаточно средств на кошельке',
  deGate_insufficient_fees:
    'Недостаточно средств DeGate для оплаты комиссии за газ',
  token_search_placeholder: 'Поиск токена, адрес контракта',
  token: 'Токен',
  degate_balance: 'Баланс DeGate',
  tips_gas:
    'Комиссия за газ для выполнения этой он-чайновой транзакции будет вычтена непосредственно с вашего баланса DeGate',
  tips_gas2:
    'Комиссия за газ покрывает он-чайновые расходы на урегулирование торговли. Лишние комиссии возвращаются',
  Close: 'Закрыть',
  Help: 'Помощь',
  no_token: 'Токен не найден',
  Cancel: 'Отменить',
  go_back: 'Вернуться',
  Back: 'Назад',
  copied: 'Скопировано',
  Confirm: 'Подтвердить',
  Create: 'Создать',
  Abort: 'Прервать',
  btn_confirm: 'Закрыть',
  btn_got_it: 'Понял',
  wallet_cancelled_tips: 'Вы отменили подпись',
  connect_ledger: 'Подключить Ledger',
  ledger_disconnect:
    "Не удалось выполнить 'TransferOut' на 'USBDevice': устройство было отключено",
  wallet_tips: 'Пожалуйста подтвердите в браузерном кошельке',
  wallet_ledger_tips: 'Пожалуйста подтвердите в аппаратном кошельке Ledger',
  wallet_metamask_tips: 'Пожалуйста подтвердите в MetaMask',
  wallet_walletconnect_tips:
    'Пожалуйста перейдите в ваш кошелек, чтобы подтвердить через WalletConnect',
  view_asset_key: 'Просмотреть ключ актива',
  export_key_warning:
    'Утечка ключа актива может привести к потере активов. Пожалуйста обеспечьте его хранение',
  export_key_confirm_btn: 'Продолжить просмотр',
  btn_buy_ETH: 'Купить ETH',
  btn_sell_ETH: 'Продать ETH',
  around: '～',
  need_help: 'Помощь',
  time_now: 'сейчас',
  time_1_minute: '1 минута',
  time_1_hour: '1 час',
  time_1_day: '1 день',
  time_1_year: '1 год',
  time_M_minutes: 'M минут',
  time_M_m: 'Mm',
  time_H_hours: 'H часов',
  time_H_h: 'Hh',
  time_D_days: 'D дней',
  time_D_d: 'Dd',
  time_Y_years: 'Y лет',
  time_Y_y: 'Yy',
  personal_sign_reason: 'Возможные причины',
  personal_sign_reason1: 'MetaMask подключен к аппаратному кошельку',
  personal_sign_reason2: 'Версия MetaMask устарела',
  personal_sign_reason3: 'Другие',
  personal_sign_btn: 'Подписать снова',
  switch_wallet: 'Сменить аккаунт',
  switch_walletConnect_tips1:
    'Если вы хотите переключиться на другой аккаунт в том же программном обеспечении для кошелька, пожалуйста, выполните это непосредственно из кошелька и отмените этот запрос',
  switch_walletConnect_tips2:
    'Если вы хотите использовать WalletConnect через другое программное обеспечение для кошелька, система сначала отключит существующее соединение',
  switch_walletConnect_continue: 'Отключить и продолжить',
  switch_metamask_tips: 'Пожалуйста, перейдите в MetaMask для смены аккаунта',
  switch_browser_wallet_tips:
    'Пожалуйста, смените аккаунт в браузерном кошельке',
  period_expired: 'Истекло',
  period_D_day_H_hour: 'Dd Hh',
  period_H_hour_M_minute: 'Hh Mm',
  login_success: 'Подключение успешно',
  advanced: 'Расширенные',
  edit: 'Редактировать',
  save: 'Сохранить',
  speed_up: 'Ускорить',
  continue: 'Продолжить',
  Submit: 'Подать',
  icon_copy: 'Скопировать адрес',
  icon_view_explorer: 'Посмотреть на блок-эксплорере',
  upcoming_lock_tips:
    'Из-за периода бездействия режим без подписи будет выключен для вашей безопасности',
  auto_locked_tips:
    'Для вашей безопасности режим без подписи был выключен после 15 минут бездействия',
  keep: 'Оставить',
  turn_off_now: 'Выключить сейчас',
  turn_on: 'Включить',
  turn_on_signature_free_mode: 'Включить режим без подписи',
  turn_on_signature_free_mode_success: 'Режим без подписи включен',
  max_XXX: 'Максимум XXX',
  min_XXX: 'Минимум XXX',
  common_err: 'Что-то пошло не так. Пожалуйста, попробуйте позже',
  input_auto_corrected_tips:
    'Автоматически исправлено ваше введение после превышения максимального количества цифр',
  maximum_decimal_reached:
    'Достигнуто максимальное количество десятичных знаков',
  verify_ownership: 'Подтвердите право собственности',
  execute: 'Выполнить',
  sign_step1: 'Завершить в вашем кошельке',
  sign_step2: 'Завершить 2-й подпись',
  sign_step3: 'Завершить 3-й подпись',
  place_order: 'Разместить ордер',
  create_spot_order: 'Разместить ордер',
  create_grid_strategy: 'Создать Grid стратегию сетки',
  create_DCA_plan: 'Создать план DCA',
  cancel_order: 'Отменить ордер',
  end_grid_strategy: 'Завершить стратегию сетки',
  end_DCA: 'Завершить план DCA',
  complete_in_seconds: 'Завершить за секунды',
  complete_in: 'Завершить за',
  me: 'я',
  eth_code_tips: 'Нативный токен Ethereum. Нет адреса контракта токена',
  total: 'Всего',
  order_amount: 'Сумма ордера',
  operation_has_expired: 'Операция завершена',
  Approve: 'Одобрить',
  tips_hide_forever: 'Больше не показывать',
  Tips: 'Подсказка',
  Note: 'Заметка',
  Summary: 'Резюме',
  Orders: 'Ордера',
  Side: 'Сторона',
  Sell: 'Продажа',
  Buy: 'Покупка',
  now: 'Сейчас',
  order_type: 'Тип ордера',
  limit_order: 'Лимит',
  market_order: 'Рынок',
  required: 'Обязательно',
  check_address_format: 'Проверьте формат адреса',
  start_time: 'Время начала',
  end_time: 'Время окончания',
  None: 'Никакой',
  time_out: 'Время вышло. Пожалуйста, попробуйте еще раз',
  deposit_ETH: 'Добавить ETH',
  'grid.confirm_grid': 'Подтвердить Grid стратегию сетки',
  'grid.initial_investment': 'Инвестиции',
  'grid.price_range': 'Ценовой диапазон',
  'grid.grid_level': 'Количество сеток',
  'grid.grid_volume': 'Количество на сетку',
  'grid.profit_per_grid': 'Прибыль на сетку',
  'grid.expired_in': 'Истекает через',
  'grid.replace_modal_title': 'Стратегия сетки обновлена',
  'grid.replace_modal_content':
    'Из-за недавних изменений в книге ордеров первоначальная стратегия сетки была обновлена следующим образом',
  'grid.replace_modal_pre': 'До',
  'grid.replace_modal_next': 'После',
  'grid.replace_modal_err':
    'Недостаточно баланса для создания стратегии сетки. Пожалуйста, вернитесь для редактирования параметров сетки',
  'ledger.connect_rule_1': '1. Подключите Ledger к вашему устройству',
  'ledger.connect_rule_2': '2. Разблокируйте в Ledger',
  'ledger.connect_rule_3': '3. Откройте приложение Ethereum в Ledger',
  'ledger.connect_rule_4':
    '4. Убедитесь, что Blind Signing/Contract Data и Browser Support включены',
  'ledger.unable_to_approve': 'Невозможно одобрить',
  'ledger.webusb_1tab_tips_desc_1':
    'Этот браузер поддерживает только одну вкладку для одобрения через Ledger. Невозможно одобрить, так как другая вкладка использует эту функцию',
  'ledger.webusb_1tab_tips_desc_2':
    'Пожалуйста, попробуйте повторно подключить Ledger для перезапуска операции',
  'ledger.locked_tips':
    'Пожалуйста, разблокируйте Ledger, откройте приложение Ethereum и одобрите',
  'ledger.account_not_match':
    'Обнаружен неправильный кошелек Ledger. Пожалуйста, подключитесь к правильному Ledger',
  'ledger.ledger_choose_address': 'Выберите адрес',
  'ledger.address': 'Адрес',
  'ledger.connect': 'Подключить',
  'ledger.un_supported_title':
    'Подключение кошелька Ledger не поддерживается текущим браузером',
  'ledger.un_supported_desc': 'Рекомендуем использовать браузеры Chrome и Edge',
  'ledger.confirm_gas_fee': 'Подтвердите комиссию за газ',
  'ledger.confirm_gas_fee_desc':
    'Вы собираетесь инициировать транзакцию в Ethereum, пожалуйста, подтвердите:',
  'ledger.max_gas_fee': 'Максимальная комиссия за газ',
  'ledger.edit_gas_fee': 'Редактировать комиссию за газ',
  'ledger.max_fee': 'Цена газа (Gwei)',
  'ledger.max_base_fee': 'Максимальная базовая комиссия (Gwei)',
  'ledger.max_base_fee_tips':
    'Когда ваша транзакция будет включена в блок, любая разница между вашей максимальной базовой комиссией и фактической базовой комиссией будет возвращена',
  'ledger.priority_fee': 'Приоритетная комиссия (Gwei)',
  'ledger.priority_fee_tips':
    'Приоритетная комиссия (также известная как ""чаевые майнерам"") идет напрямую к майнерам и стимулирует их приоритизировать вашу транзакцию',
  'ledger.gas_limit': 'Лимит газа:',
  'ledger.tx_speed_up_title': 'Ускорить транзакцию',
  'ledger.tx_speed_up_desc':
    'Вы собираетесь ускорить транзакцию в Ethereum, пожалуйста, подтвердите:',
  'ledger.tx_cancel_title': 'Отменить транзакцию',
  'ledger.tx_cancel_desc':
    'Вы собираетесь отменить транзакцию в Ethereum, пожалуйста, подтвердите:',
  'ledger.fee_minimum_xxx': 'Не может быть меньше XXX',
  'ledger.ledger_app_version_tips':
    'Обновите приложение Ethereum вашего Ledger до версии 1.9.19 или выше, чтобы просмотреть сообщение перед подписанием',
  'operations.register_pair': 'Добавить торговую пару',
  'operations.chain_cancel': 'Отменить ордер в сети',
  'operations.chain_cancel_title':
    'Этот запрос на отмену ордера будет размещен в сети для гарантии отмены ордера',
  'operations.chain_cancel_confirm': 'Подтвердить отмену',
  'operations.chain_cancel_confirm_tips':
    'Отмена в сети повлечет за собой расходы на комиссию за газ. Вы хотите продолжить?',
  'operations.chain_cancel_grid_text_N':
    '<b> N ордеров </b> в этой стратегии сетки будут отправлены для отмены в сети',
  'operations.chain_cancel_grid_gas_AMOUNT_ETH':
    'Пожалуйста, еще раз подтвердите комиссию за отмену в сети в размере <b> СУММА ETH </b>',
  'operations.claim_title': 'Получить награду',
  'operations.claim_desc':
    'Награда будет зачислена на ваш баланс DeGate через внутренний перевод, с комиссией за газ, вычитаемой непосредственно из суммы награды',
  'operations.claim_desc_others':
    'Эта награда будет зачислена на ваш баланс DeGate через внутренний перевод',
  'operations.claim_rewards': 'Доступные награды',
  'operations.claim_err_amount': 'Недостаточно средств для получения награды',
  'operations.claim': 'Получить',
  'operations.Claimable': 'Доступно для получения',
  'operations.Unclaimed': 'Не получено',
  'operations.claim_mining_rewards': 'Получить награду за майнинг',
  'operations.claim_rewards_desc':
    'Награда будет отправлена на ваш счет после вычета комиссии за газ',
  'operations.pay_deposit': 'Расчет',
  'operations.pay_deposit_title': 'Ожидает оплаты',
  'operations.pay_deposit_desc_XXX_ETH':
    'У вас есть ожидаемое добавление средств в размере XXX ETH',
  'operations.pay_deposit_select_account': 'Оплатить с',
  Wallet_Balance: 'Баланс кошелька',
  'operations.pay_deposit_tips_XXX_ETH': 'Оплатить XXX ETH',
  'operations.reset_account': 'Сбросить ключ актива',
  'operations.reset_desc':
    'Ключ актива хранится в кеше вашего браузера. Если безопасность вашего локального окружения вызывает сомнения, пожалуйста, сбросьте ключ актива',
  'operations.reset_warning':
    'Все операции, такие как торговля, отправка или внутренние переводы, приостанавливаются во время сброса',
  'operations.reset_estimated_time': 'Оцененное время',
  'operations.reset_order_tips':
    'После инициирования сброса все открытые ордера и стратегии сетки будут отменены',
  'operations.reset_order_tips_btn2': 'Отменить',
  'operations.claim_dg_rewards': 'Получить DG Rewards',
  'operations.claim_REBASE': 'Получить REBASE',
  'operations.claim_REBASE_desc':
    'REBASE будет отправлен на ваш баланс DeGate через внутренний перевод',
  'operations.claim_REBASE_tips':
    'Невыплаченный REBASE учитывается при расчете доходности',
  'operations.view_yield_history': 'Просмотреть историю доходности',
  'operations.cancel_orders_on_chain': 'Отменить ордера в сети',
  'operations.chain_cancel_dca_text_N':
    '<b> N ордеров </b> в этом DCA плане будут отправлены для отмены в сети.',
  'operations.confirm_cancel_gas_AMOUNT_ETH':
    'Пожалуйста, еще раз подтвердите комиссию за отмену в сети в размере <b> СУММА ETH </b>.',
  'trade.confirm_order': 'Подтвердить ордер',
  'trade.stop_limit_order': 'Стоп Лимит',
  'trade.stop_price': 'Стоп Цена',
  'trade.limit_price': 'Лимит Цена',
  'trade.market_price': 'Рыночная Цена',
  'trade.total': 'Итого',
  'trade.pay': 'Оплатить',
  'trade.receive': 'Получить',
  'trade.hide_pair_confirm': 'Больше не показывать для этой пары',
  'trade.pay_the_following_amount_to_place_order':
    'Оплатите следующую сумму, чтобы разместить ордер:',
  'trade.flow_of_funds': 'поток средств',
  'trade.flow_of_funds_tip2':
    'Ваш ордер был размещен. Средства с ордера будут зачислены на ваш баланс DeGate, а не на баланс кошелька.',
  'trade.pay_to_place_order': 'Оплатить для размещения ордера',
  'trade.pay_xxx_USDC_to_place_order':
    'Оплатите xxx USDC, чтобы разместить ордер',
  'trade.deposit_type': 'Метод',
  'trade.deposit_type_standard': 'Стандартный',
  'transfer.transfer_1_eth_ACCOUNT': 'Перевести 1 ETH на',
  'transfer.internal_transfer_address_new_tips':
    'Этот адрес не имеет истории DeGate. Перевод на этот адрес потребует дополнительных комиссий за газ.',
  address_placeholder: 'Введите адрес',
  'transfer.to_new_account_tips':
    'Этот адрес не имеет истории DeGate. Так как первый прием актива инициирует дополнительное использование данных в сети, выполнение этого внутреннего перевода приведет к дополнительным комиссиям за газ.',
  'transfer.confirm_internal_transfer': 'Подтвердить внутренний перевод',
  'transfer.internal_transfer_address_oneself_tips':
    'Внутренний перевод на свой собственный адрес не поддерживается.',
  'transfer.transfer_max_err_XXX_USDT':
    'Внутренний перевод ограничен XXX USDT за перевод',
  'transfer.before': 'До',
  'transfer.after': 'После',
  'transfer.recipient_cex_warning':
    'Предупреждение: Пожалуйста, не переводите на централизованную биржу. Вы потеряете средства.',
  'withdraw.withdraw_max_tips': 'Превышен лимит системы',
  'dca.confirm_dca_plan': 'Подтвердить DCA План',
  'dca.number_of_orders': 'Количество ордеров',
  'dca.amount_per_order': 'Сумма за ордером',
  'dca.time_scheduled': 'Запланированное время',
  'dca.creating_the_plan': 'Создание плана...',
  'dca.maximum_price': 'Максимальная цена',
  'dca.minimum_price': 'Минимальная цена',
  'dca.do_not_close': 'НЕ закрывайте и не обновляйте эту страницу.',
  'dca.frequency': 'Частота',
  total_amount: 'Общая сумма',
  'dca.daily': 'Ежедневно',
  'dca.weekly': 'Еженедельно',
  'dca.every': 'Каждые',
  'airdrop.review_airdrop': 'Просмотр Airdrop',
  'airdrop.create_airdrop': 'Создать Airdrop',
  'airdrop.recipients_number': 'Количество получателей',
  'airdrop.airdrop_fee': 'Комиссия за Airdrop',
  'airdrop.pay_airdrop_fee': 'Оплатить комиссию за Airdrop',
  'airdrop.send_airdrop_token': 'Отправить токен Airdrop',
  'airdrop.claim_airdrop': 'Получить Airdrop',
  'airdrop.retrieve': 'Забрать обратно',
  'countdown.create_countdown_plan': 'Создать план обратного отсчета',
  'countdown.countdown_display': 'Отображение обратного отсчета',
  'countdown.max_30_days': 'Не может быть более чем 30 дней с текущей даты',
  'countdown.review_countdown_plan': 'Просмотр плана обратного отсчета',
  'countdown.countdown_fee': 'Комиссия за обратный отсчет',
  grid_slippage_over_2_tips_SLIPPAGE_QUOTE_BASE:
    'Система сначала обменяет часть QUOTE на BASE с использованием рыночного ордера, с ожидаемым проскальзыванием SLIPPAGE.',
  grid_slippage_over_5_tips_SLIPPAGE_QUOTE_BASE:
    'Система сначала обменяет часть QUOTE на BASE с использованием рыночного ордера, с ожидаемым проскальзыванием SLIPPAGE. Рекомендуется инвестирование в режиме Dual Asset.',
  connected: 'Подключено',
  browser_wallet: 'Браузерный кошелек',
  Convert_to_YYY: 'Конвертировать в YYY',
  sell_XXX_to_YYY: 'Вы хотите продать ваш XXX за YYY по рыночной цене?',
  you_sell: 'Вы продаете',
  you_receive: 'Вы получаете',
  est_slippage: 'Ожидаемое проскальзывание',
  No: 'Нет',
  closing_sell: 'Закрытие продажи',
  connect_wallet: 'Подключить кошелек',
  Add: 'Добавить',
  Add_Funds: 'Добавить средства',
  send_USDC_to_this_address: 'Отправить USDC на этот адрес',
  Failed_to_proceed: 'Не удалось продолжить.',
  Please_select_the_Ethereum_network: 'Пожалуйста, выберите сеть Ethereum.',
  NATIVE_USDC_ONLY: 'Только нативный токен USDC',
  NEVER_send_bridged_USDC: 'НИКОГДА не отправляйте бриджированный USDC',
  Network: 'Сеть',
  Arrival_Time: 'Время прибытия',
  Token_Contract: 'Контракт токена',
  please_select_network: 'Пожалуйста, выберите сеть',
  maximum_amount: 'Максимальная сумма',
  Select: 'Выбрать',
  cannot_send_to_yourself: 'Невозможно отправить самому себе в сети DeGate',
  max_amount_exceeded: 'Превышена максимальная сумма',
  do_not_trasnfer_to_cex:
    'Пожалуйста, <b> НЕ </b> переводите на централизованные биржи. Вы можете потерять свои средства.',
  I_understand: 'Я понимаю',
  Continue: 'Продолжить',
  chain_0: 'DeGate',
  chain_1: 'Ethereum',
  chain_17000: 'Ethereum',
  chain_42: 'Kovan',
  chain_42161: 'Arbitrum',
  chain_421614: 'Arbitrum',
  chain_10: 'Optimism',
  chain_11155420: 'Optimism',
  chain_137: 'Polygon',
  chain_80002: 'Polygon',
  deposit_tips_region:
    'Обратите внимание, что вы получаете доступ к DeGate в REGION. Функции торговли и внутреннего перевода недоступны после добавления средств.',
  deposit_1_ETH: 'Добавьте 1 ETH на свой баланс DeGate',
  'account.deposit_contract_tips_over_AMOUNT':
    'Добавление средств свыше AMOUNT USD требует использования Расширенного метода.',
  'account.deposit_contract_tips_only_all':
    'Поддерживается только Расширенный метод добавления средств',
  Approved: 'Одобрено',
  Deposit: 'Добавить',
  'account.deposit_tips': 'Вы сохраняете полный контроль над этими средствами.',
  'account.deposit_arrive_in_30s_s': 'Прибытие через ~ 30 секунд',
  reset_approval_USDT: 'Сбросить одобрение USDT',
  reset_approval_USDT_tips:
    'USDT требует сброса одобрения, когда лимиты на расходы слишком низки.',
  token_has_not_listed: 'Этот токен не был добавлен на DeGate.',
  list_now: 'Добавить сейчас',
  Retry: 'Повторить попытку',
  switch_network: 'Переключить сеть',
  switch_to_MAINNET_in_metamask:
    'Пожалуйста, переключитесь на MAINNET в MetaMask',
  switch_to_MAINNET: 'Пожалуйста, переключитесь на MAINNET',
  'account.pay_deposit_warning':
    'Добавление средств может повлечь дополнительные комиссии за газ',
  send_method: 'Метод',
  Economy: 'Экономный',
  Fast: 'Быстрый',
  Instant: 'Мгновенный',
  less_than_X_hours: '< X часов',
  less_than_1_hour: '< 1 часа',
  Economy_tips:
    'DeGate обрабатывает запросы на отправку как минимум каждые 4 часа, часто быстрее. Например, если другой пользователь инициирует Быструю Отправку, ваш запрос на Экономную Отправку будет также обработан немедленно.',
  just_a_moment: 'Момент',
  wait_confirmation_from_wallet: 'Ожидание подтверждения от кошелька',
  wrap: 'обернуть',
  s: 's',
  doc_title:
    'DeGate: Децентрализованная биржа с книгой ордеров | Бесплатный крипто-трейдинг бот на GRID и DCA',
  doc_desc:
    'DeGate — это ведущая децентрализованная биржа с ордер-буком, предлагающая торговлю сотнями криптовалют с низкими комиссиями, бесплатную торговлю лимитными ордерами, сеточными Grid стратегиями и ботами DCA.',
  doc_title_spot: 'Децентрализованный ордер-бук | DeGate DEX',
  doc_title_grid: 'Децентрализованный Grid Торговый Бот| DeGate DEX',
  doc_title_dca: 'Децентрализованный DCA Торговый Бот | DeGate DEX',

  view_asset_key_tips:
    '<div>Вот детали вашего Ключа Активов. <strong>НЕ делитесь</strong> ими ни с кем, чтобы избежать возможных потерь активов.</div>',
  personal_sign_tips:
    '<div>MetaMask запрашивает повторную подпись с помощью метода <i>Personal Sign</i></div>',
  sign_and_open_free_mode_tips:
    'Подпись не требуется, так как режим без подписи будет включен после этого действия.<br/><br/>Чтобы переключить режим, перейдите в "Настройки" под кнопкой "Торговать".',
  'trade.i_understand': '<span>Я понимаю </span>',
  'trade.flow_of_funds_tips':
    '<h3>Поток средств</h3>Средства перейдут на ваш баланс DeGate, а не на баланс кошелька.<br/><br/><h3>О балансе DeGate</h3>Баланс DeGate представляет собой стоимость, которую пользователи держат в смарт-контракте DeGate.<br/>Пользователи сохраняют полный контроль над балансом DeGate благодаря полностью децентрализованному смарт-контракту DeGate.',
};
export default ru;
