const tr = {
  language: 'tr-TR',
  choose_token: 'Token Seç',
  recipient: 'Alıcı',
  recent: 'Son',
  price: 'Fiyat',
  amount: 'Miktar',
  available: 'Mevcut',
  gas_fee: 'Gas Ücreti',
  Send: 'Gönder',
  Send_ETH: 'ETH Gönder',
  Internal_Transfer: 'Dahili Transfer',
  transfer_tips: 'Tokeni DeGate Protokolü ile başka bir adrese transfer et.',
  transfer_ETH: 'Dahili ETH Transferi',
  btn_max: 'Maksimum',
  degate_insufficient_balance: 'Yetersiz bakiye',
  max_digits_exceeded: 'Maksimum basamak sayısı aşıldı',
  wallet_insufficient_balance: 'Cüzdanda yetersiz bakiye',
  deGate_insufficient_fees: 'Gas Ücreti için yetersiz DeGate bakiyesi',
  token_search_placeholder: 'Token, kontrat adresi ara',
  token: 'Token',
  degate_balance: 'DeGate Bakiyesi',
  tips_gas:
    'Bu zincir üzeri işlemi gerçekleştirmek için gereken gas ücreti doğrudan DeGate bakiyenizden düşülecektir.',
  tips_gas2:
    'Gaz Ücreti, zincir üzerindeki işlem sonuçlandırma maliyetlerini karşılar. Fazla ücretler iade edilir.',
  Close: 'Kapat',
  Help: 'Yardım',
  no_token: 'Token Bulunamadı',
  Cancel: 'İptal',
  go_back: 'Geri Dön',
  Back: 'Geri',
  copied: 'Kopyalandı',
  Confirm: 'Onayla',
  Create: 'Oluştur',
  Abort: 'İptal Et',
  btn_confirm: 'Kapat',
  btn_got_it: 'Anladım',
  wallet_cancelled_tips: 'İmzayı iptal ettiniz',
  connect_ledger: 'Ledger Bağla',
  ledger_disconnect:
    "USB Aygıtı' üzerinde 'transferOut' gerçekleştirilemedi: Aygıt bağlantısı kesildi.",
  wallet_tips: 'Lütfen tarayıcı cüzdanında onaylayın',
  wallet_ledger_tips: 'Lütfen Ledger cihazında onaylayın',
  wallet_metamask_tips: "Lütfen MetaMask'te onaylayın",
  wallet_walletconnect_tips:
    'Onay için cüzdanınıza gidin ve WalletConnect ile onaylayın',
  view_asset_key: 'Varlık Anahtarını Görüntüle',
  export_key_warning:
    'Varlık Anahtarının sızdırılması varlık kaybına yol açabilir. Lütfen güvenliğini sağlayın.',
  export_key_confirm_btn: 'Görmeye Devam Et',
  btn_buy_ETH: 'ETH Satın Al',
  btn_sell_ETH: 'ETH Sat',
  around: 'ï½',
  need_help: 'Yardım',
  time_now: 'şimdi',
  time_1_minute: '1 dakika',
  time_1_hour: '1 saat',
  time_1_day: '1 gün',
  time_1_year: '1 yıl',
  time_M_minutes: 'M dakika',
  time_M_m: 'Mm',
  time_H_hours: 'H saat',
  time_H_h: 'Hh',
  time_D_days: 'D gün',
  time_D_d: 'Dd',
  time_Y_years: 'Y yıl',
  time_Y_y: 'Yy',
  personal_sign_reason: 'Olası Nedenler',
  personal_sign_reason1: '1. MetaMask donanım cüzdanına bağlı',
  personal_sign_reason2: '2. MetaMask sürümü eski',
  personal_sign_reason3: '3. Diğerleri',
  personal_sign_btn: 'Tekrar İmzala',
  switch_wallet: 'Hesap Değiştir',
  switch_walletConnect_tips1:
    'Aynı cüzdan yazılımında başka bir hesaba geçmek istiyorsanız, lütfen bunu doğrudan cüzdandan yapın ve bu isteği iptal edin.',
  switch_walletConnect_tips2:
    'Farklı bir cüzdan yazılımı aracılığıyla WalletConnect kullanmak istiyorsanız, sistem önce mevcut bağlantıyı sonlandıracaktır.',
  switch_walletConnect_continue: 'Bağlantıyı Kes ve Devam Et',
  switch_metamask_tips: "Hesap değiştirmek için lütfen MetaMask'e gidin.",
  switch_browser_wallet_tips: 'Lütfen tarayıcı cüzdanında hesap değiştirin.',
  period_expired: 'Süresi Doldu',
  period_D_day_H_hour: 'Gg Ss',
  period_H_hour_M_minute: 'Ss Dd',
  login_success: 'Bağlantı Başarılı',
  advanced: 'Gelişmiş',
  edit: 'Düzenle',
  save: 'Kaydet',
  speed_up: 'Hızlandır',
  continue: 'Devam Et',
  Submit: 'Gönder',
  icon_copy: 'Adresi Kopyala',
  icon_view_explorer: "Blok Gezgini'nde Görüntüle",
  upcoming_lock_tips:
    'Bir süre hareketsiz kaldığınız için, İmzasız mod güvenliğiniz için kapatılacaktır.',
  auto_locked_tips:
    'Güvenliğiniz için, 15 dakikalık hareketsizlikten sonra İmzasız mod kapatıldı.',
  keep: 'Sürdür',
  turn_off_now: 'Şimdi Kapat',
  turn_on: 'Aç',
  turn_on_signature_free_mode: 'İmzasız Modu Aç',
  turn_on_signature_free_mode_success: 'İmzasız Mod Açık',
  max_XXX: 'Maksimum XXX',
  min_XXX: 'Minimum XXX',
  common_err: 'Bir şeyler ters gitti. Lütfen daha sonra tekrar deneyin.',
  input_auto_corrected_tips:
    'Maksimum basamak sayısını aştıktan sonra girdiniz otomatik olarak düzeltildi',
  maximum_decimal_reached: 'Maksimum ondalık basamak sayısına ulaşıldı',
  verify_ownership: 'Sahipliği Doğrula',
  execute: 'Yürüt',
  sign_step1: 'Cüzdanınızda Tamamlayın',
  sign_step2: 'İkinci İmzayı Tamamlayın',
  sign_step3: 'Üçüncü İmzayı Tamamlayın',
  place_order: 'Emir Ver',
  create_spot_order: 'Emir Ver',
  create_grid_strategy: 'Grid Stratejisi Oluştur',
  create_DCA_plan: 'DCA Planı Oluştur',
  cancel_order: 'Emri İptal Et',
  end_grid_strategy: 'Grid Stratejisini Sonlandır',
  end_DCA: 'DCA Planını Sonlandır',
  complete_in_seconds: 'Saniyeler içinde tamamlayın',
  complete_in: 'Tamamla',
  me: 'ben',
  eth_code_tips: "Ethereum'un yerel tokeni. Sözleşme adresi yok.",
  total: 'Toplam',
  order_amount: 'Emir Miktarı',
  operation_has_expired: 'İşlemin süresi doldu',
  Approve: 'Onayla',
  tips_hide_forever: 'Tekrar Gösterme',
  Tips: 'İpucu',
  Note: 'Not',
  Summary: 'Özet',
  Orders: 'Emirler',
  Side: 'Yön',
  Sell: 'Sat',
  Buy: 'Al',
  now: 'Şimdi',
  order_type: 'Emir Türü',
  limit_order: 'Limit',
  market_order: 'Piyasa',
  required: 'Gerekli',
  check_address_format: 'Adres formatını kontrol edin',
  start_time: 'Başlama Zamanı',
  end_time: 'Bitiş Zamanı',
  None: 'Yok',
  time_out: 'Zaman aşımı. Lütfen tekrar deneyin.',
  deposit_ETH: 'ETH Ekle',
  'grid.confirm_grid': 'Grid Stratejisini Onayla',
  'grid.initial_investment': 'Yatırım',
  'grid.price_range': 'Fiyat Aralığı',
  'grid.grid_level': 'Grid Sayısı',
  'grid.grid_volume': 'Grid Başına Miktar',
  'grid.profit_per_grid': 'Grid Başına Kar',
  'grid.expired_in': 'Süresi Dolacak',
  'grid.replace_modal_title': 'Grid Stratejisi Güncellendi',
  'grid.replace_modal_content':
    'Emir defterindeki son değişiklikler nedeniyle, orijinal grid stratejisi aşağıdaki şekilde güncellenmiştir.',
  'grid.replace_modal_pre': 'Önce',
  'grid.replace_modal_next': 'Sonra',
  'grid.replace_modal_err':
    'Grid stratejisini oluşturmak için yetersiz bakiye. Lütfen grid parametrelerini düzenlemek için geri dönün.',
  'ledger.connect_rule_1': 'Cihazınıza Ledger bağlayın',
  'ledger.connect_rule_2': "Ledger'de Kilidi Açın",
  'ledger.connect_rule_3': "Ledger'de Ethereum uygulamasını açın",
  'ledger.connect_rule_4':
    'Kör İmzalama/Sözleşme Verisi ve Tarayıcı Desteğinin etkin olduğundan emin olun',
  'ledger.unable_to_approve': 'Onaylanamıyor',
  'ledger.webusb_1tab_tips_desc_1':
    'Bu tarayıcı yalnızca Ledger onayı için tek bir "tarayıcı sekmesi"ni destekler. Başka bir sekme bu özelliği kullanıyor olduğu için onaylanamıyor.',
  'ledger.webusb_1tab_tips_desc_2':
    "İşlemi yeniden başlatmak için lütfen Ledger'ı tekrar takmayı deneyin.",
  'ledger.locked_tips':
    "Lütfen Ledger'ınızı açın, Ethereum uygulamasını başlatın ve onaylayın.",
  'ledger.account_not_match':
    "Yanlış Ledger cüzdanı algılandı. Lütfen doğru Ledger'a bağlanın.",
  'ledger.ledger_choose_address': 'Adres Seçin',
  'ledger.address': 'Adres',
  'ledger.connect': 'Bağla',
  'ledger.un_supported_title':
    'Mevcut Tarayıcı Ledger cüzdan bağlantısını desteklemiyor',
  'ledger.un_supported_desc':
    'Chrome ve Edge tarayıcılarını kullanmanızı öneririz.',
  'ledger.confirm_gas_fee': 'Gaz Ücretini Onaylayın',
  'ledger.confirm_gas_fee_desc':
    'Ethereum üzerinde bir işlem başlatmak üzeresiniz, lütfen onaylayın:',
  'ledger.max_gas_fee': 'Maksimum Gaz Ücreti',
  'ledger.edit_gas_fee': 'Gaz Ücretini Düzenle',
  'ledger.max_fee': 'Gaz Fiyatı (Gwei)',
  'ledger.max_base_fee': 'Maksimum Baz Ücret (Gwei)',
  'ledger.max_base_fee_tips':
    'İşleminiz bloğa dahil edildiğinde, maksimum Baz ücretiniz ile gerçek temel ücret arasındaki fark size iade edilecektir.',
  'ledger.priority_fee': 'Öncelik Ücreti (Gwei)',
  'ledger.priority_fee_tips':
    'Öncelik ücreti (diğer adıyla “madenci bahşişi”) doğrudan madencilere gider ve işleminizin önceliklendirilmesi için onları teşvik eder.',
  'ledger.gas_limit': 'Gaz Limiti:',
  'ledger.tx_speed_up_title': 'İşlemi Hızlandır',
  'ledger.tx_speed_up_desc':
    'Ethereum üzerinde bir işlemi hızlandırmak üzeresiniz, lütfen onaylayın:',
  'ledger.tx_cancel_title': 'İşlemi İptal Et',
  'ledger.tx_cancel_desc':
    'Ethereum üzerinde bir işlemi iptal etmek üzeresiniz, lütfen onaylayın:',
  'ledger.fee_minimum_xxx': 'XXX’den az olamaz',
  'ledger.ledger_app_version_tips':
    'Mesajı imzalamadan önce önizlemek için Ledger’ın Ethereum uygulamasını 1.9.19 veya daha yüksek bir sürüme güncelleyin.',
  'operations.register_pair': 'İşlem Çifti Ekle',
  'operations.chain_cancel': 'Zincir Üzerinde Emri İptal Et',
  'operations.chain_cancel_title':
    'Bu emir iptal talebi, emrin iptalini garanti etmek için zincir üzerinde yayınlanacaktır.',
  'operations.chain_cancel_confirm': 'İptali Onayla',
  'operations.chain_cancel_confirm_tips':
    'Zincir üzeri iptal bir gaz ücreti doğuracaktır. Devam etmek istiyor musunuz?',
  'operations.chain_cancel_grid_text_N':
    'Bu grid stratejisindeki <b>N emir</b> zincir üzeri iptal için gönderilecektir.',
  'operations.chain_cancel_grid_gas_AMOUNT_ETH':
    'Zincir üzeri iptal gaz ücretini <b>AMOUNT ETH</b> olarak tekrar onaylayın.',
  'operations.claim_title': 'Ödülleri Talep Et',
  'operations.claim_desc':
    'Ödüller, gaz ücretleri doğrudan ödül miktarından düşülerek DeGate bakiyenize İç Transfer yoluyla aktarılacaktır.',
  'operations.claim_desc_others':
    'Bu talep, DeGate Bakiyenize iç transfer yoluyla aktarılacaktır.',
  'operations.claim_rewards': 'Mevcut Ödüller',
  'operations.claim_err_amount': 'Talep etmek için yeterli miktar yok',
  'operations.claim': 'Talep Et',
  'operations.Claimable': 'Talep Edilebilir',
  'operations.Unclaimed': 'Talep Edilmemiş',
  'operations.claim_mining_rewards': 'Madencilik Ödüllerini Talep Et',
  'operations.claim_rewards_desc':
    'Ödüller, gaz ücretleri düşüldükten sonra hesabınıza gönderilecektir.',
  'operations.pay_deposit': 'Tasfiye',
  'operations.pay_deposit_title': 'Bekleyen Ödeme',
  'operations.pay_deposit_desc_XXX_ETH':
    'XXX ETH tutarında bekleyen fon eklemeniz var.',
  'operations.pay_deposit_select_account': 'Ödemeyi Şuradan Yap',
  Wallet_Balance: 'Cüzdan Bakiyesi',
  'operations.pay_deposit_tips_XXX_ETH': 'XXX ETH Öde',
  'operations.reset_account': 'Varlık Anahtarını Sıfırla',
  'operations.reset_desc':
    'Varlık Anahtarı tarayıcı önbelleğinizde bulunur. Yerel ortamınızın güvenliği sorgulanıyorsa, varlık anahtarını sıfırlayın.',
  'operations.reset_warning':
    'Sıfırlama sırasında, ticaret, gönderme veya iç transfer gibi tüm işlemler durdurulur.',
  'operations.reset_estimated_time': 'Tahmini Süre',
  'operations.reset_order_tips':
    'Sıfırlama başlatıldığında, tüm açık emirler ve ızgara stratejileri iptal edilecektir.',
  'operations.reset_order_tips_btn2': 'İptal Et',
  'operations.claim_dg_rewards': 'DG Ödüllerini Talep Et',
  'operations.claim_REBASE': 'REBASE Talep Et',
  'operations.claim_REBASE_desc':
    'REBASE, iç transfer yoluyla DeGate Bakiyenize gönderilecektir.',
  'operations.claim_REBASE_tips':
    'Talep edilmemiş REBASE, getiri hesaplamasına dahil edilmiştir.',
  'operations.view_yield_history': 'Getiri Geçmişini Görüntüle',
  'operations.cancel_orders_on_chain': 'Zincir Üzerinde Emirleri İptal Et',
  'operations.chain_cancel_dca_text_N':
    'Bu DCA planındaki <b>N emir</b> zincir üzeri iptal için gönderilecektir.',
  'operations.confirm_cancel_gas_AMOUNT_ETH':
    'Zincir üzeri iptal gaz ücretini <b>AMOUNT ETH</b> olarak iki kez onaylayın.',
  'trade.confirm_order': 'Emri Onayla',
  'trade.stop_limit_order': 'Durdurma Limiti',
  'trade.stop_price': 'Durdurma Fiyatı',
  'trade.limit_price': 'Limit Fiyatı',
  'trade.market_price': 'Piyasa Fiyatı',
  'trade.total': 'Toplam',
  'trade.pay': 'Öde',
  'trade.receive': 'Al',
  'trade.hide_pair_confirm': 'Bu çift için tekrar gösterme',
  'trade.pay_the_following_amount_to_place_order':
    'Emir vermek için şu tutarı ödeyin:',
  'trade.flow_of_funds': 'Fon akışı',
  'trade.flow_of_funds_tip2':
    'Emriniz verildi. Emir fonları, cüzdan bakiyeniz yerine DeGate Bakiyenize gidecektir.',
  'trade.pay_to_place_order': 'Emir Vermek İçin Öde',
  'trade.pay_xxx_USDC_to_place_order': 'Emir Vermek İçin XXX USDC Öde',
  'trade.deposit_type': 'Yöntem',
  'trade.deposit_type_standard': 'Standart',
  'transfer.transfer_1_eth_ACCOUNT': "1 ETH'yi Şuraya Transfer Et",
  'transfer.internal_transfer_address_new_tips':
    'Bu adresin DeGate geçmişi yok. Bu adrese transfer yapmak, ek gaz ücretleri gerektirecektir.',
  address_placeholder: 'Adres Girin',
  'transfer.to_new_account_tips':
    'Bu adresin DeGate geçmişi yok. İlk varlık alımı, zincir üzeri veri kullanımını başlattığı için bu iç transferi gerçekleştirmek ek gaz ücretlerine neden olacaktır.',
  'transfer.confirm_internal_transfer': 'İç Transferi Onaylayın',
  'transfer.internal_transfer_address_oneself_tips':
    'Kendinize iç transfer yapmak desteklenmemektedir.',
  'transfer.transfer_max_err_XXX_USDT':
    'İç transfer, transfer başına XXX USDT ile sınırlıdır.',
  'transfer.before': 'Önce',
  'transfer.after': 'Sonra',
  'transfer.recipient_cex_warning':
    'Uyarı: Lütfen Merkezi Borsaya transfer yapmayın. Fonları kaybedersiniz.',
  'withdraw.withdraw_max_tips': 'Sistem limiti aşıldı',
  'dca.confirm_dca_plan': 'DCA Planını Onayla',
  'dca.number_of_orders': 'Emir Sayısı',
  'dca.amount_per_order': 'Emir Başına Tutar',
  'dca.time_scheduled': 'Planlanan Zaman',
  'dca.creating_the_plan': 'Plan Oluşturuluyor...',
  'dca.maximum_price': 'Maksimum Fiyat',
  'dca.minimum_price': 'Minimum Fiyat',
  'dca.do_not_close': 'Bu sayfayı kapatmayın veya yenilemeyin.',
  'dca.frequency': 'Sıklık',
  total_amount: 'Toplam Tutar',
  'dca.daily': 'Günlük',
  'dca.weekly': 'Haftalık',
  'dca.every': 'Her',
  'airdrop.review_airdrop': "Airdrop'u İncele",
  'airdrop.create_airdrop': 'Airdrop Oluştur',
  'airdrop.recipients_number': 'Alıcı Sayısı',
  'airdrop.airdrop_fee': 'Airdrop Ücreti',
  'airdrop.pay_airdrop_fee': 'Airdrop Ücretini Öde',
  'airdrop.send_airdrop_token': 'Airdrop Token Gönder',
  'airdrop.claim_airdrop': 'Airdrop Talep Et',
  'airdrop.retrieve': 'Geri Al',
  'countdown.create_countdown_plan': 'Geri Sayım Planı Oluştur',
  'countdown.countdown_display': 'Geri Sayım Ekranı',
  'countdown.max_30_days': 'Şu andan itibaren 30 günden fazla olamaz',
  'countdown.review_countdown_plan': 'Geri Sayım Planını İncele',
  'countdown.countdown_fee': 'Geri Sayım Ücreti',
  grid_slippage_over_2_tips_SLIPPAGE_QUOTE_BASE:
    'Sistem, başlangıçta SLIPPAGE tahmini kayma ile bir piyasa emri kullanarak QUOTE’un bir kısmını BASE ile değiştirecektir.',
  grid_slippage_over_5_tips_SLIPPAGE_QUOTE_BASE:
    'Sistem, başlangıçta SLIPPAGE tahmini kayma ile bir piyasa emri kullanarak QUOTE’un bir kısmını BASE ile değiştirecektir. İkili Varlık moduyla yatırım yapmanız önerilir.',
  connected: 'Bağlandı',
  browser_wallet: 'Tarayıcı Cüzdanı',
  Convert_to_YYY: 'YYY’ye Dönüştür',
  sell_XXX_to_YYY: 'XXX’i piyasa fiyatıyla YYY’ye çevirmek istiyor musunuz?',
  you_sell: 'Satıyorsunuz',
  you_receive: 'Alıyorsunuz',
  est_slippage: 'Tahmini Kayma',
  No: 'No',
  closing_sell: 'Satış Kapatılıyor',
  connect_wallet: 'Cüzdanı Bağla',
  Add: 'Ekle',
  Add_Funds: 'Fon Ekle',
  send_USDC_to_this_address: "USDC'yi bu adrese gönderin",
  Failed_to_proceed: 'Devam etme başarısız oldu.',
  Please_select_the_Ethereum_network: 'Lütfen Ethereum ağını seçin.',
  NATIVE_USDC_ONLY: 'Yalnızca Yerel USDC Tokeni',
  NEVER_send_bridged_USDC: 'Asla köprülenmiş USDC göndermeyin',
  Network: 'Ağ',
  Arrival_Time: 'Varış Zamanı',
  Token_Contract: 'Token Sözleşmesi',
  please_select_network: 'Lütfen ağı seçin',
  maximum_amount: 'Maksimum Tutar',
  Select: 'Seç',
  cannot_send_to_yourself: 'DeGate ağı içinde kendinize gönderemezsiniz',
  max_amount_exceeded: 'Maksimum tutar aşıldı',
  do_not_trasnfer_to_cex:
    'Lütfen merkezi borsalara <b>ASLA</b> transfer yapmayın. Fon kaybına uğrayabilirsiniz.',
  I_understand: 'Anladım',
  Continue: 'Devam Et',
  chain_0: 'DeGate',
  chain_1: 'Ethereum',
  chain_17000: 'Ethereum',
  chain_42: 'Kovan',
  chain_42161: 'Arbitrum',
  chain_421614: 'Arbitrum',
  chain_10: 'Optimism',
  chain_11155420: 'Optimism',
  chain_137: 'Polygon',
  chain_80002: 'Polygon',
  deposit_tips_region:
    'Lütfen DeGate’e REGION’de eriştiğinizi unutmayın. Fon ekleme sonrası ticaret ve iç transfer özellikleri kullanılamaz.',
  deposit_1_ETH: 'DeGate Bakiyenize 1 ETH Ekleyin',
  'account.deposit_contract_tips_over_AMOUNT':
    'AMOUNT USD üzerindeki fon eklemeleri için Gelişmiş yöntem gereklidir.',
  'account.deposit_contract_tips_only_all':
    'Yalnızca Gelişmiş fon ekleme yöntemi desteklenir',
  Approved: 'Onaylandı',
  Deposit: 'Ekle',
  'account.deposit_tips': 'Bu fonların tam kontrolü sizdedir.',
  'account.deposit_arrive_in_30s_s': '~ 30 saniyede ulaşır',
  reset_approval_USDT: 'USDT Onayını Sıfırla',
  reset_approval_USDT_tips:
    'USDT harcama limitleri çok düşük olduğunda onayı sıfırlamak gerekir.',
  token_has_not_listed: "Bu token DeGate'de listelenmedi.",
  list_now: 'Şimdi Listele',
  Retry: 'Tekrar Dene',
  switch_network: 'Ağı Değiştir',
  switch_to_MAINNET_in_metamask: "Lütfen MetaMask'te MAINNET’e geçin",
  switch_to_MAINNET: 'Lütfen MAINNET’e geçin',
  'account.pay_deposit_warning': 'Fon eklemek ek gaz ücreti doğurabilir',
  send_method: 'Yöntem',
  Economy: 'Ekonomik',
  Fast: 'Hızlı',
  Instant: 'Anında',
  less_than_X_hours: '< X saat',
  less_than_1_hour: '< 1 saat',
  Economy_tips:
    'DeGate, Gönder isteklerini en az her 4 saatte bir işleme alır, genellikle daha hızlı. Örneğin, başka bir kullanıcı Hızlı Gönder başlatırsa, Ekonomik Gönder isteğiniz de hemen işleme alınacaktır.',
  wrap: 'sar (wrap)',
  just_a_moment: 'Biraz bekleyin',
  wait_confirmation_from_wallet: 'Cüzdandan onay bekleniyor',
  s: 's',
  doc_title:
    "DeGate: Merkeziyetsiz Emir Defteri Borsası | GRID ve DCA'da Ücretsiz Kripto Ticaret Botu",
  doc_desc:
    'DeGate, yüzlerce kripto para için düşük ücretli ticaret sunan, ücretsiz limit emir ticareti, grid stratejileri ve DCA botlarıyla öne çıkan üst düzey merkeziyetsiz bir emir defteri borsasıdır.',
  doc_title_spot: '| Merkeziyetsiz Emir Defteri | DeGate DEX',
  doc_title_grid: '| Merkeziyetsiz Grid Ticaret Botu | DeGate DEX',
  doc_title_dca: '| Merkeziyetsiz DCA Ticaret Botu | DeGate DEX',

  view_asset_key_tips:
    '<div>İşte Varlık Anahtarınızın detayları. <strong>Kimseyle PAYLAŞMAYIN</strong> ki potansiyel varlık kaybını önleyin.</div>',
  personal_sign_tips:
    '<div>MetaMask, <i>Personal Sign</i> yöntemiyle yeniden imzalamanızı istiyor.</div>',
  sign_and_open_free_mode_tips:
    'İmza gerekli değildir, bu işlemden sonra İmzasız mod açılacaktır.<br/><br/>Modu değiştirmek için Ticaret Düğmesinin altındaki &quot;Ayarlar&quot; bölümüne gidin.',
  'trade.i_understand': '<span>Anlıyorum </span>',
  'trade.flow_of_funds_tips':
    '<h3>Fon Akışı</h3>Fonlar cüzdan bakiyenize değil, DeGate Bakiyenize gidecektir.<br/><br/><h3>DeGate Bakiyesi Hakkında</h3>DeGate Bakiyesi, kullanıcıların DeGate akıllı kontrato içindeki değerini temsil eder.<br/>Kullanıcılar, tamamen merkeziyetsiz DeGate akıllı kontratı sayesinde DeGate Bakiyesinin tam sahipliğini korur.',
};
export default tr;
