const uk = {
  language: 'ukr-UKR',
  choose_token: 'Вибрати токен',
  recipient: 'Одержувач',
  recent: 'Останні',
  price: 'Ціна',
  amount: 'Сума',
  available: 'Доступно',
  gas_fee: 'Комісія за газ',
  Send: 'Надіслати',
  Send_ETH: 'Надіслати ETH',
  Internal_Transfer: 'Внутрішній переказ',
  transfer_tips: 'Перевести токен на іншу адресу в середині DeGate Protocol',
  transfer_ETH: 'Внутрішній переказ ETH',
  btn_max: 'Максимум',
  degate_insufficient_balance: 'Недостатньо коштів',
  max_digits_exceeded: 'Перевищено максимальну кількість цифр',
  wallet_insufficient_balance: 'Недостатньо коштів на гаманці',
  deGate_insufficient_fees: 'Недостатньо коштів DeGate для комісії за газ',
  token_search_placeholder: 'Пошук токена, адреса контракту',
  token: 'Токен',
  degate_balance: 'Баланс DeGate',
  tips_gas:
    'Комісія за газ для виконання цієї он-чайнової транзакції буде відрахована безпосередньо з вашого балансу DeGate',
  tips_gas2:
    'Комісія за газ покриває он-чайнові витрати на урегулювання торгівлі. Зайві комісії повертаються',
  Close: 'Закрити',
  Help: 'Допомога',
  no_token: 'Токен не знайдено',
  Cancel: 'Скасувати',
  go_back: 'Повернутися',
  Back: 'Назад',
  copied: 'Скопійовано',
  Confirm: 'Підтвердити',
  Create: 'Створити',
  Abort: 'Скасувати',
  btn_confirm: 'Закрити',
  btn_got_it: 'Зрозуміло',
  wallet_cancelled_tips: 'Ви скасували підпис',
  connect_ledger: 'Підключити Ledger',
  ledger_disconnect:
    "Не вдалося виконати 'TransferOut' на 'USBDevice': пристрій був відключений",
  wallet_tips: 'Будь ласка підтвердіть у браузерному гаманці',
  wallet_ledger_tips: 'Будь ласка підтвердіть у апаратному гаманці Ledger',
  wallet_metamask_tips: 'Будь ласка підтвердіть у MetaMask',
  wallet_walletconnect_tips:
    'Будь ласка перейдіть до вашого гаманця для підтвердження через WalletConnect',
  view_asset_key: 'Переглянути ключ активу',
  export_key_warning:
    'Утеча ключа активу може призвести до втрати активів. Будь ласка забезпечте його збереження',
  export_key_confirm_btn: 'Продовжити перегляд',
  btn_buy_ETH: 'Купити ETH',
  btn_sell_ETH: 'Продати ETH',
  around: '～',
  need_help: 'Допомога',
  time_now: 'зараз',
  time_1_minute: '1 хвилина',
  time_1_hour: '1 година',
  time_1_day: '1 день',
  time_1_year: '1 рік',
  time_M_minutes: 'M хвилин',
  time_M_m: 'Mm',
  time_H_hours: 'H годин',
  time_H_h: 'Hh',
  time_D_days: 'D днів',
  time_D_d: 'Dd',
  time_Y_years: 'Y років',
  time_Y_y: 'Yy',
  personal_sign_reason: 'Можливі причини',
  personal_sign_reason1: 'MetaMask підключено до апаратного гаманця',
  personal_sign_reason2: 'Версія MetaMask застаріла',
  personal_sign_reason3: 'Інші',
  personal_sign_btn: 'Підписати знову',
  switch_wallet: 'Змінити обліковий запис',
  switch_walletConnect_tips1:
    'Якщо ви хочете перейти на інший обліковий запис в тому ж програмному забезпеченні для гаманця, будь ласка, виконайте це безпосередньо з гаманця та скасуйте цей запит',
  switch_walletConnect_tips2:
    'Якщо ви хочете використовувати WalletConnect через інше програмне забезпечення для гаманця, система спочатку відключить існуюче з’єднання',
  switch_walletConnect_continue: 'Відключити та продовжити',
  switch_metamask_tips:
    'Будь ласка, перейдіть до MetaMask для зміни облікового запису',
  switch_browser_wallet_tips:
    'Будь ласка, змініть обліковий запис у браузерному гаманці',
  period_expired: 'Прострочено',
  period_D_day_H_hour: 'Dd Hh',
  period_H_hour_M_minute: 'Hh Mm',
  login_success: 'Підключення успішне',
  advanced: 'Розширені',
  edit: 'Редагувати',
  save: 'Зберегти',
  speed_up: 'Прискорити',
  continue: 'Продовжити',
  Submit: 'Подати',
  icon_copy: 'Скопіювати адресу',
  icon_view_explorer: 'Переглянути на блок-експлорері',
  upcoming_lock_tips:
    'Через період бездіяльності режим без підпису буде вимкнено для вашої безпеки',
  auto_locked_tips:
    'Для вашої безпеки режим без підпису був вимкнений після 15 хвилин бездіяльності',
  keep: 'Залишити',
  turn_off_now: 'Вимкнути зараз',
  turn_on: 'Увімкнути',
  turn_on_signature_free_mode: 'Увімкнути режим без підпису',
  turn_on_signature_free_mode_success: 'Режим без підпису увімкнено',
  max_XXX: 'Максимум XXX',
  min_XXX: 'Мінімум XXX',
  common_err: 'Щось пішло не так. Будь ласка, спробуйте ще раз пізніше',
  input_auto_corrected_tips:
    'Автоматично виправлено ваш ввід після перевищення максимальної кількості цифр',
  maximum_decimal_reached: 'Досягнуто максимальну кількість десяткових знаків',
  verify_ownership: 'Перевірити право власності',
  execute: 'Виконати',
  sign_step1: 'Завершити у вашому гаманці',
  sign_step2: 'Завершити 2-й підпис',
  sign_step3: 'Завершити 3-й підпис',
  place_order: 'Розмістити ордер',
  create_spot_order: 'Розмістити ордер',
  create_grid_strategy: 'Створити Grid стратегію сітки',
  create_DCA_plan: 'Створити план DCA',
  cancel_order: 'Скасувати ордер',
  end_grid_strategy: 'Завершити стратегію сітки',
  end_DCA: 'Завершити план DCA',
  complete_in_seconds: 'Завершити за секунди',
  complete_in: 'Завершити за',
  me: 'я',
  eth_code_tips: 'Нативний токен Ethereum. Немає адреси контракту токена',
  total: 'Загалом',
  order_amount: 'Сума ордеру',
  operation_has_expired: 'Операція завершена',
  Approve: 'Схвалити',
  tips_hide_forever: 'Більше не показувати',
  Tips: 'Підказка',
  Note: 'Примітка',
  Summary: 'Підсумок',
  Orders: 'Ордери',
  Side: 'Сторона',
  Sell: 'Продавати',
  Buy: 'Купувати',
  now: 'Зараз',
  order_type: 'Тип ордеру',
  limit_order: 'Ліміт',
  market_order: 'Ринок',
  required: 'Необхідно',
  check_address_format: 'Перевірте формат адреси',
  start_time: 'Час початку',
  end_time: 'Час закінчення',
  None: 'Жоден',
  time_out: 'Час вийшов. Будь ласка, спробуйте ще раз',
  deposit_ETH: 'Додати ETH',
  'grid.confirm_grid': 'Підтвердити Grid стратегію сітки',
  'grid.initial_investment': 'Інвестиції',
  'grid.price_range': 'Ціновий діапазон',
  'grid.grid_level': 'Кількість сіток',
  'grid.grid_volume': 'Кількість на сітку',
  'grid.profit_per_grid': 'Прибуток на сітку',
  'grid.expired_in': 'Завершується через',
  'grid.replace_modal_title': 'Стратегію сітки оновлено',
  'grid.replace_modal_content':
    'Через нещодавні зміни в книзі ордерів початкова стратегія сітки була оновлена наступним чином',
  'grid.replace_modal_pre': 'До',
  'grid.replace_modal_next': 'Після',
  'grid.replace_modal_err':
    'Недостатньо балансу для створення стратегії сітки. Будь ласка, поверніться для редагування параметрів сітки',
  'ledger.connect_rule_1': '1. Підключіть Ledger до вашого пристрою',
  'ledger.connect_rule_2': '2. Розблокуйте в Ledger',
  'ledger.connect_rule_3': '3. Відкрийте додаток Ethereum у Ledger',
  'ledger.connect_rule_4':
    '4. Переконайтеся, що Blind Signing/Contract Data і Browser Support увімкнені',
  'ledger.unable_to_approve': 'Неможливо схвалити',
  'ledger.webusb_1tab_tips_desc_1':
    'Цей браузер підтримує лише одну вкладку для схвалення через Ledger. Неможливо схвалити, оскільки інша вкладка використовує цю функцію',
  'ledger.webusb_1tab_tips_desc_2':
    'Будь ласка, спробуйте повторно підключити Ledger для перезапуску операції',
  'ledger.locked_tips':
    'Будь ласка, розблокуйте Ledger, відкрийте додаток Ethereum та схваліть',
  'ledger.account_not_match':
    'Виявлено неправильний гаманець Ledger. Будь ласка, підключіться до правильного Ledger',
  'ledger.ledger_choose_address': 'Виберіть адресу',
  'ledger.address': 'Адреса',
  'ledger.connect': 'Підключити',
  'ledger.un_supported_title':
    'Підключення гаманця Ledger не підтримується поточним браузером',
  'ledger.un_supported_desc':
    'Рекомендуємо використовувати браузери Chrome та Edge',
  'ledger.confirm_gas_fee': 'Підтвердити комісію за газ',
  'ledger.confirm_gas_fee_desc':
    'Ви збираєтесь ініціювати транзакцію в Ethereum, будь ласка, підтвердіть:',
  'ledger.max_gas_fee': 'Максимальна комісія за газ',
  'ledger.edit_gas_fee': 'Редагувати комісію за газ',
  'ledger.max_fee': 'Ціна газу (Gwei)',
  'ledger.max_base_fee': 'Максимальна базова комісія (Gwei)',
  'ledger.max_base_fee_tips':
    'Коли ваша транзакція буде включена в блок, будь-яка різниця між вашою максимальною базовою комісією та фактичною базовою комісією буде повернена',
  'ledger.priority_fee': 'Пріоритетна комісія (Gwei)',
  'ledger.priority_fee_tips':
    'Пріоритетна комісія (також відома як ""чайові майнерам"") йде безпосередньо до майнерів і стимулює їх надавати пріоритет вашій транзакції',
  'ledger.gas_limit': 'Ліміт газу:',
  'ledger.tx_speed_up_title': 'Прискорити транзакцію',
  'ledger.tx_speed_up_desc':
    'Ви збираєтесь прискорити транзакцію в Ethereum, будь ласка, підтвердіть:',
  'ledger.tx_cancel_title': 'Скасувати транзакцію',
  'ledger.tx_cancel_desc':
    'Ви збираєтесь скасувати транзакцію в Ethereum, будь ласка, підтвердіть:',
  'ledger.fee_minimum_xxx': 'Не може бути менше XXX',
  'ledger.ledger_app_version_tips':
    'Оновіть додаток Ethereum вашого Ledger до версії 1.9.19 або вище, щоб переглянути повідомлення перед підписом',
  'operations.register_pair': 'Додати торгову пару',
  'operations.chain_cancel': 'Скасувати ордер в мережі',
  'operations.chain_cancel_title':
    'Цей запит на скасування ордеру буде розміщений у мережі для гарантії скасування ордеру',
  'operations.chain_cancel_confirm': 'Підтвердити скасування',
  'operations.chain_cancel_confirm_tips':
    'Скасування в мережі призведе до витрат на комісію за газ. Ви хочете продовжити?',
  'operations.chain_cancel_grid_text_N':
    '<b> N ордерів </b> у цій стратегії сітки будуть відправлені для скасування в мережі',
  'operations.chain_cancel_grid_gas_AMOUNT_ETH':
    'Будь ласка, ще раз підтвердьте комісію за скасування в мережі у розмірі <b> СУМА ETH </b>',
  'operations.claim_title': 'Отримати винагороду',
  'operations.claim_desc':
    'Винагорода буде зарахована на ваш баланс DeGate через внутрішній переказ, з комісією за газ, що вираховується безпосередньо з суми винагороди',
  'operations.claim_desc_others':
    'Ця винагорода буде зарахована на ваш баланс DeGate через внутрішній переказ',
  'operations.claim_rewards': 'Доступні винагороди',
  'operations.claim_err_amount': 'Недостатньо коштів для отримання винагороди',
  'operations.claim': 'Отримати',
  'operations.Claimable': 'Доступно для отримання',
  'operations.Unclaimed': 'Неотримано',
  'operations.claim_mining_rewards': 'Отримати винагороду за майнінг',
  'operations.claim_rewards_desc':
    'Винагорода буде відправлена на ваш рахунок після вирахування комісії за газ',
  'operations.pay_deposit': 'Розрахунок',
  'operations.pay_deposit_title': 'Очікує на оплату',
  'operations.pay_deposit_desc_XXX_ETH':
    'У вас є очікуване додавання коштів у розмірі XXX ETH',
  'operations.pay_deposit_select_account': 'Сплатити з',
  Wallet_Balance: 'Баланс гаманця',
  'operations.pay_deposit_tips_XXX_ETH': 'Сплатити XXX ETH',
  'operations.reset_account': 'Скинути ключ активу',
  'operations.reset_desc':
    'Ключ активу зберігається в кеші вашого браузера. Якщо безпека вашого локального середовища викликає сумніви, будь ласка, скиньте ключ активу',
  'operations.reset_warning':
    'Усі операції, такі як торгівля, відправка або внутрішні перекази, припиняються під час скидання',
  'operations.reset_estimated_time': 'Оцінений час',
  'operations.reset_order_tips':
    'Після ініціювання скидання всі відкриті ордери та стратегії сітки будуть скасовані',
  'operations.reset_order_tips_btn2': 'Скасувати',
  'operations.claim_dg_rewards': 'Отримати DG Rewards',
  'operations.claim_REBASE': 'Отримати REBASE',
  'operations.claim_REBASE_desc':
    'REBASE буде відправлено на ваш баланс DeGate через внутрішній переказ',
  'operations.claim_REBASE_tips':
    'Невиплачений REBASE враховується при розрахунку доходності',
  'operations.view_yield_history': 'Переглянути історію доходності',
  'operations.cancel_orders_on_chain': 'Скасувати ордери в мережі',
  'operations.chain_cancel_dca_text_N':
    '<b> N ордерів </b> у цьому DCA плані будуть подані для скасування в мережі.',
  'operations.confirm_cancel_gas_AMOUNT_ETH':
    'Будь ласка, ще раз підтвердьте комісію за скасування в мережі у розмірі <b> СУМА ETH </b>.',
  'trade.confirm_order': 'Підтвердити ордер',
  'trade.stop_limit_order': 'Стоп Ліміт',
  'trade.stop_price': 'Стоп Ціна',
  'trade.limit_price': 'Ліміт Ціна',
  'trade.market_price': 'Ринкова Ціна',
  'trade.total': 'Загалом',
  'trade.pay': 'Сплатити',
  'trade.receive': 'Отримати',
  'trade.hide_pair_confirm': 'Більше не показувати для цієї пари',
  'trade.pay_the_following_amount_to_place_order':
    'Сплатіть наступну суму, щоб розмістити ордер:',
  'trade.flow_of_funds': 'потік коштів',
  'trade.flow_of_funds_tip2':
    'Ваш ордер було розміщено. Кошти з ордеру будуть зараховані на ваш баланс DeGate, а не на баланс гаманця.',
  'trade.pay_to_place_order': 'Сплатити для розміщення ордера',
  'trade.pay_xxx_USDC_to_place_order':
    'Сплатіть xxx USDC, щоб розмістити ордер',
  'trade.deposit_type': 'Метод',
  'trade.deposit_type_standard': 'Стандартний',
  'transfer.transfer_1_eth_ACCOUNT': 'Перевести 1 ETH на',
  'transfer.internal_transfer_address_new_tips':
    'Ця адреса не має історії DeGate. Переведення на цю адресу вимагатиме додаткових комісій за газ.',
  address_placeholder: 'Введіть адресу',
  'transfer.to_new_account_tips':
    'Ця адреса не має історії DeGate. Оскільки перший прийом активу ініціює додаткове використання даних у мережі, виконання цього внутрішнього переказу призведе до додаткових комісій за газ.',
  'transfer.confirm_internal_transfer': 'Підтвердити внутрішній переказ',
  'transfer.internal_transfer_address_oneself_tips':
    'Внутрішній переказ на власну адресу не підтримується.',
  'transfer.transfer_max_err_XXX_USDT':
    'Внутрішній переказ обмежений XXX USDT за переказ',
  'transfer.before': 'До',
  'transfer.after': 'Після',
  'transfer.recipient_cex_warning':
    'Попередження: Будь ласка, не переводьте на централізовану біржу. Ви втратите кошти.',
  'withdraw.withdraw_max_tips': 'Перевищено ліміт системи',
  'dca.confirm_dca_plan': 'Підтвердити DCA План',
  'dca.number_of_orders': 'Кількість ордерів',
  'dca.amount_per_order': 'Сума за ордером',
  'dca.time_scheduled': 'Запланований час',
  'dca.creating_the_plan': 'Створення плану...',
  'dca.maximum_price': 'Максимальна ціна',
  'dca.minimum_price': 'Мінімальна ціна',
  'dca.do_not_close': 'НЕ закривайте і не оновлюйте цю сторінку.',
  'dca.frequency': 'Частота',
  total_amount: 'Загальна сума',
  'dca.daily': 'Щодня',
  'dca.weekly': 'Щотижня',
  'dca.every': 'Кожні',
  'airdrop.review_airdrop': 'Переглянути Airdrop',
  'airdrop.create_airdrop': 'Створити Airdrop',
  'airdrop.recipients_number': 'Кількість отримувачів',
  'airdrop.airdrop_fee': 'Комісія за Airdrop',
  'airdrop.pay_airdrop_fee': 'Сплатити комісію за Airdrop',
  'airdrop.send_airdrop_token': 'Відправити токен Airdrop',
  'airdrop.claim_airdrop': 'Отримати Airdrop',
  'airdrop.retrieve': 'Отримати назад',
  'countdown.create_countdown_plan': 'Створити план зворотного відліку',
  'countdown.countdown_display': 'Відображення зворотного відліку',
  'countdown.max_30_days': 'Не може бути більше ніж 30 днів від сьогодні',
  'countdown.review_countdown_plan': 'Переглянути план зворотного відліку',
  'countdown.countdown_fee': 'Комісія за зворотний відлік',
  grid_slippage_over_2_tips_SLIPPAGE_QUOTE_BASE:
    'Система спочатку обміняє частину QUOTE на BASE за допомогою ринкового ордера, з очікуваним прослизанням SLIPPAGE.',
  grid_slippage_over_5_tips_SLIPPAGE_QUOTE_BASE:
    'Система спочатку обміняє частину QUOTE на BASE за допомогою ринкового ордера, з очікуваним прослизанням SLIPPAGE. Рекомендується інвестування в режимі Dual Asset.',
  connected: 'Підключено',
  browser_wallet: 'Гаманець браузера',
  Convert_to_YYY: 'Конвертувати в YYY',
  sell_XXX_to_YYY: 'Ви хочете продати ваш XXX за YYY за ринковою ціною?',
  you_sell: 'Ви продаєте',
  you_receive: 'Ви отримуєте',
  est_slippage: 'Очікуване прослизання',
  No: 'Ні',
  closing_sell: 'Закриття продажу',
  connect_wallet: 'Підключити гаманець',
  Add: 'Додати',
  Add_Funds: 'Додати кошти',
  send_USDC_to_this_address: 'Надіслати USDC на цю адресу',
  Failed_to_proceed: 'Не вдалося продовжити.',
  Please_select_the_Ethereum_network: 'Будь ласка, виберіть мережу Ethereum.',
  NATIVE_USDC_ONLY: 'Тільки нативний токен USDC',
  NEVER_send_bridged_USDC: 'НІКОЛИ не надсилайте бриджований USDC',
  Network: 'Мережа',
  Arrival_Time: 'Час прибуття',
  Token_Contract: 'Токен контракт',
  please_select_network: 'Будь ласка, виберіть мережу',
  maximum_amount: 'Максимальна сума',
  Select: 'Вибрати',
  cannot_send_to_yourself: 'Неможливо надіслати собі в межах мережі DeGate',
  max_amount_exceeded: 'Перевищено максимальну суму',
  do_not_trasnfer_to_cex:
    'Будь ласка, <b> НЕ </b> переказуйте на централізовані біржі. Ви можете втратити свої кошти.',
  I_understand: 'Я розумію',
  Continue: 'Продовжити',
  chain_0: 'DeGate',
  chain_1: 'Ethereum',
  chain_17000: 'Ethereum',
  chain_42: 'Kovan',
  chain_42161: 'Arbitrum',
  chain_421614: 'Arbitrum',
  chain_10: 'Optimism',
  chain_11155420: 'Optimism',
  chain_137: 'Polygon',
  chain_80002: 'Polygon',
  deposit_tips_region:
    'Зверніть увагу, що ви отримуєте доступ до DeGate в REGION. Функції торгівлі та внутрішнього переказу недоступні після додавання коштів.',
  deposit_1_ETH: 'Додайте 1 ETH на свій баланс DeGate',
  'account.deposit_contract_tips_over_AMOUNT':
    'Додавання коштів понад AMOUNT USD вимагає використання Розширеного методу.',
  'account.deposit_contract_tips_only_all':
    'Підтримується лише Розширений метод додавання коштів',
  Approved: 'Схвалено',
  Deposit: 'Додати',
  'account.deposit_tips': 'Ви зберігаєте повний контроль над цими коштами.',
  'account.deposit_arrive_in_30s_s': 'Прибуття за ~ 30 секунд',
  reset_approval_USDT: 'Скинути схвалення USDT',
  reset_approval_USDT_tips:
    'USDT потребує скидання схвалення, коли ліміти витрат занадто низькі.',
  token_has_not_listed: 'Цей токен не було додано на DeGate.',
  list_now: 'Додати зараз',
  Retry: 'Повторити спробу',
  switch_network: 'Змінити мережу',
  switch_to_MAINNET_in_metamask:
    'Будь ласка, перемкніться на MAINNET у MetaMask',
  switch_to_MAINNET: 'Будь ласка, перемкніться на MAINNET',
  'account.pay_deposit_warning':
    'Додавання коштів може призвести до додаткової комісії за газ',
  send_method: 'Метод',
  Economy: 'Економний',
  Fast: 'Швидкий',
  Instant: 'Миттєвий',
  less_than_X_hours: '< X годин',
  less_than_1_hour: '< 1 години',
  Economy_tips:
    'DeGate обробляє запити на відправку щонайменше кожні 4 години, часто швидше. Наприклад, якщо інший користувач ініціює Швидку Відправку, ваш запит на Економну Відправку буде також оброблений негайно.',
  wrap: 'обгорнути',
  just_a_moment: 'Ще мить',
  wait_confirmation_from_wallet: 'Очікування підтвердження від гаманця',
  s: 's',
  doc_title:
    'DeGate: Децентралізована біржа з книгою ордерів| Безкоштовний крипто-трейдинг бот на GRID і DCA',
  doc_desc:
    'DeGate — це провідна децентралізована біржа з , яка пропонує торгівлю сотнями криптовалют з низькими комісіями, безкоштовну торгівлю лімітними ордерами, сітковими Grid стратегіями та ботами DCA.',
  doc_title_spot: 'Децентралізований ордер-бук | DeGate DEX',
  doc_title_grid: 'Децентралізований Grid Торговий Бот | DeGate DEX',
  doc_title_dca: 'Децентралізований DCA Торговий Бот | DeGate DEX',

  view_asset_key_tips:
    '<div>Ось деталі вашого Ключа Активів. <strong>НЕ діліться</strong> ними ні з ким, щоб уникнути можливих втрат активів.</div>',
  personal_sign_tips:
    '<div>MetaMask запитує, щоб ви знову підписали за допомогою методу <i>Personal Sign</i></div>',
  sign_and_open_free_mode_tips:
    'Підпис не потрібен, оскільки режим без підпису буде увімкнено після цієї дії.<br/><br/>Щоб змінити режим, перейдіть до "Налаштування" під кнопкою "Торгувати".',
  'trade.i_understand': '<span>Я розумію </span>',
  'trade.flow_of_funds_tips':
    '<h3>Рух коштів</h3>Кошти перейдуть на ваш баланс DeGate, а не на баланс гаманця.<br/><br/><h3>Про баланс DeGate</h3>Баланс DeGate представляє вартість, яку користувачі тримають у смарт-контракті DeGate.<br/>Користувачі зберігають повний контроль над балансом DeGate завдяки повністю децентралізованому смарт-контракту DeGate.',
};
export default uk;
